### ISSUE TITLE
no buefy.css after npm install buefy

### ISSUE THREAD

**Issue by Youdaman** [rafaelpimpa/buefy#1]
`import 'buefy/lib/css/buefy.css'` does not work because it seems there's no buefy.css

![screenshot 2017-04-10 14 36 20](https://cloud.githubusercontent.com/assets/287330/24846171/c8e34e12-1dfb-11e7-81d0-7b94b0ddad27.png)

**Comment by Youdaman** [comment]
If you `cd node_modules/buefy` and then `npm install` and `npm run build` it builds the buefy.css file.

It does throw one error though: `ERROR in static/js/app.f466c15a725595e2f890.js from UglifyJs
Unexpected token: operator (>) [./docs/router/index.js:6,0][static/js/app.f466c15a725595e2f890.js:199,18]`

But yeah simply using `npm install buefy` doesn't seem to run the install/build for the module (on Windows at least with npm v4.0.3 node v6.9.1)

**Comment by Youdaman** [comment]
Ok so in the browser console of my app I now get `Uncaught SyntaxError: Unexpected token import` when I add `import Buefy from 'buefy';` -- my only guess is there's a syntax error within buefy somewhere.

**Comment by Youdaman** [comment]
I can download buefy-master.zip and `npm install` then `npm run dev` without any problem btw, it's just if I do `npm install buefy` and use the code as per the installation instructions that problems occur.

**Comment by Youdaman** [comment]
~~Ok so in the browser console of my app I now get `Uncaught SyntaxError: Unexpected token import` when I add `import Buefy from 'buefy';` -- my only guess is there's a syntax error within buefy somewhere.~~

Turns out things work fine if setup a standard vue cli webpack project, then follow the steps above (cd into node_modules/buefy and npm install/run build) -- so yeah it's just that build step that's missing from the standard install of buefy I'm guessing (and that error to do with UglifyJs) that needs fixing.

**Comment by rafaelpimpa** [comment]
Sorry for the delay! I actually forgot to add a npmignore (or remove the /lib from gitignore), just updated the package, should work fine now!

**Comment by CharlesOkwuagwu** [comment]
Good Evening, 
Please is there a direction on how to do a fresh install for a new project?
 1) start with vue init webpack my-project
 2) cd my-project
 3) npm install
 4) npm install buefy [--save ???]

Please confirm if this is indeed the expected steps to follow for a new project setup with buefy

**Comment by rafaelpimpa** [comment]
Yep that's it, you can also use ``npm install buefy --save-dev`` as well.

**Comment by CharlesOkwuagwu** [comment]
Will you update the docs to reflect this please, it will help novices

**Comment by rafaelpimpa** [comment]
Not sure if necessary, people wanna have control about this things :)
