### ISSUE TITLE
Feature request: Popover

### ISSUE THREAD

**Issue by mborders** [rafaelpimpa/buefy#103]
Hello,

Would you consider adding a popover component that could be triggered by click/hover events?

**Comment by Tobbe** [comment]
I'm actually working on a popover component :) I'll try to create a PR next week

**Comment by mborders** [comment]
Awesome, thanks for letting me know! :)

**Comment by rafaelpimpa** [comment]
I'm not a fan of popovers but I can see their utility, gonna wait for @Tobbe PR :)

**Comment by Tobbe** [comment]
We're using it for login/logout in our current project.

![popover_signin_shifted](https://user-images.githubusercontent.com/30793/27285495-34e867d6-54fd-11e7-97ec-e1e9e5c48f1f.png)

**Comment by Tobbe** [comment]
Re #47 that would probably look something like this

```html
<b-popover trigger="hover">
    <div slot="content">
        <img src="preview.png" alt="Preview of image">
    </div>
    <span>Element to hover to trigger preview</span>
</b-popover>
```

**Comment by rafaelpimpa** [comment]
If you don't have the time to do so, let me know so I can start one.

**Comment by Tobbe** [comment]
I can put up a quick and dirty PR just so we have something to discuss :)

**Comment by Tobbe** [comment]
Making some progress on that PR...
![image](https://user-images.githubusercontent.com/30793/27379014-f71dd994-5679-11e7-8b6b-3fd1ba68435e.png)

Writing the documentation I realize there is a lot of work left to do to align it more with the rest of Buefy... This will take some time.

**Comment by rafaelpimpa** [comment]
Oh before making the docs, let me see how it is? You can make a PR or a fork link :)

**Comment by Tobbe** [comment]
PR created. Will not have much more time to spend on this during the week I'm afraid. (Smal fixes/changes are no problem of course.)

**Comment by rafaelpimpa** [comment]
Probably not gonna have time to test it before weekend as well. Thanks man.

**Comment by Tobbe** [comment]
Haven't forgotten about this. But vue's `<transition>` element is giving me some problems with unit testing...

**Comment by rafaelpimpa** [comment]
Me neither! Just out of time, gonna take a look on weekend maybe.

**Comment by rafaelpimpa** [comment]
Dropdown now works like Popver as well.

**Comment by jwahdatehagh** [comment]
I think a proper popover that you can render HTML in (aka [Bootstrap Popovers](http://getbootstrap.com/docs/4.0/components/popovers/)) is a useful feature. The current dropdowns don't really accommodate for that use-case (especially centered positioning & arrows like the tooltip has are missing). May i give it another go?

**Comment by rafaelpimpa** [comment]
@jwahdatehagh Thanks but I don't think it's worth, dropdown the way it is covers most of cases

**Comment by grebebird** [comment]
I arrived here hoping to find a solution specifically for creating a tooltip with rendered HTML content. Is there a way to take the _styling_ from tooltip and apply it to dropdown? I can't easily figure it out. @jwahdatehagh is onto something for sure.

**Comment by jwahdatehagh** [comment]
@grebebird i'm just using the excellent https://github.com/Akryum/v-tooltip with buefy/bulma styling now. If file size is an issue, you can remove Buefy's Tooltip import to make up for it 😉

**Comment by grebebird** [comment]
Thanks @jwahdatehagh ! 

I feel like I'm on to something with using a dropdown with a "notification is-primary" inside (looks like a tooltip without the arrow), and I'm battling removing the top/bottom padding of the "dropdown-content" class, which for some reason isn't working (yet?). I feel like just adding "is-tooltip" to "b-dropdown" could encapsulate this more cleanly than I am hacking it (e.g. remove all padding, set background color like the is-primary notification).
