### ISSUE TITLE
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten...

### ISSUE THREAD

**Issue by patleeman** [rafaelpimpa/buefy#106]
### Overview of the problem

**Buefy** version: [0.4.0]
**Vuejs** version: [2.3.3]
**OS/Browser**: Mac - Sierra / Chrome

### Description
Message:
vue.esm.js?65d7:434 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value"

Found in BInput

This warn message is being triggered by the Dialog component.

[Here's a gif of the warning triggering](http://www.giphy.com/gifs/l4FGKJrdWDsqdJJni)

### Steps to reproduce

Include components and type into dialog.

**Comment by rafaelpimpa** [comment]
I actually have seem it before but couldn't reproduce, will take a look again on it, thanks.

**Comment by jivemonkey2000** [comment]
I saw this too this morning, in 0.4.3.2 and 0.4.3. OSX Sierra, Chrome. 

Had a sniff around the component but couldn't see anything obvious. 

In addition, the dialogue prompt does not show the help text on submit with an empty input.

![screen shot 2017-06-30 at 14 16 20](https://user-images.githubusercontent.com/17082749/27737144-f99c3bee-5d9e-11e7-9400-6e1dc31c3e8b.png)

😕

**Comment by rafaelpimpa** [comment]
It's probably only throwing this error on OSX, I can't reproduce by any means :/

**Comment by jivemonkey2000** [comment]
What makes it more odd, is that as the example on the documentation page works perfectly.. :man_shrugging:

**Comment by AmazeCPK** [comment]
I have the same issue with the prompt component
I'm using Windows 10, so not just limited to OSX
Here is a gif if it in action

http://i.imgur.com/mGCOTNG.gifv

**Comment by rafaelpimpa** [comment]
@AmazeCPK could you share the prompt code? I'm gonna test on another project, the one in the docs is not triggering the warn.

**Comment by AmazeCPK** [comment]
@rafaelpimpa I've included just the prompt code, as well as the entire component in this gist: https://gist.github.com/anonymous/951fb4e1b8a7165d65e02e593c6a60b6

**Comment by rafaelpimpa** [comment]
Couldn't yet see the warning in action, but I see your code has a small error @AmazeCPK , should be 'inputMaxlength' and 'inputPlaceholder':

```javascript
prompt() {
  this.$dialog.prompt({
    message: 'New Category',
    inputMaxlength: 40,
    inputPlaceholder: 'Please enter category title...',
    onConfirm: cat => this.addCategory(cat)
  })
}
```

**Comment by AmazeCPK** [comment]
@rafaelpimpa Thank you. I have updated my code to reflect yours, and it seems I am still receiving the same error on each keystroke as before.
I can upload my project to github if it would help.

**Comment by rafaelpimpa** [comment]
That would be great actually.

**Comment by AmazeCPK** [comment]
@rafaelpimpa Here you go:
https://github.com/AmazeCPK/c-bravo-photo/blob/master/application/src/components/Admin/Dashboard/Images/New_Image.vue

**Comment by rafaelpimpa** [comment]
@AmazeCPK returning 404

**Comment by AmazeCPK** [comment]
@rafaelpimpa updated to public repo

**Comment by rafaelpimpa** [comment]
Ok I've found the root of the warning message, you can remove the repo if you want, thanks!

**Comment by jivemonkey2000** [comment]
👏

**Comment by AmazeCPK** [comment]
Thanks!

**Comment by rafaelpimpa** [comment]
Unfortunately couldn't find another way than using native ``<input>``.

What was causing is that the Dialog is created on runtime outside of the main Vue instance, so the custom components doesn't work correctly with the compiled js files.
