### ISSUE TITLE
[Document - Data - Table] Miss the loading property

### ISSUE THREAD

**Issue by gongzza** [rafaelpimpa/buefy#107]
https://buefy.github.io/#/documentation/table

I couldn't find the loading property on this document.

put it please ~

**Comment by rafaelpimpa** [comment]
What you mean?

**Comment by gongzza** [comment]
Properties of Table have no location's explain

**Comment by rafaelpimpa** [comment]
Sorry, I don't get what you want, please elaborate.

**Comment by gongzza** [comment]
i apologize. i'm very sorry it was my mistake.
i mean it's a loading property.

**Comment by jaybeecave** [comment]
I think he is trying to say that the demo has no example of how to use the loading property on a data table. I just hit this myself.

**Comment by jaybeecave** [comment]
For reference it is simply a boolean property 
```
<b-table :loading="isLoading">... </b-table

data () {
  return {
    isLoading: true
  }
}
```
