### ISSUE TITLE
Feature request: Tabs

### ISSUE THREAD

**Issue by Trevald** [rafaelpimpa/buefy#11]
Great work putting Vue and Bulma together. Couldn't find tabs-component anywhere. Any plans to add that?

**Comment by rafaelpimpa** [comment]
Thank you! Yes, it's on the backlog ;)

**Comment by mirshko** [comment]
It seems there is a bug disabling the animated attribute on b-tabs. Doing `animated="false"` on the b-tabs component fires a invalid type check.

<img width="685" alt="screenshot 2017-05-20 11 38 35" src="https://cloud.githubusercontent.com/assets/8116716/26276978/e7a16d06-3d50-11e7-8c1d-1519a8e38032.png">

**Comment by rafaelpimpa** [comment]
It's boolean, use ``:animated=false"`` 👍
