### ISSUE TITLE
Auto assumed has-addons class breaking layout

### ISSUE THREAD

**Issue by Tirke** [rafaelpimpa/buefy#114]
### Overview of the problem

**Buefy** version: 0.4.0
**Vuejs** version: 2.3.3

### Description

Because you want to assume that users will not know about input addons you auto apply the class has-addons on b-fields with more than one slot. I don't think it is a good idea to assume anything here 😞 It also breaks my use case of using a custom select input with an error message in the same field.

### Expected behavior

If I remove the auto-added has-addons class :

<img width="460" alt="capture d ecran 2017-06-21 a 18 19 22" src="https://user-images.githubusercontent.com/15009522/27394901-3902f676-56ae-11e7-970a-cd6b3e4868f4.png">

### Actual behavior

<img width="444" alt="capture d ecran 2017-06-21 a 18 18 43" src="https://user-images.githubusercontent.com/15009522/27394883-1d06cc40-56ae-11e7-8b38-1315a1e92aeb.png">

**Comment by rafaelpimpa** [comment]
Are you using the b-field ``message`` prop to apply that help message?

**Comment by Tirke** [comment]
I wasn't using the `b-field` with the message prop because I didn't really understand that setting it will always display the message without using the internal communication happening between `b-input` or `b-select`.

By setting it layout is working as intended but now I need to handle another data for this specific message. As I use custom validation what I did previously was like that :

```html
<p class="field is-expanded">
  <multiselect @close="$v.$touch()" v-model="newTag.category" track-by="id" label="label"
                         placeholder="Choisir une catégorie" :options="categories" :searchable="false">
  </multiselect>
  <span v-if="$v.newTag.category.$error" class="help is-danger">Veuillez renseigner ce champ.
  </span>
</p>
```

Which is not really something extravagant in my mind and it was quite disturbing to see that by using `b-field` buefy assumed things for me.

However, you provided a way to fix my problem and I can understand if you don't want to change the internals of `b-field` but, in my opinion, it may be worth to not always assume things especially when you are building such a flexible library.

**Comment by rafaelpimpa** [comment]
Thanks for the input, I've made some pages and auto-assuming the addons is working fine for me. I might revert it more user are having trouble, changing it right away would be a breaking change and it's not worth IMO (at least yet).

**Comment by williamabbott** [comment]
The auto has-addons is a little frustrating when wanting to add extra messages to the field. Also, I want to have the label contain a tooltip, but dropping the label attr from Field and including a label as a child also triggers the has-addons. Maybe an attr :has-addons="false" could overrule the auto behaviour?
