### ISSUE TITLE
Simple question about table rows

### ISSUE THREAD

**Issue by wanxe** [rafaelpimpa/buefy#115]
### Question
_With your Table component:_
How can I assign a class to a row depending on its property?
From a regular VUE loop it would be very simple:
`<tr :class = "{ 'warning', amount < 10 }" > {{ foo }} </tr>`
but don't know how I can do this with your component.

**Comment by rafaelpimpa** [comment]
It's inside the ``b-table-column`` where you specify the field it'll show:

```html
<b-table :data="tableData">

    <template scope="props">
        <b-table-column field="id" label="ID">
            {{ props.row.id }} <-- here I'm specifying the property "id"
        </b-table-column>

        <b-table-column field="user.first_name" label="First Name">
            {{ props.row.user.first_name }} <-- and here I'm specifying the property "user.first_name"
        </b-table-column>
    </template>
</b-table>
```

**Comment by wanxe** [comment]
Oops, wrong answer due to my missed code. Now it's corrected so that the question is better understood.

So I want to put a class to entire row of the table.

**Comment by rafaelpimpa** [comment]
Hmm... I'm gonna have to add a new property that receives a function for this, something like this:

```html
<template>
    <b-table :data="tableData" :row-class="getRowClass"></b-table>
</template>

<script>
    export default {
        methods: {
            getRowClass(row, index) {
                if (row.amount < 10) return 'is-warning'
            }
        }
    }
</script>
```

**Comment by wanxe** [comment]
Yes! Just that man. Waiting for the new release 👍

**Comment by rafaelpimpa** [comment]
It's also possible to make it one-liner with ES6:

```html
<b-table :data="tableData" :row-class="row => row.amount < 10 && 'is-warning'">[...]</b-table>
```

**Comment by wanxe** [comment]
I've tested yesterday and works fine. But if you set the table as striped, you need to add '!important' to your class to get the desired result. Would it be possible to make it less aggressive?

**Comment by rafaelpimpa** [comment]
It's from bulma, nothing can be done :(
