### ISSUE TITLE
Select item

### ISSUE THREAD

**Issue by mikekaranja** [rafaelpimpa/buefy#116]
### Overview of the problem

**Buefy** version: [X.X.X]
**Vuejs** version: [X.X.X]
**OS/Browser**:

### Description

Hi thanks for making this library. I am having a bit of trouble triggering the change event when an option is selected. How do you go about this?
### Steps to reproduce

This is my code
` <b-select class="select" placeholder="Sort By: Popularity">
                    <option v-for="option in options" :change="sortSelect"> {{ option }} </option>         
    </b-select>  `

`  methods: {
    sortSelect() {
      return console.log('option selected')
    },
  },`
### Expected behavior

I don't get any response when i select an option. The sortSelect method is not called.

### Actual behavior

No response.

**Comment by gongzza** [comment]
i guess is this you want.
```
<b-select class="select" placeholder="Sort By: Popularity" @change="sortSelect">
  <option v-for="option in options" :value="option"> {{ option }} </option>
</b-select>
```

**Comment by mikekaranja** [comment]
Alright thanks
