### ISSUE TITLE
Loading overlay similar to the loading spinner on data table

### ISSUE THREAD

**Issue by jaybeecave** [rafaelpimpa/buefy#118]
Thoughts on exposing a loading component that can be used as an overlay while loading async data... Similar to how the table works with loading... 

Just for consistency using the same spinner etc....

Would anyone like this.. happy to implement and create a PR if its a good idea.

**Comment by rafaelpimpa** [comment]
Yea, it's pretty cool addition. You can make a PR if you have the time 👍

**Comment by AmazeCPK** [comment]
I was just searching for a way to do this today.
Trying to achieve the same spinner with a modal
