### ISSUE TITLE
$size is not defined

### ISSUE THREAD

**Issue by ankitrg** [rafaelpimpa/buefy#12]
I get the following error when I try to import buefy:

ERROR in ./~/css-loader?{"minimize":false}!./~/postcss-loader!./~/sass-loader/lib/loader.js!./~/buefy/lib/buefy.css
    Module build failed: 
      margin-left: -calc($size / 2px);
                        ^
          Undefined variable: "$size".
          in /home/aks/playground/forme/node_modules/buefy/lib/buefy.css (line 7927, column 22)

**Comment by rafaelpimpa** [comment]
How exactly are you importing? Seems like you're importing the noncompiled style

**Comment by rafaelpimpa** [comment]
Actually, you're right, let me take a look

**Comment by rafaelpimpa** [comment]
OK, I found the error (have no idea how didn't catch this before), will update the package in about an hour.

**Comment by rafaelpimpa** [comment]
Package updated
