### ISSUE TITLE
toast from vuex

### ISSUE THREAD

**Issue by ggGoblin** [rafaelpimpa/buefy#124]
Is there any way to use Toast from Vuex?
I'm still rather new to Vue, and was not able to find a solution.

**Comment by rafaelpimpa** [comment]
Not tested, but this probably gonna work:

```javascript
import Vue from 'vue'

const state = {[...]}
const mutations = {[...]}
const getters = {[...]}
const actions = {
    login: ({ commit, state }, payload) => {
        commit('IS_LOGGED', true)
        Vue.$toast.open([...])
    }
}

export default {
    state,
    mutations,
    getters,
    actions
}
```

**Comment by ggGoblin** [comment]
hmmm,
I tried something very similiar.
Vue.$toast is undefined

**Comment by rafaelpimpa** [comment]
Available in next release:

```javascript
import { Toast } from 'buefy'

Toast.open([...])
```

Be aware that the constructor options won't work this way, you have to set params on ``open``.

**Comment by ggGoblin** [comment]
Great,  thanks

**Comment by AmazeCPK** [comment]
@rafaelpimpa 
> Be aware that the constructor options won't work this way, you have to set params on open.

Could you explain this a bit more in depth? 
How exactly do we set params?
Thank you.

**Comment by rafaelpimpa** [comment]
Means that if you use any of these:

- ``defaultContainerElement``
- ``defaultSnackbarDuration``
- ``defaultToastDuration``

From [constructor options](https://buefy.github.io/#/documentation/constructor-options) they won't work, you have to set on ``open``.

**Comment by jlsjonas** [comment]
@rafaelpimpa could we do the same for `Dialog`?

**Comment by rafaelpimpa** [comment]
New method of import outside vue instance is described in last changelog and docs! It's working for dialog, modal, toast and snackbar

**Comment by jlsjonas** [comment]
As stated in my edit; sorry if I didn't make that clear enough 😅 

> works fine if using import { Dialog } from 'buefy/dist/components/dialog' instead. ignore my comment :) (and you're welcome future googler 😉 )

**Comment by Ashtonian** [comment]
```js
import { DialogProgrammatic as Dialog } from 'buefy'
```

**Comment by fabiom91** [comment]
Yes be aware of the correct import, you can find it on buefy documentation. E.g., for `snackbar`:
https://buefy.org/documentation/snackbar/

```javascript
import { SnackbarProgrammatic as Snackbar } from 'buefy'

Snackbar.open({...})
```
