### ISSUE TITLE
Feature request: Stack or queue snackbar/toast

### ISSUE THREAD

**Issue by doorgan** [rafaelpimpa/buefy#125]
Hello,

If it's possible, I would like to have the ability to choose if I want to stack or queue snackbars and/or toasts, in a similar way to [toastr](http://codeseven.github.io/toastr/demo.html).

**Comment by rafaelpimpa** [comment]
I'm not addind this because:

* The animations are gonna suck, I'll have to spend a lot of times on it to be OK
* It's not user friendly so not worth the time

**Comment by doorgan** [comment]
There are use cases when used as realtime notifications for example, so user friendlyness is highly relative to the case, not to the feature itself.

Thanks for the reply, anyway.

**Comment by rafaelpimpa** [comment]
I'll take a closer look when I have time.
