### ISSUE TITLE
Dropdown seperator

### ISSUE THREAD

**Issue by monder007** [rafaelpimpa/buefy#126]
### Overview of the problem

**Buefy** version: [0.4.2]
**Vuejs** version: [2.1.10]
**OS/Browser**: Chrome, firefox

### Description

Copying drop down menu with seperator. I get a error in the console

"Error: You should wrap bDropdownOption on a bDropdown"

It doesn't render the reset of the dropdown to get this to work i have to put an ending tag.

`<b-dropdown-option separator></b-dropdown-option>`

![image](https://user-images.githubusercontent.com/10171157/27561126-da504baa-5abe-11e7-8a8a-13a8f9a098a6.png)

**Comment by gongzza** [comment]
You should wrap bDropdownOption on a bDropdown like this:
```
<b-dropdown>
  <a class="nav-item" slot="trigger">
    <span>Menu</span>
    <b-icon icon="arrow_drop_down"></b-icon>
  </a>

  <b-dropdown-option subheader>
    Logged as <b>Rafael Beraldo</b>
  </b-dropdown-option>
  <b-dropdown-option separator />
  <b-dropdown-option value="home">
    <b-icon icon="home"></b-icon>
    Home
  </b-dropdown-option>
  <b-dropdown-option value="products">
    <b-icon icon="shopping_cart"></b-icon>
    Products
  </b-dropdown-option>
  <b-dropdown-option value="blog" disabled>
    <b-icon icon="art_track"></b-icon>
    Blog
  </b-dropdown-option>
  <b-dropdown-option separator></b-dropdown-option>
  <b-dropdown-option value="settings">
    <b-icon icon="settings"></b-icon>
    Settings
  </b-dropdown-option>
  <b-dropdown-option value="logout">
    <b-icon icon="exit_to_app"></b-icon>
    Logout
  </b-dropdown-option>
</b-dropdown>
```

**Comment by monder007** [comment]
Hi

I did, I copied the example on the website and that's what gives me the error.

The only way to get it to work is putting an ending tag in
________________________________

**Comment by rafaelpimpa** [comment]
You mean that the self closing tag is returning error? It's the best practice tbh.

**Comment by monder007** [comment]
Yeah the self closing tag is causing the error.

I don't think I'm doing anything to cause this.

Do you expect the self closing tag to work or does the documentation need updating to include them as seperate opening and closing tags?

**Comment by rafaelpimpa** [comment]
I've removed the self-closing tag from docs.
