### ISSUE TITLE
Style doesn't work with CSS

### ISSUE THREAD

**Issue by ankitrg** [rafaelpimpa/buefy#13]
I tried importing `import 'buefy/lib/buefy.css'` but the toast style did not work.

I am able to get the style after importing the scss file now!

**Comment by rafaelpimpa** [comment]
I just tested on a different project and it seems to work fine (v0.1.5), with this setup:

```javascript
// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import Buefy from 'buefy'
import 'buefy/lib/buefy.css'

Vue.use(Buefy)
```

**Comment by rafaelpimpa** [comment]
Closing this since nothing more was provided
