### ISSUE TITLE
Checkbox not emitting change event

### ISSUE THREAD

**Issue by gongzza** [rafaelpimpa/buefy#130]
### Overview of the problem

**Buefy** version: [0.4.2]
**Vuejs** version: [2.3.4]
**OS/Browser**: Windows/Chrome

### Description
i used the b-checkbox component like this:
`<b-checkbox v-model="todo.done" @change="update(todo)"></b-checkbox>`

i could get the change event when i clicked the checkbox
but when i pressed space or enter key, i couldn't get the change event.

`todo.done` is changed well.

### Steps to reproduce

1. Focus the checkbox (using tab key or click).
2. Press space or enter.
3. Didn't call the update function.

### Expected behavior

Get the change event when the v-model is changed

### Actual behavior

Didn't get the change event

**Comment by gdutwyg** [comment]
@gongzza  if i want to focus the checkbox and Press enter , the checkbox should not  be selected(but space can select), how  should i do?

**Comment by gdutwyg** [comment]
@rafaelpimpa

**Comment by gdutwyg** [comment]
i want to preventDefault(), but it don't work
