### ISSUE TITLE
Feature Request: Add watcher to Dropdown isActive to emit event on change

### ISSUE THREAD

**Issue by bartboy011** [rafaelpimpa/buefy#132]
### Overview of the problem

**Buefy** version: [0.4.2]
**Vuejs** version: [2.3.4]
**Mac/Chrome**:

### Description

By adding a a watcher to `Dropdown.isActive` and emitting an event (such as `isActiveChanged`) with the new value, it'll make working with the dropdown in the parent component easier.

Example - I'm building a navbar that uses the Dropdown component for nested links. However, when the dropdown is active, I'd like to change the background color (similar to a tab, but without built-in style changes). The easiest way to do this is to add a listener in the parent to when the isActive attribute changes and adding a class based on that change. 

I've [forked this repo](https://github.com/bartboy011/buefy) and added the watcher and event emitter under the branch add-dropdown-events. Let me know if you'd like me to open a pull request!

**Comment by rafaelpimpa** [comment]
Please submit the PR!

**Comment by bartboy011** [comment]
Great, just did!
