### ISSUE TITLE
Component Modal - this

### ISSUE THREAD

**Issue by byronferguson** [rafaelpimpa/buefy#136]
### Overview of the problem

**Buefy** version: [0.4.2]
**Vuejs** version: [2.3.4]
**OS/Browser**: Chrome 59.0.3071.115

### Description

When opening the modal through script as a component modal the `this` stays mapped to the calling objects VueJS vm in DEV. However, in production the modal's `this` does not know anything about the calling objects vm, so plugins/components that are loaded to that vm are not usable.

For example, the `<b-input>` tags do not render.

```
createContact(event) {
    this.$modal.open({
        component: contactModal,
        width: 500,
        props: {
            id: this.$route.params.id,
            positions: this.positions
        },
        onCancel: this.updateContacts
    })
},
```

### Steps to reproduce

1. Create a form component using Buefy elements
2. Create a calling component with an action button
3. Action button should trigger a method which calls `this.$modal.open()`
4. Run using `npm run dev`, and compare `npm run build` deployed behavior

### Expected behavior

I expect that the Buefy components, the vuex state, and any other plugins to be available to the modal component as they are in DEV.

### Actual behavior

The `<b-input>` tags are in the source code, but they do not render any visual objects.

**Comment by rafaelpimpa** [comment]
This is a known issue, the programmatic modal is created outside of the main vue instance, that's why there is the non-programmatic modal. I will add a disclaimer for that on docs.

**Comment by byronferguson** [comment]
@rafaelpimpa , you should also include in your note that Buefy components will also not be available.
