### ISSUE TITLE
Components to tables

### ISSUE THREAD

**Issue by korpa** [rafaelpimpa/buefy#14]
Hi Rafael,

Thank you very much for these great components. Sadly a few features are missing that I could use it in my projects. One of the most important features I would need is the following:

I would need something similar as described in #8 but for tables. Filters are a good way to change the data it self, but if I want to add html/css as well, this does not work. Therefore injecting components would be a great feature.

Here are a few examples how I would like to represent data in tables:

![screenshot_20170415_115943](https://cloud.githubusercontent.com/assets/2982785/25062835/3675bd2a-21d5-11e7-9f86-8fd746d8de32.png)

![screenshot_20170415_121343](https://cloud.githubusercontent.com/assets/2982785/25062873/c3975e5c-21d5-11e7-8734-58687aaff94a.png)

**Comment by rafaelpimpa** [comment]
For HTML/CSS you can do like this following the [docs example](http://localhost:8080/#/documentation/table).

Add the ``html`` property to Table (be aware this will be changed to ``render-html`` in next release:
```html
<b-table html>
    <!-- Others columns -->
    <b-table-column 
        field="date" 
        label="Date" 
        sortable :format="formatDate">
    </b-table-column>
</b-table>
```

Return the html you want in the filter:
```javascript
formatDate(value, row) {
    return `<span class="tag is-primary">
                ${new Date(value).toLocaleDateString()}
            </span>`
}
```

**Comment by korpa** [comment]
I tried this before but sadly this does not work:
![screenshot_20170416_113120](https://cloud.githubusercontent.com/assets/2982785/25070194/59b8b364-2298-11e7-85fe-af1bf1de79ca.png)

I had a similar problem with one of my components. When I read how to solve this in Vue, the makers of Vue clearly said that you should not add HTML code into variables but use components.
Therefore I still think that you should add a feature to inject components.

If you don't mind I would dig into this the next days and submit a PR as proposal.

**Comment by rafaelpimpa** [comment]
You missed the ``html`` attribute on table.

Sure if you have the time to make a PR I would welcome. If you wait a few days I'll make the code a bit more readable adding comments for every methods.

**Comment by korpa** [comment]
PR was merged => closed
