### ISSUE TITLE
Feature request: Some features

### ISSUE THREAD

**Issue by lucawen** [rafaelpimpa/buefy#143]
Yea, I have seen that there is another issue similar to this, but there are more features that I think could be interesting (catching a view of vue-admin)

ProgressBar
Notification animation (not only the block)
Datepicker
Cleavejs
Datatables (Maybe heavy request ??)

Then that's it.
Are there any predictions of any of these features already being made ??
Thanks for the great work done so far! Success!

**Comment by rafaelpimpa** [comment]
No predictions, please create single-issue for feature requests.
