### ISSUE TITLE
Feature Request: Row numbers in b-field textarea

### ISSUE THREAD

**Issue by AmazeCPK** [rafaelpimpa/buefy#144]
I don't see a way to manipulate teh number of rows on the b-field text area upon creation.
Is this something that's missing from buefy? or am I missing something?

**Comment by amartinez-forrester** [comment]
I dont see this in the latest version, did we remove it?

**Comment by wesdevpro** [comment]
> I dont see this in the latest version, did we remove it?

@amartinez-forrester this should still be a feature unless it was removed later on in the change log. Please see
https://github.com/buefy/buefy/blob/f6fe38ac2305e37a0fa33d4b7814a943e838a770/CHANGELOG.md?plain=1#L1601-L1609

**Comment by wesdevpro** [comment]
> > I dont see this in the latest version, did we remove it?
> 
> @amartinez-forrester this should still be a feature unless it was removed later on in the change log.
> 
> Please see the following:
> 
> 1. https://github.com/buefy/buefy/blob/f6fe38ac2305e37a0fa33d4b7814a943e838a770/CHANGELOG.md?plain=1#L1601-L1609
> 2. [4be01ad](https://github.com/buefy/buefy/commit/4be01ad9a448f8daed89fa0cd3a8b88f1e0423cc)

Update: 
The current version of Buefy no longer has this prop as a feature. I am checking the commit history and change log to understand why.

**Comment by wesdevpro** [comment]
> [amartinez-forrester](/amartinez-forrester)

@amartinez-forrester the rows prop is removed in [v0.5.0](https://github.com/buefy/buefy/releases/tag/v0.5.0). I have no clue why though. https://github.com/buefy/buefy/commit/3c4af83b48dfcd9e2a3b7c9e24f0f4e00481e49f#diff-0f426a66e9eb7ae834c8020b2378ecfd3871f9f2d48fed5d2643b8b3abf7a9d7
