### ISSUE TITLE
validation messages i18n

### ISSUE THREAD

**Issue by osman-mohamad** [rafaelpimpa/buefy#148]
### Overview of the problem
make validation messages translatable
**Buefy** version: 0.4.2
**Vuejs** version: 2.3.4

### Description
 I am working on application for arabic language speakers . and i want to translate the **validation** messages in when form field is validated . do you have any suggestions ?

### Steps to reproduce
1. when set field type to email it 
2. insert invalid email
3. default `This email is invalid` message show

### Expected behavior
 I want to customize email validation message and any other field validation message

Thank You

**Comment by rafaelpimpa** [comment]
Those messages are just the HTML5 default browser message, if you need more robust validation I suggest that you use [vee-validate](https://github.com/baianat/vee-validate) (which is really good) or any other lib.
