### ISSUE TITLE
Add v-cloak support on some components

### ISSUE THREAD

**Issue by Tirke** [rafaelpimpa/buefy#149]
At the moment, `v-cloak` doesn't work on components like Notification (because the top element is `<transition>` I think).
Would be nice to have it working.

**Comment by rafaelpimpa** [comment]
This one is actually tricky, if I add an element as root the animations are gonna need a timeout to work correctly, and the root element will always have to be rendered even when closing the message/notification. I've research and every other component library also use ``<transition>`` as root. I'm probably gonna leave this way.

If you REALLY need the ``v-cloak`` I suggest that you use the native html elements with bulma classes: http://bulma.io/documentation/components/message/ and http://bulma.io/documentation/elements/notification/
