### ISSUE TITLE
Add return value for checkHtml5Validity

### ISSUE THREAD

**Issue by htfy96** [rafaelpimpa/buefy#153]
### Overview of the problem

**Buefy** version: 0.4.4
**Vuejs** version: 2.3.3
**OS/Browser**: Fx54 on Linux

### Description

Currently `checkHtml5Validity` does not return the validity of value in field, thus we have to hack into the [source code](https://github.com/rafaelpimpa/buefy/blob/dev/src/utils/FormElementMixin.js#L79) and use the undocumented `isValid` property.

The typical use case is a `/register` page, where we have to check the strength of password before submitting the data.

### Expected behavior

`checkHtml5Validity` returns the validity of underlying DOM element. 

### Actual behavior
No return value thus we have to use `isValid`.

**Comment by rafaelpimpa** [comment]
Not really undocumented (it's in the "methods" tab in docs), but I'll add the return value.

**Comment by mustafa-kahraman** [comment]
Pls give me a example. How can I set `isValid` to `true` grammatically?
I am trying to show the server side errors in form elements.
Thanks

**Comment by rafaelpimpa** [comment]
@mustafa-kahraman Just add a ``message`` and ``type`` to the ``b-field`` and you're good.

**Comment by mustafa-kahraman** [comment]
I was doing that but It does not change input's `isValid` value as you can see at attachment.
I was looking for some kind of method to set error message isValid class etc.
![error](https://user-images.githubusercontent.com/2879826/32635210-f3f0f956-c5b7-11e7-80b7-e66503e0303b.png).

**Comment by rafaelpimpa** [comment]
Maybe I should rename it to ``isHtml5Valid``, but currently is only to know when its html5 validation is true or not.

**Comment by mustafa-kahraman** [comment]
I solved my problem. But it's still as same as in the picture `isValid` still `true`. Anyway it's working... 
Maybe when you have time you can rethink about the validation part of the forms.

I really thankful for your work. Thanks a lot.

**Comment by mustafa-kahraman** [comment]
I am using graphql for backend...

`<template>
    <div class="container main">
        <section class="section">
            <article class="message">
                <div class="message-header is-info">
                    <p>Register Form</p>
                </div>
                <div class="message-body">
                    <form ref="form" @submit.prevent="onSubmit">
                        <b-field
                            :type="formError.username ? 'is-danger': ''" 
                            :message="formError.username"                    
                        >
                        <b-input
                            placeholder="Username"
                            name="username"
                            v-model="formData.username"
                            @focus="clearInputs"
                        ></b-input>
                        </b-field>
                        
                        <b-field
                                :type="formError.email ? 'is-danger': ''" 
                                :message="formError.email"                    
                        >
                            <b-input
                                placeholder="E-Mail"
                                name="email"
                                v-model="formData.email"
                                @focus="clearInputs"
                            ></b-input>
                        </b-field>
                        
                        <b-field 
                                :type="formError.password ? 'is-danger': ''"
                                :message="formError.password"
                        >
                            <b-input
                                placeholder="Password"
                                name="password"
                                type="password"
                                v-model="formData.password"
                                @focus="clearInputs"
                                password-reveal
                            ></b-input>
                        </b-field>


                        <button 
                            class="button is-success"
                            @click.prevent="onSubmit"
                            :disabled="isDisabled"
                        >
                            Register
                        </button>
                    </form>
                </div>
            </article>

            <b-loading :active.sync="isLoading"  :canCancel="false"></b-loading>

        </section>
    </div>
</template>

<script>
export default {
  data() {
    return {
      isLoading: true,
      isDisabled: true,
      formData: {
        username: "",
        email: "",
        password: ""
      },
      formError: {
        username: "",
        email: "",
        password: ""
      }
    };
  },
  methods: {
    onSubmit() {
      if (this.isDisabled) return;

      this.isDisabled = true;
      this.isLoading = true;

      this.formError.username = "";
      this.formError.email = "";
      this.formError.password = "";

      this.registerUser(this.formData);
    },
    registerUser({ username, email, password }) {
      const query = `
            mutation ($username: String!, $email: String!, $password: String!) {
                register(username: $username, email: $email, password: $password) {
                    ok
                    user {
                        id
                        username
                        email
                    }
                    errors {
                        path
                        message
                    }
                }
            }
        `;

      const vars = { username, email, password };

      console.log("Router: ", this.$router);

      this.$http.request(query, vars).then(data => {
        this.isLoading = false;

        if (data.register.ok) {
          this.$toast.open({
            message: "New user created successfuly!",
            type: "is-success",
            position: "is-top-right",
            duration: 4000
          });

          this.$router.push({ name: "home" });
        } else {
          this.showErrors(data.register.errors);

          this.$toast.open({
            message: `Something's not good!!!`,
            type: "is-danger",
            position: "is-top-right",
            duration: 4000,
            onAction: () => {
              alert("Yay...");
            }
          });
        }
      });
    },
    clearInputs(e) {
      if (e.target && e.target.nodeName == "INPUT") {
        e.target.className = "input";
        this.formError[e.target.name] = "";
      }
    },
    showErrors(errors) {
      if (errors && typeof errors == "object") {
        errors.forEach(({ path, message }) => {
          this.formError[path] = message;
        });
      }
    }
  },
  created() {
    // this only works with html5 validation
    this.$multiwatch(
      ["formData.username", "formData.email", "formData.password"],
      function() {
        const valid = this.$refs.form.checkValidity();
        this.isDisabled = !valid;
      }
    );

    setTimeout(() => {
      this.isLoading = false;
    }, 750);
  }
};
</script>

<style>
.main {
  width: 550px;
}
.loading-icon {
  position: absolute !important;
  top: 30px !important;
  right: 50px !important;
  font-size: 8px;
}
</style>`

**Comment by mustafa-kahraman** [comment]
You can find the form at the gist....

https://gist.github.com/mustafa-kahraman/13bc7ef26acb54107f779dbc95172bd0
