### ISSUE TITLE
Cannot set a default row on b-table when data is empty

### ISSUE THREAD

**Issue by exitedprotek** [rafaelpimpa/buefy#154]
### Overview of the problem

**Buefy** version: [0.4.4]
**Vuejs** version: [2.3.4]
**OS/Browser**: Windows 10/Chrome 59/Firefox 54

### Description

Hi, i would like to add a default row in a `<b-table>` when my array (data) is empty.
Is there a correct way to do it without changing the source code ?

### Steps to reproduce

Just make a simple `<b-table>` and use an empty array as `data` source.
Example with a simple table:
![Example](https://user-images.githubusercontent.com/7212435/27828034-6ed35032-60ba-11e7-8a7d-8e7934c7bad6.png)

**Comment by rafaelpimpa** [comment]
Does it have to be a row or do you want to display just a message that there's nothing?

**Comment by exitedprotek** [comment]
The ideal solution will be to display a single message in a row and keep the `<thead>` untouched.

Using a slot on a `<td>` or `<th>` would be great if think.

Example:
```html
<b-table
        :data="myArray"
        :paginated="true"
        :per-page="25">
        <template scope="props">
            <b-table-column field="test" label="Test">
                {{props.row.test}}
            </b-table-column>
            <b-table-column field="value" label="Value">
                {{props.row.value}}
            </b-table-column>
            <td slot="empty" colspan="2">
                Sorry, there is nothing to display here.
            </td>
        </template>
    </b-table>
```

**Comment by rafaelpimpa** [comment]
Yep I thought about that, it's nice to have, going to add.

**Comment by coderabsolute** [comment]
Am wondering if this functionality was added?

**Comment by jtommy** [comment]
@coderabsolute Yes, you have to use `empty` slot

**Comment by coderabsolute** [comment]
@jtommy  I thought `empty` slot is just to display the message like `No records found.` But, I want my columns to be visible as well, how do I achieve this?

**Comment by jtommy** [comment]
No it's no possible at the moment.

**Comment by coderabsolute** [comment]
Is there any workaround you can think of to make my `columns visible` when the data array is empty, please?

**Comment by jtommy** [comment]
What do you mean with columns? Header?

**Comment by coderabsolute** [comment]
Ah sorry, I meant Header (not columns)..

**Comment by jtommy** [comment]
There is already an issue a about it. Please follow it and we'll think how and when add it, if possible.
