### ISSUE TITLE
use vue-awesome for icons

### ISSUE THREAD

**Issue by akubasa** [rafaelpimpa/buefy#158]
Hello,
I am using https://www.npmjs.com/package/vue-awesome for my font-awesome icons.
Is it possible to use it with Buefy? within their components?

**Comment by rafaelpimpa** [comment]
Buefy components internally uses font-awesone or material-design-icons **font** icons, no support for svg yet unfortunately.

**Comment by akubasa** [comment]
Ok. Thank you for your quick reply.

**Comment by sohailalam2** [comment]
Hi @rafaelpimpa... whats the plan for supporting vue-awesome or custom svg icons? Personally I think the icon should be a slot with default fallbacks, so as a user I can choose my own set of icons and not load the entire library.
