### ISSUE TITLE
Modal size and scrollbars

### ISSUE THREAD

**Issue by jtommy** [rafaelpimpa/buefy#159]
Hi,
there is a issue (compare to Bulma) about modal in mobile screen (the screen is about your example ModalComponent without inner form component):

<img width="826" alt="modal-desktop" src="https://user-images.githubusercontent.com/8029488/27868783-1c3b676c-619e-11e7-8d81-01d64ddbdba0.png">

Desktop, it is ok.

<img width="551" alt="modal-mobile" src="https://user-images.githubusercontent.com/8029488/27868788-204967f0-619e-11e7-841d-8051af64236e.png">

Mobile, it isn't ok.

Other question is about the style. I have to add the style .modal-card { margin: 0 auto; width: auto } to see the correct modal. By Bulma official Modal, i haven't add this and the modal is ok and i haven't the previous issue.
I'm watching in Buefy Modal and there is a difference: 
`<div class="modal-content animation-content" :style="{ maxWidth: newWidth }">`
I think that is the "problem", but what do you think about it ?

**Comment by mikekaranja** [comment]
jtommy i have the same issue with modal on mobile. Is there any way you can change/edit some of the sass/css variables directly in the npm package?

**Comment by rafaelpimpa** [comment]
The reason for the ``width`` is that bulma sets a defined width for modals (https://github.com/jgthms/bulma/blob/master/sass/components/modal.sass#L16)

I'm making some tests right now.

**Comment by rafaelpimpa** [comment]
So basically three things to change:

* ``margin: 0 auto`` is not necessary anymore
* The root element of the component is now the ``<form>``
* Add the ``has-modal-card`` prop to modal

**Comment by jtommy** [comment]
@rafaelpimpa i have just updated to 0.4.5 but modal in mobile mode doesn't look good.

```
<div class="animation-content"
                :class="{ 'modal-content': !hasModalCard }"
                :style="{ maxWidth: newWidth }">
                ...
</div>
```
In Modal.vue component there is that Div and it is the problem. 
In desktop mode the modal is ok but when I resize to mobile the modal is very little; if I remove the div is ok or if I set width: 100% (but i have to set margin: 0 auto to div with class 'modal-card') it's ok.

**Comment by evandroabukamel** [comment]
Could you set the root element of the modal to be the `<body>` instead?
Because my page uses the navbar and sidemenu like admin.vuebulma.com and the modal background appears between them.

**Comment by rafaelpimpa** [comment]
@evandroabukamel I'm a little late but did you mean the programmatic modal? It always has been in the ``<body>`` (or is that the non-programmatic)?

**Comment by evandroabukamel** [comment]
No. I was talking about the component modal.
