### ISSUE TITLE
Unable to catch @keydown.enter event on b-input or b-autocomplete

### ISSUE THREAD

**Issue by akubasa** [rafaelpimpa/buefy#160]
Hello. I tried to catch the keydown.enter event on input or autocomplete element.
Am I missing something?

 <b-field position="is-centered"
             @keydown.enter="doSearch()">
        <b-autocomplete
                class="is-expanded searchfield"
                v-model="search"
                :data="[]"
                placeholder=""
                icon="search"
                @select="option => selected = option"
            @keydown.enter="doSearch()">
        </b-autocomplete>
        <p class="control">
            <button @click="doSearch()" class="button is-info">Suchen</button>
        </p>
    </b-field>

**Comment by rafaelpimpa** [comment]
Use as ``@keydown.native.enter`` as described in the docs, works for any event.
