### ISSUE TITLE
Feature Request: Cancel click event on on certain columns in a table

### ISSUE THREAD

**Issue by AmazeCPK** [rafaelpimpa/buefy#162]
Can we have a way to cancel the b-table click event when clicking a on a column element in a row
For instance I would like to click on the star icon pictured in the following image, and launch a method, without launching the main b-table click method

Here is my example:
http://prntscr.com/fskwp7
https://gist.github.com/anonymous/f26dc570360308346084875e2dc4cc1d

When a user clicks on a row, a modal pops up with information about that row.
However, I'd like when the user clicks on the star icon, I don't want to open the modal, but instead just launch that specific method.

Thank you.

**Comment by jtommy** [comment]
Hi @AmazeCPK,
you could try to stop propagation event.

Example:

`<b-table-column label="" @click.native.prevent="test($event, props.row)"> ... </b-table-column>` 

or

`<span @click.prevent="test($event, props.row)" ... `

`methods: {
  test (event, row) {
  event.stopPropagation()
  ....
}
}`

.prevent, it isn't mandatory but you have to remember that you can listen for a native event (by .native modifier) on the root element of the custom component (see Vue official docs)

**Comment by AmazeCPK** [comment]
@jtommy That worked flawlessly thank you! I wonder if it is a feature that can/should be included in the b-table.

**Comment by rafaelpimpa** [comment]
What you mean that should be included? Doesn't that work?

**Comment by AmazeCPK** [comment]
Yes, it did work. It just wasn't clear how to accomplish from the b-table docs at the time. Thank you
