### ISSUE TITLE
b-table default sort doesn't work as intended ?

### ISSUE THREAD

**Issue by Tirke** [rafaelpimpa/buefy#163]
## Version
Last version of Bulma and Buefy.

## Context
b-table is used with data fetched from API in beforeRouteEnter of vue-router with assign in the next() call.

## Issue
Default sort column is not triggered at all. Nothing happens.

## Expected
Table is sorted according to default sort option.

## Current hacky fix

In my function used to init data : 
```javascript
this.$nextTick(() => {
  this.$refs.table.initSort()
})
```
Update : Doesn't even work every time 😢

**Comment by rafaelpimpa** [comment]
Use initSort() after the return from the ajax call.

**Comment by Tirke** [comment]
I already use

```javascript
this.$nextTick(() => {
  this.$refs.table.initSort()
})
```

After my AJAX call and it didn't always trigger. Looks fine for now, will comme back if I have any other info/problem. Thanks.

**Comment by rafaelpimpa** [comment]
nextTick is not necessary if you chain it after the request:

```javascript
this.$http.get(`${endpoints.example}`)
    .then(response => {
        // ...
    })
    .catch((error) => {
        // ...
    })
    .then(() => this.$refs.table.initSort())
```

**Comment by redpitbull** [comment]
Hi Guys,
I have investigated your table code and found that you forgot to add a reset of a sorted column.
the method this.$refs.table.initSort() no works
For now, I'm using this.$refs.table.currentSortColumn = {} for reset, because initSort doesn't work with a empty defaultSort property -   if (!this.defaultSort) return ;

**Comment by Hunter1r** [comment]
> Hi Guys,
> I have investigated your table code and found that you forgot to add a reset of a sorted column.
> the method this.$refs.table.initSort() no works
> For now, I'm using this.$refs.table.currentSortColumn = {} for reset, because initSort doesn't work with a empty defaultSort property - if (!this.defaultSort) return ;

currentSortColumn is worked, but i solved the problem so:

`<b-table :default-sort="[defaultSort, defaultSortDirection]" ref="tbl">
        ...
</b-table>
...

export default {
  data() {
    return {
      ...
      defaultSort: 'hasUser',
      defaultSortDirection: 'asc',
      ...
      }
      }
      mounted(){
          ...
      }
      activated(){
        this.$refs.tbl.initSort();  
      }
      }`
