### ISSUE TITLE
Confirm dialog dont show correctly on mobile

### ISSUE THREAD

**Issue by prsolucoes** [rafaelpimpa/buefy#165]
### Overview of the problem

**Buefy** version: latest
**Vuejs** version: latest
**OS/Browser**: ios/safari

### Description

Confirm dialog dont show correctly on mobile

### Steps to reproduce

1. Open "https://buefy.github.io/?#/documentation/dialog" on safari on iOS
2. Click on "Confirm default" button.

![error-confirm-alert](https://user-images.githubusercontent.com/395096/27983623-b408e826-6397-11e7-854c-4d391bb6b190.png)

**Comment by prsolucoes** [comment]
Now i think it is a more generic problem. Tested on mac/safari, same problem.

<img width="1266" alt="screenshot 2017-07-08 04 44 16" src="https://user-images.githubusercontent.com/395096/27983649-34d540bc-6398-11e7-9148-9da495b5c01f.png">

**Comment by rafaelpimpa** [comment]
You mean the 'OK' is disaligned? Could you try to debug for me whats the cause of the problem? I don't have mac to test it.

**Comment by prsolucoes** [comment]
I solve the problem setting "display:inline" on the footer buttons:

![screenshot 2017-07-10 15 01 30](https://user-images.githubusercontent.com/395096/28032436-d5634ba2-6580-11e7-8cc2-a689610075a8.png)

**Comment by rafaelpimpa** [comment]
Take a look at the PR, ``display: table-cell`` on buttons, will be fixed in next release.

**Comment by prsolucoes** [comment]
Ok, have any date to next release? I want launch my new tool version with it fixed too. Thanks.
