### ISSUE TITLE
Question: How do I trigger validation of inputs when the user "saves"?

### ISSUE THREAD

**Issue by talismax** [rafaelpimpa/buefy#166]
Sorry, I know this is probably simple; just not seeing it. 

I have b-inputs with required, max lengths, etc. If the field has never been visited I want to trigger the validations when the user attempts to save the form. It seems dumb to recreate the validations that are already built in.

**Comment by rafaelpimpa** [comment]
If you put them in a form, when you submit they are gonna be validated.

**Comment by danielclariondoor** [comment]
I tried to do this like so:
`
let form = this.$rerf.form
form.submit()
`
the form submit without displaying errors on empty required fields.

**Comment by agersea** [comment]
I used this.$refs.form.reportValidity() and that presented the standard HTML5 Validation I expected.

**Comment by akshitrcrm** [comment]
why should we use form element if just using b-field also works. Just need a method to trigger the validation manually... 🥲
