### ISSUE TITLE
New Bulma 4.3 components not rendering (Breadcrumb & Navbar)

### ISSUE THREAD

**Issue by whereisjefe** [rafaelpimpa/buefy#169]
### Overview of the problem

**Buefy** version: [0.4.4]
**Vuejs** version: [2.3.4]
**OS/Browser**: Windows 10 / Chrome & Firefox

### Description

Not sure if i'm doing something wrong locally but it appears the 0.4.4 version of Buefy is using Bulma v0.4.2. All other features work except the new 4.3 features. When i take a look at the `node_modules` folder the `buefy/lib/buefy.css` it looks like it's using Bulma v0.4.2

### Steps to reproduce

1. Install Buefy
2. Configure Buefy
3. Verify Buefy is working (test Bulma 0.4.2 components)
4. Use a new Bulma 0.4.3 component like navbar or breadcrumb

### Expected behavior

render Bulma components per the Bulma docs

### Actual behavior

doesn't render new compenent's CSS

**Comment by whereisjefe** [comment]
looking over source looks like the change has been made just hasn't been merged into master

**Comment by rafaelpimpa** [comment]
Exactly, available in next patch/release.
