### ISSUE TITLE
Issue modal #159

### ISSUE THREAD

**Issue by jtommy** [rafaelpimpa/buefy#171]
See #159

@rafaelpimpa i have just updated to 0.4.5 but modal in mobile mode doesn't look good.

```
<div class="animation-content"
                :class="{ 'modal-content': !hasModalCard }"
                :style="{ maxWidth: newWidth }">
                ...
</div>
```

In Modal.vue component there is that Div and it is the problem.
In desktop mode the modal is ok but when I resize to mobile the modal is very little; if I remove the div is ok or if I set width: 100% (but i have to set margin: 0 auto to div with class 'modal-card') it's ok.

**Comment by prsolucoes** [comment]
I think the modal is with the size of content.

![img_1460](https://user-images.githubusercontent.com/395096/28079642-988156f6-663f-11e7-91cb-57852854d14a.PNG)

**Comment by prsolucoes** [comment]
Now, with a larger content.

![img_1461](https://user-images.githubusercontent.com/395096/28080129-352af29a-6641-11e7-8664-199719bd2b59.PNG)

**Comment by jtommy** [comment]
Actually, no, I don't.
Try the modal component quite bigger in desktop mode and then look that in mobile. In the last way, the modal should be all page size (width). You can see in Bulma official docs.

**Comment by rafaelpimpa** [comment]
You mean that it should always take 100% width on mobile?

**Comment by prsolucoes** [comment]
No, it need have the same width with few or large amount of data, like in the screenshot from bulma site:

![img_1462](https://user-images.githubusercontent.com/395096/28084594-6e668f2a-664f-11e7-8e60-d7bb091e2e12.PNG)

**Comment by jtommy** [comment]
Yes @rafaelpimpa. As you can see in the screenshot or in Bulma docs
