### ISSUE TITLE
Feature Request: Add a CDN install method

### ISSUE THREAD

**Issue by SharkBeard** [rafaelpimpa/buefy#172]
It would be much more convenient for rails asset pipeline users to have a CDN link. We can just include vue, bulma, and buefy via the CDN and run the constructor.

**Comment by rafaelpimpa** [comment]
I've made a fiddle (https://jsfiddle.net/rafaelpimpa/0afsyg9v/) but didn't have time to add to the docs, the CDNs used was:

```
script:
https://unpkg.com/buefy

style:
https://unpkg.com/buefy/lib/buefy.css
```

**Comment by SharkBeard** [comment]
Thanks, this works great.

**Comment by rafaelpimpa** [comment]
Added to docs and readme.
