### ISSUE TITLE
Could I contribute components that are similar to Element UI

### ISSUE THREAD

**Issue by tsctao** [rafaelpimpa/buefy#175]
I have been using Element UI but it lacks mobile support. Therefore, I'm searching for new component library to replace it and your library looks good. But I need some components like DatePicker, Searchable select box, Cascader. 

Would you mind if I make these components to your library.

**Comment by rafaelpimpa** [comment]
That would be great actually! You just have to keep within the [guidelines](https://github.com/rafaelpimpa/buefy/blob/dev/.github/CONTRIBUTING.md), and keep some general design consistencies:

* Desktop and mobile support
* Transitions GPU-only
* Bulma design
* Keep simple

I also have to add eslint to keep code consistent (currently I'm using only the VSCode extension).

The ones you mentioned I'm just not sure about searchable select, we already have autocomplete that works for complex list (It's really hard to emulate a native select without thousands of lines of code).

**Comment by tsctao** [comment]
In my case, it is better to use select that shows all options first and make it searchable if having many options. I'll try to make and have you review it.

Other question, why do you implement dropdown for mobile as modal? I think it may confuse user.

**Comment by jtommy** [comment]
@tsctao I think that the current mobile implementation of dropdown is perfect. 
Other frameworks work like that.

**Comment by rafaelpimpa** [comment]
@tsctao because that's how native select works for mobile, I don't really think it confuses the user.
