### ISSUE TITLE
Feature Request: Autocomplete set text

### ISSUE THREAD

**Issue by matthewpull** [rafaelpimpa/buefy#176]
### Description

Can you implement a method to set the text of the autocomplete element without triggering the suggestions opening? I am creating an edit page which loads the existing data and sets up the editor to the state it was in when an item was created, and this includes adding the name of the selected item to the autocomplete box. When I do, however, the autocomplete thinks that the text has just been entered so pulls up the list of suggestions, which is not as intended.

Thanks :)

**Comment by rafaelpimpa** [comment]
Setting the ``selected`` is good enough? I noticed it has a bug when setting the selected, the text won't update.

**Comment by matthewpull** [comment]
Sorry for the long response, I've only just got back from holiday.

setSelected could work; ideally I would pass in the object that is to be selected rather than an array position i.e. if my data looks like this ...
```
[
  {
    key: 'd66b34697e',
    name: 'Banana'
  },
  {
    key: '31c3d3467b',
    name: 'Apple'
  },
  {
    key: 'e5603ae8d8',
    name: 'Pear'
  }
]
```
... then I would like to be able to pass in one of the objects rather than the correct array id.

However, if there are good reasons why this cannot easily be done this way, an array id would work. My array is likely to be over a thousand entries long, however, which is why for my use case it works best to just pass in an object.

Just for some context, I have an autocomplete element used in both a create view and an edit view. When the edit view is loaded I fill all of the inputs with the previously-stored values, so that the user can easily edit them. For the autocomplete I want to just set the currently-selected object (which I will have easy access to because it is part of the larger item that I am loading to edit) or as a worst case set the text.

What are your thoughts on this?

**Comment by rafaelpimpa** [comment]
The way I posted is already released, you can try that.

For that to work without the reference (id) I would have to make a search functionality inside the component, not impossible but not sure if necessary.

**Comment by matthewpull** [comment]
FYI, I implemented your suggestion last month and have had no issues with it. I think that setSelected should be documented, as I don't see it listed on the documentation site at the moment, but other than that this issue is resolved.

**Comment by rafaelpimpa** [comment]
We added to the docs, thanks :)
