### ISSUE TITLE
Feature request: Panel

### ISSUE THREAD

**Issue by jtommy** [rafaelpimpa/buefy#177]
@rafaelpimpa 
I would like develop panel component in case collapsible by props (animation too).
What do you think about it ?

**Comment by rafaelpimpa** [comment]
Great, @jtommy !

But wait until I fix the ESLint (I'm gonna replace for a new vue-cli structure), I'll let you know when it's ready!

**Comment by rafaelpimpa** [comment]
Project updated, ESLint added, I recommend cloning project again to avoid any errors 👍
