### ISSUE TITLE
Buefy components are not showing

### ISSUE THREAD

**Issue by dragidavid** [rafaelpimpa/buefy#181]
Hey there,

I have a problem importing Buefy. I'm using the newest release of everything.. Laravel, laravel-mix, bulma, and buefy but for some reason nothing works after importing. 

My app.js looks like this:
```
require('./bootstrap');
window.Vue = require('vue');
import Buefy from 'buefy';
Vue.use(Buefy);
```

and the app.scss

```
@import "variables";
@import "node_modules/font-awesome/scss/font-awesome";
@import "node_modules/bulma/bulma";
@import "node_modules/buefy/src/scss/buefy";
```

It builds successfully with `npm run dev` but when I try to use `<b-checkbox> ` for example, nothing comes up.

Any ideas?

**Comment by rafaelpimpa** [comment]
If you share the repo I could take a look, but for now, try to adjust the buefy to use the standalone way with:

```javascript
Vue.use(Buefy.default)
```

**Comment by dragidavid** [comment]
Added you as a collaborator. I tried your advice but didnt work.. :/ At this point I think its a really simple solution but I just can't seem to find what's wrong.

The page I tried Buefy on, is the login.blade.php

**Comment by rafaelpimpa** [comment]
I'm getting 404 when accessing /login, what's the endpoint?

**Comment by rafaelpimpa** [comment]
You probably just have to uncomment this line
```
// var app = new Vue({
//     el: '#app',
//     data: {}
// });
```

**Comment by dragidavid** [comment]
Still doesn't work.. It gave me a constant error for checkboxState, like it wasnt declared.

I feel like it doesnt import the js and css correctly. Any idea on how to build it? I just used npm run dev in the project folder..

**Comment by rafaelpimpa** [comment]
In fact that is something to do with the structure of the laravel/laravel-mix probably (I'm not too familiar with it), you should ask them how to import js correctly.
