### ISSUE TITLE
Nuxt and Buefy 

### ISSUE THREAD

**Issue by wishinghand** [rafaelpimpa/buefy#183]
### Overview of the problem
**Buefy** version: [0.4.5]
**Vuejs** version: [2.4.1]
**OS/Browser**: macOS Sierra/Chrome 59

### Description
I cannot get Buefy to run with Nuxt after an npm installation.

### Steps to reproduce
1. install Buefy with `npm install --save buefy`
2. Run Nuxt with `npm run dev`
3. Errors show for a Vue and vue-server-renderer version mismatch. After correcting those...
4. Undefined variables in the .scss files: 
 buefy/src/scss/utils/_animations.scss: line 90, missing `$slow` and `$easing` variables
 buefy/src/scss/components/_autocomplete.scss: line 11, missing `unselectable` mixin

### Expected behavior
Have Buefy running globally in a Nuxt installation

### Actual behavior
Version mismatch, undefined SCSS variables/mixins

**Comment by rafaelpimpa** [comment]
Paste the code you're running to import, looks like you're missing Bulma should be in this order:

```scss
@import "~bulma";
@import "~buefy/src/scss/buefy";
```

**Comment by wishinghand** [comment]
I was totally missing the javascript it turns out. This link: https://www.reddit.com/r/vuejs/comments/6nvx69/has_anyone_gotten_buefy_and_nuxt_working_together/dkh2oql/ has what I was doing wrong. I needed to add a `buefy.js` file to the `plugins` directory of Nuxt and add this code:

```
import Vue from 'vue'
import Buefy from 'buefy'
import 'buefy/lib/buefy.css'

Vue.use(Buefy)
```

and then in the `nuxt.config.js` file I add this:
`plugins: ['~plugins/buefy']`

**Comment by rafaelpimpa** [comment]
Does it works fine now?

**Comment by wishinghand** [comment]
Yes! I have Buefy components working as well as regular Bulma classes. I could do a pull request that describes how to add Buefy for Nuxt in the documentation if you're interested.

**Comment by rafaelpimpa** [comment]
Sure! That would help newcomers with a Nuxt setup 👍

**Comment by wishinghand** [comment]
#196 - made a pull request to add Nuxt instructions to the documentation.
