### ISSUE TITLE
Add Cleavejs dependency

### ISSUE THREAD

**Issue by rafaelpimpa** [rafaelpimpa/buefy#185]
Hello everyone,

As it's described in README and docs, Buefy doesn't use any dependencies aside from Bulma, but recently I see myself in the need of [Cleavejs](https://nosir.github.io/cleave.js/) functionalities. The tool itself is kinda small (something like 4KB min+gzip), it's also well known and tested.

I want to add as dependency to use with ``b-input``, with the ``options`` (or maybe ``cleave``) prop. Is everyone in agreement with that, any other idea / suggestions?

**Comment by jtommy** [comment]
I don't know Celave.js but at a first glance it's a good tool and without specific dependencies (jQuery, etc).
I approve your idea! 👍

**Comment by bartboy011** [comment]
Agreed with @jtommy, to me the benefits of having an input-parser outweigh the added weight.

**Comment by rafaelpimpa** [comment]
OK, after some time I realised that it's not needed, I've made a directive in my personal project, clearly needs some tweaks but it's just as easy:

```javascript
import Cleave from 'cleave.js'

Vue.directive('cleave', (el, binding) => {
    const input = el.querySelector('input')
    new Cleave(input, binding.value)
})
```

```html
<b-input v-cleave="{ creditCard: true }"></b-input>
```

**Comment by recoiladam** [comment]
> OK, after some time I realised that it's not needed, I've made a directive in my personal project, clearly needs some tweaks but it's just as easy:
> 
> ```js
> import Cleave from 'cleave.js'
> 
> Vue.directive('cleave', (el, binding) => {
>     const input = el.querySelector('input')
>     new Cleave(input, binding.value)
> })
> ```
> 
> ```
> <b-input v-cleave="{ creditCard: true }"></b-input>
> ```

I know this is closed but just wanted to say that this does not work for me. I also tried via Prototype and a CSS class which did not work either. I also tried vue-inputmask which did not work either. At this point, I have no way of masking input values and it's driving me crazy!
