### ISSUE TITLE
Feature Request: DatePicker

### ISSUE THREAD

**Issue by jtommy** [rafaelpimpa/buefy#189]
@rafaelpimpa 
DatePicker it's an important component in the major part of web apps.
Have you planned something about it ? 
Would you like implement a new component from scratch or use a specific lib and customize it ?

**Comment by ismet** [comment]
I was thinking to add exactly the same request. I am an hour late!  :)

**Comment by bartboy011** [comment]
Amazing timing, I started working on a DatePicker built around Buefy this morning, I'll submit a pull request once I've had a chance to test everything out if it's a feature that would be appreciated!

**Comment by rafaelpimpa** [comment]
I haven't stop yet to think about it TBH, pickers are really important indeed. Unfortunately right now I'm not gonna have time to do so. I can analise your PRs tho.

**Comment by bartboy011** [comment]
Just opened a pull request (#194) with the first pass at the datepicker, let me know what you think!

**Comment by byronferguson** [comment]
https://github.com/charliekassel/vuejs-datepicker

So far this one is integrating pretty well with Buefy.

**Comment by jtommy** [comment]
@byronferguson Good to know! 
But there is a PR (working in progress) made by @bartboy011

**Comment by bartboy011** [comment]
@byronferguson Thanks for the heads up! I'll take a look at it and see if it couldn't be a good guide on additional features. It could potentially be rolled into Buefy, but so far @rafaelpimpa has managed to keep dependencies to exclusively Vue and Bulma, and vuejs-datepicker depends upon Babel Runtime, so it would have to be discussed.

**Comment by jamespdaily** [comment]
Would love to this

**Comment by bartboy011** [comment]
@jamespdaily check out #194, we're in the midst of some code review now.

**Comment by jtommy** [comment]
#194 https://github.com/rafaelpimpa/buefy/commit/9e218907851383eee564900fc8aa21beebddbd4b
