### ISSUE TITLE
Empty label for b-table-column

### ISSUE THREAD

**Issue by Tirke** [rafaelpimpa/buefy#195]
So, we have one use case of a table with multiple columns having empty labels.
The only way we have found to make it work is by setting `label=" "` for the first column then `label="  "` (two spaces) for the second col ... and you guess it for the rest.

It is really not that great and it just feels like a hack. I know that the label prop is currently required and that you rely on it for some computation but I don't really think I'm asking something too crazy.

Btw we are using icons in our columns without labels and it doesn't feel great to put a label on those columns.

Thanks.

**Comment by rafaelpimpa** [comment]
Yep, unfortunately right now it's not possible, we could add a ``key`` prop (that would be required) for that purpose. Lets see what people think.

**Comment by byronferguson** [comment]
I agree with the design approach of no visible label on columns which are being populated with just icons for alignment and maybe sorting.

Could the label prop be modified to allow duplicate labels, or blank labels, and use a second optional prop that defines _label_visible_. It might avoid breaking some things.

**Comment by rafaelpimpa** [comment]
@byronferguson I thought about that but didn't have a clear way to do, it's actually pretty simple, will add it later.
