### ISSUE TITLE
Server Side Pagination

### ISSUE THREAD

**Issue by daenuprobst** [rafaelpimpa/buefy#198]
Is server side pagination support for b-table planned for a (near) future release? Currently, the best approach would probably be to load dummy data to fill up non-loaded pages and then load the actual data on page change (or am I wrong?).

**Comment by jtommy** [comment]
Hi @daenuprobst, 
you have to use b-pagination and disabled pagination from b-table. 'Change' event (b-pagination) tell you the current page and so you can reload your data but of course you have to know the total number of elements.

**Comment by daenuprobst** [comment]
Thanks @jtommy. I'll do it like this. Would be nice to have a server-side pagination option with b-table in a future release (is it on the roadmap yet?). I could start working on it but not before November ...

**Comment by rafaelpimpa** [comment]
No plans for it, I think it's even easier to implement with them separated.
