### ISSUE TITLE
B-table animation/transition state

### ISSUE THREAD

**Issue by Tirke** [rafaelpimpa/buefy#199]
I'm sorry to write this as an issue because it may not be one, but we have a very hard time animating (using vuejs tools like transition) a b-table and we were wondering if anyone has already done this and could provide us with a working example.

Thanks.

**Comment by Tirke** [comment]
Closing this seems we are out of luck on this one ...

**Comment by dbarrington** [comment]
Did you ever find a solution, or workaround, to this? This would be really useful with row deletions and so on.

**Comment by Tirke** [comment]
Never found an easy way sorry. Maybe try full manual animation ....

**Comment by kamaladenalhomsi** [comment]
looks like I am not the only one facing this :)
also me coming from 2020 facing this, in my current project I am doing an infinite scroll in the table,
and I want to fadeIn the elements smoothly

I tried to do a workaround, but it's quite complicated

**Comment by dbarrington** [comment]
I checked over my old code, I never ended up figuring out a work around. I think I hoped someone would find a solution in the meantime, then forgot about it. :D

**Comment by kamaladenalhomsi** [comment]
@dbarrington Thank you
I think it might require breaking changes to do this.

**Comment by xstevenyung** [comment]
I manage to successfully make this work by forcing re-rendering specifying a `custom-row-key` (for some reason buefy doesn't render a new row but update existing ones, specifying that key force rendering / re-rendering) and `row-class` to add our animation class.

Here a CodeSandbox:
https://codesandbox.io/s/kind-wright-vnllr?file=/src/App.vue

Feel free to mention me if you have any questions.
