### ISSUE TITLE
select addon appears squashed

### ISSUE THREAD

**Issue by Youdaman** [rafaelpimpa/buefy#2]
https://buefy.github.io/#/documentation/input

The currency symbol overlaps the dropdown arrow:

![screencapture-buefy-github-io-1491802337223](https://cloud.githubusercontent.com/assets/287330/24847262/3aec7b12-1e03-11e7-8d30-54a213cced2d.png)

**Comment by Youdaman** [comment]
Solution (worked out from inspecting Bulma docs element):

Add `padding-right: 2.5em;` to `.select select` CSS rules.

**Comment by rafaelpimpa** [comment]
The last release from Bulma came with a lot of bugs, I'm gonna make a temporary fix for this and others bugs until next Bulma's release 👍
