### ISSUE TITLE
Question: how to make submit button disabled if form isnt valid

### ISSUE THREAD

**Issue by BjornMelgaard** [rafaelpimpa/buefy#200]
can someone adjust example or give a hint? 

```jsx
<template>
  <form class="box" @submit.prevent="onSubmit">

    <b-field label="Email *">
      <b-input v-model="model.email" type="email" required></b-input>
    </b-field>

    <b-field label="Password *">
      <b-input v-model="model.password" type="password" required maxlength="30"></b-input>
    </b-field>

    <button class="button is-primary" type="submit" :disabled="ref on form????">Submit</button>
  </form>
</template>

<script>
  export default {
    name: 'LoginForm',
    data () {
      return {
        model: {
          email: '',
          password: ''
        }
      }
    },
    methods: {
      onSubmit () {
        this.$emit('submit', this.model)
      }
    }
  }
</script>

```

**Comment by rafaelpimpa** [comment]
If you just wanna check if they are not null, you can do this: https://jsfiddle.net/rafaelpimpa/y6r57k2w/

Now if you need more complex validation, I recommend you to use [vee-validate](https://github.com/baianat/vee-validate) or any other validation library.

Buefy validation is just like normal HTML5, prevents the form from submitting.

**Comment by BjornMelgaard** [comment]
yeah, its fine, simpler - better 

+ example, [where button is disabled if form isnt valid](https://jsfiddle.net/3tp1njqe/)

thanks for awesome library!!
