### ISSUE TITLE
[FEATURE REQUEST] multiple help text for field component

### ISSUE THREAD

**Issue by darkylmnx** [rafaelpimpa/buefy#201]
Hi,

i would like to suggest a feature which i think may happen often, in most forms you can have multiple errors and some time you maye show all errors unders a field.

Currently the field component lets us add only one message (i'm not even sure we can pass html to se different messages with br for example)

In my case i'm using Vuelidate, and i often have this situation

```
<p class="help is-danger" v-show="$v.user.firstname.$error &&!$v.user.firstname.required">
  {{ $t('validation.required') }}
</p>
<p class="help is-danger" v-show="$v.user.firstname.$error &&!$v.user.firstname.maxLength">
  {{ $t('validation.max.string', {max: 190}) }}
</p>
```

It would be nice to pass both messages to the field component, what do you think ?

**Comment by jtommy** [comment]
Hi @darkylmnx,
about your request we could update message prop to accept Array too. Whether the message prop is an Array, the field'll show each message one by one. What you think about ?

**Comment by darkylmnx** [comment]
@jtommy yes that could be it, but the question of the "class" attribute will be questioned though, like if you want to pass two messages with different help types "is-danger" and "is-info" for example

**Comment by jtommy** [comment]
@darkylmnx Ok, but a given time you can have only one class (type prop) and so you have to bind (v-bind) this prop and message prop too. Otherwise what is the "general/unambiguous" condition to switch from one class to other class (type) ?

**Comment by rafaelpimpa** [comment]
If you need multiple type/messages it's better to just add simple HTML on it.

**Comment by jtommy** [comment]
https://github.com/rafaelpimpa/buefy/commit/5b51e8e2aa34da291e1039740eb94c493fd8e899
