### ISSUE TITLE
How can I hide one column in a b-table?

### ISSUE THREAD

**Issue by zhangzhen** [rafaelpimpa/buefy#203]
One can hide columns in HTML table by setting style of <tr>. For example,
`<td style="display:none;">`
How this can be done in a b-table?

Regards,
Zhen

**Comment by jtommy** [comment]
@zhangzhen Did you try the prop "visible" on b-table-column ?

**Comment by zhangzhen** [comment]
Setting the prop "visible" to false cannot hide its label.

**Comment by jtommy** [comment]
@zhangzhen Did you have an appointment example? What happen when you set visibile to false to bColumn?

**Comment by zhangzhen** [comment]
after page fresh it works. thank you.
