### ISSUE TITLE
Menu navigation rendering broken on most recent release.

### ISSUE THREAD

**Issue by mpatino117** [rafaelpimpa/buefy#204]
**Buefy** v0.4.6
**Chrome & Firefox**:

I am running on the most recent version of Buefy. All components work perfectly, however the drop-down menu navigation is shooting me a rendering error, which states name is not defined. Visually it is not working and it just displaying text as it is failing to render.

`[Vue warn]: Unknown custom element: <b-menu-item> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

**Comment by jtommy** [comment]
Hi @mpatino117, 
what is your Vue.js version ? 
Could you give us an example ?

**Comment by teleyinex** [comment]
It's happening the same to me with <b-dropdown-item>Action</b-dropdown-item>.

Vue.js 2.4.2

I just copied the example of the docs.

**Comment by rafaelpimpa** [comment]
Closing this since menu has been removed.

@teleyinex create another issue for that please!
