### ISSUE TITLE
b-table-column alignment

### ISSUE THREAD

**Issue by byronferguson** [rafaelpimpa/buefy#207]
### Overview of the problem

**Buefy** version: [0.4.3]
**Vuejs** version: [2.4.2]
**OS/Browser**:

### Description

The current default alignment for all columns is "left". It would be great to have the option of specifying an alignment of: left, center, right as a prop.

### Suggested behavior

```
<b-table-column field="name" label="Name" sortable>
    {{ props.row.name }}
</b-table-column>

<b-table-column field="price" label="Price" align="right" sortable>
    {{ props.row.price | currency }}
</b-table-column>

<b-table-column label="Action" align="center" valign="middle">
    <a class="button is-success" @click="addToList(props.row)"><b-icon icon="plus" /></a>
    <a class="button is-warning" @click="updateItem(props.row)"><b-icon icon="pencil" /></a>
    <a class="button is-danger" @click="removeItem(props.row)"><b-icon icon="times" /></a>
</b-table-column>
```

**Comment by rafaelpimpa** [comment]
Didn't add the valign suggestion because it should be a row-level option, better to do it with custom css.

**Comment by itsmatteomanf** [comment]
Yeah, but you added the centered prop, but what about right align @rafaelpimpa?

**Comment by NERDYLIZARD** [comment]
Try `cellClass` property
`<b-table-column cellClass="has-text-right"></b-table-column>`
