### ISSUE TITLE
[QUESTION] about b-panel, why v-if and not v-show ?

### ISSUE THREAD

**Issue by darkylmnx** [rafaelpimpa/buefy#209]
This is more a question than an issue and since there's not a dedicated forum i'm asking here :)

Why did you use a `v-if` for the `b-panel` component when it's **collapsible** and not a `v-show` or an **is-open** class on the **panel element** ?

**Comment by jtommy** [comment]
@darkylmnx your question is correct.  We know the difference between the two directive but when i made that component i added the inner div to avoid transition group. We'll update It soon. Thanks

**Comment by darkylmnx** [comment]
okay no prob :) @jtommy 

And a suggestion would be to place the toggle in absolute position relative to the heading, and put a right padding on the heading.

Why ? Because i can't use a **block **element** as header **slot**, when i put a block element, the toggle goes at the bottom, and it would be nice to chose the heading tag or at least make it a div because it's weird to have **h2** in a **p** for example.

In my case i have something like

```
<b-panel class="Feed-info is-danger"
    :collapsible="true"
    :open="false">
    <h2 slot="header">Nouveaux challenges de la semaine</h2>

    <div class="content">
      <h3>
        Subtitle
      </h3>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br />
        Nulla accumsan, metus ultrices eleifend gravida, nulla nunc varius lectus, nec rutrum justo nibh eu lectus. <br />
        Ut vulputate semper dui. Fusce erat odio, sollicitudin vel erat vel, interdum mattis neque.
      </p>
    </div>
  </b-panel>
```
