### ISSUE TITLE
Table checked also calls select event handler

### ISSUE THREAD

**Issue by proehlen** [rafaelpimpa/buefy#21]
I have a table that is checkable and selectable.  With both these options set, clicking the checkbox results in the select callback being called first without any way to determine if the select was triggered by a check. 
 Since my code navigates on select, the check callback is never called.  If I set selectable to false or remove the navigation code in the select callback, then the check callback behaves as expected.

**Comment by rafaelpimpa** [comment]
Gonna take a look at it tomorrow, thanks!

**Comment by proehlen** [comment]
Thanks.  Just to be clear, I'm not entirely sure that it's a bug.  It may be a use-case that buefy doesn't support. But thanks for taking the time to look at it. 

Ideally, for my use case, I'd like the check not to call select or, alternatively, some additional event parameter in the select callback that I can test to know it was triggered by a check and therefore ignore it.

**Comment by rafaelpimpa** [comment]
Actually, I thought that the select event was never being called? If both are being called then it's working as intended.

**Comment by proehlen** [comment]
Ok thanks, could you maybe suggest any work around for me?

I wan't to navigate via vue router on row selection (to the row detail page) and I also independently want the ability to be able to check rows to perform multi-row actions (ie without navigation).  I have no way of preventing the navigation at present in my select callback as I can't tell it was only triggered by the user checking a row.

If it can't be done then I'll have to live with it and you can close the issue.

**Comment by rafaelpimpa** [comment]
The way I thought when doing this (because I will also use it like you) was:

- The user selects the row whenever he wants
- If anything is selected, show or enable a button to navigate to the detail page
- Add the double-click event for a faster approach

**Comment by proehlen** [comment]
Ok thanks, will give that a try.

And thanks for Vuefy. I've almost finished a small app and its been very pleasant to work with.

**Comment by rafaelpimpa** [comment]
Thanks a lot! Appreciate it :)

**Comment by mateuswetah** [comment]
Hi @rafaelpimpa.

Although I understand your proposed way to use it, I really think this is a design choice. By limiting the selectable only for check (when checkable is activated) you would limit our interactions with table. It took me a time to figure out situations where this would be really not desired, but some designers working with me gave a clear example:

On Gmail's, if you click on a row (not only on text, but any place on row), you go the selected email. While checkbox is still there to perform a multiple selection. So I guess there must be a way to perform a click on a row and still do the check action isolated. 

For now my temporary solution is to wrap b-table-column with a router-link, but this only makes inner text clickable...

**Comment by subins2000** [comment]
Yes, as @mateuswetah pointed out, feature request : Allow both selectable (multiple selections too) and checkbox

**Comment by subins2000** [comment]
I achieved both selectable and checkable with :
```
<b-table
  :data.sync="torrents"
  :checked-rows.sync="tableCheckedRows"
  checkable
  checkbox-position="left"
  focusable
  :selected.sync="tableSelectedRow"
  v-click-outside="onOutsideClick"></b-table>
```
data :
```js
data () {
  return {
    tableCheckedRows: [],
    tableSelectedRow: {}
  }
}
```
and getting the rows with :
```js
getSelectedRows () {
  if (this.tableCheckedRows.length === 0) {
    return [this.tableSelectedRow]
  } else {
    return this.tableCheckedRows
  }
},
doSomethingWithRows () {
  const rows = this.getSelectedRows()
    for (const key in rows) {
      console.log(key)
    }
  }
}
```
