### ISSUE TITLE
 Undefined variable: "$table-row-active" with bulma 0.5.0

### ISSUE THREAD

**Issue by darkylmnx** [rafaelpimpa/buefy#210]
### Overview of the problem

**Buefy** version: 0.4.6
**Vuejs** version: 2.4.0
**OS/Browser**: all (error at compile)
bulma version: 0.5.0

### Description

![image](https://user-images.githubusercontent.com/1426357/28749881-a547f58e-74d6-11e7-92f7-3572a92bdae9.png)

### Steps to reproduce
error occurs when loading bulma 0.5.0

### Expected behavior
to run like normally

### Actual behavior
no compile possible

**Comment by rafaelpimpa** [comment]
I haven't updated to use Bulma 0.5 yet.

**Comment by darkylmnx** [comment]
That's what I figured so I rolled back my Bulma version

Le 31 juil. 2017 1:32 PM, "Rafael Beraldo" <notifications@github.com> a
écrit :
