### ISSUE TITLE
b-table dont have header when rendered server-side

### ISSUE THREAD

**Issue by Xelia** [rafaelpimpa/buefy#213]
**Buefy** version: [0.4.6]
**Vuejs** version: [2.4.2]
**OS/Browser**:  all(ssr issue)

### Description

When b-table is server side rendered table has no headers(column titles), header appears only after hydration, (if you disable client side js, header does not appear)

### Steps to reproduce

Try using b-table with ssr(nuxt for example)

### Expected behavior

Table has header

### Actual behavior

Table has no header, if js is enabled header appears after hydration

**Comment by rafaelpimpa** [comment]
This has been fixed after 0.5
