### ISSUE TITLE
Customizable table headers

### ISSUE THREAD

**Issue by gfviegas** [rafaelpimpa/buefy#215]
### Overview of the problem
**Buefy** version: 0.4.6
**Vuejs** version: 2.3.3
**OS/Browser**: Any

### Description
I'm trying to add a tooltip to a `b-table` column, to better describe what it means.

### Steps to reproduce
Add a `b-tooltip` tag before `b-table-column` inside a `template(scope="props")` on a `b-table`.

### Expected behavior
Tooltip added in table column

### Actual behavior
Error since we cant add anything but a `b-table-column`.

**Comment by Xelia** [comment]
In other words it would be nice to have ability to customize table headers
