### ISSUE TITLE
Customize buefy

### ISSUE THREAD

**Issue by Pakovia** [rafaelpimpa/buefy#22]
Hi, I don't know how to customize buefy sass file in vue-cli project. Followed documentation but without success. Thank you

**Comment by rafaelpimpa** [comment]
If you don't give any other info, code, I can't help

**Comment by Pakovia** [comment]
for example when i create a project with "vue init webpack-simple.." 1st step is to install "npm install buefy -S". What do i have to do in 2nd step? Create a new file with variables? add something to webpack? 3rd step- where to put those import statements? Into style tag in vue component or into entry .js file?
Thank you

**Comment by rafaelpimpa** [comment]
* You don't have to add anything else to webpack
* Yes, you can use another file for the variables or put it in the <style> tag in your App.vue
* The import statement can be in your index.js or in your App.vue

Just make sure webpack-simple has ``sass-loader`` and ``node-sass``, or just use the webpack (non simple)

**Comment by rafaelpimpa** [comment]
I'm gonna create a repo with a basic setup and link to you

**Comment by rafaelpimpa** [comment]
That's all I can do for you: [buefy-simple](https://github.com/rafaelpimpa/buefy-simple), I think you can now sort things off.

**Comment by Pakovia** [comment]
Great, Thank you!
