### ISSUE TITLE
Support for footer on table

### ISSUE THREAD

**Issue by oppiansteve** [rafaelpimpa/buefy#223]
Apologies if this has been raised, or if there is a published roadmap/plan, but I couldn't find it.

### Overview of the problem

I'd like to add a (totals) footer onto my table and can't see a way to do it currently.

**Buefy** version: 0.4.5
**Vuejs** version: 2.4.1
**OS/Browser**: Google Chrome Mac 59.0.3071.115 (Official Build) (64-bit)

### Description

I guess I could try adding it as a row and customise the sort to always leave it at the bottom (including when paginated) and add custom styling etc. but having support for a custom footer directly would be very useful.

Potentially, just a named slot for footer content would allow me to keep going.

And later could come components for `<b-table-column-footer>` or an extension to `<b-table-column>` to add a footer slot in it etc.

### Steps to reproduce

n/a

### Expected behavior

n/a

### Actual behavior

n/a

**Comment by byronferguson** [comment]
I second that a footer slot would be neat to have

**Comment by alqu** [comment]
Me too.

**Comment by serdem** [comment]
+1
