### ISSUE TITLE
Options are empty when clicking the select element in Chromium

### ISSUE THREAD

**Issue by Gerche** [rafaelpimpa/buefy#225]
### Overview of the problem
I tried to open the select elements on https://buefy.github.io/#/documentation/select but the options are empty.

**Buefy** version: [X.X.X]
**Vuejs** version: [X.X.X]
**OS/Browser**: Ubuntu 16.04 / Chromium 59.0.3071.109 (64-bit)

### Description

I'm not sure what versions the documentation site uses so I left these blank. The problem is that the select item doesn't show the options the first time i click on it. (It works on the second try though).
As soon as i refresh the page the bug returns most of the time (It works 1 out of 3 times).
I did not experience this issue with Chrome (58.0.3029.96).

![screenshot from 2017-08-07 14-50-31](https://user-images.githubusercontent.com/16115263/29027539-605c04ea-7b81-11e7-8f2d-eb8907aa6ac9.png)

### Steps to reproduce

1. Go to https://buefy.github.io/#/documentation/select
2. Click on the select element
3. If the bug did not occur refresh and try again

### Expected behavior

I expect to see the options.

### Actual behavior

I see an empty box.

**Comment by iwan-wijaya** [comment]
Just tested this using the exact same browser, It's not happening here. Any console errors?

**Comment by Gerche** [comment]
No, I'm afraid the console seems fine.

**Comment by rafaelpimpa** [comment]
Nothing wrong here either, FF54 / Chrome59. Did a few refreshs on both.

**Comment by Gerche** [comment]
I've tried to reproduce the problem with Debian 8.7 Chromium 57 and some other operating systems with chromium but no luck. I Still have the issue in my Ubuntu/Chromium setup though.

**Comment by Gerche** [comment]
I am also unable to reproduce the bug in this fiddle https://jsfiddle.net/ddawwqeq/
It seems to only occur on the documentation website.

**Comment by Gerche** [comment]
Closing this since it can't be reproduced.
