### ISSUE TITLE
Checked rows on Table do not set checkedRows

### ISSUE THREAD

**Issue by johnwebbcole** [rafaelpimpa/buefy#228]
### Overview of the problem

**Buefy** version:0.5.0
**Vuejs** version:2.4.2
**OS/Browser**: Windows 10 /Chrome 60.0.3112.90

### Description

There seems to be an issue with checked rows on the Table.  After upgrading to 0.5.0 our tables with checkboxes no longer function correctly.  

You can see this on the [documentation page](https://buefy.github.io/#/documentation/table).  Clicking on the `check all` does not check all.  checking any row does not add it to the `checkedRows` array.  The `clear checked` button is never enabled when rows are checked.

![image](https://user-images.githubusercontent.com/230922/29097028-4e4c5750-7c5d-11e7-96b2-fa5d06e3c4a2.png)

### Steps to reproduce
Go to the [Table](https://buefy.github.io/#/documentation/table) documentation page and enable `checkable`.   Click the checkbox on any row.

### Expected behavior

Previous versions would put the checked row in the `checkedRows` array.

### Actual behavior

The `checkedRows` array is empty.

**Comment by johnwebbcole** [comment]
Thanks for the quick fix... any idea on when the next release will happen?

**Comment by leesand1** [comment]
Hope we have a release for this soon - can't update without this 😢
