### ISSUE TITLE
Demo page is not updated

### ISSUE THREAD

**Issue by prsolucoes** [rafaelpimpa/buefy#229]
Hi,

Demo page is not updated to new buefy version with bulma 5.

It will be updated?

Thanks for the good work.

**Comment by rafaelpimpa** [comment]
Which demo page?

**Comment by koerbaecher** [comment]
Guess he means this: https://github.com/rafaelpimpa/buefy-simple

**Comment by rafaelpimpa** [comment]
Buefy-simple repo is just to show how to customize, its still the same way.
