### ISSUE TITLE
New select component broken on mobile screens

### ISSUE THREAD

**Issue by rodymol123** [rafaelpimpa/buefy#23]
First of all: the new select component is great. 

However, it does have a bug. When opened, the select options float out of view in the top right corner of the screen instead of, what I assume is the intention, in the middle of the screen like dropdowns, which work as intended.

I really love your work on Buefy :)

**Comment by rafaelpimpa** [comment]
Thanks, looks like the page layout is overflowing because of the Addons, taking a closer look.
