### ISSUE TITLE
Problem with b-menu-item

### ISSUE THREAD

**Issue by teleyinex** [rafaelpimpa/buefy#232]
Buefy v0.4.6
Chrome & Firefox:

I am running on the most recent version of Buefy installed via npm.

If I use the following component: `**<b-dropdown-item>Action</b-dropdown-item>**.` I get the following error:

[Vue warn]: Unknown custom element: <b-menu-item> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

I'm running Vue.js 2.4.2

Cheers.

**Comment by Tirke** [comment]
Hello,

You are not using the latest Buefy version which is v0.5.0.
In v0.5.0 `b-dropdown-option` was renamed to `b-dropdown-item`.

So ... with you current version you need to use `b-dropdown-option` 😄

**Comment by teleyinex** [comment]
So the docs are missing that. I'm actually using v0.5.0 (:facepalm:). The problem has been the docs:

https://buefy.github.io/#/documentation/dropdown

**Comment by teleyinex** [comment]
Now working without any issues!
