### ISSUE TITLE
Checkable Table and Server-Side Pagination, Filtering and Sorting 

### ISSUE THREAD

**Issue by daenuprobst** [rafaelpimpa/buefy#235]
### Overview of the problem

**Buefy** version: 0.5.0
**Vuejs** version: 2.4.2
**OS/Browser**: Ubuntu 16.04.3 / Firefox, Chrome, Chromium

### Description

In a table which is paginated, filtered and sorted server-side, checked rows are not preserved in the table, however the rows are being kept in the array bound to `:checked-rows.sync`.

### Steps to reproduce

1. Implement a server-based pagination.
2. Check columns on page one.
3. Switch to page two.
4. Go back to page one.
5. Rows are no longer checked. Check more rows, including the ones checked before.
6. Inspect the array bound to  `:checked-rows.sync`. All rows checked have been added to the array, the once that have been checked twice were added to the array twice.

### Expected behavior

Rows should be checked and stay checked even after server-side pagination, filtering and sorting. 

### Actual behavior

See "Steps to reproduce"

**Comment by jtommy** [comment]
@daenuprobst Thanks.
We added a new function prop called 'custom-is-checked'. You can use it to compare two element by their properties (i think for example "id" property into your data array)

**Comment by daenuprobst** [comment]
Nice! Exactly what I needed. I imagine that people will come across this in the future, so it (together with a server-side table implementation) might be a candidate to add to the documentation / data / table page.

**Comment by martymclaughlan** [comment]
Hello - Is there any instructions/examples on how to implement this function?

**Comment by jtommy** [comment]
@martymclaughlan There is no example in the official docs but in the API section there is custom-is-checked function description. https://buefy.github.io/#/documentation/table

**Comment by martymclaughlan** [comment]
"Function (a: Object, b: Object)"

Do you know what a/b are?

**Comment by jtommy** [comment]
Yes, A and B are elements of checkedRows array.
