### ISSUE TITLE
Reload Table columns

### ISSUE THREAD

**Issue by kletteraffe11** [rafaelpimpa/buefy#239]
### Overview of the problem

**Buefy** version: [0.5.0]
**Vuejs** version: [2.4.2]
**OS/Browser**: Chrome / Firefox on Windows and Mac

### Description

I'm using `b-table` in a component with asynchronous loaded data inputs. Often the column names of the inputs distinguish. Changing the data a few times results in all column names used added up:

![2017-08-11 10_00_08-netdoghapi](https://user-images.githubusercontent.com/7096010/29205383-c1ddb65c-7e7c-11e7-8676-53e311b8ba3f.png)

The marked ones are the ones currently needed. Reloading the whole page solves the problem.

Would it be possible to create a function to reload the columns? Looking at the Vue Chrome Plugin, you can see the columns property of `b-table` growing. 

![image](https://user-images.githubusercontent.com/7096010/29206060-83b06e16-7e80-11e7-8f1a-8cf593215d96.png)

Thanks for the great plugin!

**Comment by Tirke** [comment]
Vue is a very reactive framework and b-table is also reactive to changes so, I think it's your fault if the columns keep growing.
Although I don't have your exact context, you should try clearing your data array when you fetch new data ...

**Comment by kletteraffe11** [comment]
Thanks for the hint to clear my data array. 

I'm creating my columns dynamically like this: 
```html
 <template scope="props">
        <template v-for="(entry,keymain) in props.row">
          <b-table-column :field="keymain" :label="keymain">
            <template>{{ entry }}</template>
          </b-table-column>
        </template>
      </template>
</template>
```
I'm watching for a route change to refresh my data array. Clearing the data array instead of refreshing at this point results in an empty table. However the columns stay the same.

```javascript
watch: {
      '$route': function () {
        this.tableData= []
        /* this.tableData$refresh() */
      }
    }
```
Shouldn't the columns be empty when I set `tabledata = []`?

**Comment by Xelia** [comment]
I have same problem on page change: when vue decides to reuse old table on route change old and new columns mix.

**Comment by Tirke** [comment]
@kletteraffe11 Oh, ok I see interesting. This needs investigation :)

**Comment by Xelia** [comment]
Here is reproduction of column bug: http://jsfiddle.net/pd98s4pn/ switch between routes 1 and 2 few times

**Comment by rafaelpimpa** [comment]
Thanks for the repro!

**Comment by Tirke** [comment]
@Xelia Your repro doesn't repro anything for me after switching 20 times +

**Comment by rafaelpimpa** [comment]
This is a better approach: http://jsfiddle.net/rafaelpimpa/pd98s4pn/1/

**Comment by kletteraffe11** [comment]
This is my use case : http://jsfiddle.net/gmm2f74t/2/

Where should I add the key prop?

**Comment by Xelia** [comment]
Well, visible prop solves my case good enough, it makes actual columns stay same and it works. But issue is still there when coulmns really need to be dynamic(loading from backend for example).

**Comment by rafaelpimpa** [comment]
@kletteraffe11 in the ``b-table-column``: http://jsfiddle.net/rafaelpimpa/gmm2f74t/3/.

@Xelia can you elaborate better? I can't see how it's different, visible prop will work either way.

**Comment by Xelia** [comment]
Example with v-for and key still have same issue

**Comment by rafaelpimpa** [comment]
Couldn't repro, open another issue with examples if needed.

**Comment by kletteraffe11** [comment]
@rafaelpimpa I don't see where your jsfiddle is working. The two buttons insert different data into the table. Clicking the first button results in a nicely displayed table. If you click the second "Hit me!" Button afterwords the new data gets inserted correctly. But if you look at the column names you can still see the old names. If you insert an empty array into the table the columns still stay the same. 

This was my intentional reason for opening this issue therefore i don't see a reason to open a new issue.

**Comment by rafaelpimpa** [comment]
Oh my bad I didn't realise that, let me see.

**Comment by rafaelpimpa** [comment]
You can reset the columns by doing this:

```javascript
this.$refs.table.columns = []
```

See http://jsfiddle.net/rafaelpimpa/gmm2f74t/4/

I can add a method for that later.

**Comment by kletteraffe11** [comment]
Thank you this solves my issue!

**Comment by rafaelpimpa** [comment]
Next release it's gonna work automatically 👍
