### ISSUE TITLE
Add optional "Show Password" label to password-reveal

### ISSUE THREAD

**Issue by evangipson** [rafaelpimpa/buefy#24]
When using a password input:
```
<b-input type="password"
        placeholder="Password reveal input"
        password-reveal>
```
It'd be nice if you could hover on the eye and a label would appear that says "Show Password", maybe with another optional flag like password-reveal-tooltip, so the use would be something like this:
```
<b-input type="password"
        placeholder="Password reveal input"
        password-reveal
        password-reveal-tooltip="Show Password">
```

**Comment by rafaelpimpa** [comment]
Doen anyone else missed this?

**Comment by evangipson** [comment]
First of all, thanks so much for this framework! It's so great!

I'm using it here: http://evangipson.com/vueture/#/login (you can check the code here: https://github.com/evangipson/vueture-game)

The UI is so clean and great, but I think a curious user could really benefit from some contextual tooltip.

**Comment by rafaelpimpa** [comment]
Actually, as you said (and I was thinking about this) it's meant to be very clean. The best option IMO here is you use the input with a button add-on and add the tooltip in the button yourself.

**Comment by rafaelpimpa** [comment]
I'm fixing that error on ``password-reveal`` icon with the invalid icon.
