### ISSUE TITLE
B-field does not show the icon on the right when dynamically binding the type.

### ISSUE THREAD

**Issue by norbert-berenyi** [rafaelpimpa/buefy#240]
### Overview of the problem

**Buefy** version: 0.5.0
**Vuejs** version: 2.4.2
**OS/Browser**: Chrome

### Description

B-field does not show the icon on the right when dynamically binding the type using the object syntax.

#### HTML
``` html
<!-- Shows the icon on the right side of the input field. -->
<b-field label="Name" type="is-danger">
    <b-input value="John Silver"></b-input>
</b-field>

<!-- Shows the icon on the right side of the input field. -->
<b-field label="Name" 
         :type="type">
    <b-input value="John Silver"></b-input>
</b-field>

<!-- Does not shows the icon on the right side of the input field. -->
<b-field label="Name" :type="{'is-danger':error}">
    <b-input value="John Silver"></b-input>
</b-field>
```

#### JS
``` javascript
Vue.use(Buefy.default);

var App = new Vue({
    el: '#app',
    data: {
      error: true,
      type: 'is-danger' 
    }
});
```

### Steps to reproduce

https://codepen.io/norbert-berenyi/pen/qXjoqj

**Comment by Tirke** [comment]
For `b-field` type props should be a string and you are giving it an object. 
I you want a dynamic type please use a String. 
Also I understand your use case of if there is an error this should be of type error but juste use something like :

```javascript
checkForm () {
  if(error) this.type = 'is-danger'
  else this.type = ''
}
```

**Comment by rafaelpimpa** [comment]
Exactly what Tirke commented, ``type`` prop only accepts string.
