### ISSUE TITLE
Tab of b-tab-items bound to an array stays in tab nav when removed from array

### ISSUE THREAD

**Issue by daenuprobst** [rafaelpimpa/buefy#241]
### Overview of the problem

**Buefy** version: [0.5.0
**Vuejs** version: 2.4.2
**OS/Browser**: Ubuntu 16.04.3 / Firefox, Chrome, Chromium

### Description

When `b-tab-items` are "bound" to an array `items` like

```html
<b-tabs v-model="activeTab" type="is-boxed">
  <b-tab-item v-for="item in items" :label="item.title">
    <div>{{ item.content }}</div>
  </b-tab-item>
</b-tabs>
```

and an element is removed from the array

```javascript
remove: function(index) {
  this.items.pop(index);
}
```
The content is removed, however the tab ("header") stays in the nav.

### Steps to reproduce

1. Setup a `b-tabs` elements as shown in the description.
2. Create a button which calls the function `remove` as shown in the description.
3. Use the button to remove elements from the array.

### Expected behavior

The `b-tab-item` should be completely removed.

### Actual behavior

The content of `b-tab-item` is removed, however the tab "head" is still in the nav element and can also be clicked / activated.

**Comment by jtommy** [comment]
@daenuprobst thanks but you have to remember to update bTabs v-model value after remove

**Comment by daenuprobst** [comment]
Thanks a lot!
