### ISSUE TITLE
b-table-column default sort direction

### ISSUE THREAD

**Issue by byronferguson** [rafaelpimpa/buefy#243]
### Overview of the problem

**Buefy** version: [0.5.0]
**Vuejs** version: [2.3.4]
**OS/Browser**:

### Description

I have several use cases where it would be useful to be able to specify the default sort direction on the initial click of the column. Subsequent clicks would perform the default action of resorting in the opposite direction. However, the current implementation is to always sort ASC on the first click.

Overriding the sort function to is possible; however, the directional arrows would be in direct opposition to the actual order of the field.

**Comment by alqu** [comment]
Nearly the same on my use case:
I have backend sorting enabled and it would be cool to mark a column initially sorted from the beginning, since the data always comes sorted back from the server.
