### ISSUE TITLE
When two or more detail rows are open, errors occur by sorting table headers or clicking pagination buttons

### ISSUE THREAD

**Issue by sanderheilbron** [rafaelpimpa/buefy#246]
### Overview of the problem

**Buefy** version: 0.5.0
**Vuejs** version: 2.4.2
**OS/Browser**: MacOS 10.12.5 / Chrome 60

### Description
1. By opening two or more detail rows, errors occur when clicking a table header to sort data. Different errors could show up, this depends on which column is clicked to sort the data.

2. By opening two or more detail rows, errors occur when clicking pagination buttons. 

### Steps to reproduce
1.1 First Step
Open two or more detail rows.

1.2 Second Step
Click a table header once or a few times (the number of times differs per column) to sort a column.

1.3 Third step 
The details row isn't visible below its 'parent' row and the following errors occur:

In production:
* ```TypeError: Cannot read property 'key' of undefined```

OR

* ```DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node. ```

In development:
* ``` [Vue warn]: It seems there are duplicate keys that is causing an update error. Make sure each v-for item has a unique key.```
* ```[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'key' of undefined"```
* ```TypeError: Cannot read property 'key' of undefined```

OR

* ```[Vue warn]: Error in nextTick: "NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node."```
* ``` DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.```

2.1 First Step
Open two or more detail rows.

2.2 Second Step
Click pagination button for page 'two' and then click on pagination button for page 'one'.

2.3 Third step 
The following errors occur:

In production:
* ```TypeError: Cannot read property 'key' of undefined```

In development:
* ``` [Vue warn]: It seems there are duplicate keys that is causing an update error. Make sure each v-for item has a unique key.```
* ```[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'key' of undefined"```
* ```TypeError: Cannot read property 'key' of undefined```

### Expected behavior
By opening two or more details rows, it is expected each detail row remains visible below their 'parent' row after sorting columns. It is also expected that sorting will continue to work.

By opening two or more details rows, it is expected pagination will continue to work.

### Actual behavior

By opening two or more details rows, each detail row is disconnected from their 'parent' row after sorting columns. A details row appears below another 'parent' row. Sorting of columns stops working.

By opening two or more details rows, pagination stops working after clicking a pagination button followed by clicking the pagination button for page 'one'.

**Comment by Tirke** [comment]
Ok thanks for the detailed report, the fix is actually quite easy for this one, will PR.
