### ISSUE TITLE
Table row selection not working in Chrome (macOS Sierra)

### ISSUE THREAD

**Issue by jivemonkey2000** [rafaelpimpa/buefy#252]
### Overview of the problem

**Buefy** version: [0.5.0]
**Vuejs** version: [2.4.2]
**OS/Browser**: MacOS Sierra/ Chrome

### Description

Checking rows on the table component does not update 'selected-rows' prop and checking 'select all' checkbox does not change the selected state of any rows.

### Steps to reproduce

1. Go to https://buefy.github.io/#/documentation/table
2. Check the 'checkable' switch
3. Check any number of rows or check 'check all' box

### Expected behavior

'selected-rows' should reflect rows that are selected.

### Actual behavior

'selected-rows' is an empty array.

### Screenshots

<img width="571" alt="screen shot 2017-08-15 at 16 13 06" src="https://user-images.githubusercontent.com/17082749/29322207-a39d044e-81d4-11e7-98c1-e64ea172e52a.png">
<img width="512" alt="screen shot 2017-08-15 at 16 13 12" src="https://user-images.githubusercontent.com/17082749/29322206-a39b1422-81d4-11e7-9076-2d3c00d98540.png">
<img width="429" alt="screen shot 2017-08-15 at 16 12 54" src="https://user-images.githubusercontent.com/17082749/29322208-a39ec644-81d4-11e7-82fe-d57af7999476.png">

**Comment by jtommy** [comment]
Fixed #228
