### ISSUE TITLE
Error in generating app.css

### ISSUE THREAD

**Issue by tanhs** [rafaelpimpa/buefy#253]
I run npm run dev it show errors

      Undefined variable: "$dropdown-item-hover-background-color".
      in c:\xampp\htdocs\dmarketer\node_modules\buefy\src\scss\components\_autocomplete.scss (line 13, column 25)

 @ ./resources/assets/sass/app.scss 4:14-266
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

 error  in ./resources/assets/sass/app.scss

Module build failed: ModuleBuildError: Module build failed:
            background: $dropdown-item-hover-background-color;
                       ^
      Undefined variable: "$dropdown-item-hover-background-color".
      in c:\xampp\htdocs\dmarketer\node_modules\buefy\src\scss\components\_autocomplete.scss (line 13, column 25)
    at runLoaders (c:\xampp\htdocs\dmarketer\node_modules\webpack\lib\NormalModule.js:194:19)
    at c:\xampp\htdocs\dmarketer\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at c:\xampp\htdocs\dmarketer\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (c:\xampp\htdocs\dmarketer\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (c:\xampp\htdocs\dmarketer\node_modules\sass-loader\lib\loader.js:55:13)
    at Object.<anonymous> (c:\xampp\htdocs\dmarketer\node_modules\async\dist\async.js:2244:31)
    at Object.callback (c:\xampp\htdocs\dmarketer\node_modules\async\dist\async.js:906:16)
    at options.error (c:\xampp\htdocs\dmarketer\node_modules\node-sass\lib\index.js:294:32)

**Comment by rafaelpimpa** [comment]
Use issue template

**Comment by tylerjheslop** [comment]
Check your package.json. I was facing the same issue but the following fixed it AFAIK. I'll update you as I work on it.
`"buefy": "^0.5.0",
    "bulma": "^0.5.0",`

**Comment by tanhs** [comment]
What I have done.  It resolved my problem.
`
c:\xampp\htdocs\dmarketer>npm update

c:\xampp\htdocs\dmarketer>npm outdated
Package  Current  Wanted  Latest  Location
bulma      0.4.4   0.4.4   0.5.1

c:\xampp\htdocs\dmarketer>ncu --upgrade bulma
Using c:\xampp\htdocs\dmarketer\package.json
[..................] - :
 bulma  ^0.4.4  →  ^0.5.1

Upgraded c:\xampp\htdocs\dmarketer\package.json


c:\xampp\htdocs\dmarketer>npm outdated
Package  Current  Wanted  Latest  Location
bulma      0.4.4   0.5.1   0.5.1

c:\xampp\htdocs\dmarketer>npm update
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","ar
ch":"x64"})

+ bulma@0.5.1
added 114 packages and updated 1 package in 16.258s
`
