### ISSUE TITLE
Blur event doesn't trigger when a field is not valid

### ISSUE THREAD

**Issue by yarbshk** [rafaelpimpa/buefy#255]
### Overview of the problem

**Buefy** version: 0.5.0
**Vuejs** version: 2.4.1
**OS/Browser**: Opera 46.0

### Description

Hi, Rafael. I'm develop own plugin based on your library and today was discovered that you **change  behavior of a blur event** for the Input component as a result the plugin behaves pointless. 

Older versions of Buefy was emitted blur event independent of checking HTML5 validity. However v0.5.0 has strict dependency `@blur="checkHtml5Validity() && $emit('blur', $event)"`. IMHO: It's not proper to mute a blur event when a field isn't valid because this behavior isn't logical and hasn't native ground:

> [MDN](https://developer.mozilla.org/en-US/docs/Web/Events/blur): The blur event is fired when an element **has lost focus**.

**Could you explain your choice, please? Can you revert the behavior of blur event?**

### Steps to reproduce

1. Focus an input field => Then blur (all's well because the field is valid).
2. Focus an input field => Then remove all characters => Then blur again (oops, the field is danger but an error message doesn't show because blur event doesn't work properly when field doesn't pass HTML5 validity)!

### Expected behavior

I expect the behavior of blur event the same as in **v0.4.6** for example.

### Actual behavior

Doesn't emit a blur event when an input field doesn't pass HTML5 validty.

**Comment by rafaelpimpa** [comment]
This is already fixed: https://github.com/rafaelpimpa/buefy/issues/237, available for next release
