### ISSUE TITLE
Uncaught TypeError: Cannot read property 'install' of undefined

### ISSUE THREAD

**Issue by tanhs** [rafaelpimpa/buefy#256]
### Overview of the problem

**Buefy** version: ["^0.5.0"]
**Vuejs** version: [^2.4.2]
**OS/Browser**: Chrome

### Description
It shows me error when run in browser in the app.js file when I include this 2 lines.
import Buefy from 'buefy';
Vue.use(Buefy.Default);
During compilation using npm run dev, no error message prompted.

Error:
Uncaught TypeError: Cannot read property 'install' of undefined
    at Function.Vue.use (app.js:sourcemap:36044)
    at Object.<anonymous> (app.js:sourcemap:806)
    at __webpack_require__ (app.js:sourcemap:20)
    at Object.defineProperty.value (app.js:sourcemap:775)
    at __webpack_require__ (app.js:sourcemap:20)
    at app.js:sourcemap:63
    at app.js:sourcemap:66

### Steps to reproduce

1. npm install buefy
2. Add in this 2 lines into the app.js
import Buefy from 'buefy';
Vue.use(Buefy.Default);
3. run npm run dev to get the app.js in the public folder
4. it shows above error in the console
5. What I have in the php file 
```

 <div id='app'>
        <example></example>
      </div>
        <script src='{{ asset('js/app.js') }}'></script>     

```    
<img width="932" alt="screen shot 08-16-17 at 01 29 pm" src="https://user-images.githubusercontent.com/1995229/29348661-ee8330b0-8287-11e7-9e57-8ff4f1034cee.PNG">

### Expected behavior

No error in the console and show Example template in the browser.

### Actual behavior

Error appearing in the console.   Screen attached.
<img width="932" alt="screen shot 08-16-17 at 01 29 pm" src="https://user-images.githubusercontent.com/1995229/29348678-05ddd9a4-8288-11e7-80a8-5a0ffc2fb070.PNG">

**Comment by iwan-wijaya** [comment]
```
import Vue from 'vue'
import Buefy from 'buefy'
import 'buefy/lib/buefy.css'

Vue.use(Buefy)
```

No need for `.default` using imports. `.default` is only needed if you are not using a bundler (webpack).

**Comment by tanhs** [comment]
I have removed the .default and it works now.  Thanks.

**Comment by saidlagauit** [comment]
import { createApp } from "vue";
import Buefy from "buefy";
import App from "./App.vue";
createApp(App).use(Buefy.Default).mount("#app");
