### ISSUE TITLE
b-field type does not show icons 

### ISSUE THREAD

**Issue by OGhawsi** [rafaelpimpa/buefy#259]
#
![buefy](https://user-images.githubusercontent.com/30488194/29408011-d14accd6-835b-11e7-821d-872d9fea48c8.png)

### Overview of the problem

**Buefy** version: [0.5.0]
**Vuejs** version: [2.1.10]
**OS/Browser**:Chrom Ubuntu Linux

### Description
``
<b-field label="Email"
    type="is-danger"
    message="This email is invalid">
    <b-input type="email"
        value="john@"
        maxlength="30">
    </b-input>
</b-field>
``
### Expected  @rafaelpimpa 

When I type a wrong email id it alerts the danger type but the small icon on the right-hand side of the input field is not shown instead it shows a message on that corner saying "ERROR" or for other types, it says like "WARNING" or "INFO" etc.
Thanks in advance.

**Comment by jtommy** [comment]
@OGhawsi Did you import font-awesome or material icons? Is it working?

**Comment by thamibn** [comment]
change #Vue.use(Buefy); to look like this
Vue.use(Buefy, {
    defaultIconPack: 'fa'
})

**Comment by OGhawsi** [comment]
Thanks so much @thamibn it worked.
