### ISSUE TITLE
v-model with textarea input throwing TypeError

### ISSUE THREAD

**Issue by gwvt** [rafaelpimpa/buefy#26]
First off, great work! I love Buefy 👍👍👍 

V-model with a textarea input is throwing this error:
```
Uncaught TypeError: Cannot read property 'checkValidity' of undefined
    at VueComponent.onBlur (eval at <anonymous> (app.js:1226), <anonymous>:3:5151)
    at boundFn (eval at <anonymous> (app.js:721), <anonymous>:125:14)
    at HTMLTextAreaElement.invoker (eval at <anonymous> (app.js:721), <anonymous>:1659:18)
onBlur @ index.js?b243:3
boundFn @ vue.esm.js?65d7:124
invoker @ vue.esm.js?65d7:1658
```
For this straightforward code in my template:

`<b-input type="textarea" v-model="modelMe"></b-input>`

I tried wrapping it in a field but same result. Changing the input type to textbox resolves the issue (both for wrapped in a field and unwrapped).

**Comment by rafaelpimpa** [comment]
Have you got the new release (v0.2.0)?

**Comment by gwvt** [comment]
I just updated, it works now! Thank you very much.
