### ISSUE TITLE
b-autocomplete suggestion : default message when there is no suggestions

### ISSUE THREAD

**Issue by Yaty** [rafaelpimpa/buefy#262]
Hi,
I think it would be nice to show a message when there is no suggestions with b-autocomplete.
Maybe set a placeholder to the dropdown ? Or it could be like a [select with an error](https://buefy.github.io/#/documentation/select).

**Comment by jtommy** [comment]
@Yaty I think it's a good idea. 
We could add a new slot to show when data array (options) is empty like an item but disabled.

**Comment by Yaty** [comment]
@jtommy Something like that ?
![Screenshot](https://image.prntscr.com/image/yNAIH2WOS667D3BnWRojsA.png)
If you want I can try to add that and send a PR :)

**Comment by jtommy** [comment]
Yes, it is!
About a PR, i'm working on it. By a named slot you'll add a text (styled if you want) as empty message.
Anyway thanks!
