### ISSUE TITLE
b-table checkable don't work

### ISSUE THREAD

**Issue by pandada8** [rafaelpimpa/buefy#263]
### Overview of the problem

**Buefy** version: 0.5.0
**Vuejs** version: 2.4.2
**OS/Browser**: Chrome 59 on OSX

### Description

The table using `@change.native` to track if the row is checked, and it did not work

### Steps to reproduce

In the official [demo](https://buefy.github.io/#/documentation/table) of table, when enable checkable and check some rows, the checked rows didn't change

A possible fix could be changing the `@change.native` to `@input`, and it actually fix the problem in my environment

**Comment by jtommy** [comment]
Fixed #228
