### ISSUE TITLE
Table component row checking doesn't work in Chrome

### ISSUE THREAD

**Issue by lexuzieel** [rafaelpimpa/buefy#268]
### Overview of the problem

**Buefy** version: [0.5.0]
**Vuejs** version: [2.4.2]
**OS/Browser**: Windows/Elementary OS / Chrome (**works in Firefox**)

### Description

So this one is strange, but **Table component** `checkable` functionality doesn't seem to work in Chrome for me. At first I thought it was my mistake, but apparently it is the same on [documentation page](https://buefy.github.io/#/documentation/table).

If you try enabling `checkable` and check a couple of rows, `checkedRows` won't update in Chrome. However this appears to work as intended in Firefox.

### Steps to reproduce

1. Initialize **Table component** with `checkable` enabled in Chrome.
2. Check several (or all with checkbox in the header) rows.

### Expected behavior

Rows are checked and `checkedRows` is populated with data.

***Screenshots are taken in Firefox:***

![Visual representation](http://i.imgur.com/QmrMKRk.png)

![Populated checkedRows object](http://i.imgur.com/ycHh3Ti.png)

### Actual behavior

Checkboxes change their state visually but this doesn't affect `checkedRows`.
Also checking header checkbox doesn't do anything.

***Screenshots are taken in Google Chrome and browsers based on it:***

![Visual representation](http://i.imgur.com/JzmdAhv.png)

![Empty checkedRows object](http://i.imgur.com/uZQbcOr.png)

**Comment by jtommy** [comment]
Fixed #228

**Comment by lexuzieel** [comment]
Ah! Sorry for posting same issue for the third time, I forgot to check closed issues while searching ><
