### ISSUE TITLE
Missing placeholders

### ISSUE THREAD

**Issue by dukadin** [rafaelpimpa/buefy#270]
I updated Buefy from 0.2.2 to 0.5.0 and placeholders aren't visible anymore.

This is how I use component:
`<b-field label="Data Source">
     <b-input v-model="form.dataSource" required placeholder="Data Source"></b-input>
</b-field>`

And this is rendered DOM:
```
<div class="field">
    <label class="label">Data Source</label> 
    <div class="control is-clearfix" required="required" placeholder="Data Source">
        <input type="text" autocomplete="on" class="input"> 
        <!----> 
        <!----> 
        <!---->
    </div> 
    <!---->
</div>
```

**Comment by iwan-wijaya** [comment]
Are you using Vue 2.3?
https://github.com/rafaelpimpa/buefy/pull/242#issuecomment-321956357

**Comment by dukadin** [comment]
Yes, v2.3.4

**Comment by iwan-wijaya** [comment]
You should upgrade to 2.4

**Comment by dukadin** [comment]
Done. Now is everything ok with placeholders. Thanks 👍
