### ISSUE TITLE
Datepicker is one day off

### ISSUE THREAD

**Issue by focussing** [rafaelpimpa/buefy#275]
```
<b-field label="Startdatum">
   <b-datepicker v-model="startDate" placeholder="Selecteer..." icon="today" @click="start()"></b-datepicker>
</b-field>
<p>{{startDate}} </p>
```
Selecting a date displays day earlier

**Comment by jtommy** [comment]
@focussing Is it a problem about input or your code `<p>{{startDate}} </p>` ? startDate is a Date Object and so you have to format correctly (for example: startDate.toLocaleDateString())

**Comment by apocalyarts** [comment]
It looks like the datepicker is one day off for me when i specify the "first-day-of-week" attribute. Docs say I should use "1" for Monday but this way the editor starts on Tuesday.

**Comment by jtommy** [comment]
@apocalyarts See that https://jsfiddle.net/5oap3x65/. Is it ok ?

**Comment by apocalyarts** [comment]
@jtommy Your fiddle works.

Also, I too discovered that my calendar is one day off. I way able to narrow it down to this:

```Vue.use(Buefy, {
    defaultDateFormatter: (date) => date.toISOString().split('T')[0]
})```

Looks like this is causing the error.

**Comment by jtommy** [comment]
@apocalyarts It's a problem about your formatter. 
If you try with `date.toISOString()` (i know it isn't good but i was an example) will be correct
Anyway you can use external library (ex: moment js) or your custom function that manage Date object (https://www.w3schools.com/jsref/jsref_obj_date.asp)

**Comment by thc1967** [comment]
I'm getting this problem without doing anything seemingly special to the dates.

In my HTML:

```HTML
<b-datepicker icon="today"
    name="solution_date"
    :focused-date="new Date()"
    v-model="forms.status.solution_date">
</b-datepicker>
```

In my JavaScript:

```js
var ticketStatus = {
    data: function () {
        return {
            uriStatus: statusUris,

            forms: {
                status: {
                    assigned_to: 0,
                    corrected_by: 53,
                    disposition_id: 10,
                    reason_id: 3,
                    solution_date: new Date('2017-08-09'),
                    target_id: 365,
                }
            },
        };
    },
```

In my UI:
![corrected_on_buefy](https://user-images.githubusercontent.com/2651772/30872508-54acd03a-a2b8-11e7-9e0e-797564cefcc5.jpg)

**Comment by jtommy** [comment]
@thc1967 Where the date is not correct? In the  datepicker input?

**Comment by thc1967** [comment]
I would have expected the UI (b-datepicker) to show the date I put into the field via JavaScript:  ` solution_date: new Date('2017-08-09'),`.

Given that seed value, the UI should have shown August 9, not August 8.

Digging a bit deeper, when I look at the `b-datepicker` instance in Vue tools in Chrome, I see that it seems to have the date I expect: `dateSelected:"2017-08-09T00:00:00.000Z"` and `value:"2017-08-09T00:00:00.000Z"`.

However, when I dig down into the `b-input` child of the `b-datepicker`, I see the wrong date: `newValue:"8/8/2017"` and `value:"8/8/2017"`.

It appears that somewhere in the data exchange between the parent `b-datepicker` and child `b-input`, the date value is changing.

If I initialize with `solution_date: new Date(),`, I get the right date - today.

If I initialize with `solution_date: new Date('2017-09-26'),`, I get yesterday.

I'm starting to fear this is a timezone issue?

**Comment by jtommy** [comment]
Try `new Date('2017/09/26')` or `new Date(2017, 8, 26)`.

**Comment by thc1967** [comment]
Both of those formats result in the date I expect showing up in the UI. Intriguing.

**Comment by jtommy** [comment]
@thc1967 I'm sorry, Is it works?

**Comment by thc1967** [comment]
Yes, formatting the dates using '/' instead of '-' makes the datepicker display the right date. I don't understand why, but it works.

**Comment by jtommy** [comment]
See Date docs. It isn't an issue of datepicker component but about how to create a Date object.

**Comment by Kaeltis** [comment]
I still have this Issue, when creating a Datepicker and setting it to new Date() its working, but when selecting a date, it's setting the Date to the day before at 22:00.

```
<template>
    <div class="card-content">
        <b-field label="Date">
            <b-datepicker
                    placeholder="Select Date"
                    v-model="modelData.assignment_date"
                    icon="calendar"
                    :first-day-of-week="1"
                    :month-names="monthNames"
                    :day-names="dayNames">
            </b-datepicker>
        </b-field>

        {{ modelData.assignment_date }}
    </div>
</template>

<script>
    export default {
        data() {
            return {
                monthNames: ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"],
                dayNames: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
                modelData: {
                    assignment_date: new Date(),
                }
            }
        }
    }
</script>
```
After reloading, modelData.assignment_date is correctly set to Today
![screenshot_20171007_164541](https://user-images.githubusercontent.com/809734/31308944-0c0244b2-ab7f-11e7-9baf-b323e9e47558.png)

After picking a Day (10/6/2017), modelData.assignment_date is set to the day before the one I selected at 22:00
![screenshot_20171007_164557](https://user-images.githubusercontent.com/809734/31308949-2027df88-ab7f-11e7-948c-b14b91edc173.png)

**Comment by rikiless** [comment]
I got this problem too. When I select **16.12.2017** the value in result is: `2017-12-15T23:00:00.000Z`.

In Google Chrome's console:
```javascript
new Date();
Sat Dec 16 2017 17:56:06 GMT+0100 (CET)
```

I don't have setting default value for datepicker. Only just used v-bind:model="date" with a default value `null`). How can I fix it?

**Comment by agriboz** [comment]
I am having the same issue. Can not find any solution for that.

**Comment by jtommy** [comment]
@agriboz Could you provide the code that you're using when you send the date to the server or how to do you format the date?

**Comment by agriboz** [comment]
@jtommy here is the configuration.

```
Vue.use(Buefy, {
  defaultDayNames: ['Pz', 'Pzts', 'Sal', 'Çrş', 'Prş', 'Cuma', 'Cmts'],
  defaultMonthNames: ['Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran', 'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'],
  defaultFirstDayOfWeek: 1,
  defaultDateFormatter: date => date.toLocaleDateString('tr-Tr')
})
```

**Comment by jtommy** [comment]
@agriboz Ok, that is configuration how to you show the `datepicker` (months, days, and formatter to input) but the issue is when you send the date to the server. 
You have remember that datepicker `v-model` use a Date Object and it contains timezone information.

**Comment by agriboz** [comment]
@jtommy did you have any chance to see the video about the issue? i tried to explain as much as i can.

**Comment by jtommy** [comment]
@agriboz Yes, sure. The issue is how to you send "sentDate" param in "/supplier/email" request.
`defaultDateFormatter` prop is only to format the selected date into the input field.

**Comment by agriboz** [comment]
I didn't do any change for "sentDate" to send "/supplier/email" endpoint. Do i need to make anything different?

**Comment by jtommy** [comment]
@agriboz You should format Date Object to String or Number with your custom function or external library (for example), before to send it to your endpoint.

**Comment by agriboz** [comment]
is there a good example of how to do it with nuxt/axios module interceptor?

**Comment by jtommy** [comment]
It's only an idea as example using `moment` and `axios`
```
axios.interceptors.request.use((config) => {
  for (let key in Object.keys(config.params)) {
     const value = config.params[key]
     if (value instanceof Date) {
         config.params[key] = moment(value).format('DD-MM-YY')
     }
  }
  return config
}, function (error) {
  return Promise.reject(error)
})

**Comment by agriboz** [comment]
@jtommy oh, that is my bad. I was trying to do it with transformRequest config. thank you btw.

**Comment by jtommy** [comment]
@SSolomonCT a fix will be available in the next release https://github.com/buefy/buefy/commit/a06eed4b2753d31a8082be68397b643b922e2cd8

**Comment by caryevans** [comment]
Thanks for all the great work... This is still an issue :) 

Try it on the official Buefy website:
https://buefy.github.io/#/documentation/datepicker   - It is still off by a day. 

Tested using Chrome, Safari on Mac.

**Comment by jtommy** [comment]
@caryevans We didn't release the new version

**Comment by kushbhandari** [comment]
@jtommy this happens for all cases or only when user is in a timezone which has different date than the UTC. For example: 2 AM UTC today was 10 PM yesterday in New York. So user in New York will see -1 day if we try to set current date to date-picker.

**Comment by jtommy** [comment]
@kushbhandari Did you try the develop branch? Anyway you might fix it using date-formatter prop untill the new version will be released

**Comment by kushbhandari** [comment]
@jtommy haven't tried on develop branch though I see another issue with mobile native browsers. On iOS safari, as soon as I click the datepicker, ( today's date - 1day ) is displayed in input. I was not able to find any property to control that. Is there any workaround to not display date at least in input on click of datepicker for native browsers ?

**Comment by jtommy** [comment]
@kushbhandari We have non control for native picker. You might disable it using `mobile-native` prop

**Comment by kushbhandari** [comment]
@jtommy but I didn't click anything on native picker. I just clicked datepicker which triggers native picker and datepicker is populated with date without any interaction with native picker. So not sure how/why datepicker input is populating date ?

**Comment by jtommy** [comment]
Can you provide an example ?

**Comment by kushbhandari** [comment]
Ok, here are the steps -
- Goto https://buefy.github.io/#/documentation/datepicker on mobile browser (iOS, Safari)
- Click the first example of Datepicker
- Notice that no date is displayed on datepicker (as expected)
- Native datepicker will showup on your device and you will notice datepicker is set to current date.

Is there anyway to prevent setting of date in datepicker on native broswer?

Attaching screenshot:
![date_safari](https://user-images.githubusercontent.com/342763/43304583-2e2f4ca0-9121-11e8-9b69-ad0daabcf2e6.jpg)

**Comment by jtommy** [comment]
It's an issue a about input "date" type and not related to Buefy

**Comment by aalabiso** [comment]
I'm experiencing this issue as well. The problem is that the Javascript Date Object is formatted to browser's local timezone. So if you create a Date object from a record in your database that's in UTC time, it will be represented as the equivalent date in your locale.

For instance if you are in UTC+8 and select the date 2018-08-01, the Date object looks like "Wed Aug 01 2018 00:00:00 GMT+0800". However when the form is submitted the value up being "2018-07-31T16:00:00.000Z" which is the same date, converted into UTC format.

Sure, you can do a bunch of translation in Vue or intercepts via axios to get it to "work right" but the intent of the input is to select a date (absent a time or timezone). The date picker doesn't implement times or timezones so this can get a bit confusing. The Javascript Date object represents a date, a time and a timezone but the Date Picker should only represent a date. For most use cases developers need a method to view/store/modify a date without an associated time/timezone so it might make more sense for Buefy to drop the Date object in favor of a date string.

**Comment by philipithomas** [comment]
We're still having issues with this on 0.6.7. We just need the day, not the full date with time. We end up with a lot of extra code to just parse out the date.

**Comment by philipithomas** [comment]
> We fixed issue about formatting date but the components manage always a Date object that contains time information.
> What's the problem? You might get only date part with or without other libraries

Basically, we end up with this computed setter/getter for the date. On the getter, we have to take an ISO day (e.g. `2017-08-01`) from the API, and turn it into a date object, to then turn it back into a day in the display. The setter then has to take the date object, and turn it into an ISO day for the API. 

I'm not really familiar with the Vue internals for computed setters/getters, but - it seems like Vue does an immediate read following a set. If the getter returns a different value than what was set, it tries to set that new value. So, if the date object returned by the getter is not perfectly returned to the setter, it results in an infinite loop. So then, we ended up adding an intermediate caching layer to store the date object that we considered "latest". 

With buefy 0.6.7, we still had some weirdness around timezones and calculating the right date object from the API. After spending a lot of time looking at the formatters and parsers for this Datepicker, I ended up looking at some other components. 

I ended up switching to [vue-bulma/datepicker](https://github.com/vue-bulma/datepicker) because it provides the kind of API I need - where it can just deal in ISO days.  

We love Buefy and use it extensively. But, the Datepicker component required too much glue code in converting between dates and days.

**Comment by philipithomas** [comment]
> @philipithomas At the moment we don't want to add dependency and create a complete datepicker take us a great effort.
> I'm sorry but at the moment we cannot compare to that datepicker because internal is flatpckr, a specific date time picker lib.

All good - I dug into the internals, and realized how complex this component is. Thanks for working so hard on Buefy, and for being responsive on this issue!

**Comment by abarreraaponte** [comment]
This worked for me using moment

`moment(date).utcOffset(date).toDate();`

**Comment by sadedil** [comment]
> This worked for me using moment
> 
> `moment(date).utcOffset(date).toDate();`

Where to put this? `:date-creator` or something similar?

**Comment by tyuwan** [comment]
I just put mine in compute with momentjs, i hope this will help someone.
` date: {
            get() {
                return moment(this.date, 'YYYY-MM-DD').toDate()
            },
            set(dob) {
                this.date = moment(date).format('YYYY-MM-DD')
            }
        }`

**Comment by alexndr-n** [comment]
I'm just saying a lazy fix for this could be having the datepicker select 12:00PM by default, sorry for those of you in Australia.
