### ISSUE TITLE
Column cannot be fixed by setting the property width to a certain value.

### ISSUE THREAD

**Issue by zhangzhen** [rafaelpimpa/buefy#278]
I use a b-table to represent my data. One column has a long text, so I restricted its width as follows:

```
            <b-table-column field="karyotype" label="Karyotype" width="100">
                <a v-if="props.row.conclusion === 'Abnormal'" @click="showAbnormalChroms(props.row.sample_name, props.row.karyotype)">
                  {{ props.row.karyotype }}
                </a>
                <span v-if="props.row.conclusion !== 'Abnormal'">{{ props.row.karyotype }}</span>
            </b-table-column>
```
But the width of the column cannot be fixed.

Cheers,
Zhen

**Comment by jtommy** [comment]
@zhangzhen I don't understand. Could you provide us an example ?

**Comment by zhangzhen** [comment]
![screenshot from 2017-08-24 08-20-29](https://user-images.githubusercontent.com/782824/29644190-cf589f8e-88a6-11e7-8e08-15b3c8e04b9a.png)
I pasted a screenshot of my analysis app above. The red box shows the column Karyotype is too wide. This breaks the layout of page header and footer.

**Comment by jtommy** [comment]
@zhangzhen Did you change table layout by css/sass ? Did you see if th ("Karyotype") width it's 100px ?

**Comment by nick-beers** [comment]
I've just run into this problem and I can point out the issue in the source code. In the documentation there is a `<b-table-column>` property called `width` that states "Column fixed width in pixels". When you set this property nothing happens in the html or css.

If you review the table column source code you'll see a width property exists, but it is not used currently. So basically it looks like a property is documented and exists, but the functionality was not implemented.

https://github.com/rafaelpimpa/buefy/blob/8302133d19be1e8a67377533bb4521be70d24a32/src/components/table/TableColumn.vue#L17

**Comment by shazha** [comment]
I have the same issue here. And I figured out the `width` property works only if the column's value contains at least one white space.

**Comment by jtommy** [comment]
@shazha Good to know!

**Comment by consciousnessdev** [comment]
> word-break:break-all;

where you implemented word-break: break-all; ?
