### ISSUE TITLE
Default sort is not working properly

### ISSUE THREAD

**Issue by gfviegas** [rafaelpimpa/buefy#279]
**Buefy** version: 0.5.1
**Vuejs** version: 2.3.3
**OS/Browser**: Mac/Chrome

I'm trying to use default-sort with a string or an array and neither will work. As you can see on this screenshot from vue extension, the props are passed properly but it won't set the data

![image](https://user-images.githubusercontent.com/6178801/29648185-42cb39ca-8863-11e7-81ef-ebc6017315d1.png)

My example implementation:

```javascript
// Using PUG
b-table(
          v-bind:data="news",
          v-bind:mobile-cards="true",
          default-sort-direction="desc",
          v-bind:default-sort="['created_at', 'title', 'slug']"
        )
          template(scope="props")
            b-table-column(field="title" label="Título" sortable) {{props.row.title}}
            b-table-column(field="slug" label="Slug" sortable) {{props.row.slug}}
            b-table-column(field="created_at" label="Criado" sortable) {{props.row.created_at | moment('DD/MM/YYYY HH:mm')}}
```

**Comment by jtommy** [comment]
@gfviegas Your example is not correct. 
Default sort prop accept an array with field name in the first position and sort direction in the second position. 
You can order by only one column at once.

**Comment by gfviegas** [comment]
@jtommy 

I said i tried with array or string as it's described in the docs and neither will work.

**Comment by Tirke** [comment]
@gfviegas 

I'm sorry if this sounds rude but you should try harder, the doc is quite clear.

default-sort | Sets the default sort column and order — e.g. ['first_name', 'desc'] | String, Array | — | order: default-sort-direction prop
-- | -- | -- | -- | --

If it is a string, you can only use one value like that :
`default-sort="name"` =>  Will sort by the `name` column by default

If it is an array, the first value is unique and represents the default sorted column and the second value is unique and represents the default sort order :
`default-sort=['name', 'desc']` => Will sort by the `name`column in a `desc` order.

All the following values are not valid:

`['name', 'email', 'otherProp']`
`name,email,anyPro`

**Comment by gfviegas** [comment]
All right dude, it still won't work if I set only the field name and pass
the order mode on its own prop.

**Comment by gfviegas** [comment]
To make myself clear: even tough my array example was wrong, the issue remains if I pass the default-sort as a string with the field name and pass the default-sort-direction as a string with 'asc' or 'desc'.

**Comment by Tirke** [comment]
`default-sort-direction`and `default-sort`do different things.

* `default-sort-direction` control wether your first click will sort `asc` or `desc` for every column.
* `default-sort` will sort your table according to the value set ON THE FIRST RENDER. 

Maybe there is a bug I don't deny that but as you didn't explain what behavior you are expecting we cannot provide more help ...

**Comment by jtommy** [comment]
@gfviegas We found a issue about sort but with async data. Is it your case ?
 Did you have a problem the first time or always (each click) ?

**Comment by gfviegas** [comment]
@jtommy Yes, it's my case.

I have the problem only trying to set a default sort, the field actually defaults empty and will only sort if I click to sort, that's the problem.

**Comment by gfviegas** [comment]
@jtommy If you mean i'm using a custom sort function to sort async, that's not my case tho

**Comment by gfviegas** [comment]
Okay so let me explain the behaviour properly:

## What I'm doing
I'm loading some data via HTTP and displaying it on the buefy table data.
My data is like: 

```json
[
  {
    "_id": "59a4b0191dd1f900e15338f8",
    "email": "test@gmail.com",
    "username": "test",
    "name": "user Test"
  },
  {
    "_id": "59a4b0191dd1f900e15338f7",
    "email": "webviegas@gmail.com",
    "username": "gfviegas",
    "name": "Gustavo Viegas"
  }
]
```
and I'm passing the props to b-table as `default-sort="name", default-sort-direction="asc"`.

## What I expect
I expect the table renders with the data field name sorted without I need to click on it, default.

## What happens
No field is sorted and the sort field is empty (on mobile).

![image](https://user-images.githubusercontent.com/6178801/29798783-9d1553a4-8c35-11e7-954f-b3b556c75282.png)


In case if anything is not clear yet, my usage is as it follows:

PS: Using Pug.
```javascript
b-table(
          v-bind:data="users",
          default-sort="name",
          default-sort-direction="asc"
        )
          template(scope="props")
            b-table-column(field="name" label="Nome" sortable) {{props.row.name}}
            b-table-column(field="email" label="Email" sortable) {{props.row.email}}
            b-table-column(field="username" label="Username" sortable) {{props.row.username}}
```

and the users data is loaded on the Vue Router event beforeRouteEnter, idk if this relates to anything but that's it.


Any more info needed @Tirke ?

**Comment by jtommy** [comment]
@gfviegas Ok. We're working on it.
