### ISSUE TITLE
buefy.css much too aggressive

### ISSUE THREAD

**Issue by kylebradshaw** [rafaelpimpa/buefy#28]
If you set a base font-family for example and then subsequently add buefy.css, buefy stomps all over the site rules.

Is the inclusion re-adding all of the bulma styles back in? Is there a way to only add styles necessary?

**Comment by rafaelpimpa** [comment]
Yes, Buefy compiled css has all Bulma's styles included. I wouldn't recommend utilizing the compiled css if you're customizing the theme. You have two options:

1. Use the non compiled (Sass) instead.
2. Recompile the css with your variables.

**Comment by sldobri** [comment]
or add https://github.com/purifycss/purifycss(remove unused CSS) in your webpack

**Comment by kylebradshaw** [comment]
@rafaelpimpa Including the specific utils + component sass files worked for me thank you
