### ISSUE TITLE
Feature: return promise from Dialog confirm() and prompt()

### ISSUE THREAD

**Issue by TomKaltz** [rafaelpimpa/buefy#282]
Would be nice to be able to get a Promise back from Dialog that will resolve when Dialog is closed.

**Buefy** version: [0.5.1]
**Vuejs** version: [2.4.2]
**OS/Browser**: Chrome

**Comment by jtommy** [comment]
@TomKaltz You can listen 'close' event by `onCancel` prop. 
At the moment we have no plans about that request.

**Comment by jlsjonas** [comment]
It's 2018... Promises should really be reconsidered imho. @jtommy
