### ISSUE TITLE
ability to change pagination icons (rtl)

### ISSUE THREAD

**Issue by moeenzarrinfam** [rafaelpimpa/buefy#284]
### Overview of the problem
ability to change pagination icons
**Buefy** version: 0.5.1
**Vuejs** version: 2.4.2
**OS/Browser**: chrome/firefox

### Description
sometimes (for example in rtl pages) we need to change the pagination next and previous icons
![screenshot from 2017-08-27 12-48-04](https://user-images.githubusercontent.com/13137143/29748221-0d0d2412-8b27-11e7-8ed5-c5894f16b193.png)

**Comment by jtommy** [comment]
@moeenzarrinfam About rtl there is PR to Bulma project https://github.com/jgthms/bulma/pull/650.
I think it's better a base solution that only single component feature.

**Comment by moeenzarrinfam** [comment]
this is a very simple idea to solve this problem
you can mirror navigator items with CSS:
`
  .pagination-next , .pagination-previous{
    -moz-transform: scale(-1, 1);
    -webkit-transform: scale(-1, 1);
    -o-transform: scale(-1, 1);
    -ms-transform: scale(-1, 1);
    transform: scale(-1, 1);
  }
`

**Comment by jtommy** [comment]
@moeenzarrinfam Good to know, thanks!
We'are waiting for Bulma progress about RTL to think something for all components.

**Comment by Tovli** [comment]
Following @jtommy comment about RTL support
Is there a plan for this? maybe a constructor option?

**Comment by jtommy** [comment]
@tovil as you can see bulma author is working on it https://github.com/jgthms/bulma/commits/rtl-support

**Comment by Tovli** [comment]
That's great
thanks a lot.
I really need to improve my search skills :-(
