### ISSUE TITLE
Customize not working while build for production, but works on develop mode.

### ISSUE THREAD

**Issue by BrikerMan** [rafaelpimpa/buefy#287]
### Overview of the problem

**Buefy** version: 0.5.1
**Vuejs** version: 2.3.3
**OS/Browser**: latest Chrome, firefox and safari

### Description

Customize color works perfectly when I use `npm run dev`, But the color reset to original color when `npm run build`.

I have tried the [buefy-simple](https://github.com/rafaelpimpa/buefy-simple). It work fine on dev and build mode.  I have copied the whole code to my project, it works on dev but still not working when I build. Is there any other step i need to keep in mind?

```javascript
<style lang="scss">
  // Import Bulma's core
  @import "~bulma/sass/utilities/_all";

  // Set your colors
  $primary: #4d4d4d;
  $primary-invert: findColorInvert($primary);
  $twitter: #2f6d8b;
  $twitter-invert: findColorInvert($twitter);

  // Setup $colors to use as bulma classes (e.g. 'is-twitter')
  $colors: (
      "white": ($white, $black),
      "black": ($black, $white),
      "light": ($light, $light-invert),
      "dark": ($dark, $dark-invert),
      "primary": ($primary, $primary-invert),
      "info": ($info, $info-invert),
      "success": ($success, $success-invert),
      "warning": ($warning, $warning-invert),
      "danger": ($danger, $danger-invert),
      "twitter": ($twitter, $twitter-invert)
  );

  // Links
  $link: $primary;
  $link-invert: $primary-invert;
  $link-focus-border: $primary;

  // Import Bulma and Buefy styles
  @import "~bulma";
  @import "~buefy/src/scss/buefy";
</style>
```

**Comment by jtommy** [comment]
@BrikerMan Your code is ok. We are need more info about project and/or build config.

**Comment by BrikerMan** [comment]
Thanks for your reply, here is demo https://github.com/BrikerMan/buefy_customize_issue_demo

**Comment by jtommy** [comment]
@BrikerMan The problem is https://github.com/BrikerMan/buefy_customize_issue_demo/blob/master/src/main.js.
You have to remove `import 'buefy/lib/buefy.css'`

**Comment by BrikerMan** [comment]
Thanks~ It worked~
