### ISSUE TITLE
How can I make same Hero as Buefy website has?

### ISSUE THREAD

**Issue by OGhawsi** [rafaelpimpa/buefy#290]
### Overview of the problem

**Buefy** version: [0.5.0]
**Vuejs** version: [2.1.10]
**OS/Browser**:Ubuntu 17.04/Chrome

### Description
This is not an actual issue but I would like to know if someone can guide me through the same hero as the Buefy website has. Hero-foot is the actual part which I am looking for.
Your ideas are well appreciated. Thanks in advance.

**Comment by iwan-wijaya** [comment]
Just check the source files :eyes:
https://github.com/rafaelpimpa/buefy/blob/fc71ace1e17890e1aeb39dfed63ebda3fa106453/docs/pages/documentation/Documentation.vue#L13

**Comment by OGhawsi** [comment]
I am really new to Vue actually so I need to learn that lil bit . THanks @iwan-wijaya
