### ISSUE TITLE
b-input didnt get attritbutes

### ISSUE THREAD

**Issue by avivsalman** [rafaelpimpa/buefy#294]
### Overview of the problem

**Buefy** version: [0.5.1]
**Vuejs** version: [2.2.0]
**OS/Browser**:

### Description

# Usage:
    b-input(id="test", disabled="true", placeholder="test")

# Result In DOM:
```
<div class="control is-clearfix" id="test" disabled="disabled" placeholder="test">
      <input type="text" autocomplete="on" class="input"> <!----> <!----> <!---->
</div>
```

the parent div get all the attributes instead of the input.

### Expected behavior

solve the bug as soon as possible, thanks :)

**Comment by jtommy** [comment]
@avivsalman Are you sure about your Vue.js (last) ?

**Comment by avivsalman** [comment]
yes you right, my Vue version is 2.2.0

**Comment by jtommy** [comment]
https://buefy.github.io/#/documentation/start

**Comment by deckar01** [comment]
@jtommy I am confused by the resolution of this issue. I am using Vue 2.5.16 with buefy 0.7.1 and I am running into the same problem.

I need a way to add attributes to the input element, but the component only adds them to the control.

**Comment by jtommy** [comment]
@deckar01 an example?

**Comment by deckar01** [comment]
```html
<b-input class="is-static" disabled></b-input>
```

```html
<div class="control is-static is-clearfix">
  <input type="text" autocomplete="on" class="input" disabled="disabled">
</div>
```

I ended up taking a peek at the source and finding a hack that let my CSS class to leak into the input `class` via the `size` attribute.

```html
<b-input size="is-static" disabled></b-input>
```

**Comment by deckar01** [comment]
The field component solves a similar problem with styling the field label by providing a `custom-class` attribute. Would you be interested in reviewing a pull request that adds a `custom-class` attribute to to the input component, which is applied to the input element?

**Comment by kerbo** [comment]
Yes, the "size" hack works! Seems I can pass through any class attribute using this method. This solved the problem of getting vertically centered text in the b-input.
