### ISSUE TITLE
Help A Noob?

### ISSUE THREAD

**Issue by thc1967** [rafaelpimpa/buefy#295]
This isn't so much a problem statement as a request.

I've done a bit of programming with Vue but the tables in Buefy are beyond my comprehension, unfortunately. I'd love to be able to use them.

Is there a place where I can see real, working, source with any of the Table examples in the Buefy documentation? Ideally I'd like a single source file I can copy and paste into my own development environment, that will just work upon pasting, and I can mess around with to learn.

Thank you!

**Comment by jtommy** [comment]
@thc1967 Table component documentation is complete and in next release will be async data example (backend sorting and pagination too).
What's your doubt or use case?

**Comment by thc1967** [comment]
Consider the following shell:

```
<html>
    <head>
        <link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">
        <link href="{{ mix('css/app.css') }}" rel="stylesheet">
    </head>
    <body>
        <div id="app">
            <h1 class="title">Buefy Test</h1>

            <!-- Buefy Content Here -->

        </div>
        <script src="{{ mix('/js/app.js') }}"></script>
    </body>
</html>
```

(I'm using Laravel so this is a Blade template...)

When I paste the following into the app's DIV tag, the controls all work exactly as I expect and Chrome's Java console reports no errors:

```
            <b-tabs>
                <b-tab-item label="Tab1">
                    <div class="field">
                        <b-checkbox>Basic</b-checkbox>
                    </div>
                </b-tab-item>
                <b-tab-item label="Tab2">
                    <div class="field">
                        <b-switch>Default</b-switch>
                    </div>                
                </b-tab-item>
                <b-tab-item label="Tab3">
                    Tab3 Content
                </b-tab-item>
            </b-tabs>
```
This proves that Vue, Bulma, and Buefy are all working properly. Great! Let's try a table!

Unfortunately, when I paste verbatim the first sample table code from the documentation (not copied here for brevity), I get several errors in Chrome's Java console:

* Uncaught SyntaxError: Unexpected token export

* [Vue warn]: Error compiling template: *(`<div id="app"> contents echoed)*

* - Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.

* [Vue warn]: Property or method "isBordered" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. *(repeats once per prop that didn't get exported)*

The switches display and switch on and off, but generate errors that Chrome reports in the console because the data didn't get exported. The table area shows up with the frowny face and "Nothing here."

I'm absolutely certain I've done something wrong by simply pasting the entirety of the table sample into my `<div id="app">` tag... but I'm just not experienced enough with Vue to figure out what.

**Comment by jtommy** [comment]
@thc1967 I'm sorry but it's not easy help you in this way. 
Could you provide us an example of your project ?

**Comment by thc1967** [comment]
What more do you need to see than what I offered above?

Am I supposed to put the example code from the tables page into a Vue component of my own instead of putting it into an HTML page verbatim? Is that the step / trick I'm missing?

**Comment by jtommy** [comment]
For example your b-table code..

**Comment by thc1967** [comment]
OK... all I did was paste the sample into the shell I posted above. I'm sure that's wrong but I don't know how to split it up correctly. Here is the entirety of the code.

```
<html>
    <head>
        <link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">
        <link href="{{ mix('css/app.css') }}" rel="stylesheet">
    </head>
    <body>
        <div id="app">
            <h1 class="title">Buefy Test</h1>

            <b-table
                :data="tableDataSimple"
                bordered="false"
                striped="true"
                narrowed="true"
                loading="false"
                mobile-cards="true">

                <template scope="props">
                    <b-table-column label="ID" width="40" numeric>
                        @{{ props.row.id }}
                    </b-table-column>

                    <b-table-column label="First Name">
                        @{{ props.row.first_name }}
                    </b-table-column>

                    <b-table-column label="Last Name">
                        @{{ props.row.last_name }}
                    </b-table-column>

                    <b-table-column label="Date" centered>
                        @{{ new Date(props.row.date).toLocaleDateString() }}
                    </b-table-column>

                    <b-table-column label="Gender">
                        @{{ props.row.gender }}
                    </b-table-column>
                </template>

                <template slot="empty">
                    <section class="section">
                        <div class="content has-text-grey has-text-centered">
                            <p>
                                <b-icon
                                    icon="sentiment_very_dissatisfied"
                                    size="is-large">
                                </b-icon>
                            </p>
                            <p>Nothing here.</p>
                        </div>
                    </section>
                </template>
            </b-table>

        </div>
        <script src="{{ mix('/js/app.js') }}"></script>
        <script>
            export default {
                data() {
                    const tableDataSimple = [
                        { 'id': 1, 'first_name': 'Jesse', 'last_name': 'Simmons', 'date': '2016-10-15 13:43:27', 'gender': 'Male' },
                        { 'id': 2, 'first_name': 'John', 'last_name': 'Jacobs', 'date': '2016-12-15 06:00:53', 'gender': 'Male' },
                        { 'id': 3, 'first_name': 'Tina', 'last_name': 'Gilbert', 'date': '2016-04-26 06:26:28', 'gender': 'Female' },
                        { 'id': 4, 'first_name': 'Clarence', 'last_name': 'Flores', 'date': '2016-04-10 10:28:46', 'gender': 'Male' },
                        { 'id': 5, 'first_name': 'Anne', 'last_name': 'Lee', 'date': '2016-12-06 14:38:38', 'gender': 'Female' }
                    ]

                    return {
                        tableDataSimple
                    }
                }
            }
        </script>
    </body>
</html>
```

With this code, I see the outline of the table with a frowny face, "Nothing here" under it, and a loading spinner spinning over the top of it.
