### ISSUE TITLE
Simple Test - Checkbox Doesn't Submit with Form

### ISSUE THREAD

**Issue by thc1967** [rafaelpimpa/buefy#297]
### Overview of the problem

**Buefy** version: 0.5.1
**Vuejs** version: 2.4.2
**OS/Browser**: Windows 10 / Chrome

### Description

b-checkbox doesn't seem to submit any value when included into an HTML form tag and that form is submitted to the server.

### Steps to reproduce

1) Include the following code in an HTML page that has Buefy included and other Buefy controls working as expected:

```HTML
<form action="/formdump" method="POST" class="section">

    <div class="field">
        <b-checkbox name="basic_checkbox"
            v-model="basic_checkbox"
            true-value="1"
            false-value="0">Basic Checkbox</b-checkbox>
    </div>

    <hr />

    <button class="button is-success" type="Submit">
        <span class="icon">
            <i class="fa fa-check-circle" aria-hidden="true"></i>
        </span>
        <span>Submit</span>
    </button>

</form>
```

2) Visit the page, check the checkbox, and submit the form.

### Expected behavior

I would have expected the contents of the POST variable, `basic_checkbox` to be 1 or true or yes or something to indicate it was checked.

### Actual behavior

When I have the checkbox checked and submit the form to the server and evaluate the contents of the POST variable, `basic_checkbox`, it is null.

I feel confident that I have Buefy and Vue working correctly because:

- I'm using Buefy tabs on the page and those work as I expect them to

- I can use the Vue Chrome add-on debugger to watch values on the checkbox change as I check and uncheck it.

**Comment by thc1967** [comment]
Answer: Use `native-value="1"` to get it to send something on the form submit when checked.

**Comment by cldershem** [comment]
This just held me up for a good half hour. I think this should be more clearly documented in the docs.
