### ISSUE TITLE
[Nuxt.js] Datepicker stop working on SSR

### ISSUE THREAD

**Issue by juan-manuel-alberro** [rafaelpimpa/buefy#298]
### Overview of the problem

**Buefy** version: 0.5.1
**Vuejs** version: 2.4.2
**OS/Browser**: Mac / Linux
**Nuxt.js**: 1.0.0-rc8
### Description

The datepicker component works perfect in Nuxt until you refresh the page and the page is rendered in the server side, you get `navigator is not defined`

### Steps to reproduce

1. Add a date picker component into a `.vue` file
2. Navigate to that page and verify that the component is working
3. Refresh page (cmd + R or F5) 
4. :bomb: 

### Expected behavior

Render the date picker without any error

### Actual behavior

Page is not working since `navigator is not defined` (screenshot below)

![](https://i.imgur.com/T3Lr6SW.png)

**Comment by jtommy** [comment]
It's fixed!
Anyway if you want to use native datepicker, you have to inject current user agent to enable the correct mobile detection because Buefy depends on existence of `window.navigator.userAgent` to do it.

**Comment by juan-manuel-alberro** [comment]
Lovely, thanks @jtommy!

**Comment by davegriffin** [comment]
We've also seen this with a Nuxt.js project and observed a different and somewhat non-sensical error message in the server logs related to the time/date pickers (expected Date, got Date), but wrapping the b-datepicker / b-timepicker component references in <no-ssr> </no-ssr> tags resolved the issue.  (The pickers were working fine on the client, just throwing errors in the server log.)

Just an FYI for anyone looking for a workaround.

**Comment by jtommy** [comment]
Thanks @davegriffin but maybe the correct place is this issue https://github.com/buefy/nuxt-buefy/issues

**Comment by davegriffin** [comment]
Fair point!  Googling found this first, but I'll make mention of it there as well  (perhaps it can be resolved!)  Thank you!
