### ISSUE TITLE
Datepicker format output

### ISSUE THREAD

**Issue by defiant** [rafaelpimpa/buefy#299]
Currently you have the ability to format the date value shown Datepicker component using a custom function. However the value returned by the component to the model is always the same date object. It would be nice to have the ability to format the output as well.

**Comment by flick36** [comment]
Was about to post the same thing!

**Comment by jtommy** [comment]
@defiant I'm sorry, i don't understand. Custom function format a date object to a string and v-model accepts Date object. 
So you could use the same function to format v-model, no ?

**Comment by defiant** [comment]
@jtommy Maybe you could do that but I was saying it would be more convenient if we passed a custom format string (or function) we could use it directly when we submit the form

**Comment by jtommy** [comment]
@defiant No custom format string because we want an easy and light component that helps to manage date but it haven't to cover all features like other specific library.
When you submit form if you do it by ajax call you can format Date object as you want otherwise will be submit input value (that depends on format function prop).
I think i don't understand your request yet.

**Comment by defiant** [comment]
There are cases when you submit the whole form without using model, or cases when you use Formdata. I was trying to say it would be easier if we could specify the output format as an option

**Comment by alqu** [comment]
Most of the time you are dealing with stuff that comes from some api, which usually transports data as a JSON object. In JSON, there is no native Date type.

In my case, JSON contains ISO8601 strings like `2015-10-31T00:00:00.000Z`.
To make it seamlessly work with the datepicker, it should also consume ISO-strings.

**Comment by jtommy** [comment]
Yes, but at the moment we don't want cover all patterns but it's the developer to do it (you can use moment library) because we want keep Datepicker simple and without dependency.

**Comment by alqu** [comment]
> Yes, but at the moment we don't want cover all patterns but it's the developer to do it (you can use moment library) because we want keep Datepicker simple and without dependencies.
I see.

Formatting the date for display: I agree, you can set up a global config in your `main.js` like this:
```js
Vue.use(Buefy, {
  // ... global Buefy config stuff ...
  defaultDateFormatter: filters.dateFormat,
  defaultDateParser: date => {
    const m = moment(date)
    return m.isValid() ? m.toDate() : null
  }
})
```
OK.

But if we want to support common use cases like parsing an ISO8601 string, then only these adjustments need to be done in `src/components/datepicker/Datepicker.vue`:
```js
        // ...
        props: {
            value: [Date, String],
            // ...
        },
        watch: {
            dateSelected (value) {
                const currentDate = !value ? new Date() : value
                // Here:
                this.$emit('input', value.toISOString())
                // ...
            },
            value (value) {
                // And here:
                this.dateSelected = new Date(value)
                // ...
            }
        },
```

What do you think?

**Comment by jtommy** [comment]
We removed String value support because Date object it's to easy to manage.
About your example, i don't know because the `v-model` could be Date or String but when date is changed or selected emit a string value. It's quite strange.

**Comment by alqu** [comment]
@jtommy You are right - this is a bit confusing, but works OK in my case.

Ideally I would need only a good tool that automatically converts all fields in my json-response to Date-Objects.

**Comment by jtommy** [comment]
@alqu A great library is moment.js. 
You can format (date to string) and parse (string to date) as you want.

**Comment by alqu** [comment]
@jtommy Thanks for setting up the jsfiddle. I know, it is easily doable.

Looking closer at my app, there are some cases where I directly use the date object via v-model, and others that uses the plain ISO strings, coming directly from a server response.

I guess I have to ask in the VueJS community about best practices where to apply the data transformation. Probably not in a component.

Thanks!
