### ISSUE TITLE
Module build failed: Error: Couldn't find preset "env"

### ISSUE THREAD

**Issue by dukadin** [rafaelpimpa/buefy#3]
```
Module build failed: Error: Couldn't find preset "env" relative to directory "/node_modules/buefy"
    at /node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
```
I got this error when I tried to import Buefy with Webpack using laravel-mix.

**Comment by rafaelpimpa** [comment]
Actually I'm not really familiar with webpack, I'm not sure how to fix that, maybe it's something with your config?

**Comment by dukadin** [comment]
I updated _laravel-mix_ and everything working fine now 👍

**Comment by rafaelpimpa** [comment]
I have a beta published with compiled builds, maybe it would work out of the box right now, could you help me test it out?

```
npm install buefy@compiled
```
import css like this: ``import 'buefy/lib/buefy.css'``

**Comment by dukadin** [comment]
I will try it.

Right now I'm importing Buefy components as:
`import BInput from "buefy/src/components/input/Input"` and I'm looking for way to change default icon pack without using `Vue.use(Buefy, {})`. Is there any way to achive this?

Right now I can't see passwordReveal icon on input even if I set `iconPack="fa"` attribute.

**Comment by rafaelpimpa** [comment]
try like this 
```javascript
import bIcon from 'buefy/src/components/icon/Icon'
bIcon.props.pack.default = 'fa'
```

**Comment by rafaelpimpa** [comment]
Looks like the constructor options aren't work with the compiled build. Gonna take a look.

**Comment by rafaelpimpa** [comment]
I'm gonna make a overhaul of how constructor options work.

**Comment by rafaelpimpa** [comment]
Just letting you know, next release ``bIcon.props.pack.default = 'fa'`` won't work anymore, I'm remaking the constructor options, I'll let you know how to proceed.

**Comment by rafaelpimpa** [comment]
Ok just released v0.1.4, for that to work now you have to use like this:

```javascript
import config from 'buefy/src/utils/config'
config.defaultIconPack = 'fa' // or any other constructor options
```

**Comment by dukadin** [comment]
Awesome! Thank you mate 👍

**Comment by dukadin** [comment]
@rafaelpimpa can you please don't use ES6 syntax inside `buefy/src/utils/config` file? Because I can't run UglifyJs on it :/

**Comment by rafaelpimpa** [comment]
Actually I'll keep it as pattern, maybe wrap it on other file that you're parsing with babel?

**Comment by dukadin** [comment]
Fixed it with _harmony_ branch of UglifyJS2 👍
