### ISSUE TITLE
Table backend-sorting resetting sorted column

### ISSUE THREAD

**Issue by kieusonlam** [rafaelpimpa/buefy#30]
I'm not quire sure if I do it wrong. When enable `backend-sorting` this mean I click on table header to sort, I also reload data for the table right? So here is my sort method to fetch data from the backend.
```
sorted(field, order) {
    this.$store.dispatch('FETCH_ARTICLES', {
        sort: {
            field,
            order: (order === 'asc') ? 1 : -1
        }
    })
}
```
But the problem when reload data, table seem to be losing current state of ordering, so it always be ascending when I click on it.

![image](https://cloud.githubusercontent.com/assets/13093313/25217757/4aa42c0e-25d2-11e7-9cae-fb0b3876a744.png)

Am I do it the wrong way?

**Comment by rafaelpimpa** [comment]
Gonna take a look at it
