### ISSUE TITLE
No way to close B-table detail block except link in table row

### ISSUE THREAD

**Issue by Rh1N0** [rafaelpimpa/buefy#300]
Thanks for awesome lib.
I have a small but annoying issue with b-table component. I'm using detail slot to place form for editing row data. Once data updated i want to close details block, but not found any way to do it, except of clicking expand link from first column of row. 
I'd propose to move **visibleDetailRows** from data to props like it was done with checkedRows.

**Buefy** version: [0.5.1]
**Vuejs** version: [2.4.2]
**OS/Browser**: MacOS Sierra / Chrome

**Comment by jtommy** [comment]
Does it work for you ?  
`this.$refs.table.toggleDetails(row)`

`table` is name of ref attribute that you have to set to b-table;
`row` is the current row that you retrieve from 'detail' scoped slot.

**Comment by Rh1N0** [comment]
Great thanks, your solutions works well.
