### ISSUE TITLE
User can still select date when disabled attribute added to Datepicker

### ISSUE THREAD

**Issue by laij84** [rafaelpimpa/buefy#302]
### Overview of the problem

**Buefy** version: [0.51]
**Vuejs** version: [2.4.2]
**OS/Browser**: Mac Sierra / Chrome 

### Description

When the disabled attribute is added to the <b-datepicker> component, clicking on the disabled input still loads the calendar drop down and the user is able to select a date.  

### Steps to reproduce

1. Add disabled attribute to datepicker (e.g. <b-datepicker disabled></datepicker
2. Even though the input appears disabled when hovering the mouse over it, if you click the calendar appears.
3. Select a date and the value appears in the disabled input field. 

### Expected behavior

Users should not be able to trigger the calendar and select a date when the datepicker input is disabled.

### Actual behavior
User is able to select date when datepicker is disabled.

**Comment by deckar01** [comment]
@jtommy This same problem exists for inputs and is related to #294.

**Comment by yxxa** [comment]
i just look at https://buefy.org/documentation/datepicker/, and still no update about :disabled property in API documentation

**Comment by Elfoslav** [comment]
Still not fixed in 2020

**Comment by jtommy** [comment]
@Elfoslav an example?
