### ISSUE TITLE
Vue warn: Invalid default value for prop "canCancel"

### ISSUE THREAD

**Issue by sainf** [rafaelpimpa/buefy#304]
### Overview of the problem

**Buefy** version: [0.5.2]
**Vuejs** version: [2.4.2]
**OS/Browser**: Chrome 60

### Description

Vue warn after upgrading to 0.5.2 when using model component.

> [Vue warn]: Invalid default value for prop "canCancel": Props with type Object/Array must use a factory function to return the default value.

In: 
```
canCancel: {
                type: [Array, Boolean],
                default: ['escape', 'x', 'outside']
            },
```

perhaps...

```
canCancel: {
                type: [Array, Boolean],
                default: () => ['escape', 'x', 'outside']
            },
```

**Comment by takotuesday** [comment]
@jtommy what ended up being the issue with this? I am running into the same error

**Comment by guamacherox** [comment]
@takotuesday same problem over here, when b-modal is used on any template this warn occurs.

**Comment by jtommy** [comment]
It's fixed but will be available in the next release

**Comment by guamacherox** [comment]
thanks a lot for your answer @jtommy
