### ISSUE TITLE
Customize Buefy/Bulma in nuxt.js without payload increase

### ISSUE THREAD

**Issue by colsen1991** [rafaelpimpa/buefy#306]
### Overview of the problem

**Buefy** version: 0.5.2
**Vuejs** version: 2.4.2
**OS/Browser**: Chrome 60.0.3112.113

### Description

I am trying to customize the sass variables in bulma and buefy in my nuxt.js project. I currently got it working following https://buefy.github.io/#/documentation/customization, but with an increase in payload size.

See steps below please.

A side note is that the payload increases by about 50kB for every compoenent I add customization too. 
At the moment I only add it to the default layout and accept the 50kB increase, but there must be a way to make customizations without the increase in payload?

Thanks in advance  for the help!

### Steps to reproduce

1. Have a clean nuxt.js project.
2. Add buefy according to this guide https://buefy.github.io/#/documentation/start and also add buefy to `build.vendors` in `nuxt.config.js`
3. Run `generate` or `build`, then `start`. Open in browser and note the total kB transferred.
4. Install `node-sass` and `sass-loader` and add code to i.e. `default.vue` layout according to this guide https://buefy.github.io/#/documentation/customization

```.sass
<style lang="sass">
  @import "~bulma/sass/utilities/_all"

  /* some customization. i.e */
  /*$navbar-height: 5rem*/

  @import "~bulma"
  @import "~buefy/src/scss/buefy"
</style>
```
5. Run `generate` or `build`, then `start`.

### Expected behavior

 Open in browser and note that the total kB transferred has is the same, or on scale with customization made.

### Actual behavior

 Open in browser and note that the total kB transferred has increased by about 50kB.

**Comment by jtommy** [comment]
@colsen1991 Ok. We'll review your PR as soon as possible.
Thanks a lot!

**Comment by kieusonlam** [comment]
Hi, I got this warning when use this solution.
```
 warning  in ./assets/css/buefy-overrides.scss

(Emitted value instead of an instance of Error) postcss-custom-properties: C:\Users\xxxx\Desktop\xxxx\node_modules\bulma
\sass\grid\columns.sass:328:6: Custom property ignored: not scoped to the top-level :root element (.columns.is-variable.is
-8 { ... --columnGap: ... })

 @ ./assets/css/buefy-overrides.scss 4:14-210 13:3-17:5 14:22-218
 @ ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":["C://Users//xxxx//Desktop//xxxx//no
de_modules//babel-preset-vue-app//dist//index.common.js"]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!.
/.nuxt/App.vue
 @ ./.nuxt/App.vue
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=3000&path=/__webpack_hmr ./.nuxt/client.js
```
any idea how to fix it?

**Comment by colsen1991** [comment]
Sorry for the late reply. Had a busy weekend :)

Anyways, it seems like your problem has to do with CSS-next and the use of custom vars, not scss vars. I haven't played around with this yet, but i did get plenty of hits on google with parts of your error excerpt. Could you possibly post your `buefy-overrides.scss`?

**Comment by kieusonlam** [comment]
@colsen1991 thanks for reply.

```
// Import Bulma's core
@import "~bulma/sass/utilities/_all";

// Set your colors
$primary: #212121;
$primary-invert: findColorInvert($primary);

// Setup $colors to use as bulma classes (e.g. 'is-twitter')
$colors: (
    "white": ($white, $black),
    "black": ($black, $white),
    "light": ($light, $light-invert),
    "dark": ($dark, $dark-invert),
    "primary": ($primary, $primary-invert),
    "info": ($info, $info-invert),
    "success": ($success, $success-invert),
    "warning": ($warning, $warning-invert),
    "danger": ($danger, $danger-invert)
);

// Links
$link: $primary;
$link-invert: $primary-invert;
$link-focus-border: $primary;

// Import Bulma and Buefy styles
@import "~bulma";
@import "~buefy/src/scss/buefy";
```
I copied it from buefy document. I did try to remove all line except for the import, but still got the same warning. 
```
// Import Bulma's core
@import "~bulma/sass/utilities/_all";

// Import Bulma and Buefy styles
@import "~bulma";
@import "~buefy/src/scss/buefy";
```
By the way I using Windows 10.

**Comment by colsen1991** [comment]
Hmm, I could you also post your `nuxt.config.js` and `package.json`? Sorry for not mentioning the first time.

**Comment by kieusonlam** [comment]
Here are they `nuxt.config.js`
```
module.exports = {
  /*
  ** Headers of the page
  */
  head: {
    title: 'LâmKS',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'Nuxt.js project' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
      { rel: 'stylesheet', href: '//fonts.googleapis.com/icon?family=Material+Icons' }
    ]
  },
  css: [
    { src: '@/assets/css/buefy-overrides.scss', lang: 'sass' }
  ],
  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#f40' },
  /*
  ** Build configuration
  */
  build: {
    /*
    ** Run ESLINT on save
    */
    extend (config, ctx) {
      if (ctx.dev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
  },

  plugins: [
    { src: '~plugins/buefy' },
    { src: '~/plugins/nuxt-client-init.js', ssr: false }
  ],

  router: {
    linkActiveClass: 'is-active'
  }
}
```
`package.json`
```
{
  "name": "lamks",
  "version": "1.0.0",
  "description": "Nuxt.js project",
  "author": "Lâm Kiều <rainbow.lam25@gmail.com>",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "buefy": "^0.5.2",
    "nuxt": "^1.0.0-rc11"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "eslint": "^4.3.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-html": "^3.1.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.1.1",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^3.0.1",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.6"
  }
}
```

**Comment by colsen1991** [comment]
I'm sorry, but I'm drawing a blank using my own knowledge. It seems to be an error related to custom properties, and the bulma file(s). Found 1 hit on google scoping down https://github.com/nuxt/nuxt.js/issues/1670 which suggests disabling custom properties in postcss. Not an ideal fix, but if you are planning to use sass, it shouldn't be a problem :) Let me know how it goes!

**Comment by kieusonlam** [comment]
@colsen1991 cool, thanks. The warning is gone 👍

**Comment by colsen1991** [comment]
Awesome! Glad I could help :)

**Comment by RyosukeCla** [comment]
if you wanna use postcss-custom-properties without warnings, try this

https://github.com/nuxt/nuxt.js/issues/1670#issuecomment-330899099

**Comment by acidduck** [comment]
Can't get it to work. Followed @colsen1991 guide. Now sass/css files are not loaded twice, but overrides are still not happening.

**Comment by acidjazz** [comment]
Tried all of the solutions in this issue, none work, don't know why it's been closed

**Comment by adamnator92** [comment]
@acidduck 
this solution works too
https://github.com/buefy/buefy/issues/319#issuecomment-427642851
