### ISSUE TITLE
How to hide table header?

### ISSUE THREAD

**Issue by proehlen** [rafaelpimpa/buefy#310]
### Overview of the problem

There doesn't appear to be an easy way to hide the Table header.

**Buefy** version: 0.5.2
**Vuejs** version: 2.4.2
**OS/Browser**: Linux/Chrome

### Description

I've tried leaving the label attribute for all columns as a blank string, adding an empty custom header slot and manually hiding thead via css however I'm still left with a gap at the top of the table where the header would be.

I basically want all of the table functionality just without the column headings.

**Comment by jtommy** [comment]
@proehlen By css you can hide thead `.table thead { display: none; }` (that example apply for all
Anyway you should set `customKey` prop for all columns if they have empty `label` prop.

**Comment by proehlen** [comment]
@jtommy Thanks a lot.  I was still getting the blank header area with your CSS but then on a hunch I also added `:has-modal-cards="false"` and it went away.  Thanks again for your help.

**Comment by rajsinghUSA** [comment]
> @proehlen By css you can hide thead, for example `.table thead { display: none; }` but surely you know that sorting will be lost.
> Anyway you should set `custom-key` prop for all columns if they have empty `label` prop.

To anyone trying this solution, be aware that `.table thead { display: none; }` will also break the width property (_i.e._, `width="40"` will no longer work)
