### ISSUE TITLE
Style of a table inside a table detail row changed

### ISSUE THREAD

**Issue by sanderheilbron** [rafaelpimpa/buefy#311]
### Overview of the problem

**Buefy** version: 0.5.2
**Vuejs** version: 2.4.2
**OS/Browser**: MacOS 10.12.5 / Chrome 60

### Description

Since Buefy 0.5.2 the styling of a table inside a table detail row is different compared to previous versions. 

In 0.5.2. each row or cell contains a box-shadow, striped rows are missing and hovering over a table row does not change the color of the row. The inset shadow of the border of the detail row itself also changed.

#### 0.5.2
<img width="1092" alt="0 5 2" src="https://user-images.githubusercontent.com/41921/30242798-772e508e-959d-11e7-8b0b-26ce731ba304.png">

#### 0.5.1
<img width="1092" alt="0 5 1" src="https://user-images.githubusercontent.com/41921/30242800-7d2af514-959d-11e7-9299-9d532209a9d7.png">

**Comment by wanxe** [comment]
It seems that we have any issue with the overrides. I will try to correct it.

**Comment by wanxe** [comment]
I'm implementing some new changes into it. Let me check what happened with the new version of Bulma :)

Thanks for the review!

**Comment by wanxe** [comment]
Fixed in  #403
