### ISSUE TITLE
Using bLoading inside VueRouter beforeEach - IT IS NOT A BUG

### ISSUE THREAD

**Issue by rof20004** [rafaelpimpa/buefy#312]
I know this is not a bug, but I do not know where to ask about something in Bulma or Buefy.

My problem is:

1. I want to use Buefy.Loading inside beforeEach, in my router.js to show centralize the loading of each page, how can I do this?

Thanks and Regards,

Rodolfo Azevedo

**Comment by jtommy** [comment]
@rof20004 I think there are serveral solutions, for example:
```
import Vue from 'vue'
import Buefy from 'buefy'

Vue.use(Buefy)

export default {
    beforeRouteEnter(to, from, next) {
        const loading = Vue.prototype.$loading.open()
        next(vm => {
            loading.close()
        })
    }
}
```

**Comment by rof20004** [comment]
@jtommy Thanks man, Is what I am looking:

```
Vue.prototype.$loading.open()
```

I was using Vue.loading, I forgott that I need to prototype.

Thanks again :D
