### ISSUE TITLE
Modal and Loading conflict

### ISSUE THREAD

**Issue by defiant** [rafaelpimpa/buefy#313]
I was using and modals and loading on the same components. It look like after the loading is displayed and removed the modals came up empty.

The modal overlay is there, but no content #

**Comment by jtommy** [comment]
@defiant Did you use loading by component or programmatically ? 
Can you provide us an example ?

**Comment by defiant** [comment]
As it turns out there was no conflict between the two components. The problem (at least in my case) when the the page is too long default  positioning can create some problems and the overlay shows but the modal content stays below the fold which makes you think its not working
