### ISSUE TITLE
Inline Datepicker does not change to Font Awesome when adding attribute icon-pack="fa"

### ISSUE THREAD

**Issue by laij84** [rafaelpimpa/buefy#314]
### Overview of the problem

**Buefy** version: [0.5.2]
**Vuejs** version: [2.4.2]
**OS/Browser**: Mac Sierra / Chrome

### Description

When adding attribute `icon-pack="fa"`, the Datepicker still continues to use mdi icons. 

### Expected behavior

icon class should change to "fa"

### Actual behavior

icon class still is "mdi".

**Comment by jtommy** [comment]
@laij84  Icon pack is applied to input and inline mode doesn't have input.
