### ISSUE TITLE
Add default datepicker settings to constructor

### ISSUE THREAD

**Issue by apocalyarts** [rafaelpimpa/buefy#317]
**Buefy** version: [0.5.2]
**Vuejs** version: [2.1.10]
**OS/Browser**: Win/Chrome

### Description

Please add more datepicker settings to the global constructor options. I'm from Germany, so we have different labels and our weeks usually start on Monday. Would be great to have:

- day-names
- month-names
- first-day-of-week

...So I don't need to define this attributes on each component. Also while you're at it, you accidentially switched the default values for day-names and week-names under "API" in the docs at https://buefy.github.io/#/documentation/datepicker

**Comment by jtommy** [comment]
@apocalyarts Good request! We thought about it and we'll be available in next release. 
Thanks
