### ISSUE TITLE
Feature request: Name attribute for input fields

### ISSUE THREAD

**Issue by maxleaver** [rafaelpimpa/buefy#320]
### Overview of the problem

There is no method for setting a name attribute on an input field. The name attribute is useful when using Vue events. For example, when trying to determine which input field had a keydown event in a form (ie. using $event.target.name on an keydown event).

### Description

I propose adding an optional name property that simply populates the standard HTML input name property. This would require an update to the Input component and an update to the docs to reflect the new option. I'm happy to provide a pull-request.

**Comment by thc1967** [comment]
When I do this:

```PHP
<b-field label="E-Mail Address">
    <b-input type="email" value="" name="email" icon="email"></b-input>
</b-field>
```

In Chrome's Inspect UI, it renders as:

```
<input type="email" autocomplete="on" name="email" class="input">
```

It also posts to the server as I expect it to.

What can't Vue do with it?

**Comment by maxleaver** [comment]
Haha. You're right. Somehow I didn't notice that it just passes straight through. That's embarrassing. Thank you. I'll close this and go back to my hole in the ground.
