### ISSUE TITLE
Add click event to children of b-table-column component?

### ISSUE THREAD

**Issue by ghprod** [rafaelpimpa/buefy#322]
### Overview of the problem

**Buefy** version: 0.5.2
**Vuejs** version: 2.4.2
**OS/Browser**: Chrome

### Description

Hi @rafaelpimpa 

In my table, i need to add action buttons for each row like this

![image](https://user-images.githubusercontent.com/1922652/30510217-bc260974-9ae9-11e7-840c-c90ffc40f271.png)

```html
<b-table-column>
  <button class="button is-small is-light" @click="edit(props.row)">
    <b-icon icon="edit" size="is-small"></b-icon>
  </button>
  <button class="button is-small is-danger" @click.native="delete(props.row)">
    <b-icon icon="delete" size="is-small"></b-icon>
  </button>
</b-table-column>
```

But click event never triggered even with `click.native`. If I change my code like this, then it's works

```html
<b-table-column @click.native="delete(props.row)">
  <button class="button is-small is-light">
    <b-icon icon="edit" size="is-small"></b-icon>
  </button>
  <button class="button is-small is-danger">
    <b-icon icon="delete" size="is-small"></b-icon>
  </button>
</b-table-column>
```

But with this code means i can only bind 1 event per column, not for each button icon.

Any idea how to achieve this? or i should think another approach?

Thanks

**Comment by thc1967** [comment]
The approach I took was to make the rows selectable and put the edit and delete buttons above the table. I set my buttons up to call methods I add to my `methods` grouping by adding `@click.prevent="onEdit"` and `@click.prevent="onDelete"` to the Edit and Delete buttons, respectively.

Once I'm in the `onEdit()` method, I can access the `id` of the selected record with `indexTable.selected.id` and take the appropriate action, be it confirm and make an Ajax request for my delete or navigate to the edit page.

For your particular layout, why can't you bind the click event to the buttons inside the column instead of the column? Something like this (untested):

```html
<b-table-column label="Actions">
  <button class="button is-small is-light" @click.prevent="onEdit(props.row)">
    <b-icon icon="edit" size="is-small"></b-icon>
  </button>
  <button class="button is-small is-danger" @click.prevent="onDelete(props.row)">
    <b-icon icon="delete" size="is-small"></b-icon>
  </button>
</b-table-column>
```

**Comment by ghprod** [comment]
Hi @thc1967 

Thanks for your reply.

Actually approach with selected row and put button action above table has crossed my mind, inspired by material design table https://material.io/guidelines/components/data-tables.html

![image](https://user-images.githubusercontent.com/1922652/30514193-7ebef2e8-9b3a-11e7-8de9-c96922864378.png)

But sometimes, for UX purposer, we need to add button for each row for quick action :)

For your code above, i've tried it too, even with `click.native` (see my post above). but still no luck :(

Regards

**Comment by Tirke** [comment]
Is perfectly possible to add an action column. Everything works out of the box.

```javascript
<b-table-column custom-key="actions">
  <button class="button is-small is-light" @click="edit(props.row)">
    <b-icon icon="edit" size="is-small"></b-icon>
  </button>
</b-table-column>
```

This code is 100% working, don't forget `custom-key` if you don't set any label.

**Comment by ghprod** [comment]
Hi @Tirke,

Strange, everything is working now :confused: 

I can confirm that this code working perfectly 

```html
<b-table-column custom-key="actions">
  <button class="button is-small is-light" @click="edit(props.row)">
    <b-icon icon="edit" size="is-small"></b-icon>
  </button>
</b-table-column>
```

I close this issue right now :)

Thanks

**Comment by gevera** [comment]
This doesn't work, unfortunately with the latest Buefy

**Comment by jtommy** [comment]
@gevera what?

**Comment by hashims** [comment]
`<b-table-column custom-key="actions" label="Actions" v-slot="props">
    <button class="button is-small is-danger" @click="delete(props.row)">
      <b-icon icon="delete" size="is-small"></b-icon>
    </button>
</b-table-column>`

This is not working on latest versionof Beufy. I've gone through all the possible solution mentioned above but none of them worked.

**Comment by hashims** [comment]
`<b-table-column custom-key="actions" label="Actions" v-slot="props">
    <button class="button is-small is-danger" @click="delete(props.row)">
      <b-icon icon="delete" size="is-small"></b-icon>
    </button>
</b-table-column>`

This is not working on latest version of Beufy. I've gone through all the possible solution mentioned above but none of them worked.

**Comment by consciousnessdev** [comment]
> `<b-table-column custom-key="actions" label="Actions" v-slot="props"> <button class="button is-small is-danger" @click="delete(props.row)"> <b-icon icon="delete" size="is-small"></b-icon> </button> </b-table-column>`
> 
> This is not working on latest version of Beufy. I've gone through all the possible solution mentioned above but none of them worked.

So do i, its only show button

**Comment by dumbleedore** [comment]
`        <b-table-column v-slot="props" custom-key="actions">
          <button class="button is-small is-light" @click="editRow(props.row)">
            <b-icon icon="edit" size="is-small"></b-icon>
          </button>
        </b-table-column>`
This seems to work fine for me
