### ISSUE TITLE
Datepicker @change problem

### ISSUE THREAD

**Issue by srunicornio** [rafaelpimpa/buefy#323]
### Overview of the problem

**Buefy** version: [0.5.2]
**Vuejs** version: [2.4.1]
**OS/Browser**:

### Description
Datepicker @change don't work after select date.  

```
<b-datepicker
  v-model="date"
  :readonly="false"
  @change="updateData(date)">
</b-datepicker>
```

**Comment by jtommy** [comment]
@srunicornio Date picker doesn't emit `change` event but only `input`.

**Comment by orangeShadow** [comment]
Why you don't generate event change ? It's very useful if you make some hard component ?
