### ISSUE TITLE
styling on fields wrapping inputs disappears on blur

### ISSUE THREAD

**Issue by gwvt** [rafaelpimpa/buefy#33]
Blur removes the styling bound to the field type wrapping inputs on blur. This happens on the documentation page for Buefy, where the green 'Success' etc disappears on leaving the input box. When the field type is bound to a property it will only display the appropriate styling when the property changes.

**Comment by rafaelpimpa** [comment]
I see, should I only update the Field type on-blur when there's nothing set from the user then?

**Comment by rafaelpimpa** [comment]
I'm doing the same for ``message``, if user defined any message, the HTML5 validation message will not override.

**Comment by gwvt** [comment]
It might be nice to have the option to clear or not clear the field type styling on blur. My use case is for custom validating particular fields before allowing the user to click 'save' to update the resource. In this situation, if any field has not validated I want the 'danger' styling to remain until the user has entered a value that validates. But there may be other cases where you want the type to clear on blur, like if a method is called immediately upon the 'success' condition and user input is disabled. Then you would want the success styling to clear on blur.

**Comment by rafaelpimpa** [comment]
I'm gonna keep it this way: if user defined a type or message, the validation will not override on-blur. You can always remove the type to clear it tho.

**Comment by gwvt** [comment]
OK, not sure I understand which way you decided.
Here's my use case: each keyup in the given input calls a validation function. If that function returns false, the field type is bound to 'is-danger' and the accompanying message is displayed.
If the user blurs out of the input, I want the 'is-danger' styling to remain until the user re-enters the input and changes the value so that the validation function returns true.
The 'Save' button is disabled until all validation functions return true, so it is confusing to the user to not be able to click 'Save' and not see which field(s) have not validated yet.
Is that possible?

**Comment by rafaelpimpa** [comment]
It will work like that now, your own validations will have priority.

I'm publishing the patch right now btw.

**Comment by gwvt** [comment]
You're awesome! Thanks so much.
