### ISSUE TITLE
Hide slected b-table columns on mobile

### ISSUE THREAD

**Issue by mirahost** [rafaelpimpa/buefy#333]
Is it possible to do this? I tried the is-hidden-mobile class but it did not work.

Is there another reliable method to do this?

**Comment by jtommy** [comment]
@mirahost What did you want to do ? Hide selected row style on mobile or disable selected behaviour on mobile ?

**Comment by mirahost** [comment]
I don't understand your question. The goal is to not display certain columns on narrow screens because the number of columns is too wide and only suitable for very large monitors.

**Comment by jtommy** [comment]
I'm sorry but you asked about selected table row. You can enable mobile-cards, no?

**Comment by mirahost** [comment]
I see how my question was confusing. Mobile cards do work, but on some displays, like a small laptop, the mobile cards are not practical and there are still too many columns to view.

**Comment by jtommy** [comment]
At the moment you can't set a class to th. 
I think to do it you have to play with visible prop for each bTableColumn and change these value listening matchMedia in JavaScript

**Comment by mirahost** [comment]
thank you for the tip on matchMedia, that might help me sort this out.

**Comment by dumptyd** [comment]
Hijacking this thread to ask a somewhat similar question. Is it possible to hide some columns when table turns into cards?

**Comment by Lukasiniho** [comment]
> Hijacking this thread to ask a somewhat similar question. Is it possible to hide some columns when table turns into cards?

I have the same question, ie is it possible to specify that a column should not be shown on mobile?

**Comment by swaylock** [comment]
+1 for reopening this issue. Should be able to selectively hide table columns. Sadly, ` class="is-hidden-touch"` does not hide table column header

**Comment by jtommy** [comment]
You can use cellClass and headerClass props

**Comment by swaylock** [comment]
@jtommy thank you!
