### ISSUE TITLE
Discrepancy between Bulma CSS and Buefy CSS on `.container` class

### ISSUE THREAD

**Issue by Jak893** [rafaelpimpa/buefy#34]
So I've been having some weird issues with the containers styling inside Buefy for the past day or so and finally, I think I've narrowed it down to an discrepancy between the Buefy CSS and the CSS you'd get from  Bulma directly.

The specific case in question I've been dealing with is based around their full height hero sections but is replicated anywhere where you use a container.

This is the CSS from Bulma documentation:
![bulmacss](https://cloud.githubusercontent.com/assets/664193/25270774/a8d2f9f2-2679-11e7-9361-456149e5ca03.PNG)

This is the CSS from importing the Buefy CSS inside my project:
![buefycss](https://cloud.githubusercontent.com/assets/664193/25270780/abdb7458-2679-11e7-90f5-f8d211bc89ca.PNG)

Notice the lack of a `max-width` within the included Buefy CSS, as a result, it is causing the container to expand the full-width of this hero element on the page in question.

For reference, the component that I am trying to render is located [here](http://bulma.io/documentation/layout/hero/)

**Comment by Jak893** [comment]
Oddly enough, I just tried installing Bulma directly and referencing that CSS over Buefy CSS and the issue is persisting so it seems to be a Bulma issue and not a Buefy one! :(

**Comment by rafaelpimpa** [comment]
Thanks for digging out. Didn't have time before to look at it.
