### ISSUE TITLE
Feature Request: BMessage popable like Message from Vue-Bulma-Admin

### ISSUE THREAD

**Issue by evandroabukamel** [rafaelpimpa/buefy#342]
Hi,

Can you make the BMessage component to be capable of being instantiated in the `.notices` container like the Message component from Vue-Bulma-Admin, so we can instantiate a new message from anywhere and it can be closed after the duration time.

https://admin.vuebulma.com/#/components/message

Thanks.

**Comment by rafaelpimpa** [comment]
For that we have snackbars and toasts, I have no intention on implementing it.
