### ISSUE TITLE
Bind click action to b-tab-item

### ISSUE THREAD

**Issue by mirahost** [rafaelpimpa/buefy#343]
### Overview of the problem

**Buefy** version: 0.5.3
**Vuejs** version: 2.4.4
**OS/Browser**: OSX / Firefox / Chrome

### Description

When a click event is added to b-table-item it is not fired. 

### Steps to reproduce

 ```
<template>
        <section>
            <b-tabs>
                <b-tab-item @click="myFunction('test')" label="Pictures">
                    Lorem ipsum dolor sit amet.
                </b-tab-item>

                <b-tab-item label="Music">
                    Lorem <br>
                    ipsum <br>
                    dolor <br>
                    sit <br>
                    amet.
                </b-tab-item>

                <b-tab-item label="Videos">
                    Nunc nec velit nec libero vestibulum eleifend.
                    Curabitur pulvinar congue luctus.
                    Nullam hendrerit iaculis augue vitae ornare.
                    Maecenas vehicula pulvinar tellus, id sodales felis lobortis eget.
                </b-tab-item>
            </b-tabs>
        </section>
    </template>

// Snip from vue properties //

        methods: {
            myFunction(message) {

                console.log(message);

            },
        }



```

### Expected behavior

When the tab with the click event is click, the event should fire

### Actual behavior

The tab functions (changes) but the event is not fired

**Comment by jtommy** [comment]
@mirahost There isn't click event to bTabsItem.
You have to add v-model to bTabs and watch the binded data or listen change event to bTab. Both example the value is the index of bTabItem position (0-n).

**Comment by mirahost** [comment]
I am trying to sort out your examples. Do you happen to have a demo?

**Comment by jtommy** [comment]
`v-model` example: https://jsfiddle.net/eohh8cjt/
`@change` example: https://jsfiddle.net/ou86r95y/

**Comment by mirahost** [comment]
Awesome, thank you! I really appreciate your help.

**Comment by giovannilaperna** [comment]
@jtommy the second example, with `@change`, doesn't work anymore. Any workaround?

**Comment by jtommy** [comment]
@giovannilaperna you have to use native modifier
