### ISSUE TITLE
Feature Request: Input Formatting Masks

### ISSUE THREAD

**Issue by ismet** [rafaelpimpa/buefy#344]
I wish Buefy has built-in input mask directives for any kind of number, text and currency formatting. I am already using the following external libs:
https://github.com/vuejs-tips/vue-the-mask
https://github.com/vuejs-tips/v-money

**Comment by rafaelpimpa** [comment]
We're not adding it since you can add it as a directive with better libs, and example with Cleavejs here: https://github.com/rafaelpimpa/buefy/issues/185#issuecomment-317073290
