### ISSUE TITLE
Hiding Checked Rows Number in Table

### ISSUE THREAD

**Issue by ismet** [rafaelpimpa/buefy#345]
If we use **`checkable`** property in _`b-table`_ and make rows checkable, then the total number of checked rows is displayed as `(number)` in the footer. I don't understand why it is implemented since we can easily display it anywhere by using a property like `checkedRows.length`.

So, how can I get rid of that number and show nothing in the footer section of table? Or, is there a way to make it optional?

**Comment by rafaelpimpa** [comment]
You are right, we could remove that and open that for a slot as a PR we have opened.
