### ISSUE TITLE
Inverting icon colors in selected rows

### ISSUE THREAD

**Issue by ismet** [rafaelpimpa/buefy#346]
I have added `:selected.sync` property in `b-table` and enabled selection of rows. 

When I select a row, color of text in that row inverts automatically, so they are being more readable. 
However, when I use icons in rows their colors remains the same and they aren't as clear as texts and even visible if `is-primary`.

Is there a way to change icon colors in selected rows?

**Comment by ismet** [comment]
Ok, I have just realized that if you don't specify type property or specify it as `type="is-default"` for the icon it works, otherwise not..

**Comment by jtommy** [comment]
@ismet Default icon color follows text color and when a row is selected the table change color style.
You might change icon color in selected rows, for example: `<b-icon :type="props.row === selected ? 'is-default' : 'is-primary'"`.
