### ISSUE TITLE
Incompatibility with v-money

### ISSUE THREAD

**Issue by ismet** [rafaelpimpa/buefy#347]
buefy and [v-money (input mask for currency)](https://github.com/vuejs-tips/v-money) have a problem with each other. 

If you use `<b-input>`,  you cannot set the value of v-money input. It took several hours for me to figure it out.. 

The following is not working;
`<b-input v-model="price" v-money="money"></b-input>`

The following is working;
`<input class="input" v-model="price" v-money="money" />`

**Comment by jtommy** [comment]
@ismet What's the problem ? I saw v-money code and i think it's good for b-input. Could you provide us your full code ?

**Comment by ismet** [comment]
@jtommy Below is the full code..

```
<template>
    <section>
        <b-input v-model="price1" v-money="moneyFormat"></b-input>
        <input v-model="price2" v-money="moneyFormat" class="input" />
        <button @click="setPrices">Set Prices</button>
    </section>
</template>
<script>
    export default {
        data() {
            return {
                price1     : 0.0,
                price2     : 0.0,
                moneyFormat: {
                    decimal  : '.',
                    thousands: ',',
                    prefix   : '£ ',
                    suffix   : '',
                    precision: 2,
                    masked   : false  /* doesn't work with directive */
                }
            };
        },
        methods: {
            setPrices: function() {
                this.price1 = 123.45;
                this.price2 = 123.45;
            }
        }
    }
</script>
```
If you click button here, you can change **price2**(`<input>`) but you can't change **price1** (`<b-input>`).

**Comment by jtommy** [comment]
You have to set value by DOM. See my example https://jsfiddle.net/rjzk6hh2/

**Comment by ismet** [comment]
If I have to follow a workaround, then I wouldn't use `<b-input>` anyways. 

I think it is clearly a bug and needs to be fixed..

**Comment by jtommy** [comment]
It's a workaround only about to set a value but you can use other prop of `b-input`.
We might investigate about it but are you sure it isn't a problem of `v-money`? I don't know that component `money` component doesn't work very well https://jsfiddle.net/rjzk6hh2/2/

**Comment by zeurgo** [comment]
It works perfectly, but it is giving this error right after it starts.
Error in nextTick: "TypeError: Can not read property 'value' of null"
