### ISSUE TITLE
[QUESTION] Can I use datepicker to pick a month?

### ISSUE THREAD

**Issue by gfviegas** [rafaelpimpa/buefy#348]
Can I use the buefy datepicker to pick a month instead of a date itself? Just like the input(type="month") does but with the datepicker layout and options?

Thanks.

**Comment by jtommy** [comment]
@gfviegas No, you can't.

**Comment by zevektor** [comment]
Could this feature be planned in future releases?

While I understand that implementing a DIY solution is totally feasible, I'd like (and I guess other users as well) to have a standard option that fits quite well with the styling of the other components of bulma/buefy.

**Comment by jtommy** [comment]
Added in 0.7.7

**Comment by jtommy** [comment]
@gfviegas @zevektor Added in 0.7.7
