### ISSUE TITLE
Making "checkable" a true boolean

### ISSUE THREAD

**Issue by ismet** [rafaelpimpa/buefy#349]
I have a scenario where `b-table` component property **`checkable`** must be conditional. 

I need something like this (where isCheckable is a boolean);
`
<b-table checkable="isCheckable"  ...
`

Currently, it gives an error like;
`Invalid prop: type check failed for prop "checkable". Expected Boolean, got String.`

In order to make it non-checkable, we have to remove `checkable `prop from table definition, which is not a right approach..

**Comment by thc1967** [comment]
I think it would be ```:checkable="isCheckable"``` with ```isCheckable: true,``` in your vue data structure.

**Comment by ismet** [comment]
@thc1967 Thank you, it worked.. 

The documentation has only `checkable` like this;
```
<b-table
        :data="tableDataSimple"
        :checked-rows.sync="checkedRows"
        checkable> ...
```

**Comment by jtommy** [comment]
@ismet Yes but it works like `paginated` prop or other Boolean prop
