### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by bahit** [rafaelpimpa/buefy#35]
When using Dropdown (General > Dropdown), I get console error of cannot read property 'length' of undefined, which is located at `node_module/buefy/lib/src/index.js`.

```
TypeError: Cannot read property 'length' of undefined
    at /Users/bahit/Projects/markx/app/node_modules/buefy/lib/src/index.js:formatted:3637
    at Array.<anonymous> (/Users/bahit/Projects/markx/app/node_modules/buefy/lib/src/index.js:formatted:2445)
    at t (/Users/bahit/Projects/markx/app/node_modules/buefy/lib/src/index.js:formatted:2413)
```
Above error lines expanded after I used chrome dev tool's expanding the minified code (else it would just indicate line 3 minified).

I don't know how to use source map.

I only used the provided code:

```
<b-dropdown>
    <button class="button" slot="trigger">
        <span>Dropdown</span>
        <b-icon icon="arrow_drop_down"></b-icon>
    </button>

    <b-option>Action</b-option>
    <b-option>Another action</b-option>
    <b-option>Something else</b-option>
</b-dropdown>
```

**Comment by surgiie** [comment]
Having same issue? Any fixes?

**Comment by rafaelpimpa** [comment]
I'm on a travel right now. When I get back by Monday gonna take a look at it.
