### ISSUE TITLE
Could we get an example of using row-class on b-table?

### ISSUE THREAD

**Issue by thc1967** [rafaelpimpa/buefy#351]
I don't know that this is a problem with the code as much as maybe me not understanding how it should work.

I have a ```b-table``` that includes ``` @row-class="onRowClass"```.

In my code, I have:

```
methods: {
    onRowClass: function (row, index) {
        console.log('onRowClass(%d)', index);
    },
},
```

Nothing is logged to the browser console when the table loads.

Just to add fun on top of the fun, this is for a b-table that is embedded into the detail area of a detailed b-table. :)

**Comment by jtommy** [comment]
@thc1967 There is an example in the official docs https://buefy.github.io/#/documentation/table.
Anyway `row-class` is a prop (Function type) and not an event (@). 
You have to bind `:row-class="onRowClass"`.

**Comment by thc1967** [comment]
Ah, you are correct. I apologize for missing that. Works correctly when I use it as documented, of course. Thanks.
