### ISSUE TITLE
placeholder doesn't work for <b-select>

### ISSUE THREAD

**Issue by Tobbe** [rafaelpimpa/buefy#352]
### Overview of the problem

**Buefy** version: https://unpkg.com/buefy
**Vuejs** version: https://unpkg.com/vue/dist/vue.js
**OS/Browser**: Win 10, Chrome latest

### Description

No placeholder text is shown in the `<select>`. If I remove the `v-model` attribute the placeholder shows up.

![image](https://user-images.githubusercontent.com/30793/31231651-c15589f8-a9e7-11e7-8359-8b6ec6ff50d1.png)

As you can see in the developer tools an `<option>` is generated for the placeholder, but no placeholder text is showing up in the `<select>` dropdown

### Steps to reproduce

Look here: https://jsfiddle.net/Lyegqxja/

### Expected behavior

Placeholder text should show up

### Actual behavior

Placeholder text is not visible

**Comment by jtommy** [comment]
@Tobbe You have to set null as default value, `selected` data in your example.

**Comment by Tobbe** [comment]
Perfect! Thank you 👍 😃

**Comment by Scarittagle** [comment]
@jtommy But what if the `selected` is a empty array (which is necessary on my work) ?

**Comment by jtommy** [comment]
Same way, default value is null and not empty array
