### ISSUE TITLE
Hiding rows on <b-table>?

### ISSUE THREAD

**Issue by Pitu** [rafaelpimpa/buefy#353]
I was wondering with the latest Buefy if there is a way to hide certain rows? I have my own search function that goes through the tableData loaded into `<b-table>` and sets the `display` key to either `true` or `false` based on the search output.

So far I haven't found a way to hide said rows and trigger a pagination compute again (although I can do this manually by using the pagination element separate from the table). I tried different approaches like the following but this ends in a blank row instead of hiding it.

```html
<b-table :data="songs">
	<template scope="props" vf-if="props.row.display">
		<b-table-column v-for="(column, index) in columnsTemplate"
			:key="index"
			:field="column.field"
			:label="column.title"
			:visible="column.visible">
			{{ props.row[column.field] }}
		</b-table-column>
	</template>
</b-table>
```
and
```html
<b-table :data="songs">
	<template scope="props">
		<b-table-column v-for="(column, index) in columnsTemplate"
			:key="index"
			:field="column.field"
			:label="column.title"
			:visible="column.visible">
			<template v-if="props.row.display">
				{{ props.row[column.field] }}
			</template>
		</b-table-column>
	</template>
</b-table>
```
Any help would be appreciated, thanks!

**Comment by jtommy** [comment]
@Pitu I think the easy way is to manipulate `data `prop (songs) and remove the elements that you want to hide.

**Comment by Pitu** [comment]
Hi @jtommy , that's what I'm doing it right now and it works. But I realized that it gets wonky when showing images on the table, since removing an element from the array and adding it back again later (when search is cleared for example) triggers a reload. This could be solved by implementing some form of client side cache, but before diving into that I wanted to ask around and see if there was a simpler way by hiding rows instead.

**Comment by jtommy** [comment]
@Pitu Only way to hide `tr` tag (tbody row) is to bind `row-class` prop, for example: 
`<b-table :row-class="(row, index) => row.id === 1 ? 'is-hidden' : ''"> .... </b-table>`

**Comment by Pitu** [comment]
That looks like what I was looking for, thank you!

**Comment by dejurin** [comment]
**b-table-column**
prop -> :visible
