### ISSUE TITLE
b-autocomplete search results don't display when within a b-tab-item

### ISSUE THREAD

**Issue by talismax** [rafaelpimpa/buefy#355]
### b-autocomplete doesn't work (search results don't display) within a b-tab-item

**Buefy** version: [0.5.3]
**Vuejs** version: [2.4.4]
**OS/Browser**: Windows 10/Chrome latest stable

### When I wrap a working autocomplete component within a tab/tab-item I can no longer see the search results. API calls work, data is populated and oddly enough I can see the drop down html generated in Chrome Dev Tools:
![image](https://user-images.githubusercontent.com/2261681/31289460-734186c0-aa8e-11e7-9cf1-13506d3b2e69.png)

However, the rendered app does not display the search results:
![image](https://user-images.githubusercontent.com/2261681/31289546-b467caa6-aa8e-11e7-9095-8b7393dbbda3.png)

### Expected behavior

Drop down values show

### Actual behavior

Drop down values do not show

**Comment by talismax** [comment]
The solution is just to add some controls with a height below the autocomplete. The search results need something to float on top of in order to be visible. Duh!

**Comment by SSebigo** [comment]
Hey, I have the same problem and somehow I don't understand how you fixed it, can you explain, please?
