### ISSUE TITLE
Table Header Alignment

### ISSUE THREAD

**Issue by ismet** [rafaelpimpa/buefy#356]
I want to make a specific column text (header + data) to align center.

I added `class="has-text-centered"` or `style="text-align:center"` to the `<b-table-column>`. This makes only data centered, not header.

How can I change the alignment of `<b-table>` header?

_Note: The header scoped slot change all column headers, not one of them.._

**Comment by ismet** [comment]
I think we need something like this;
```
<b-table-column field="price">
        <b-table-column-header class="headerClass" style="headerStyle">
                Header Label  {{ props.row.dynamicText1 }}
        </b-table-column-header>
        <b-table-column-data   class="dataClass"   style="dataStyle">
                Row Data  {{ props.row.dynamicText2 }}
        </b-table-column-data>
</b-table-column>
```

**Comment by jtommy** [comment]
@ismet Header slot allow to read all bColumn properties and it is applied to each header column.
In your case you might have something like to apply a custom style only for one column:
```
<template scope="props" slot="header">
   <div style="width: 100%" :class="{'has-text-centered': props.column.label === 'FN'}">
     {{ props.column.label }}
   </div>
</template>
```

**Comment by ismet** [comment]
@jtommy, `:class` property works however the header text is not aligned properly if has-text-centered or has-text-centered is applied.

`has-text-right`
![image](https://user-images.githubusercontent.com/109025/31371871-edde3cc4-ad9b-11e7-9718-cefbb3abef6f.png)

`has-text-centered`
![image](https://user-images.githubusercontent.com/109025/31371900-0fb4118e-ad9c-11e7-8d83-644458e2b6ca.png)

As you can see, there is an interesting and unnecessary space at the right of the header cell.
