### ISSUE TITLE
can't disable/hide tooltip without disabling wrapped button

### ISSUE THREAD

**Issue by gwvt** [rafaelpimpa/buefy#36]
I have a button wrapped by a tooltip. Based on a condition x, I want the button to be disabled if x === true and the tooltip to be disabled/hidden if x === false. Since the tooltip wraps the button, there seems no way to decouple this logic. Is it possible to disable/hide the tooltip without disabling/hiding the wrapped button?

**Comment by gwvt** [comment]
Sorry, I figured it out:

`<b-tooltip :label="theCondition ? '' : 'The tooltip text'">`

**Comment by Tobbe** [comment]
Perhaps it should be considered to add a `for` prop to b-tooltip that works the same way the `for` attribute for `<label>` works.

**Comment by rafaelpimpa** [comment]
Hmm nice one. Gonna think about it thanks.

**Comment by luixal** [comment]
In case someone gets here, just check the ```active``` property in [the tooltip component docs](https://buefy.org/documentation/tooltip).
