### ISSUE TITLE
Correct way to group Input/Autocomplete and Switch

### ISSUE THREAD

**Issue by Kaeltis** [rafaelpimpa/buefy#363]
### Overview of the problem

**Buefy** version: 0.5.3
**Vuejs** version: 2.4.4
**OS/Browser**: Linux/Chrome 61.0.3163.100

### Description

I'm trying to correctly group an input and an autocomplete with a switch in the same line, however I cant manage to find the correct way to combine those.

### Steps to reproduce

```
                <b-field grouped group-multiline>
                    <b-field expanded>
                        <b-input
                                type="text"
                                v-model="modelData.title"
                                placeholder="Titel"
                                required>
                        </b-input>
                    </b-field>

                    <div class="control is-flex">
                        <b-switch v-model="modelData.priority">Priorität</b-switch>
                    </div>
                </b-field>
```

Displays like this:
![screenshot_20171007_165634](https://user-images.githubusercontent.com/809734/31309063-7f64537c-ab80-11e7-8b86-0c5adf1280bb.png)
As you can see, the spacing between the Input and the button is not correct.

```
                <b-field grouped group-multiline>
                    <div class="control is-flex">
                        <b-switch v-model="modelData.approved">Genehmigt</b-switch>
                    </div>

                    <b-field expanded>
                        <b-autocomplete
                                placeholder="Verantwortlich"
                                field="name">
                        </b-autocomplete>
                    </b-field>
                </b-field>
```

Displays like this:
![screenshot_20171007_165722](https://user-images.githubusercontent.com/809734/31309081-c83fc644-ab80-11e7-92c6-c963a7f1997d.png)
As you can see, the button is not centered.

### Expected behavior

Have correct spacing

### Actual behavior

Has wrong spacing

**Comment by jtommy** [comment]
@Kaeltis You have to remove div wrapper from `bSwitch`.
For example (first case):
```
 <b-field grouped group-multiline>
      <b-field expanded>
           <b-input
                  type="text"
                  v-model="modelData.title"
                  placeholder="Titel"
                  required>
            </b-input>
     </b-field>
     <b-switch class="switch-right" v-model="modelData.priority">Priorität</b-switch>
</b-field>

<style>
.switch-right {
    margin-left: 0.75rem;
    margin-bottom: 0.75rem;
}
</style>
```
For example (second case):
```
<b-field grouped group-multiline>
     <b-switch class="switch-left" v-model="modelData.approved">Genehmigt</b-switch>
     <b-field expanded>
        <b-autocomplete
             placeholder="Verantwortlich"
             field="name">
        </b-autocomplete>
     </b-field>
</b-field>

<style>
.switch-left {
    margin-left: 0.75rem;
}
</style>
```

**Comment by Kaeltis** [comment]
Thanks, it's working! However if the b-field shows a validation error, the switch isn't in the correct height anymore.

**Comment by jtommy** [comment]
@Kaeltis It was an example. You have to play with the styles or show error in an other way.
