### ISSUE TITLE
Collapse isOpen is a global only?

### ISSUE THREAD

**Issue by joannesalfa** [rafaelpimpa/buefy#367]
### Overview of the problem

**Buefy** version: 0.5.4
**Vuejs** version: 2.4.4.
**OS/Browser**: Win10 / Opera

### Description

isOpen a prop from collapse, not sure it's a global only or perhaps I'm doing it wrong, I need to compare arrow icon which is closed or open See GIF below.

![Ibuefy collapses](https://i.imgur.com/voFndDS.gif)

### Steps to reproduce

1. Create 2 elements of collapse
2. Click an arrow

### Expected behavior

isOpen should be private variable each component.

### Actual behavior

isOpen acts like global and it picks all the same components.

**Comment by jtommy** [comment]
@joannesalfa `open` is the prop. I think you are using the same variable for your two components. 
Could you provide us your code?

**Comment by joannesalfa** [comment]
Component:

`var productList = Vue.component('product-list', {
  props: {
    isOpen: true
  },
  template: `<b-collapse v-for='index of variations' class="card" :open.sync="isOpen" id="collapse">
          <div slot="trigger" class="card-header">
              <p class="card-header-title">
                  {{index.type}}
              </p>
              <a class="card-header-icon">
                  <b-icon slot="trigger" :icon="isOpen ?
                      'arrow_drop_down' : 'arrow_drop_up'">
                  </b-icon>
              </a>
          </div>
          <div class="card-content">
              <div>
                <ul>
                  <li v-for="values in index.values"> {{values}} </li>
                </ul>
              </div>
          </div>
      </b-collapse>`,
  data: function() {
    return {
      variations: [{
          type: 'color',
          values: ['red', 'blue', 'yellow']
        },
        {
          type: 'size',
          values: ['large', 'medium', 'small']
        },
      ]
    }
  }
})`


Instance:

```
var App = new Vue({
    el: '#app',
    components: {
      productList
    })
```

**Comment by jtommy** [comment]
@joannesalfa Yes, the problem is you are using the same variable (`isOpen`) to `open` prop for each `bCollapse` component.
You should to move `v-for` before your component.

**Comment by joannesalfa** [comment]
@jtommy What do you mean with move `v-for` before component in other component that use it.

Sorry, I don’t understand this logic...

**Comment by jtommy** [comment]
You are sharing your `isOpen` prop for each `bCollapse` component and that is not correct if you want that `bCollapse` are indipendent.

**Comment by joannesalfa** [comment]
Would you mind to provide a small example that I shouldn’t share `isOpen`? If I dont include `isOpen` as prop or data, the function will return error.

If we have a solution and prove I’m wrong, I will close this issue.

**Comment by jtommy** [comment]
```
var productList = Vue.component('product-list', {
  props: {
    isOpen: true
  },
  template: `<b-collapse v-for='index of variations' class="card" :open.sync="index.isOpen" id="collapse">
          <div slot="trigger" class="card-header">
              <p class="card-header-title">
                  {{index.type}}
              </p>
              <a class="card-header-icon">
                  <b-icon slot="trigger" :icon="index.isOpen ?
                      'arrow_drop_down' : 'arrow_drop_up'">
                  </b-icon>
              </a>
          </div>
          <div class="card-content">
              <div>
                <ul>
                  <li v-for="values in index.values"> {{values}} </li>
                </ul>
              </div>
          </div>
      </b-collapse>`,
  data: function() {
    return {
      variations: [{
          isOpen: this.isOpen,
          type: 'color',
          values: ['red', 'blue', 'yellow']
        },
        {
          isOpen: this.isOpen
          type: 'size',
          values: ['large', 'medium', 'small']
        },
      ]
    }
  }
})

```
I don't know your project and why are you using `isOpen` as a component prop. 
As you can see in my example you have two differente `isOpen` variable with `isOpen` prop as default value (you can remove that prop if you don't need and set a default value for each `isOpen` data `variations` element)

**Comment by joannesalfa** [comment]
Ah, I see, it's supposed to be a model, I thought open is related to isOpen which is default variable as state, now I'm wrong :0, thank you for explaining.

I'm going to close this issue, anyway I would like to ask a question.

https://buefy.github.io/#/documentation/collapse

You see animation as property, the default is fade, it seems is not playing fade animation, it looks like static. Is there a list of animations are available to use from Buefy?

**Comment by jtommy** [comment]
No, there isn't. You are free to add your animation as you want.

**Comment by Oanra** [comment]
Can you please show an example using some animation in <b-clollapse> ? Im new to buefy but in the documentation i can't find any example with animation property.

Thanks

**Comment by grebebird** [comment]
@Oanra - it might be helpful to look at the collapse source code to understand how transitions work (https://github.com/buefy/buefy/blob/dev/src/components/collapse/Collapse.vue). Under the hood, it's just using Vue's transition functionality which you can read more about here: https://vuejs.org/v2/guide/transitions.html#Transition-Classes

Hopefully those two pieces will help you or others with the same question.

**Comment by hasyemiraws** [comment]
Hi sorry to jump in, even tho this is closed already, i had the same problem with having two or more b-collapse, but in my case i don't use any props/model. I use ```:open="false"``` for both of component and it triggers both of them.

I use the same example from documentation with card.

**Comment by hasyemiraws** [comment]
Ups sorry, false alarm, it's actually on css side, when i using it inside a Tile from Bulma!
