### ISSUE TITLE
"methods" option in the API 

### ISSUE THREAD

**Issue by mikejavier** [rafaelpimpa/buefy#368]
Hello, I have seen that some components have the "methods" option in the API, but it is not clear what that would be and how to use it. I tried to find some examples but to no avail. What's different about it with "events" and an example of usage.

**Comment by jtommy** [comment]
@mikejavier When you use a component the best practice is to use only props and events but sometimes you could need to force a behaviour of a component calling its method.
For example:
```
<b-autocomplete ...
       ref="autocomplete">
</b-autocomplete>

export default {
        ...
        mounted() {
             this.$refs.autocomplete.setSelected(...)
        }
}
```
