### ISSUE TITLE
<b-dropdown> doesn't change the dopdown's text when you change value

### ISSUE THREAD

**Issue by darkylmnx** [rafaelpimpa/buefy#37]
in your `<b-dropdown>` component, when i choose "another action" for example in your demo, the dropdown still says "dropdown" while that's not how a drop down works noramlly as dropdowns with text are considered as custom "select" fields.

check out the dropdown section here : https://vuetifyjs.com/components/buttons

I think you should consider adding an option that sets the value selected on the ui

**Comment by rodymol123** [comment]
No, that's not how dropdowns work :P

You should try <b-select> ;)

**Comment by rafaelpimpa** [comment]
What you described is a [select](http://localhost:8080/#/documentation/select).

You can simulate a select with Dropdown using v-model as well.
