### ISSUE TITLE
Buefy and VeeValidate

### ISSUE THREAD

**Issue by guamacherox** [rafaelpimpa/buefy#370]
### Conflict with error messages triggering

**Buefy** version: [0.5.4]
**Vuejs** version: [2.4.2]
**OS/Browser**: Windows/Google Chrome

### Description

It appears that Buefy puts as valid an email address like "juan@something", this is not valid by default on validation libraries like vee-validate (is neccesary the '.com' or any TLD, to be a valid input), even if i put the validation like this: `<b-input type="email"  v-validate="'required|email'">`, the buefy email validation style prevails. Is there a way or example to put to work these two together?

### Steps to reproduce
1. Use a `<bfield>` with the vee-validate binding on :type.
2. in the nested `<b-input>` declare the vee-validate rule` v-validate="required|email"`

### Expected behavior

The error message for email input must exist as long you write the email on format someone@something.com

### Actual behavior

Buefy validation email rule prevails over vee-validate.

**Comment by guamacherox** [comment]
Well, the solution is simple:

**Just delete de "required" attribute on the b-input** and leave only the v-validate. This worked for me.

if anybody needs to combine Buefy with vee-validate, you can consider this simple implementation:

```HTML
<b-field label="Email" :type="errors.has('email') ? 'is-danger': ''" :message="errors.has('email') ? errors.first('email') : ''">
    <b-input
        type="email"
        id="email"
        v-model="email"
        placeholder="Your Email"
        v-validate="'required|email'">
    </b-input>
</b-field>

```
Besides that, **i don't know if it is necessary to consider the buefy email validation for the missing '.' on an email type**. Anything to say about that?

P.S: Thanks a Lot for Buefy, it's really good!

**Comment by jtommy** [comment]
@guamacherox Thanks!
Anyway Buefy doesn't have any own validation. Required is only a native html5 attribute and type email it's the same (depending on browser support, email input can be automatically validated).
