### ISSUE TITLE
[Help] Call $toast.open() on main.js file

### ISSUE THREAD

**Issue by evandroabukamel** [rafaelpimpa/buefy#373]
Hi, everyone,

I am trying to call a `$toast` message from my main.js, the bootstrap script for Vue, a bit of code after `Vue.use(Buefy)`, inside axios interceptor.

I tried `this.$toast.open`, `Vue.$toast.open` and `Buefy.$toast.open` but none worked, the `$toast` is undefined on them.

Someone have an idea how to do this?

Thanks

**Comment by thc1967** [comment]
I do something like this.

```js
            axios.delete(URI)
                .then(() => {
                    this.$snackbar.open(this.texts.delete_success);
                })
```

**Comment by rafaelpimpa** [comment]
I don't think you'll be able to use it on main.js because it's not a vue instance yet, but you can do this:

```javascript
import { Toast } from 'buefy'

Toast.open([...])
```

**Comment by evandroabukamel** [comment]
@rafaelpimpa, it worked! Thank you.
