### ISSUE TITLE
b-collapse

### ISSUE THREAD

**Issue by OGhawsi** [rafaelpimpa/buefy#374]
### Overview of the problem

**Buefy** version: [0.5.2]
**Vuejs** version: [2.1.10]
**OS/Browser**:
Ubuntu 
### Description

NEED HELP USING b-collapse with LARAVEL

This is not a bug or sth I just need some help using b-collapse in Laravel. 
when I copy the example it does not work.

**Comment by jtommy** [comment]
@OGhawsi Did you have any errors in console? What example?

**Comment by OGhawsi** [comment]
No error, but toggling is not working: 
for this example 
`<b-collapse class="card" :open.sync="isOpen">
        <div slot="trigger" class="card-header">
            <p class="card-header-title">
                Component
            </p>
            <a class="card-header-icon">
                <b-icon :icon="isOpen ?
                    'arrow_drop_down' : 'arrow_drop_up'">
                </b-icon>
            </a>
        </div>
        <div class="card-content">
            <div class="content">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec iaculis mauris.
                <a>#buefy</a>.
            </div>
        </div>
        <footer class="card-footer">
            <a class="card-footer-item">Save</a>
            <a class="card-footer-item">Edit</a>
            <a class="card-footer-item">Delete</a>
        </footer>
    </b-collapse>`

I need to knwo where to put the JS section and how 
`<script>
    export default {
        data() {
            return {
                isOpen: true
            }
        }
    }
</script>`

Your help is well appreciated. Thanks

**Comment by jtommy** [comment]
@OGhawsi It's a Lavarel question :smile:
Could you provide us your page with bCollapse ? I don't know you are using Vue + Lavarel.

**Comment by OGhawsi** [comment]
![image](https://user-images.githubusercontent.com/30488194/31779768-2a75d718-b509-11e7-9e4b-293cc3cae593.png)
And this is App.js
![image](https://user-images.githubusercontent.com/30488194/31779836-4ded9d52-b509-11e7-9c93-627c944645c1.png)
Actually, I am new to Vue.js so there can be the problem.

**Comment by jtommy** [comment]
@OGhawsi It's no easy help you because I have no enough info.
Anyway you might try to put `isOpen` into `data` in App.js.

**Comment by OGhawsi** [comment]
Solved the problem with a fresh laravel installation, thanks @jtommy

**Comment by STnetwork** [comment]
@OGhawsi 

Hi, can you past the solution, I have some troubles too, where and how did you put the JS ? : 

`<script> export default { data() { return { isOpen: true } } } </script>`

**Comment by OGhawsi** [comment]
@STnetwork I would suggest learning some VueJs first, I had this problem in that time I did not know much about Vue.You can try in Vue instance data object as suggested by @jtommy.
