### ISSUE TITLE
Update Bulma to 0.6.0

### ISSUE THREAD

**Issue by neovive** [rafaelpimpa/buefy#375]
**Buefy** version: [0.5.3]
**Vuejs** version: [2.5.2]

### Description
Not a major issues, but it would be great to bump the Bulma version to 0.6.0. Only three small [breaking changes](https://github.com/jgthms/bulma/releases/tag/0.6.0), so it should be a smooth upgrade for Buefy. Thanks for such a great and easy to use library.

**Comment by rafaelpimpa** [comment]
Updated in dev branch
