### ISSUE TITLE
<b-select> does not revert to placeholder if picked option removed dynamically

### ISSUE THREAD

**Issue by IlyaSemenov** [rafaelpimpa/buefy#376]
### Overview of the problem

**Buefy** version: 0.5.4
**Vuejs** version: 2.5.2
**OS/Browser**: macOS / Chrome 61

### Description

I want to implement a select box with a placeholder, where each option element can only be picked once by a user (so the select box will revert to the placeholder state every time a new option is picked).

With the current buefy version, this breaks `b-select` which starts to show blank selection instead of placeholder. I only managed to achieve what I needed with an ugly `setTimeout()` hack (see Experiment 4).

Also, it works inconsistently in the way how the last element and all others behave, and how `@input` events are called (see below).

### Steps to reproduce

There are several similar experiments which can be conducted, each of them behaving slightly differently (and showing different problems).

#### Experiment 1

```vue
<template>
<div>
  <b-select placeholder="select something" @input="pick">
    <option
      v-for="item in items"
      v-if="pickedItemIds.indexOf(item.id) === -1"
      :key="item.id"
      :value="item.id"
      v-text="item.label"/>
  </b-select>
  <hr>
  Picked items: {{ pickedItemIds }}
</div>
</template>

<script>
export default {
  data () {
    return {
      items: [
        { id: 1, label: 'one' },
        { id: 2, label: 'two' },
        { id: 3, label: 'three' },
        { id: 4, label: 'four' },
      ],
      pickedItemIds: [],
    }
  },
  methods: {
    pick (itemId) {
      this.pickedItemIds.push(itemId)
    },
  },
}
</script>
```

jsfiddle: https://jsfiddle.net/semenov/0c5pb32y/ 

* picking any item renders blank select box without placeholder
* picking any item BUT the last makes `@input` to be called twice
* picking LAST item makes `@input` to be called once

#### Experiment 2

Add `<b-select ... v-model="itemId">`, and have `data()` return `itemId: null`. Don't use `itemId` anywhere else.

jsfiddle: https://jsfiddle.net/semenov/wfn6nm46/

* picking any item BUT the last reverts to placeholder
* picking LAST item renders blank select box without placeholder
* picking any item BUT the last makes `@input` to be called **thrice (!)**
* picking LAST item makes `@input` to be called once

#### Experiment 3

Use Experiment 2 as the base, add `this.itemId = null` to the input handler.

jsfiddle: https://jsfiddle.net/semenov/m7u0odre/

Result: everything behaves exactly as in Experiment 1 (!) with the same mistakes

#### Experiment 4

Use Experiment 2 as the base, add `setTimeout(() => { this.itemId = null }, 0)` to the input handler.

jsfiddle: https://jsfiddle.net/semenov/ugwhquh5/

* picking any item reverts to placeholder **(good)**
* picking any item BUT the last makes `@input` to be called thrice
* picking LAST item makes `@input` to be called twice

### Expected behavior

1) In experiments 1-3 I would expect the select box to revert to the placeholder automatically, and never show blank selection.

2) In all experiments I would expect `@input` to be called consistently for all elements. Also, I would expect `@input` to be called maximum two times (e.g. first when an item is picked, second when selection is reset due to changed options).

### Actual behavior

1) In experiments 1-3 `b-select` renders blank selection in certain circumstances.

2) In all experiments `@input` is called inconsistently for the last element. Also, sometimes `@input` is called not once and not even twice but **thrice**.

**Comment by rafaelpimpa** [comment]
Thanks a lot for a lot of repros.

**Comment by jtommy** [comment]
Try that https://jsfiddle.net/y13qgkom/
As you can see i changed `v-if` to `v-show`, `setTimeout` to `$nextTick` and `@input` to `@change.native`. 
I think it respect all your requirements.

**Comment by IlyaSemenov** [comment]
Which specifically info will be helpful?

Sure thing, I confirm that by applying a bunch of non-obvious hacks, specifically those:

* `@change.native` instead of documented `@input`
* `parseInt(event.target.value)` instead of plain data object access
* `$nextTick`
* knowingly using `v-show` instead of `v-if`

one can work around the problem and achieve the desired behaviour. I don't see how it fixes the original problem altogether though. It's an (arguably ugly) workaround, not a fix. For that matter, the jsfiddle in my Experiment 4 is even better, as one only needs to filter `null` events and that's it, no weird event names and such.

I stated the **expected behaviour** in the corresponding section above. If you agree with it, then it's clearly not the fix. If you disagree with it (or if you believe it's an edge case not worth the efforts), simply close the ticket. It wasn't a *support* case, I can perfectly care for myself :)

**Comment by jtommy** [comment]
@IlyaSemenov We should investigate about it. Of course your example it's an edge case.
Anyway we are open to contributions to fix and/or add features.
