### ISSUE TITLE
MDI Community Edition Icons compatibility

### ISSUE THREAD

**Issue by sempixel** [rafaelpimpa/buefy#377]
**Bulma:** v0.6.0
**Buefy:** v0.5.4

There is an update needed for correct `mdi` icons support

![capture d ecran 2017-10-20 a 17 30 47](https://user-images.githubusercontent.com/1658628/31829047-70542ede-b5bc-11e7-917a-e3744e394b90.png)

https://github.com/rafaelpimpa/buefy/blob/fd4bed9fd0ae20df108e6410fa8108b666f41282/src/components/icon/Icon.vue#L3

I guess it's linked to #375 

Thanks!

**Comment by rafaelpimpa** [comment]
Actually nothing changed to icons on bulma 0.6, I've used it already on a project and it's normal.

Are you using the community MDI or the original one?

**Comment by sempixel** [comment]
I use `@import '~mdi/css/materialdesignicons'` so it's the [Community one](https://github.com/Templarian/MaterialDesign).

Maybe you should switch to this one as Bulma documentation [points to it](https://bulma.io/documentation/elements/icon/#material-design-icons).

**Comment by rafaelpimpa** [comment]
Sure I'll add it.
