### ISSUE TITLE
Animation prop for Dialogs

### ISSUE THREAD

**Issue by darkylmnx** [rafaelpimpa/buefy#38]
i would like to know if you would consider adding animate.css as a depedency for you animations.

Use case : i want to change the animation of a alerts / confirms you have but i can't really do that as you transitions are already made by you in each component based on your own custom classes.

I already use animate.css (and many vuejs or bulma css users use it, even bulma talks about it on the docs), if you add animate.css as a depedency it would be easy to change animations with your ui-kit by just changing the animatio class i would pass to a component and i woun't have to import animate.css which has common animation names with you own animation names (there's at least 2 conflicts in the keyframe names here) https://daneden.github.io/animate.css/

**Comment by rafaelpimpa** [comment]
Buefy is supposed to be **lightweight** and **simple**, I'm not adding any dependency that is not necessary.

What I can do however, is adding a prop for the animation name and you use the one you want (in that case yuo have to pass the ``enter`` and ``leave`` animation name.

**Comment by darkylmnx** [comment]
@rafaelpimpa that's seems a good idea :)

**Comment by rafaelpimpa** [comment]
Just one name is needed, you can see the default one here: https://github.com/rafaelpimpa/buefy/blob/dev/src/scss/utils/_animations.scss#L106

**Comment by darkylmnx** [comment]
nice i'll try that !

**Comment by daenuprobst** [comment]
Would be nice to add this to the documentation (a list of the available transition names).

**Comment by rafaelpimpa** [comment]
@daenuprobst actually there aren't any available aside from ``zoom-in`` and ``zoom-out``, you have to make your own 😄

**Comment by daenuprobst** [comment]
Now that I look at the code and the vue doc... ;-). So it would be nice to document that there are no others - maybe add [this link](https://vuejs.org/v2/guide/transitions.html)?. Don't know if it would be useful to many others though...

**Comment by lsbyerley** [comment]
@rafaelpimpa can you point to any resources that covers creating your own animation for a buefy modal? I've tried using `:animation="fadeInUp"` inside the `<b-modal />` tag but get a vue warning saying it doesn't exist, even though i've added the transition css to the component style

**Comment by lsbyerley** [comment]
@rafaelpimpa thanks for clarifying!

**Comment by rafaelpimpa** [comment]
@lsbyerley my bad for the delay, is you are right, you have to create those extra classes

**Comment by Sparkenstein** [comment]
Hey I tried adding the animation as you said to b-modal. It's not working. Do we have a tutorial for the beginners? Or like include `animate.css` on your own and use animations from it directly something like that
