### ISSUE TITLE
Not Working (Might be a noob or im an idiot) 

### ISSUE THREAD

**Issue by Baker** [rafaelpimpa/buefy#381]
### Overview of the problem

**Buefy** version: [0.5.4]
**Vuejs** version: [2.4.2] `Tried 2.5.2 same issue `
**OS/Browser**: MacOS Sierra 

### Description

None of my componets are working.. 

Login.blade.php 
```
@extends('layouts.app')

@section('content')
<div class="columns login__form">
    <div class="column is-one-third is-offset-one-third m-t-100">
        <div class="card">
            <div class="card-content">
                <h1>Login</h1>
                <form action="{{route('login')}}" method="POST" role="form">
                    {{csrf_field() }}
                    
                    <div class="field">
                    <labal for="email" class="label">Email Address</labal>
                    <p class="control">
                        <input class="input" type="text" name="email" id="email" placeholder="Name@Example.com">
                    </p>
                    </div>
                    <div class="field">
                        <labal for="password" class="label">Password</labal>
                        <p class="control">
                            <input class="input" type="text" name="password" id="password">
                        </p>
                    </div>
                    <b-checkbox name="remember" class="m-t-20">Remember Me</b-checkbox>

                    <button class="button is-primary is-outlined is-fullwidth m-t-30">Login</button>
                </form>
            </div>
            <h5 class="has-text-centered"><a href="" class="is-muted">Reset Password</a></h5>
        </div>
    </div>
</div>
@endsection
```
![image](https://user-images.githubusercontent.com/9560564/31922899-b52210b8-b845-11e7-9fb3-a73236e9d8ac.png)

Here is my App.scss
```

// Fonts
// @import url("https://fonts.googleapis.com/css?family=Raleway:300,400,600");

// Variables
@import "variables";

//Bulma 
@import "node_modules/bulma/bulma"; 

// Font Awesome 
@import "node_modules/font-awesome/scss/font-awesome"; 

// Bulma Vua Modules aka Buefy
@import "node_modules/buefy/src/scss/buefy"; 

// Partials 
@import "partials/all";
```

### Steps to reproduce

After using any of the components nothing is working. 

### Expected behavior

Expected to render a checkbox

### Actual behavior

Doesn't render anything

**Comment by dmitry-ivanov** [comment]
Hey, @Baker !

Have you used Buefy in your Vue instance? Here is an example for my vendor.js:
```
import Vue from 'vue';
import Buefy from 'buefy';

Vue.use(Buefy, { defaultIconPack: 'fa' });
window.Vue = Vue;
```

Also, after that, you have to create your Vue instance, something like that in app.js:
```
var App = new Vue({
    el: '#app'
});
```

Sure, you have to add some element with that id on your layout, something like that:
```
<body>
    <div id="app">
        // Here you can use Buefy components, hurrah! :)
    </div>
</body>
```

Hope it helps!

**Comment by Baker** [comment]
@dmitry-ivanov 
Thank you for that so I ultimately added all this to my add.js 

```
require('./bootstrap');
import Vue from 'vue';
import Buefy from 'buefy';

Vue.use(Buefy, { defaultIconPack: 'fa' });
window.Vue = Vue;

var App = new Vue({
    el: '#app'
});
```


That resolved it, thanks.

**Comment by dmitry-ivanov** [comment]
@Baker Hey, np)

Note, that you can simplify it even to that, if you're using one js file:
```
import Vue from 'vue';
import Buefy from 'buefy';

Vue.use(Buefy);

var App = new Vue({
    el: '#app'
});
```

That's just to make Vue variable available in any of your js files:
>window.Vue = Vue;

And that is to make FontAwesome as default icons pack:
>{ defaultIconPack: 'fa' }

Note, that you also need to include Buefy css. You can do it in your js file like that:
>import 'buefy/lib/buefy.css'

Or in your SASS file like that:
```
@import "~bulma";
@import "~buefy/src/scss/buefy";
```

Check docs for more help:
https://buefy.github.io/#/documentation/start

**Comment by LuisGCrespo** [comment]
I have the same issue and done everything you guys said, any suggestion?
