### ISSUE TITLE
Icons size and positioning

### ISSUE THREAD

**Issue by dmitry-ivanov** [rafaelpimpa/buefy#382]
### Overview of the problem

**Buefy** version: [0.5.4]
**Vuejs** version: [2.5.2]
**OS/Browser**: Safari 11.0 (12604.1.38.1.7) (Same in Google Chrome)

### Description

Hey, Rafael! :)

When I've started to use Buefy, and switched to `<b-icon>` I've noticed all my icons a little bit changed. They're not inherit font size anymore, and their positioning looks worse.

### Steps to reproduce

The simplest example:
```
<div>
    <b-icon icon="dashboard"></b-icon>
    <i class="fa fa-dashboard"></i>
    Dashboard
</div>
```

### Expected behavior

Expected that both icons would inherit font size and fit perfectly.

### Actual behavior

`<b-icon>` moved to bottom and have bigger font size.

PS: I've checked `_icon.scss` - it looks like Buefy has fixed font sizes in pixels, but Bulma uses relative ones in rem.

![icons](https://user-images.githubusercontent.com/1286821/31943015-f10eb876-b8cf-11e7-9ac3-71c71c5b50a3.png)

**Comment by dmitry-ivanov** [comment]
PS: Removing of:

**Comment by gtalarico** [comment]
Same issue here. After installing buefy:
![image](https://user-images.githubusercontent.com/9513968/32109399-a0254134-bb02-11e7-9d7b-ce36b5f32d90.png)

Before:
![image](https://user-images.githubusercontent.com/9513968/32109417-ab42fcc8-bb02-11e7-9143-18c31ee6eeb3.png)

**Comment by rafaelpimpa** [comment]
Bulma changed some time ago their icons sizes and I kept like before to prevent breaking changes, I'll see what can be done here.

**Comment by rafaelpimpa** [comment]
Fixed in https://github.com/rafaelpimpa/buefy/commit/42d18fa4105bdd25bc3cc049a297f8f59dae3773
