### ISSUE TITLE
Forms not working with Laravel

### ISSUE THREAD

**Issue by mindbits** [rafaelpimpa/buefy#383]
### Overview of the problem

**Buefy** version: 0.5.4
**Laravel** version: 5.5

### Description

Most of Buefy works fine with Laravel but most of the form components don't work (input, checkbox etc.). 

### Steps to reproduce

app.js

```
require('./bootstrap');

import Vue from 'vue'; 

window.Vue = Vue

const app = new Vue({
    el: '#app' 
});
```

bootstrap.js

```
import Vue from 'vue';
import Buefy from 'buefy';

window._ = require('lodash')

window.Vue = Vue
Vue.use(Buefy)

```

webpack.mix.js
```
const { mix } = require('laravel-mix') 
mix.js('resources/assets/js/app.js', 'public/js')
    .sass(
        'resources/assets/sass/app.scss', 'public/css'
    ) 
    .extract(['vue', 'lodash', 'axios', 'vue-router', 'moment', 'vuex', 'vuex-router-sync', 'vee-validate'])
   
    .sourceMaps()
 
if (mix.config.inProduction) {
    mix.version()
} 
mix.disableNotifications()
```

### Expected behavior

The form input fields and checkboxes to work

### Actual behavior

The form input fields and checkboxes don't work, but dropdown and some other components do work. 

Also, components mounted with input fields throw no error. 

Did someone successfully install Buefy with Laravel 5.5 (Mix)?

**Comment by maxleaver** [comment]
What does your component look like? Laravel 5.5 + Mix + Buefy has been working fine for me.

**Comment by mindbits** [comment]
Thank you, Max, for the fast reply. 

The component is the first example copied and pasted from https://buefy.github.io/#/documentation/input

I actually reinstalled everything from scratch, now basically the only thing not working properly is just the password-reveal. It's not clickable.

```
<template>
    <section>
        <b-field label="Name">
            <b-input value="John Silver"></b-input>
        </b-field>

        <b-field label="Email"
            type="is-danger"
            message="This email is invalid">
            <b-input type="email"
                value="john@"
                maxlength="30"
                :has-counter="false">
            </b-input>
        </b-field>

        <b-field label="Username"
            type="is-success"
            message="This username is available">
            <b-input value="johnsilver" maxlength="30"></b-input>
        </b-field>

        <b-field label="Password">
            <b-input type="password"
                value="iwantmytreasure"
                password-reveal>
            </b-input>
        </b-field>

        <b-field label="Message">
            <b-input maxlength="200" type="textarea"></b-input>
        </b-field>
    </section>
</template>
```

**Comment by maxleaver** [comment]
Well, your component and setup looks good. Mine is almost identical. I really doubt this has anything to do with Laravel. I noticed you're not pulling in the Buefy CSS anywhere:

`import 'buefy/lib/buefy.css';`

I doubt that would make a control unclickable, but you may try adding it to your bootstrap.js to narrow down the culprit. Otherwise, I think we'll need more details on the behavior (or lack thereof).

**Comment by mindbits** [comment]
You are a hero, it was the buefy.css 

Thank you so much!

**Comment by aldiazhar27** [comment]
I've got the same problem. And i try  adding import 'buefy/lib/buefy.css' and still doesn't work.
