### ISSUE TITLE
Feature request: Add 'active'property to dropdown item

### ISSUE THREAD

**Issue by nextgensparx** [rafaelpimpa/buefy#384]
Can an 'active' property be added to the dropdown item that overwrites other values? I have a situation where I want to do some checks before making the clicked dropdown item the selected one. Currently, as soon as you click on a dropdown item that has a `value`, it becomes active.

**Comment by jtommy** [comment]
@nextgensparx Could you provide an example ? I think `active` prop is like `disabled` prop.

**Comment by nextgensparx** [comment]
Actually, I think using a dropdown and dropdown items might be a mistake.

All I wanted was to be able to click on a dropdown item without setting it as active. For example, a social app where you want to change your online status. The options could be `online`, `busy` or `offline`. When you click on `busy`, the app would first contact the server to attempt to do this. It would only actually set the `busy` item as the selected one after successfully updating the server database. If there was an error it would just stay on the current status.

This might still be useful for other cases though. Has an `active` prop been recently added to dropdown items? Because I am not sure what you mean by 

>  I think active prop is like disabled prop.

According to https://buefy.github.io/#/documentation/dropdown, dropdown items only have a `disabled` prop. They do not have an `active` prop.

**Comment by jtommy** [comment]
@nextgensparx There isn't any `active` prop to dropdown items. I mean that active prop could be like (not) `disabled` prop (!disabled = enabled).
Anyway for your example you have to listen `v-model` dropdown changes and if the request fails update it to previous value (you could add `is-loading` class if you use button as trigger, for example: https://jsfiddle.net/9qpnujd6/).

**Comment by nextgensparx** [comment]
@jtommy By `active` I meant it would show the purple highlight and all that. That's not the same as not `disabled`.

Yeah, I guess that would work.
