### ISSUE TITLE
Feature Request: Support secondary confirm button on dialog

### ISSUE THREAD

**Issue by houseoftech** [rafaelpimpa/buefy#385]
### Overview of the problem

**Buefy** version: [0.5.4]
**Vuejs** version: [2.5.2]
**OS/Browser**: N/A

### Description

I have come across a need in my app to offer multiple delete options (e.g. "Delete Only This" vs. "Delete All"). I tried to make a prompt work but it doesn't support a select as an input. Besides, I think a confirm dialog is the most appropriate solution.

Do you think this would be a good addition? Not moving too far from the rule of simplicity?

I can submit a PR.

**Comment by jtommy** [comment]
@houseoftech I don't think there is the need to add that to Buefy core. Confirm dialog like native confirm has two buttons and then Buefy `dialog` it's a shortcut of `modal` component (you might create your custom component that use `modal` with the same behaviour of confirm dialog).
Anyway thanks a lot! 👍
