### ISSUE TITLE
How to set initial currentPage for paginated b-table ?

### ISSUE THREAD

**Issue by frantic1048** [rafaelpimpa/buefy#386]
### Overview of the problem

**Buefy** version: 0.5.4
**Vuejs** version: 2.5.2
**OS/Browser**: Various

### Description

I am trying to sync route param's pageNumber with b-table. e.g. Accessing `/rabbithouse/menu?page=20` shows the 20th page of menu data with `b-table`.

So far, I achieved showing the correct page of data with b-table with `backend-pagination` and set new route query & update data on `page-change` event. But the page number of `b-pagination` inside `b-table` is always `1` on first load. Even I directly open `/rabbithouse/menu?page=1204`, the table is correctly showing the 1204th page of data, while the page number showing is `1`.

### Expected behavior

I think we could expose the `currentPage` prop with a default value `1` to fix this.

**Comment by dmitry-ivanov** [comment]
Hey, guys!

And what if I need to change page after some action on js?
Is it possible to do that dynamically?

I've got the similar situation: I can set my `page` property to 1, force data reloading - see proper results, but paginations still shows an old page (NOT 1).

Tried, didn't help 
>:current-page.sync="page"

Thanks!
