### ISSUE TITLE
Can't properly extend a Field with an Input as a child

### ISSUE THREAD

**Issue by pdbq21** [rafaelpimpa/buefy#390]
### Overview of the problem

Buefy version: 0.5.4
Vuejs version: 2.4.2
OS/Browser: Google Chrome 61

### Description

I got some troubles with an `Input` component when I try to extend functionality of a `Field` component by a mixin. If I use the `Field` component with the `Input` component as a child all is okay. However if I extend a `Field` component by a mixin and then I try to add an `Input` component as a child I got problems with Input's message displaying - the message has excessive margin top as a result an empty row are formed between the message and `input` HTML tag above.

### Steps to reproduce

1. Create new component then add a `b-field` tag as a root of a `template` tag with a default `slot` tag inside of it.
2. Use just created component with an `Input` component as a child whereever.
3. Add some message to the child `Input` component.
4. See broken displaying of the message :(

### Expected behavior

1. Create new component then add a `b-field` tag as a root of a `template` tag with a default `slot` tag inside of it.
2. Use just created component with an `Input` component as a child whereever.
3. Add some message to the child `Input` component.
4. See  the properly displayed message (without a top margin) :)

### Actual behavior
I think that the `is-clearfix` CSS class is unwanted on the `<div class="field is-clearfix"></div>` tag.

**Comment by jtommy** [comment]
@pdbq21 I don't understand very well the issue. Anyway I tried to create an example https://jsfiddle.net/p0usxmdw/. Is it right ?

**Comment by pdbq21** [comment]
@jtommy, just tested new version of buefy 6.0, looks like the issue was fixed. All works fine. Close the issue. Thanks!
