### ISSUE TITLE
Icon not showing in hero component

### ISSUE THREAD

**Issue by adrlen** [rafaelpimpa/buefy#392]
### Overview of the problem

**Buefy** version: [0.5.4]
**Vuejs** version: [2.5.2]
**OS/Browser**: macOS / Chrome 61

### Description

Icon not showing in hero component

### Steps to reproduce

Add icon component in bulma hero title or subtitle

### Expected behavior

Icon should be displayed

### Actual behavior

Icon is not displayed

**Comment by jtommy** [comment]
@adrlen Are you using Material Design Icons or Font Awesome Icons ?
I think there is a issue with MDI in Bulma

**Comment by adrlen** [comment]
I'm using MDI indeed. I tested with bulma-only and it seems to work.

**Comment by jtommy** [comment]
Fix https://github.com/rafaelpimpa/buefy/issues/377

**Comment by adrlen** [comment]
@jtommy Thanks for you fix, do you know if this would fix the issue I have now too :

MDI icons with multiple words as label doesn't seem to work, or maybe I didn't find how to make it work.

Example : MDI _zoom in_

**Comment by jtommy** [comment]
You have to replace space with underscore. Anyway the fix is a breaking change, please see changelog (next release).

**Comment by adrlen** [comment]
Wonderful, I tried different method but not this one ! Maybe it would be helpful to add this info in the doc ?

Anyway, thanks for being so responsive.

**Comment by adambiggs** [comment]
@adrlen I just ran into the same issue where the `floor-plan` icon wasn't showing up... Turns out many of the icons listed on materialdesignicons.com haven't actually been released yet 😑
