### ISSUE TITLE
Unexpected token import on current vue-cli project

### ISSUE THREAD

**Issue by wanxe** [rafaelpimpa/buefy#4]
If start a new project from scratch using vue init webpack "myproject" all works fine.
But when try to use Buefy on my current project (also based on vue cli) The Chrome console throws the following error:
`Uncaught SyntaxError: Unexpected token import`

I've tried to exclude: /node_modules(?![\\/]buefy[\\/])/ on the webpack.base.conf.js but haven't been lucky. 

I have tried other libraries to verify that it is not my project and they effectively work.

**Comment by rafaelpimpa** [comment]
Since Buefy is unpackaged (I'll add packaged build in the future) you'll have to add babel-core & babel-loader: http://stackoverflow.com/a/38405684

**Comment by wanxe** [comment]
I just tried and still throwing the same error :(

**Comment by rafaelpimpa** [comment]
I'm gonna serve compiled .js in the next release, will probably solve all these errors

**Comment by rafaelpimpa** [comment]
I have a beta published with compiled builds, could you help me test it out?

```
npm install buefy@compiled
```
import css like this: ``import 'buefy/lib/buefy.css'``

**Comment by wanxe** [comment]
Yes mate, now compiles perfectly. Thanks so much!
