### ISSUE TITLE
Set option on-type on non-searchable Selects

### ISSUE THREAD

**Issue by wanxe** [rafaelpimpa/buefy#40]
I think a good feature would be that when we write in the search field and press the tab, it selects the best match. It is a little tedious to have to select with cursors or the mouse.

**Comment by rafaelpimpa** [comment]
Right now is possible to use the arrows keys.

**Comment by wanxe** [comment]
At least I expect behavior like this: http://demos.telerik.com/kendo-ui/dropdownlist/index
I find it faster and more intuitive, you are with me?

**Comment by rafaelpimpa** [comment]
Humm, I see that Buefy is missing the select-on-type functionality on non-searchable selects.

The ``searchable`` one looks fine for me.

**Comment by rafaelpimpa** [comment]
To be honest I'm thinking about removing this custom select and replace with the default one. The ``searchable`` is the only thing different and it's not working very well.
