### ISSUE TITLE
.lazy modifier of v-model does not work on b-input

### ISSUE THREAD

**Issue by philipithomas** [rafaelpimpa/buefy#401]
b-input does not appear to modify the `.lazy` form modifier https://vuejs.org/v2/guide/forms.html#lazy

### Steps to reproduce

```js
<template>
  <div>
    <b-input v-model.lazy="data" />
  </div>
</template>

<script>
export default {
  data() {
    return {
      data: null,
    };
  },
  watch: {
    data(val) {
      console.log(val);
    },
  },
}
```
### Expected behavior

Only change `data` on clicking out of input

### Actual behavior

Change fires on every keystroke

**Comment by jtommy** [comment]
https://github.com/vuejs/vue/issues/5743
At the moment it's a Vue limit. You have to use the equivalent way:
`<b-input :value="data" @change.native="data = $event.target.value" ></b-input>`

**Comment by alistairholt** [comment]
Does this appear in the docs? It would be a useful addition if it's not already there.
