### ISSUE TITLE
Icons which have multiple words in their names don't work

### ISSUE THREAD

**Issue by ydogus** [rafaelpimpa/buefy#402]
### Overview of the problem

**Buefy** version: `0.5.4`
**Vuejs** version: `2.5.3`

### Description
Icons which has multiple words in their names (like: **donut small**) don't work. They just don't show up.
I'm looking for the icon names from https://material.io/icons/.

### Steps to reproduce
1. Include material icons font from google fonts: `<link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">`
2. Create `<b-icon>` tags somewhere
   - `<b-icon icon="donut small"></b-icon>`
   - `<b-icon icon="done all"></b-icon>`
   - `<b-icon icon="donut-small"></b-icon>`
   - `<b-icon icon="done-all"></b-icon>`

**Comment by jtommy** [comment]
@ydogus You have to replace space with `_`. For example `<b-icon icon="done_all"></b-icon>`.

**Comment by alalfakawma** [comment]
Why is this closed? @jtommy only replied to the space issue, not the one where you use '-'. My issue was with "menu-down", which does not work. Is there any fix or something that I did wrong which you can tell me? Thanking you.

**Comment by jtommy** [comment]
@alalfakawma Buefy supprt (since last release) mdi community icon. 
Is the only one icon that doesn't work ?

**Comment by alalfakawma** [comment]
No, it looks like a rendering issue or something, the fonts are loaded but they are not rendered correctly in `<i>` tags. Eg. `<b-icon icon="menu-down"></b-icon>` should render the element as `<i class="mdi mdi-menu-down"></i>` but renders it as `<i class="mdi">menu-down</i>`.

**Comment by jtommy** [comment]
Could you replicate it to jsfiddle for example ? Buefy version ?

**Comment by Dragnucs** [comment]
@alalfakawma make sure you are using icons from [materialdesignicons.com](https://materialdesignicons.com) and not [material.io](https://material.io/icons).

**Comment by Vineet-Sharma29** [comment]
I am facing same issue again. I have following code snippet:-
```
<div class="buttons">
        <b-button class="is-primary" icon-left="add_circle_outline" @click="addTask" expanded>Add a standard</b-button>
    </div>
```
In `main.js`, I have added `mdi` as `defaultIcon` option, though its default:-
```
import Buefy from 'buefy'
import 'buefy/dist/buefy.css'

Vue.use(Buefy, {
    defaultIconPack: 'mdi',
})

```

But the icons are not rendering.
