### ISSUE TITLE
Switch height is not the same as other inputs

### ISSUE THREAD

**Issue by ydogus** [rafaelpimpa/buefy#407]
When there are two forms side by side and one of the forms has a switch control, their field's alignments go ugly. I think this screenshot show what I mean:
![image](https://user-images.githubusercontent.com/3532488/32759004-7e20ab1c-c8e7-11e7-9720-cfc8c7790e21.png)

I think it would be more beautiful if switch control take the same place as other standard inputs.

**Buefy** version: [0.5.4]

**Comment by rafaelpimpa** [comment]
I don't actually think that they should be the same height, just like checkbox/radio aren't. I suggest you to change your own if you'd like that!
