### ISSUE TITLE
Close Dialog component other than with button

### ISSUE THREAD

**Issue by adrlen** [rafaelpimpa/buefy#408]
FEATURE REQUEST

### Description

Add the option to close Dialog component when clicking overlay / on escape keyup. Confirm and Prompt dialog will emit cancel event.

### Expected behavior

1. Dialog open
2. Press escape key / Click overlay
3. Dialog close

### Actual behavior

Nothing happens

I'm not sure if that should be a default behavior and / or configurable via props.

I can try and make a PR if this feature seems interesting to you.

**Comment by jtommy** [comment]
https://github.com/rafaelpimpa/buefy/issues/399 (in the next release)
Only Alert (dialog) need click to close it.
