### ISSUE TITLE
npm latest version is behind github version, table component affected

### ISSUE THREAD

**Issue by bathyscaaf** [rafaelpimpa/buefy#41]
I have the latest version through npm, as directed, and attempted to use the Table component.

- The table component ignores the "component" attribute.
- The formatDate method in the example displays the following as a string in the table cell: "<span class="tag is-primary"> 4/23/2017 </span>"

I cloned the Github repo, played with that and everything works as expected.  I added my own custom component and it works great.

I found that there was code in the github distributed TableColumn.js that is not in the npm distributed version.

**Comment by rafaelpimpa** [comment]
Just tested with latest release and seems to work ok.

**Comment by bathyscaaf** [comment]
I just installed it via NPM in a different project -- I can see the component code is there.  For some reason it didn't update in my main project.  Blowing away node_modules and re-installing everything.  Sorry for the hassle.
