### ISSUE TITLE
Alert is triggered on file upload

### ISSUE THREAD

**Issue by maxleaver** [rafaelpimpa/buefy#410]
It looks like an alert was left in the code for the file upload component. See line 85 in Upload.vue

```
onFileChange(event) {
     alert('event')
```

Happy to remove it in a PR if it would be helpful.

**Comment by jtommy** [comment]
@maxleaver Yes, of course!

**Comment by dmitry-ivanov** [comment]
+1

**Comment by rafaelpimpa** [comment]
published 0.6.1
