### ISSUE TITLE
b-collapse

### ISSUE THREAD

**Issue by ibanzajoe** [rafaelpimpa/buefy#414]
### Overview of the problem

**Buefy** version: [X.X.X]
**Vuejs** version: [X.X.X]
**OS/Browser**:

### Description

Transition effect in b-collapse  does not work.  Collapse.vue takes in "animation" prop as (Type: String), but the component is bound with :name instead of just "name" in the "transition" tag.

### Steps to reproduce

The B-collapse examples on the documentation site does not have the transition effect. 

### Expected behavior

I rip the component and made a separate, took out the colon from the ":name" and the transition animation works.

**Comment by jtommy** [comment]
@ibanzajoe I'm sorry but i don't understand. Default animation is fade but you can set your effect by `animation` prop.

**Comment by ehthind** [comment]
@jtommy The animation for the collapse component is broken. It does not work on the docs either.
https://buefy.github.io/#/documentation/collapse

**Comment by jtommy** [comment]
@ibanzajoe internal `:name` is correct
@ehthind For me, the animation it's ok

**Comment by dmitry-ivanov** [comment]
@jtommy Hey, Tommy! Can you plz provide an example of b-collapse with animation?

**Comment by dmitry-ivanov** [comment]
Hey, it looks like animations are working actually, but not for all browsers. I've tried Safari, Chrome, Firefox. And only in Firefox Buefy docs are working now for me.

Checked here:
https://buefy.github.io/#/documentation/collapse

**Comment by ekntrtmz** [comment]
I cannot confirm it is still broken, but there is something unclear about animations in general. The default animation "fade" is only working when uncollapsing.

**Comment by didaquis** [comment]
Seems like still broken. 
```
<b-collapse :open="!collapsed">
        <div>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br>
          Nulla accumsan, metus ultrices eleifend gravida, nulla nunc varius lectus, nec rutrum justo nibh eu lectus. <br>
          Ut vulputate semper dui. Fusce erat odio, sollicitudin vel erat vel, interdum mattis neque.
        </div>
</b-collapse>
```
