### ISSUE TITLE
timepicker disable mobile

### ISSUE THREAD

**Issue by stvnmoon** [rafaelpimpa/buefy#415]
### Overview of the problem

**Buefy** version: 0.6.0
**Vuejs** version: 2.5.3
**OS**: Android

### Description

I have an application that makes extensive use of time input on tablets in an industrial environment, however the native mobile time picker is not usable for exact minutes because of the effort it takes on Android/Samsung. This selector is perfect for my application but only in the "desktop" version.

Please add a mobileDisabled prop or similar. I've created a fork for example: https://github.com/stvnmoon/buefy/commit/4dfea0b33374ac90dcf501adb7834789f9da7ca6

**Comment by imoon** [comment]
👍
