### ISSUE TITLE
Pagination colour being overridden in 0.6.1

### ISSUE THREAD

**Issue by Youdaman** [rafaelpimpa/buefy#416]
**Buefy** version: 0.6.1
**Vuejs** version: 2.5.3
**OS/Browser**: Windows/Chrome and Windows/Firefox

### Description

The colour of the pagination (using `backend-pagination` in a b-table) buttons have changed from the default purple to blue. Looks fine on the Buefy site however the following style was found injected in a style element within the head section of the page:

```
.pagination-link.is-current {
    background-color: #3273dc;
    border-color: #3273dc;
    color: #fff;
}
```

I looked at what's happening on the Buefy site and it's purple because of a `::selection` style. This is not present on my page -- maybe the purple on the main site is from a previous compilation/build?

### Steps to reproduce

1. Open a page with a table where the pagination was previously the default purple.

### Expected behavior

See purple.

### Actual behavior

Saw blue.

**Comment by rafaelpimpa** [comment]
Are you using the CSS from buefy or compiling your own? Bulma in 0.6 is using ``$link`` color for pagination.

**Comment by Youdaman** [comment]
I'm not compiling my own, just using the default CSS from Buefy as per the docs:
```
import 'buefy/lib/buefy.css'
```

I should have mentioned I was using  0.5.4 and the pagination buttons were the default primary purple, but then I updated Buefy to 0.6.1 and they changed to blue.

**Comment by vishalkdotcom** [comment]
After upgrading to 0.6.1 from 0.5.4, I am also facing this issue in Tabs component.

It's happening because of these [breaking changes](https://github.com/jgthms/bulma/blob/master/CHANGELOG.md#improvements-2) in bulma.

**Comment by rafaelpimpa** [comment]
Yes, I'll update Buefy to use $primary for pagination.
