### ISSUE TITLE
Event handling problem @select in Autocomplete component

### ISSUE THREAD

**Issue by Rajan** [rafaelpimpa/buefy#418]
buefy@0.5.4
vue@2.5.3

Unable to capture "Selected" event while doing @select="option => selected = option" as well.

I'm able to do only one of the two things below:

- capture event @select="asked" where asked is a method.
- do @select="option => selected = option" and be able to assign the value to "selected" under Vue data.

```
<section class="modal-card-body">
        <b-field label="Type Questions or Keywords">
          <b-autocomplete
          v-model="name"
          :data="filteredDataArray"
          placeholder="e.g. What is Respond101?"
          @select="option => selected = option">
          <template slot="empty">No results found</template> </b-autocomplete>
        </b-field>

        <b>{{ selected }}</b><br>
        <div style="min-height: 10rem;"></div>
</section>

methods: {
    asked: function () {
      console.log('asked ')
    }
  }
```

Is there a way to move "option => selected = option" inside the asked? Am I missing something?

**Comment by jtommy** [comment]
@Rajan Yes of course..
```
methods: {
    asked: function (option) {
      this.selected = option
    }
}
```

**Comment by entwicklerRepo** [comment]
"buefy": "0.7.0",
"vue": "2.5.17"
@jtommy issue is quiet old, but I've got exact same problem even with your example, option returns undefined selected result. Any clues?
Thanks!

**Comment by entwicklerRepo** [comment]
@jtommy item selected, maybe this could help 
![image](https://user-images.githubusercontent.com/37245111/47256071-0fbddd80-d47a-11e8-8765-a7f7a571b4cf.png)
![image](https://user-images.githubusercontent.com/37245111/47256077-23694400-d47a-11e8-99a6-37d0760d048c.png)

**Comment by jtommy** [comment]
Your code?

**Comment by entwicklerRepo** [comment]
https://codepen.io/fidelguevera/pen/BqVdYy

**Comment by jtommy** [comment]
You are wrong . Try `@select="assignTag($event)"` or `@select="assignTag"`

**Comment by entwicklerRepo** [comment]
@jtommy Thanks a lot!!! it worked! (both ways)
