### ISSUE TITLE
Password reveal icon size

### ISSUE THREAD

**Issue by ionmike** [rafaelpimpa/buefy#419]
### Overview of the problem

**Buefy** version: [0.6.1]
**Vuejs** version: [2.5.3]
**OS/Browser**: Windows 7 / Google Chrome 62.0.3202.94

### Description

Change of password input field size (with password-reveal) will change icon size inside that makes view feel strange. On the right is the problem, left is what i would like to see.

![image](https://user-images.githubusercontent.com/31574812/32888642-fb4665da-cad8-11e7-9c65-f5f8a53cf9a8.png)

### Steps to reproduce

1) Add password `b-field` > `b-input`
2) Set it size to `is-medium` (or even larger size)
3) You will see icon inside will be resized.

### Expected behavior

Sizing should be proper. 
Good solution - just change and make nice sizing.
Perfect solution - make slot with custom icon for reveal on/off.

**Comment by evandroabukamel** [comment]
After the last update, v0.6.1, all icons in medium size are a bit larger than before, for my taste.

**Comment by ionmike** [comment]
Oh, just to notice, i've used an font-awesome icons.

**Comment by jtommy** [comment]
@ionmike Why the view feel strange after that ? 
I think it's normal that if you change input size all related items follow input size.

**Comment by ionmike** [comment]
@jtommy because of proportions of icon and input, icon feels oversized in this input. Try it yourself.

**Comment by evandroabukamel** [comment]
Before:

![image](https://user-images.githubusercontent.com/6452880/33284770-489440ca-d397-11e7-9d40-b099eb6956f0.png)

After:

![image](https://user-images.githubusercontent.com/6452880/33284781-59bd96a8-d397-11e7-9ae4-aabde695f707.png)

Now you see the difference?
