### ISSUE TITLE
Table default-sort doesn't seem to honor the sort order

### ISSUE THREAD

**Issue by bytheway** [rafaelpimpa/buefy#42]
I have a table which is setting a default sort with a descending order:

```
    :default-sort="['updated_at', 'desc']"
```

The default column appears to be honored, but not the sort order. It is always getting output in ascending order until the column is manually clicked to reverse it.

**Comment by rafaelpimpa** [comment]
Is the arrow wrong or are the rows not being ordered correctly? I've just found a bug that the arrow wasn't updating.

**Comment by bytheway** [comment]
The arrow is still indicating an asc search and the rows are in asc order.

**Comment by rafaelpimpa** [comment]
I can't reproduce it, the rows are in desc order normally.

**Comment by bytheway** [comment]
👍  Great! That fixed it. Thank you for your work on this library, has been very useful. 🥇
