### ISSUE TITLE
Bulma Vertical Menu breaks

### ISSUE THREAD

**Issue by Rajan** [rafaelpimpa/buefy#420]
I'm using Bulma's vertical menu alongside Buefy's various components.
It's great to have Buefy components to reduce efforts in building things.

    "buefy": "^0.6.1",
    "bulma": "^0.6.1",
    "bulma-badge": "0.0.3",
    "bulma-pricingtable": "^0.1.0",

Here's the code for the side menu (vertical menu from bulma examples).

```
    <section class="container has-text-centered">
      <div class="columns">
        <div class="column is-three-quarters">
          <b-tabs size="is-medium" position="is-centered" v-model="activeTab">
            <b-tab-item label="Unaswered" icon="google-photos"></b-tab-item>
            <b-tab-item label="Most Asked" icon="library-music"></b-tab-item>
            <b-tab-item label="FAQ" icon="video"></b-tab-item>
          </b-tabs>
        </div>
        <div class="column">
          <aside class="menu">
            <p class="menu-label">
              General
            </p>
            <ul class="menu-list">
              <li><a>Dashboard</a></li>
              <li><a>Customers</a></li>
            </ul>
            <p class="menu-label">
              Administration
            </p>
          </aside>
        </div>
      </div>
    </section>
```
It does seem to break as specified in the screenshot attached here.
<img width="270" alt="screen shot 2017-11-17 at 11 43 29 am" src="https://user-images.githubusercontent.com/60307/32932005-061b787e-cb8d-11e7-8459-d8eb3d83515d.png">

**Comment by rafaelpimpa** [comment]
This shouldn't be an issue, I used it in buefy docs and on a side project just fine. Are you sure you don't have any other css conflicting?

**Comment by Rajan** [comment]
It's fixed. Thank you.
