### ISSUE TITLE
Empty icon for table examples

### ISSUE THREAD

**Issue by Youdaman** [rafaelpimpa/buefy#421]
Instead of "`sentiment_very_dissatisfied`" the icon for the empty section of the table examples should be "`emoticon-sad`" now that the Material icons are now coming from a different source:

```
    <!-- <link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons"> -->
    <link rel="stylesheet" href="//cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css">
```

**Comment by jtommy** [comment]
Thanks but it's already fixed https://github.com/rafaelpimpa/buefy/issues/412
