### ISSUE TITLE
How I parse and formate date dd/mm/yyyy to datepicker  show mm/dd/yyyyy

### ISSUE THREAD

**Issue by sldobri** [rafaelpimpa/buefy#427]
**Buefy** version: 0.6.1
**Vuejs** version: 0.6.1
**OS/Browser**: safari

### Description

How I parse and formate date dd/mm/yyyy to datepicker only show mm/dd/yyyyy

**Comment by frantic1048** [comment]
Pass a custom function as `date-formatter` attribute, you could control what date displays.

And set `date-parser`, you could customize how the date was parsed.

With [`date-fns`](https://date-fns.org/), the implementation could be something like(I only know JSX syntax, so you could see manual handling of input event. However it's not the point): 

```js
import {parse, format, subWeeks, startOfToday} from 'date-fns'

// ...

<b-datepicker
  label="input date"
  on-input={v => this.date= v}
  value={this.date}
  date-formatter={d => format(d, 'M/D/YYYY')}
  date-parser={dateString => /* your own logic to deal dd/mm/yyyy */}
  min-date={subWeeks(startOfToday(), 1)}
  max-date={startOfToday()}
>

```

The doc(see The API section): https://buefy.github.io/#/documentation/datepicker

BTW, @rafaelpimpa how do you think about allowing unlimited date range, i.e. make `min-date` and `max-date` optional ?

**Comment by jtommy** [comment]
@frantic1048 Range is optional

**Comment by frantic1048** [comment]
@jtommy I see. I may pass invalid argument before thus consider it is required.

**Comment by danielclariondoor** [comment]
The above syntax doesn't work with Vue 2.5

**Comment by amirhkhadem** [comment]
i have 
v-model="startdate"
currently ${this.startdate} is displayed "Wed Apr 24 2019 00:00:00 GMT-0700 (Pacific Daylight Time)" I want it to display "2019-04-24"
what do i do?

**Comment by kaankilic** [comment]
@amirhkhadem if you would like to display it on the input you have to use `:date-parser` prop, Either if you would like to set it to var you have to use `:date-formatter`. You can simply call a function with this  props.
