### ISSUE TITLE
Focused button on Dialog not displaying

### ISSUE THREAD

**Issue by kylebradshaw** [rafaelpimpa/buefy#43]
I never get 'confirmed' to fire, escape keypress or enter keypress has the same result which toggles onCancel for me.
```
    async toDelete (resource) {
      this.$dialog.confirm({
        message: 'Are you sure?',
        onCancel: () => {
          console.log('cancelled')
        },
        onConfirm: () => {
          console.log('confirmed')
```

**Comment by rafaelpimpa** [comment]
It's because the cancel button has the focus, if you tab -> enter it'll work.
I don't know why it doesn't have the focus style tho, gonna work on that.
