### ISSUE TITLE
Add <b-collapse>slot prop to let icons key off of collapsible data.open for icons

### ISSUE THREAD

**Issue by nick-beers** [rafaelpimpa/buefy#430]
### Overview of the problem

**Buefy** version: 0.6.0
**Vuejs** version: 2.5.2
**OS/Browser**: Windows 10 / Chrome 62

### Description

When using the Collapse component from Buefy, there is no way to have the Collapse component tell the icon which direction it should be facing without extra properties and functions getting involved. My use case has multiple Collapse components on the same screen which will be dynamically generated from a list. I was hoping a scope-slot property could be exposed for the collapsible trigger slot so that the data.open property could be used in simple HTML or dynamic generation scenarios.

**Comment by jtommy** [comment]
@nick-beers I don't if I understand we'll. Could you provide us an example?

**Comment by nick-beers** [comment]
I think i can simplify what I was trying to request. 

Specifically I was looking to add the slot property `isOpen: Boolean` to the `trigger` slot for `Collapse`.  

On your Collapse Card sample, the parent has `isOpen` dictating what direction the arrow should face.
```
<b-icon :icon="isOpen ?
    'menu-down' : 'menu-up'">
</b-icon>
...

    export default {
        data() {
            return {
                isOpen: true
            }
        }
    }

```

I am dynamically adding a list of collapses, which led me to realize controlling the Icon direction is tricky when the number of Collapse components is dynamic.

**Comment by jtommy** [comment]
@nick-beers Ok. We could add a prop `open` in trigger slot.

**Comment by jtommy** [comment]
Close https://github.com/rafaelpimpa/buefy/commit/079121c5da4a37b05b0ec3c58b9d1078bdcb3f59
