### ISSUE TITLE
<b-input @change="..."> does not respond to changes

### ISSUE THREAD

**Issue by akarelas-pt** [rafaelpimpa/buefy#431]
```html
<b-input type="text" v-model="name" @change="hasChanged"></b-input>
```
If I type in the textbox something, then `hasChanged` should be called. It is not called.

It is easy to make it be called, by applying to the underlying input box all the event handlers and props of `<b-input>`.

Should this be fixed?

**Comment by adrlen** [comment]
Use `@input` instead of `@change`

**Comment by akarelas-pt** [comment]
Thanks, that solved it.
