### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tytondon1234** [rafaelpimpa/buefy#433]
Hey everyone!

Got a question. I have the below code:

`<template>
                                <section>

                                    <b-table
                                            :data="isEmpty ? [] : orders"
                                            :hoverable="isHoverable"
                                            :mobile-cards="hasMobileCards"
                                            :selected.sync="selected"
                                            @click="onSelected(selected)"
                                            focusable>

                                        <template slot-scope="props">
                                            <b-table-column label="File #" width="40" numeric>
                                                {{ props.row.id }}
                                            </b-table-column>
                                            <b-table-column label="Client" width="40">
                                                {{ props.row.client_name }}
                                            </b-table-column>
                                        </template>

                                        <template slot="empty">
                                            <section class="section">
                                                <div class="content has-text-grey has-text-centered">
                                                    <p>
                                                        <b-icon
                                                                icon="sentiment_very_dissatisfied"
                                                                size="is-large">
                                                        </b-icon>
                                                    </p>
                                                    <p>Nothing here.</p>
                                                </div>
                                            </section>
                                        </template>
                                    </b-table>
                                </section>
                            </template>`

It is working just fine. The orders data is coming through just fine. However, I am trying to pass the selected row information into a function (as you can see with @click="onSelected(selected)). This approach, however, isn't working. Any ideas on how to get this to work? I am used to using a v-for to do this task. Also, sorry for the noob question.

**Comment by jtommy** [comment]
@tytondon1234 Click event -> Triggers when a row is clicked and that event send the selected row.
But you have current selected row by `selected.sync`, what would you like to do ?

**Comment by tytondon1234** [comment]
Hey @jtommy 

Yes I noticed that and could display it on my page via {{selected}}, which is awesome and it has everything I need. However, I need the information from selected to be sent to a function. I thought I would do that with @click="onSelected(selected)", but that isn't working. So I am doing something wrong. Any ideas and thank you for your time. :)

**Comment by jtommy** [comment]
@tytondon1234 There are many way to do it..
For example:
```
<b-table ...
@click="onSelected" >

methods: {
   onSelect(row) {
        // row = selected
     }
}

or 

watch: {
  selected(value) { 
   }
}
```
`onSelect` is called everytime instead `watch` is called only when `selected` is changed.

**Comment by tytondon1234** [comment]
Oh! :) Very cool. I will give those a go and will close this out. Thanks so much @jtommy !
