### ISSUE TITLE
Building a graphs/charts dashboard with Buefy?

### ISSUE THREAD

**Issue by Rajan** [rafaelpimpa/buefy#437]
We're building a web app with Buefy and need to integrate graphs/charts to create an admin type of dashboard with analytics and all.

Shall we use vue-admin and is it compatible with Buefy? Or Is there a better way to do it? 

Thank you in advance.

**Comment by jtommy** [comment]
@Rajan You should check if vue-admin charts components depend on Bulma version because I've just seen that project it's stopped about 0.3.

**Comment by donaldinos** [comment]
Try this vue-bulma-chartjs

**Comment by aantn** [comment]
Any specific advantage of using vue-bulma-chartjs as opposed to vue-chartjs?

**Comment by bitsnaps** [comment]
> Try this vue-bulma-chartjs

No update since years for [now](https://github.com/vue-bulma/chartjs).
