### ISSUE TITLE
Using Row status With Selection

### ISSUE THREAD

**Issue by tytondon1234** [rafaelpimpa/buefy#438]
Hey guys!

Got a question. I have a table where I am using both row status and selected. It is working great except that when a row is selected, it is not updating the row background color to the default color (of which it should when using the selected property), but is rather staying in the row status background color. With this said do I have to use one or the other or can I get them to work together? I would prefer for them to work together.

Thanks!

**Comment by jtommy** [comment]
@tytondon1234 You should compare row in row-class function with selected. In this case you don't apply your custom class.

**Comment by tytondon1234** [comment]
Hey Walter,

Okay. Is there any way that you could give me a snippet of an example of
this in practice? No worries if not.

Thanks!

**Comment by jtommy** [comment]
https://jsfiddle.net/3tufc7de/2/
As default the selected row with custom style has inverted color but if you check the switch component you can see what i told you (if selected is equal to current row -> no class, for example empty string)

**Comment by tytondon1234** [comment]
Wow! Thanks @jtommy! You are the best! :)
