### ISSUE TITLE
tabs with router

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [rafaelpimpa/buefy#443]
Is there anyway I can use Tabs with router? I couldn't find a descent option for this yet with Buefy

**Comment by rafaelpimpa** [comment]
No. Tabs works good for components only. No plans on adding support for routing ATM.

**Comment by diego-lipinski-de-castro** [comment]
Feels bad but fine.

**Comment by gotexis** [comment]
just use bulma.

**Comment by Baggs** [comment]
It can be done with pure bulma like this:
```
<div>

    <div class="tabs">
      <ul>
        <router-link tag="li" :to="{name: 'TabView1'}" exact><a>Tab 1</a></router-link>
        <router-link tag="li" :to="{name: 'TabView2'}" exact><a>Tab 2</a></router-link>
        <router-link tag="li" :to="{name: 'TabView3'}"><a>Tab 3</a></router-link>
        <router-link tag="li" :to="{name: 'TabView4'}"><a>Tab 4</a></router-link>
      </ul>
    </div>

    <router-view></router-view>

  </div>
```

**Comment by codegabru** [comment]
> It can be done with pure bulma like this:
> 
> ```
> <div>
> 
>     <div class="tabs">
>       <ul>
>         <router-link tag="li" :to="{name: 'TabView1'}" exact><a>Tab 1</a></router-link>
>         <router-link tag="li" :to="{name: 'TabView2'}" exact><a>Tab 2</a></router-link>
>         <router-link tag="li" :to="{name: 'TabView3'}"><a>Tab 3</a></router-link>
>         <router-link tag="li" :to="{name: 'TabView4'}"><a>Tab 4</a></router-link>
>       </ul>
>     </div>
> 
>     <router-view></router-view>
> 
>   </div>
> ```

And a little `active-class="is-active"` prop to the router-link to make it perfect. 😃
