### ISSUE TITLE
[Request] Parse promise to :data <BTable>

### ISSUE THREAD

**Issue by redbaty** [rafaelpimpa/buefy#444]
### Overview of the problem

**Buefy** version: [0.6.1]
**Vuejs** version: [2.5.8]
**OS/Browser**:

### Description

It would be nice if I could pass a promise to the data prop

**Comment by rafaelpimpa** [comment]
Please elaborate.

**Comment by redbaty** [comment]
Sorry for the typo, I was in a hurry. I mean it would be nice if the :data prop would accept a promise and automatically subscribe to it.

**Comment by rafaelpimpa** [comment]
Since this is something too specific you should [extend](https://vuejs.org/v2/api/#extends) the component to your needs.
