### ISSUE TITLE
Incorrect displaying of label on field with addons

### ISSUE THREAD

**Issue by adrlen** [rafaelpimpa/buefy#446]
### Overview of the problem

**Buefy** version: [0.6.1]
**Vuejs** version: [2.5.9]
**OS/Browser**: MacOS / Chrome

### Description

Label not displaying correctly on fields with addons

### Steps to reproduce

https://jsfiddle.net/ua41vnox/

### Expected behavior

As you can see in the example above, when a field has an addon the label is displaying on the same line as the field and not before.

**Comment by evandroabukamel** [comment]
Try this:

`<b-field :label-for="name" :label="Your input" :addons="true">
	<b-field expanded>
		<b-input placeholder="Your input">
		</b-input>
		<p class="control">
			<span class="button is-static">@gmail.com</span>
  		 </p>
	</b-field>
</b-field>`

**Comment by adrlen** [comment]
Thanks, it works.
