### ISSUE TITLE
Feature request for b-table * detailed only 1 row

### ISSUE THREAD

**Issue by serdem** [rafaelpimpa/buefy#447]
### Overview of the problem

**Buefy** version: [X.X.X]
**Vuejs** version: [X.X.X]
**OS/Browser**:

### Description

Hi, 
First of all I would like to thank you for the greate library.
I use b-table for my data set. Every row in set contains many fields and I show only a small set of them and show whole data when user click the detail icon. Also there are some buttons for the clicked row to edit, remove etc. 
When user clicked I want to close already opened rows except the last one.

Is it possible to add a new property to b-table like detailed-one-only or accordion?

**Comment by jtommy** [comment]
@wanxe What do you think about? I don't know if it's an important feature to include in the component. Could you provide an example to do it in a own custom code ?

**Comment by wanxe** [comment]
@jtommy Yes, would be possible but @serdem, please, can you provide us an example or mock of what you need? Thanks :)

**Comment by serdem** [comment]
Hi,
I just want to use b-table as an accordion like in here
https://jqueryui.com/accordion/.
Actually I already use it like an accordion using the b-table's events. I
am not allowed to share the code but you can see the attached gif file as
example.

      <b-table :data="form.items" ref="itemsTable2" detailed
:mobile-cards="true" :narrowed="true" :striped="true" :bordered="false"
@details-open="row_opened" @click="row_clicked" :row-class="(row, index) =>
'detail-header no_caret'">
        <template slot-scope="props" slot="header">
   ...
    row_opened(row) {
      this.setRow_state(row, false);
    },
    row_clicked(row) {
      this.setRow_state(row, true);
    },
    setRow_state(row, opt) {
      this.$refs.itemsTable2.visibleDetailRows.forEach(xrow => {
        if (row != xrow) this.$refs.itemsTable2.toggleDetails(xrow);
      });
      if (opt) this.$refs.itemsTable2.toggleDetails(row);
    },
...
Thank you.


*Serdar Erdem*


2017-11-30 13:37 GMT+03:00 Jorge Nieto <notifications@github.com>:

**Comment by wanxe** [comment]
Aham, the effect of the accordion is too much tricky on the tables. But if you want to close all the detailed and keep the clicked one, you can use the `opened-detailed` prop that you can see on the [documentation](https://buefy.github.io/#/documentation/table). 
With that way you can refactor your setRow_state.

**Comment by serdem** [comment]
Ok, thanks.

*Serdar Erdem*

2017-12-01 15:36 GMT+03:00 Jorge Nieto <notifications@github.com>:
