### ISSUE TITLE
Support "is-horizontal" PR + contributing questions

### ISSUE THREAD

**Issue by electrolinux** [rafaelpimpa/buefy#448]
### Thanks you for this project

It's very pleasant to use, and well documented. 
This issue is about my PR #439 and me not opening an issue beforehand asking if it would be a good idea to work on this feature :)
So here it is, with some more general questions

### Overview of the problem

**Buefy** version: [0.6.1]
**Vuejs** version: [2.5.2]
**OS/Browser**: Any

### Description

The Field component is currently lacking support for "is-horizontal" class and related "field-label" and "field-body" classes.

### Contributing questions

* Is there any Roadmap for this project?
* is there a plan for supporting more complete/extendable validation libraries for form elements?
* if not, what would be the best way to propose extensibility in that area?
  * adding a defaultValidationMethod: 'html5', and an option for some sort of custom validation?
  * defining a generic Form interface, or Errors Interface?

**Comment by rafaelpimpa** [comment]
Hi, thanks for contributing!

I still have to review your PR, time's lacking lately.

About your questions:

- Not yet, but I'm going to provide one soon.
- No, there are good options available, I don't think it's necessary.
- Your idea is good, we could add a page on ``Extensions`` section to show how to validate using other library, would love a PR for that.

**Comment by jtommy** [comment]
Merged https://github.com/rafaelpimpa/buefy/commit/c23b44a1d8f157b46c99d192fe704bf83caac5b9
