### ISSUE TITLE
Can I use b-collapse to collapse nav items ?

### ISSUE THREAD

**Issue by asadhshujau** [rafaelpimpa/buefy#450]
just wondering its it possible to collapse nav items with b-collapse... 
if so how ?

it would be great help cos i wanna optimize for mobile viewing.

using latest version of buefy with vue 2.5

**Comment by jtommy** [comment]
@asadhshujau Why would you like collapse nav items with b-collapse ? As you can see (https://bulma.io/documentation/components/navbar/) Bulma navbar have own automatic behaviour.

**Comment by asadhshujau** [comment]
@jtommy umm i meant nested navbar links ... 
example : 

1. components
1.1 navbar
1.2 modal
1.3 etc

when we change screen size to small ...
all nested links are displayed as well. i want to press the main heading which then reveals sub nav items. toggleable main nav items

**Comment by jtommy** [comment]
Could you provide an example ? Anyway our component it's a simple way to collapse a content.
