### ISSUE TITLE
b-table: remember sort

### ISSUE THREAD

**Issue by jpbecotte** [rafaelpimpa/buefy#451]
### Description

Add support for `b-table` to remember the sort (column + direction) with a new prop: `remember-sort`(bool). This property would take precedence on `default-sort` and `default-sort-direction` if sort is saved.

`localStorage` could be used to accomplish this.

To distinguish between deferent table instances, we would need to declare a `storage-name` prop or maybe just an `id` prop. 

Right now I can use the `sort`event to implement this feature, but it would be more clean and make more sense if it was built in. (I can submit a PR if you want).

**Comment by Tirke** [comment]
This is clearly a `vuex` + persistance use case for me and as you said it can already be done by using `@sort`. 

But .. I can see that being useful nevertheless.

**Comment by jpbecotte** [comment]
I don’t see why the persistence should be elsewhere than localStorage. 

This is for the use case of an user sorting columns then closing the browser window then reopening a session.

**Comment by Tirke** [comment]
Yep, I fully understood you.

I was just trying to say that what you suggest is the perfect use case for `vuex` + a `vuex` plugin for persisting state in localStorage (or in cookies or whatever you want) like [`vuex-persistedstate`](https://github.com/robinvdvleuten/vuex-persistedstate)

**Comment by jpbecotte** [comment]
Ok, nice, I’ll take a look into that

**Comment by rafaelpimpa** [comment]
I think it's better if you use a plugin for that like @Tirke suggested. Buefy should be just an UI layer.
