### ISSUE TITLE
Stack toasts and snackbars

### ISSUE THREAD

**Issue by johnmerced** [rafaelpimpa/buefy#452]
### Overview of the problem

**Buefy** version: 0.6.1
**Vuejs** version: 2.5.4
**OS/Browser**: Any

### Description
Is it possible to have the toasts and/or snackbars stack? I didn't find a setting for that.
Something like these plugins are doing https://goo.gl/GUoSAB or https://goo.gl/8cWd54

### Expected behavior
Have toasts and snackbars stack in top/bottom instead of waiting for the previous one to finish showing.

### Actual behavior
Toast and snackbars waits until the previous one finishes causing a delay if there are multiple toats/snackbars in matter of seconds.

**Comment by jtommy** [comment]
@johnmerced Next release... https://github.com/rafaelpimpa/buefy/issues/125

**Comment by grebebird** [comment]
@jtommy - looks like you marked this as "next release" but linked to an issue that was marked as "won't fix" several months before you noted this was coming in the next release. I'm assuming "won't fix" is the answer that won? If so, is there a decent work around for when toasts could be called in quick succession? If not stacking, then perhaps not showing a toast if one is already currently being shown? The queue doesn't quite solve the UX challenge like stacking does.
