### ISSUE TITLE
Feature Request: Draggable rows in BTable

### ISSUE THREAD

**Issue by ketulm** [rafaelpimpa/buefy#453]
This is a new feature request for the BTable component - initial support might be very straightforward to add.

**Allow row(s) to be [draggable](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API) and expose drag callbacks (e.g. dragstart, dragend) through the BTable API.** 

This would allow users to drag the entire row (or possibly all the checked rows?) and drop it elsewhere (for processing, moving, linking, etc.).  A good/simple use case would be moving rows from one container to another (e.g. move files to another folder). 

I currently make individual columns draggable but that leads to undesired behavior.  First, the rendered drag image is only for the column being dragged (may confuse users into thinking only that column content is being dragged). Second, the user has to know which columns can be dragged if only selected columns are made draggable. 

_Note that this request is **not** for an ability to drag entire columns in BTable for re-arranging columns._

**Comment by jaybeecave** [comment]
I can write an implmenentation using sortablejs, but that will add a dependancy. Can someone let me know if that is okay?

**Comment by jaybeecave** [comment]
Realised SortableJS has a JQuery dependancy... No thanks. Looking into dragula

**Comment by ketulm** [comment]
For my immediate needs/use-case, I just need the ability to bind to the drag and drop events on the `<tr>` and I can take care of the rest. 

In the future, it would be nice to have richer DnD support provided by those external libraries.

**Comment by jtommy** [comment]
In the next release will be an extension with https://github.com/RubaXa/Sortable

**Comment by markokos01** [comment]
Is there any plan to improve draggable rows in BTable? For example I would like to set some rows to _draggable="false"_, freeze some rows etc. There is sortablejs extension which is shown in documentation on Tags example and I would like to make this work on BTable.
