### ISSUE TITLE
b-input key pressed events

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [rafaelpimpa/buefy#454]
b-input doesnt answer to key events..

i tried @keyup.enter=`method`

Nothing happened

**Comment by jtommy** [comment]
@diego-lipinski-de-castro You have to use `native` modifier. For example `@keyup.native.enter`.

**Comment by kerbo** [comment]
One important clarification...@keyup.native.enter does not call a method, it triggers an event, so you must do:

@keyup.native.enter="event => method"

Supporting @keyup.enter in the component would save lots of time for everyone trying to do this for the first time.

**Comment by jtommy** [comment]
@kerbo You're right but you might use `@keyup.native.enter="myMethod($event)"`
