### ISSUE TITLE
Create a b-card component

### ISSUE THREAD

**Issue by gabrielsclimaco** [rafaelpimpa/buefy#455]
There are some Bulma elements that does't have a component yet, Card is one of them.

I wonder if this is according to Buefy roadmap plans; I could try this myself with the card example or other Bulma element.

**Comment by jtommy** [comment]
@gabrielsclimaco We have no plans about a Card component. As you can see we removed support to Panel component and Card it's quite similar.
At the moment we don't want to cover all Bulma 
simple components/elements.
Thanks for the support!
