### ISSUE TITLE
Programmatically opening Modal - onCancel not working

### ISSUE THREAD

**Issue by kieusonlam** [rafaelpimpa/buefy#457]
### Overview of the problem

**Buefy** version: 0.6.1
**Vuejs** version: 2.5.2
**OS/Browser**: Windows / Chrome

### Description

I try to make an some thing like edit todo list.

```
<div v-for="todo in todos :key="todo.id">
    <div class="todo-item">
        <div>{{ todo.title }}</div>
        <div class="edit" @click="todoEditModal(todo)">Edit</div>
    </div>
</div>
```

```
removeTodo: function (todo) {
      var index = this.todos.indexOf(todo)
      this.todos.splice(index, 1)
}

todoEditModal: function (todo) {
      this.beforeEditCache = todo

      this.$modal.open({
          parent: this,
          component: MovieNewEditForm,
          props: { todo },
          onCancel: this.removeTodo(todo)
      })
}
```

### Actual behavior

The `removeTodo` function run when open the model.

### Expected behavior

The `removeTodo` run after cancel modal

**Comment by rafaelpimpa** [comment]
since you passing a parameter to the ``removeTodo`` method, it will be executed right away. You have to wrap it on a function (just like js timeout):

``onCancel: () => this.removeTodo(todo))``

**Comment by kieusonlam** [comment]
Hi @rafaelpimpa 

Is there anyway to close modals without trigger onCancel? I plan to do a saveTodo funtion on the modals, it will close the model without rolling back the data.

**Comment by shelru** [comment]
> since you passing a parameter to the `removeTodo` method, it will be executed right away. You have to wrap it on a function (just like js timeout):
> 
> `onCancel: () => this.removeTodo(todo))`

Add this into doc's.
