### ISSUE TITLE
Style B-table in scoped component style

### ISSUE THREAD

**Issue by lsbyerley** [rafaelpimpa/buefy#461]
### Overview of the problem

**Buefy** version: 0.6.1
**Vuejs** version: 2.5.9
**OS/Browser**: mac/chrome

### Description

Styling of b-table in scoped script tag in component does not seem to work. Does anyone know why?

### Steps to reproduce

    <template>
      <b-table class="games"
        :data="!games ? [] : games"
        :loading="fetchingGames">
        <template slot-scope="props">
          <b-table-column label="Game">
            {{ props.row.team[0].abbreviation }}
            vs.
            {{ props.row.team[1].abbreviation }}
          </b-table-column>
        </template>
      </b-table>
    </template>
    
    <style lang="scss" scoped>
    .b-table {
      .table {
        width: 50%;
      }
    }
    </style>

### Expected behavior

The table should be 50% width

### Actual behavior

The table is still 100% width

**Comment by jtommy** [comment]
@lsbyerley You might try without scoped style and using your custom class 'games'.
For example:
```
<style>
.games .table {
    width: 50%;
}
</style>
```

**Comment by lsbyerley** [comment]
@jtommy I've already tried that, and no, it doesn't work

**Comment by jtommy** [comment]
http://jsfiddle.net/du2oxe1r/40/. This is a simple example and it works.

**Comment by lsbyerley** [comment]
@jtommy Using `.games .table` doesn't work for me, however, when including Buefy, I'm doing `Vue.use(Buefy)` instead of `Vue.use(Buefy.default)`. When I do the latter, i get a "Cannot read property 'install' of undefined".. strange

**Comment by jtommy** [comment]
It's only an example with js and css from CDN.
 My example is the simple way and it works without `!important`.
