### ISSUE TITLE
b-icon Not rendering icons

### ISSUE THREAD

**Issue by alalfakawma** [rafaelpimpa/buefy#464]
I have a problem, whenever I use `<b-icon icon="menu-down">`, it does not render the correct i tag with proper classes. I have added the material icons in the head tag, and it does work when I manually type it in, but using b-icons is not rendering the classes, for eg. `<i class="mdi mdi-menu-down">`, it should be rendered like that but it will render as `<i class="mdi">menu-down</i>`, also I have included buefy properly as said by the documentation, also I have added the **defaultIconPack** constructor to no avail. Can anyone help me solve this issue? Thanking you in anticipation.

**Comment by jwahdatehagh** [comment]
Does closing the `b-icon` tag with `/>` help?

`<b-icon icon="menu-down" />`
or
`<b-icon icon="menu-down" ></b-icon>`

**Comment by jtommy** [comment]
I think it's the same issue https://github.com/rafaelpimpa/buefy/issues/402

**Comment by rafaelpimpa** [comment]
Update buefy to 0.6.0+

**Comment by atanderG** [comment]
how to update buefy to 0.6.0, i m using laravel 5.4
