### ISSUE TITLE
Add Icon in table column header

### ISSUE THREAD

**Issue by roni-estein** [rafaelpimpa/buefy#467]
**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.8]
**OS/Browser*osx high sierra/ chrome 62*:

### Description

I've make extensive use of the b-table, thanks, it's a great time save. I'm trying to get the label or header in the <th> portion of the column to render a font awsome icon with a tooltip. (it's the icon part that's the issue) However I can't figure that out. Any advice would be great, if it's not currently possible, please mark this as a feature request.

```
<b table ....>
    <b-table-colum ... label="<i class=\"fa fa-user\"></i>" or any combination of escape sequences I can find in laravel php or js

```

Thanks.

**Comment by jtommy** [comment]
@roni-estein You have to use `header` slot (see table docs).
For example:
```
<b-table ...
<template slot-scope="props" slot="header">
       <b-icon v-if="props.column.field === 'user.first_name'" pack="fa" icon="user"></b-icon>
{{props.column.label}}
</template>
</b-table>
```
