### ISSUE TITLE
Event for change rows per page on table

### ISSUE THREAD

**Issue by donaldinos** [rafaelpimpa/buefy#469]
I need store informations about configuration parameters of table in user session and i don't know, how is possible emit event, when user has changed parameter rows per page ?

**Comment by diego-lipinski-de-castro** [comment]
I can`t really help you now, but if you use vue devtools, you can see emitted events by clicking on the third of the four top-right side tabs

**Comment by diego-lipinski-de-castro** [comment]
https://raw.githubusercontent.com/vuejs/vue-devtools/master/media/demo.gif events tab

**Comment by donaldinos** [comment]
Thnx !
