### ISSUE TITLE
Image preview on hover - tool tip

### ISSUE THREAD

**Issue by AmazeCPK** [rafaelpimpa/buefy#47]
Would it be possible to add the ability to add an imiage to the b-tooltip attributes.
Reason for this, is I would like a image thumbnail on hover. Thank you!

**Comment by rafaelpimpa** [comment]
I'm not entirely sure if this should be embbed into Tooltip yet.

**Comment by rafaelpimpa** [comment]
Actually this is better suited for Popovers, see #103
