### ISSUE TITLE
is-toast class not added since 0.6.2

### ISSUE THREAD

**Issue by adrlen** [rafaelpimpa/buefy#470]
### Overview of the problem

**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.9]
**OS/Browser**:

### Description

The is-toast class is not added anymore in the Toast component :
https://github.com/rafaelpimpa/buefy/commit/5fa2dffb970635aff1bf6a3773e13c8099f174e7#diff-2f4b8565507a7062ea963009170f040fL30

Not sure if its an expected behavior

**Comment by rafaelpimpa** [comment]
It is, just use ``.notices .toast``
