### ISSUE TITLE
Upload drag-drop multiple files

### ISSUE THREAD

**Issue by mmerlijn** [rafaelpimpa/buefy#471]
### Overview of the problem

**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.9]
**OS/Browser**: Firefox / Chrome

### Description

By dropping multiple files at once al files will be sent. This works perfect.
By dropping files one-by-one only the last dropped only the last file will be sent.

### Steps to reproduce
`                                <b-upload v-model="dropFiles"
                                          multiple
                                          drag-drop
                                          type="is-dark"
                                          name="files[]"
                                > ...`

1 . drag and drop files one-by-one in de upload field. (Files will be presented in the dropFiles array)
2.  submit the form (only the last file will be sent after a submit)
3. By drag-and-drop multiple files at the same time, all files wil be sent.

### Expected behavior

All selected files will be sent

### Actual behavior

Only last file is sent

**Comment by jtommy** [comment]
@mmerlijn It's no possibile append files to native input so you should upload files by ajax request.
Anyway we'll add new prop `native` and in this way the component doesn't append files to `v-model` (like native input element).
