### ISSUE TITLE
Cleave extension initial formatted value

### ISSUE THREAD

**Issue by talismax** [rafaelpimpa/buefy#472]
Quick question:  How do you set the initial formatted value in the Cleave extension?  If you bind with v-model it shows the raw value at first and only starts formatting on input.

**Comment by rafaelpimpa** [comment]
Probably has to set it via ``setRawValue``

template:
``<b-input ref="input" v-cleave="{...}"/>

script:
``this.$refs.input.querySelector('input')._vCleave.setRawValue('...')``

**Comment by 4KDA** [comment]
@talismax, How did you solve this problem?
