### ISSUE TITLE
Detailed Table Rows

### ISSUE THREAD

**Issue by jethro1991** [rafaelpimpa/buefy#477]
### Overview of the problem

**Buefy** version: 0.6.2
**Vuejs** version: 2.5.11
**OS/Browser**: Chrome/Firefox

### Description

When expanding table rows i get the following error: Duplicate keys detected: '0'. This may cause an update error. 

### Steps to reproduce

Copy pasted the example code from the website and it gives me the same error without fail, all of the other table examples work correctly. 

### Expected behavior

No errors when expanding table rows.

### Actual behavior

Errors each time i expand a row using example code.

![athletes](https://user-images.githubusercontent.com/6702147/34040874-63bb8ed4-e19e-11e7-90a9-2552b72ff092.png)

**Comment by rafaelpimpa** [comment]
I've fixed it in dev branch, next release is fixed!
