### ISSUE TITLE
Click event for table cell / best way to do vue-router navigation from table cell?

### ISSUE THREAD

**Issue by gwvt** [rafaelpimpa/buefy#48]
I want to navigate to vue-router links from table cells, like this:

template:
```
<b-table>
[...]
  <b-table-column click="routerLinkToDetails"></b-table-column>
[...]
</b-table>
```

script:
```
methods: {
  routerLinkToDetails() {
    this.$router.push({ path: '/details/:recordId' });
  }
```

But it seems that a click event can only be bound to the row, not an individual cell.

Is it/would it be possible to bind a click event to a table cell? Or, is there another way to do router navigation from a table cell?

**Comment by rafaelpimpa** [comment]
Hi! Sorry for the delay. Use the ``selectable`` property on Table, than listen to ``select`` on Table as well:

```html
<b-table
    :data="tableData"
    selectable
    @select="selected">
    // Columns here
</b-table>
```
```javascript
export default {
    methods: {
        selected(item) {
            this.$router.push({ path: '/details/:recordId' })
        }
    }
}
```

Something like that, guess you already got the hang of it.

**Comment by gwvt** [comment]
Thanks, but that's only for the row. I am looking to have an <a> tag on the text in a single cell to click to a vue-router link. (Actually, several cells in each row with each one having its own independent <a> tags & vue-router link.) Is that possible?

**Comment by rafaelpimpa** [comment]
You mean like links in the cell?

**Comment by gwvt** [comment]
Yes, like this: 
<img width="618" alt="screen shot 2017-05-02 at 4 53 56 pm" src="https://cloud.githubusercontent.com/assets/17604801/25638928/0e3b75e4-2f58-11e7-879d-c56fc355230a.png">
Where you can dynamically generate the vue-router link with recordIds and link to them from individual table cells. So I think this would require a click event in the cell/column as in my original issue post above, but please correct me if I am not understanding the use of the component property.

**Comment by rafaelpimpa** [comment]
I'm gonna think about it tbh, It's probably the same use-case of #49
