### ISSUE TITLE
datepicker disable weekends

### ISSUE THREAD

**Issue by foureight84** [rafaelpimpa/buefy#483]
### Overview of the problem

**Buefy** version: [0.6.1]
**Vuejs** version: [0.6.1]
**OS/Browser**:

### Description

Is there a way to disable weekends for datepicker? Or will I have to generate a list of dates that fall on Sat and Sun as prop for unselectable-dates?

**Comment by jtommy** [comment]
@foureight84 Yes, `unselectable-dates` might be a workaround for you need but probably it's no the best way.
We could add a new prop `unselectable-days-of-week` as array (same values of `first-day-of-week`, 0 -> Sunday, 1 -> Monday, ...). For example:
```
<b-datepicker :unselectable-days-of-week="[0, 6]"> ...
```
What do you think about ?

**Comment by foureight84** [comment]
That's perfect! I ended up generating a list of weekend dates. It's not the best solution but it is good enough for now until unselectable-days-of-week is live. I have my max date set to two years so generating that list of weekends doesn't hinder performance.

Since we're on this topic, could you recommend a way to block out time buckets as well for timepicker? this one is a bit harder as it has no props for unselectable-dates

**Comment by re2005** [comment]
Hey guys, is this feature ever made ? Comes quite handy to be able to disable weekends.

Cheers

**Comment by jtommy** [comment]
It's already ready in the last releases
