### ISSUE TITLE
Feature Request - Notification Icon should use Size Prop 

### ISSUE THREAD

**Issue by nmarshall23** [rafaelpimpa/buefy#487]
### Overview of the problem

I would like to be able to set the icon size in b-notification. Notification uses the MessageMixin, which has a size prop, this would have Notification default to large or use the size prop if set.

**Buefy** version: 0.6.2
**Vuejs** version: 2.5.10
**OS/Browser**: Chrome

**Comment by jtommy** [comment]
@nmarshall23 `size` prop is better not but we could add `icon-size` prop.
