### ISSUE TITLE
Combine Datepicker and Timepicker into one

### ISSUE THREAD

**Issue by kieusonlam** [rafaelpimpa/buefy#488]
Hi guys,

As the title, how should I combine those into a single value?

**Comment by jtommy** [comment]
@kieusonlam What do you mean "single value" ? Single component  ?

**Comment by kieusonlam** [comment]
Hi @jtommy 

Thanks for reply. I mean I have a `datetime` data
```
  data () {
    return {
      datetime: null
    }
  }
```
I looking for a best practice use both Datepicker and Timepicker to update value this single `datetime`. 

P/S: If it is possible to merge them to single component that would be great too.

**Comment by jtommy** [comment]
We have no plans about merge to single component.
About your request you could add two separate variable to data, `date` and `time`, and watch it to update `datetime` variable;  you get year, month, day from `date` (date object) and hours, minutes from `time` (date object).

**Comment by kieusonlam** [comment]
Thank you for your advice!
