### ISSUE TITLE
Feature request: Table column slots

### ISSUE THREAD

**Issue by iwan-wijaya** [rafaelpimpa/buefy#49]
Hi, I just tried buefy, it is really good, but I have a problem with the table component.

I think it will be nice if we can put custom stuff inside a table column using slots and also a way to get the current loop index.

```html
<b-table-column label="#">
  // This is an example from ElemeFE/element
  <template scope="scope">
     {{ scope.$index + 1 }}
  </template>
</b-table-column>
```

**My use case**
- An "action column" (It is possible by using the `component` prop for this, but it is very limited.)
```javascript
// Not possible to listen to component events & assign a custom prop to my component.
<b-table-column field="id" label="Action" component="app-table-action"></b-table-column>
```
- Showing row numbers (This is currently possible, but it will be much easier if we can just get the row number/index)
```html
<b-table-column field="id" label="#" width="40" numeric :format="formatNumber"></b-table-column>
```
```javascript
formatNumber (value, row) {
    return this.customers.findIndex(row => row.id === value) + 1
 }
```
![screenshot_2017-04-29_19-36-38](https://cloud.githubusercontent.com/assets/11938557/25555263/e9b45cfe-2d13-11e7-99fd-fd00e6362d39.png)

**Comment by bathyscaaf** [comment]
I'm having a related issue.  I'm using a component in a table cell that needs more information than a string from the "field" attribute will provide.  My problem is I still need to maintain sort-ability, so I can't just pass stringified JSON.

In my case the cell contains a router link that needs to be sortable.  Would something like a "payload" attribute that accepts objects solve both our issues (not including the index)?

**Comment by rafaelpimpa** [comment]
I could get to something like that, but it's a breakable change for all tables, the new code will be like this:

```html
<b-table
    :data="tableData">

    <b-table-column field="id" label="ID" width="40" sortable numeric></b-table-column>
    <b-table-column field="first_name" label="First Name" sortable></b-table-column>
    <b-table-column field="last_name" label="Last Name" sortable></b-table-column>
    <b-table-column field="date" label="Date" sortable></b-table-column>
    <b-table-column field="gender" label="Gender"></b-table-column>

    <template slot="row" scope="props">
        <td> {{ props.row.id }} </td>
        <td> {{ props.row.first_name }} </td>
        <td> {{ props.row.last_name }} </td>
        <td v-html="formatDate(props.row.date)"></td>
        <td>
            <b-icon pack="fa" :icon="props.row.gender === 'Male' ? 'mars' : 'venus'"></b-icon>
            {{ props.row.gender }}
        </td>
    </template>
</b-table>
```

As you can see, it will be now possible to have full control over the cells, will solve a lot of problems. The code is not that clean as the old one but I also cannot make it work both ways at the same time.

Thoughts?

**Comment by gwvt** [comment]
I think the added flexibility is worth the extra code. Then you can do anything you want with tables.

**Comment by ismet** [comment]
I agree with @gwvt .. I would like to have full control instead of auto generated code.. 

By the way, what are the **slot="row"** and **scope="props"** attributes in the template element?

**Comment by rafaelpimpa** [comment]
https://vuejs.org/v2/guide/components.html#Scoped-Slots

**Comment by iwan-wijaya** [comment]
@rafaelpimpa  Looks good to me 👍
But doesn't it break features like sorting?

**Comment by rafaelpimpa** [comment]
@iwan-wijaya nope, all working great.

**Comment by rafaelpimpa** [comment]
Ok, so after a lot of tries I could get it to work like this, I think it's even better:

```html
<b-table :data="tableData">

    <template slot="columns" scope="props">
        <b-table-column field="id" label="ID" width="40" sortable numeric>
            {{ props.row.id }}
        </b-table-column>

        <b-table-column field="user.first_name" label="First Name" sortable>
            {{ props.row.user.first_name }}
        </b-table-column>

        <b-table-column field="user.last_name" label="Last Name" sortable>
            {{ props.row.user.last_name }}
        </b-table-column>

        <b-table-column field="date" label="Date" sortable
            v-html="formatDate(props.row.date)">
        </b-table-column>

        <b-table-column field="gender" label="Gender">
            <b-icon
                pack="fa"
                :icon="props.row.gender === 'Male' ? 'mars' : 'venus'">
            </b-icon>
            {{ props.row.gender }}
        </b-table-column>
    </template>
</b-table>
```

Probably gonna keep it, will just wait for your thoughts 👍

**Comment by rafaelpimpa** [comment]
So, the only thing you have to add from the original code (^v0.2.2) is adding the ``<template scope="props">`` before the columns and then add the slot, pretty easy to update. 

All functionalities are working great, even the ``numeric`` prop.

**Comment by ismet** [comment]
Hi @rafaelpimpa,

Sorry but, I couldn't understand from the documentation how scoped slots work. I mean, where and how do we define "props", "row", etc? It would be great if you give a super-simple but fully functional sample code using b-table.

**Comment by rafaelpimpa** [comment]
That's the full code. The prop scope is returned from table itself.

**Comment by ismet** [comment]
Hi @rafaelpimpa,

The following Vue code is not working for. I get the error "**_Cannot read property 'id' of undefined_**"". 
Did I miss something?

```
<template>
    <div>
        <b-table :data="sampleItems">
            <template scope="props">
                <b-table-column field="id" label="ID Value" sortable>
                    {{ props.row.id }}
                </b-table-column>
            </template>
        </b-table>
    </div>
</template>

<script>
export default {
  data() {
    return {
      sampleItems: [ { id:111},{ id:222},{ id:333},{ id:444}]
    }
  }
}
</script>
```

**Comment by rafaelpimpa** [comment]
Did you clone? This will be available in v0.3.0

**Comment by ismet** [comment]
Firstly I run the command **`npm install rafaelpimpa/buefy#dev --save`** 
and the package.json added line in dependencies **"buefy": "github:rafaelpimpa/buefy#dev"**. 
Then I checked the buefy folder under node_modules and verify the latest version(v.0.3.0) exists.

But I get exactly the same error.. :(

**Comment by rafaelpimpa** [comment]
That won't work buecause I didn't update the lib folder. Just wait for the release or set the import to the ``src`` folder.

**Comment by genichiro** [comment]
Hi @rafaelpimpa,
Thank you for the new table.
But I get the error
```
Uncaught TypeError: Cannot read property 'row' of undefined
    at VueComponent.selectRow (index.js:3)
    at Proxy.boundFn (vue.common.js:166)
    at click (index.js:4)
    at HTMLTableRowElement.invoker (vue.common.js:1739)
```
on click the row.
Did I miss something?

it's my template:
```pug
<template lang="pug">
b-table(:data="list" striped)
  template(scope="props")
    b-table-column(field="duration" label="Duration" sortable) {{ props.row.duration }}
</template>
```

**Comment by iwan-wijaya** [comment]
@genichiro Are you using Vue 2.1.0+ ?

**Comment by rafaelpimpa** [comment]
Minor mistake, will wait to catch more bugs before releasing a patch, thanks.

**Comment by genichiro** [comment]
@rafaelpimpa maybe I've found another problem, it seems `default-sort` is not working.

**Comment by rafaelpimpa** [comment]
The column you're setting has the ``sortable`` prop?

**Comment by genichiro** [comment]
yes, it's my template that has problem
```
<template lang="pug">
div
  b-table(:data="list" default-sort="['rate', 'desc']" striped)
    template(scope="props")
      b-table-column(field="currency" label="Currency" width="100" sortable) {{ props.row.currency }} %
      b-table-column(field="rate" label="Rate" sortable) {{ props.row.rate }} %
</template>
```
if I use old version, it's works fine.

**Comment by rafaelpimpa** [comment]
Use with ``v-bind`` because it's an array:

```
<template lang="pug">
div
  b-table(:data="list" :default-sort="['rate', 'desc']" striped)
    template(scope="props")
      b-table-column(field="currency" label="Currency" width="100" sortable) {{ props.row.currency }} %
      b-table-column(field="rate" label="Rate" sortable) {{ props.row.rate }} %
</template>
```
