### ISSUE TITLE
Feature Request - timepicker with ability to blockout time slots

### ISSUE THREAD

**Issue by foureight84** [rafaelpimpa/buefy#494]
Much like datepicker with the ability to block out dates, it would be nice to have a prop for unselectable time which accents an array of time (24hr) to be disallowed from selection. of course, if the list of given time is not within the scope of the incremental time then it will be ignored.

**Comment by jtommy** [comment]
@foureight84 Are you thinking somenthing as `unselectable-dates` (array of date object) ?

**Comment by foureight84** [comment]
Yes. that's exactly what I was thinking about.
