### ISSUE TITLE
Pack fa causing problems

### ISSUE THREAD

**Issue by StanislavBerezin** [rafaelpimpa/buefy#496]
Was just getting my hands on this UI framework, thanks for working on it. There is 1 problem that i've faced and not really sure what its behaving this way. From your example in dropdown section you have a menu with 
 
                           <a class="navbar-item"><b-icon pack="fa" icon="twitter"></b-icon></a>

The problem is that it doesnt display the icon, however if you remove <pack="fa"> it works just fine, so just letting you know, maybe should update some of these stuff :) also curios to know on why its happening. Github icon has also been changed to "github-circle", so maybe give a little update to the code on your page

**Comment by jtommy** [comment]
In Buefy website i can see twitter logo. What's your problem ?
In FontAwesome 4.x there isn't "github-circle"...

**Comment by StanislavBerezin** [comment]
By some reason the icon things are really buggy with buefy, im trying to put stuff but sometimes it dissapears, then appears again without me changing the code but simply refreshing the page.
for example i try to use.

           <b-icon
                pack="fa"
                icon="users"
                size="is-small">
            </b-icon>

It doesn display anything, just blanked, i tried to change "icon='fa-users'" but it doesnt help. Not sure whats causing the problem, but icons by some reason are the buggiest thing

**Comment by StanislavBerezin** [comment]
I'm copying your code directly from your docs like 

        <b-icon
                pack="fa"
                icon="user"
                size="is-small">
            </b-icon>

but it aint working neither

**Comment by jtommy** [comment]
@StanislavBerezin Are you sure to import FontAwesome.
`<i class="fa fa-user"></i>`, is it works ? 
https://jsfiddle.net/9pva123u/

**Comment by StanislavBerezin** [comment]
seems like the problem is with Vue.use(Buefy.default), if you remove default it doesnt work for FA pack

**Comment by jtommy** [comment]
@StanislavBerezin If you remove that line Buefy components aren't loaded and so you can't use icon component.

**Comment by StanislavBerezin** [comment]
When i said remove that line, i meant ('.default'), not the entire thing. I've installed buefy with npm in webpack for vue and wrote Vue.use(Buefy) in main.js just as docs suggest but it wasnt showing the icons, but if i write "Vue.use(Buefy.default)" in main.js then it shows the icons. So i hope u see the point im trying to convey to u

**Comment by jtommy** [comment]
I'm checking but i can't reproduce it. Could you provide us a your "complete" example ?

**Comment by StanislavBerezin** [comment]
i've put some comments inside of the main.js
https://github.com/StanislavBerezin/pleaseFixBuefy

**Comment by jtommy** [comment]
@StanislavBerezin Where is font-awesome import (npm o cdn) ??? In your example `Vue.use(Buefy.default)` is no correct and if you change it to `Vue.use(Buefy)` and add (for example) `<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">` to the index.html, it's all ok!

**Comment by brianirish** [comment]
@StanislavBerezin I just ran into this issue myself, and resolved it in this way:

In my project: `npm install --save-dev font-awesome`
In my main.js file which bootstraps my Vue application:
```
// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
...
import Buefy from 'buefy'
import 'buefy/lib/buefy.min.css'
import 'font-awesome/css/font-awesome.min.css'

Vue.config.productionTip = false

Vue.use(Buefy, {
  defaultIconPack: 'fa',
  defaultContainerElement: 'app'
})
...
```
Note the import of font-awesome's CSS. This worked for me, hope it works for you!

**Comment by brianirish** [comment]
@jtommy The documentation could probably use improving to specifically mention the import of font-awesome's CSS in the main.js being _required_ for font-awesome's icons to work at all. My assumption, and I believe @StanislavBerezin had this assumption as well, was that the font-awesome library came included in Buefy, so that all was required was to import the Buefy and Buefy's css file.

**Comment by jtommy** [comment]
@brianirish Ok, we'll add a warning in the start docs page.
