### ISSUE TITLE
Horizontal form doesn't properly convert to mobile mode.

### ISSUE THREAD

**Issue by Herteby** [rafaelpimpa/buefy#498]
### Overview of the problem

**Buefy** version: 0.6.2
**Vuejs** version: ?
**OS/Browser**: Linux Mint/Chrome

### Description

The horizontal forms of Buefy don't convert to mobile mode properly, while Bulma's does. The reason seems to be that you're adding the `.has-addons` class to the field.

### Expected behavior
Example from [Bulma docs](https://bulma.io/documentation/form/general/#horizontal-form)
![image](https://user-images.githubusercontent.com/6474685/34416848-b7663564-ebf5-11e7-990d-aec02f258d38.png)

### Actual behavior
Example from [Buefy docs](https://buefy.github.io/#/documentation/field)
![image](https://user-images.githubusercontent.com/6474685/34416773-6289d8ac-ebf5-11e7-809f-233b7e35117f.png)

**Comment by Herteby** [comment]
A workaround is to set `:addons="false`

**Comment by jtommy** [comment]
Yes it's correct. We could remove `field` component in a a way to remove `has-addons` class when field is `horizontal`.
