### ISSUE TITLE
Serve builds

### ISSUE THREAD

**Issue by rodymol123** [rafaelpimpa/buefy#5]
It would be easier to use this project if you provided the compiled JS, that way developers don't have to alter their development environment. :)

**Comment by rafaelpimpa** [comment]
You're right, I'm gonna do that for the next big release

**Comment by rafaelpimpa** [comment]
I have a beta published with compiled builds, could you help me test it out?

```
npm install buefy@compiled
```
import css like this: ``import 'buefy/lib/buefy.css'``

**Comment by rodymol123** [comment]
Sure thing, I'll get back to you :)
