### ISSUE TITLE
pageChange event on Table

### ISSUE THREAD

**Issue by smxsm** [rafaelpimpa/buefy#50]
Hi, I really like Buefy so far, but there seems to be no way to use async data for the table component with sorting, paging, filtering etc.
The pagination component is tied into the table, but has no reference to it... and the table itself does not emit events for e.g. paging - at least I couldn't find a way to detect pagination events.
So, built-in remote data support would be awesome, but at least adding a reference to the pagination component  and adding a pagination event to the table would help :)
See my table comparison here: http://www.rent-a-hero.de/wp/wp-content/uploads/2017/04/vuegrid/#/

**Comment by iwan-wijaya** [comment]
Hi, I got the same problem today and found the solution

There is a separate pagination components that emits page change event, you can add it bellow your table.
https://buefy.github.io/#/documentation/pagination
Here is my code
```html
<b-pagination
    :total="total"
    :current="currentPage"
    :simple="false"
    :per-page="filter.limit"
    order="is-right"
    @change="pageChange">
    </b-pagination>
```
```javascript
pageChange (page) {
    this.currentPage = page
    this.filter.offset = ((this.currentPage - 1) * this.filter.limit)
    this.loadData() // api call
}
```
For server side sorting use the property `backend-sorting` that can be applied to the table (not column)
```html
<b-table
      :data="customers"
      :paginated="false"
      :backend-sorting="true"
...
```
```javascript
sort (field, order) {
    this.filter.orderBy = field
    this.filter.orderDirection = order
    this.loadData()
}
```

**Comment by smxsm** [comment]
@iwan-wijaya Thanks, that works! I saw the extra pagination component, but I didn't realize you can disable the "internal" pagination for the table and use the external one 👍 
But maybe adding the paging callback and reference to the table component itself would be a good idea nonetheless? Would be more intuitive I think :)

**Comment by rafaelpimpa** [comment]
I thougtht that the table was emitting the pageChange event, gonna add it for the next release.
