### ISSUE TITLE
Message/help text of horizontal field is placed in wrong element

### ISSUE THREAD

**Issue by Herteby** [rafaelpimpa/buefy#500]
### Overview of the problem

**Buefy** version: 0.6.2
**Vuejs** version: 2.5.13
**OS/Browser**:Linux Mint/Chrome

### Description

According to Bulma, message/help text for horizontal forms should be placed like this:
```html
<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label">Email</label>
  </div>
  <div class="field-body">
    <div class="field">
      <div class="control"></div>
      <p class="help">HELP TEXT</p> <!-- In the inner field -->
    </div>
  </div>
</div>
```
But in Buefy they are placed like this:
```html
<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label">Email</label>
  </div>
  <div class="field-body">
    <div class="field">
      <div class="control"></div>
    </div>
  </div>
  <p class="help">HELP TEXT</p> <!-- In the outer field -->
</div>
```
This causes major issues in horizontal forms.

### Steps to reproduce

```html
<b-field horizontal label="Label" message="helper text">
  <b-input/>
</b-field>
```
### Expected behavior

Bulma:
![image](https://user-images.githubusercontent.com/6474685/34433592-b800974a-ec80-11e7-9b34-1589c6ce5ba1.png)

### Actual behavior
Buefy:
![image](https://user-images.githubusercontent.com/6474685/34434031-9aec5c9a-ec83-11e7-9bbc-d3f7c2e993d1.png)

**Comment by Herteby** [comment]
This workaround seems to work for now:
```html
<b-field horizontal label="Label">
  <b-field message="helper text">
    <b-input/>
  </b-field>
</b-field>
```

**Comment by ghprod** [comment]
confirmed ..

example from docs https://buefy.github.io/#/documentation/field

![image](https://user-images.githubusercontent.com/1922652/34483656-80d776e2-eff2-11e7-8a17-2e234abb5278.png)

**Comment by ghprod** [comment]
@Herteby wrapping with nested `<b-field>` seems like the best solution for now.

![image](https://user-images.githubusercontent.com/1922652/34483730-00bf4fd8-eff3-11e7-816e-5e27c81b93bc.png)


Thanks

**Comment by rafaelpimpa** [comment]
Can you take a look @electrolinux ?

**Comment by electrolinux** [comment]
Yep! Working on it right now...

**Comment by electrolinux** [comment]
See PR: #521
