### ISSUE TITLE
manually triggering input.checkHtml5Validity() short circuits when value empty

### ISSUE THREAD

**Issue by daetal-us** [rafaelpimpa/buefy#501]
https://github.com/rafaelpimpa/buefy/blob/81da1f3a2241903324a1d993ad8cf1e458037b3f/src/utils/FormElementMixin.js#L94

I think I understand why the default behavior is implemented in this way (prohibit everything from rendering as errors when type/validation set because a new form is empty) but it seems like manually triggering this should invalidate empty fields when, e.g. a value is required. Thoughts? Not sure this is the exact line to reference and I could setup references to the parent field and compute type/messages, etc. but it gets messy.

**Comment by rafaelpimpa** [comment]
In which component are you checking validity? in general it should check validity for empty fields.

**Comment by daetal-us** [comment]
hey @rafaelpimpa,

created a paste to better illustrate behavior: https://jsfiddle.net/0afsyg9v/64/

clicking validate explicitly calls `checkHtml5Validity()` which does not validate the empty field.

**Comment by daetal-us** [comment]
...just realizing I should be using the `required` attribute (doh!)

My only complaint is that the validation message should be consistent with invalid but that's subject and solvable in userland. Disregard!
