### ISSUE TITLE
Table with pagination not apply default icon pack (fa)

### ISSUE THREAD

**Issue by Insolita** [rafaelpimpa/buefy#502]
### Overview of the problem

**Buefy** version: [^0.6.2]
**Vuejs** version: [2.5.13]

### Description

I configure buefy with defaultIconPack 'fa',
```js
Vue.use(Buefy, {
    defaultIconPack:'fa',
    defaultFirstDayOfWeek:1
});
```
Try to use Table component with sorting and pagination feature
Pagination buttons for next and previous page rendered with mdi icons 
In other places font-awesome applied successful

 ![Visual](http://joxi.ru/gmvjpexSL3PyOm.png)
 ![Html-source](http://joxi.ru/EA4aLplCwBQPgr.jpg)

**Comment by jtommy** [comment]
@Insolita Are you sure to import FontAwesome ?
For example: https://jsfiddle.net/du2oxe1r/46/

**Comment by Insolita** [comment]
@jtommy Sure, if you see my screen - there contains buttons with fa icons

**Comment by Insolita** [comment]
Wow, the trouble was in my side

**Comment by okmkey45** [comment]
Hello.
I just want to use the Pagination component and so, I just import this only component.
How should I define the use of font-awesome?

I import the component like docs indicated: 
```
window.Vue.component(Buefy.Pagination.name, Buefy.Pagination);
```

**Comment by okmkey45** [comment]
@jtommy sorry to bother you. I hope you can help me.

I just want to use the Pagination component and so, I just import this only component.
How should I define the use of font-awesome?

I import the component like docs indicated:

```
window.Vue.component(Buefy.Pagination.name, Buefy.Pagination);
