### ISSUE TITLE
Issue with fields that have both a label and addons

### ISSUE THREAD

**Issue by Herteby** [rafaelpimpa/buefy#506]
### Overview of the problem

**Buefy** version: 0.6.2
**Vuejs** version: 2.5.13
**OS/Browser**: Linux Mint/Chrome

### Description

When a field has both a label and addons, the label gets treated like an addon, and gets displayed inline instead of above.

### Steps to reproduce

```html
<b-field label="Label">
  <b-input></b-input>
  <p class="control">
    <button class="button is-info">Search</button>
  </p>
</b-field>
```

### Expected behavior
![image](https://user-images.githubusercontent.com/6474685/34481879-c8919b4a-efb4-11e7-8e72-d04c8bec3084.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/6474685/34481891-da19f024-efb4-11e7-8d00-625f99158fb7.png)

### Suggested solution
If a field has both a label and addons, render it as a nested field:
```html
<div class="field">
  <label class="label">Label</label>
  <div class="field has-addons">      
    <div class="control">
      <input class="input">
    </div>
    <div class="control">
      <a class="button is-primary">Search</a>
    </div>
  </div>
</div>
```

**Comment by Herteby** [comment]
I found a workaround for now:
```
<b-field label="Label">
  <b-field>
    <b-input></b-input>
    <p class="control">
      <button class="button is-info">Search</button>
    </p>
  </b-field>
</b-field>
```

**Comment by jtommy** [comment]
@Herteby It's no a workaround but the right way (as you can see in Bulma docs).
We'll update Buefy docs with a similar field 👍

**Comment by Herteby** [comment]
@jtommy Yes it produces the correct Bulma markup, but it's a workaround since I'd think Buefy should handle it automatically.

**Comment by Herteby** [comment]
@rafaelpimpa How about adding something like this to Field.vue?
```html
<b-field v-else-if="$slots.default.length > 1 && label">
  <slot/>
</b-field>
```

**Comment by JoshZA** [comment]
👍

**Comment by rafaelpimpa** [comment]
Could you create a PR for it? So we can review better

**Comment by chrisrhymes** [comment]
Thanks for the info @Herteby 
I've discovered also, when you use has-addons with a button and an error message, the message wraps onto the same line, instead of underneath.  
![image](https://user-images.githubusercontent.com/4160546/52724123-a91f7b00-2fa6-11e9-8fbc-bcb70c02f161.png)

**Comment by CobraClutch** [comment]
I'm seeing this issue again in 0.7.4. Since the `<p class="help"></p>` is being appended inside the `<div class="field"></div>`, it also breaks the border radius css. Here's a screenshot from the official docs:

![Screen Shot 2019-04-12 at 11 03 10 AM](https://user-images.githubusercontent.com/5489691/56051229-952c9700-5d13-11e9-9165-a2dd88bc688b.png)

**Comment by yxngl** [comment]
391281b

**Comment by jtommy** [comment]
You're right! I'll fix it

**Comment by dmcbrn** [comment]
Pinging @jtommy 

I'm noticing the same behavior as @chrisrhymes

**Comment by jtommy** [comment]
I fixed it time ago

**Comment by dmcbrn** [comment]
To reproduce use this fiddle:

and replace `<section>...</section>` with

```
    <section>
        <b-field>
            <b-numberinput size="is-small" min=5 value="2">
            </b-numberinput>
            <!--comment out the p element below to show the inlined warning-->
            <!--is-small is not affecting the result-->
            <p class="control">
                <button class="button is-small is-primary">Search</button>
            </p>
        </b-field>
    </section>
```

Then click on the input, and then outside of it to trigger the error message.

![Screenshot from 2019-10-20 14-38-29](https://user-images.githubusercontent.com/40859618/67159627-5d984a80-f347-11e9-8f2e-e74bff4fc757.png)

**Comment by dmcbrn** [comment]
@jtommy Any feedback? Can you reproduce it? Should I open another issue? Do you need anything else from me?

**Comment by HugoHeneault** [comment]
I still had the original issue (doc isn't updated on https://buefy.org/documentation/field/#label-position), fixed using the "official way/workaround" proposed by @Herteby 

Updating the doc would be really nice 🍻

**Comment by HugoHeneault** [comment]
Whats actually weird is that doc code seems to work but not app code 🤔 

See 
![image](https://user-images.githubusercontent.com/4112256/73762526-97635480-4770-11ea-9979-0cba6fd0c912.png)

Vs app code 

![image](https://user-images.githubusercontent.com/4112256/73762706-c679c600-4770-11ea-8ad2-84a526c4d6cc.png)

**Comment by jtommy** [comment]
@Herteby and your code ?
