### ISSUE TITLE
TABLE - nested fields (feature request)

### ISSUE THREAD

**Issue by robsontenorio** [rafaelpimpa/buefy#51]
It would be nice to get value from nested fields :)

`<b-table-column field="city.name"></b-table-column>`

```
USER JSON
{
   name: "Joe",
   age: 34,
   city: {
        id: 12,
        name: "Paris"
    }
}
```

Currently i got it by using 

`<b-table-column field="city" :format="formatCity"></b-table-column>`

```
formatCity(value) {
      return value.name
}
```

**Comment by wanxe** [comment]
You can also use [lodash.](https://lodash.com/docs/4.17.4#get)

**Comment by rafaelpimpa** [comment]
Not that easy to do it without lodash, going to keep it this way, if someone has any simple solution please me a PR.

**Comment by rafaelpimpa** [comment]
Somewhat related to #49

**Comment by ismet** [comment]
I'm having the same problem.. In my current project, I wanted to give buefy a try, and completed most of the project using it. Now, I'm stuck, I didn't know buefy was not able to accept nested props in data tables.. 

I really wonder if it is really hard to implement..

**Comment by robsontenorio** [comment]
currently only  element-ui framework support nested syntax. But it is not responsive, neither "bulma friend" because it has own css. 

Right now , for buefy, i think the workaround is "format" prop

**Comment by rafaelpimpa** [comment]
Guys, take a look at the #49 as I said.

**Comment by ismet** [comment]
Hi @robsontenorio,

That workaround seems ok, but sorting doesn't work for such columns. I think, sorting is based on "field" not "format", so it can not figure out how to compare two objects..
