### ISSUE TITLE
Taginput not compatible with addons

### ISSUE THREAD

**Issue by gkinsman** [rafaelpimpa/buefy#512]
### Overview of the problem
Taginput does not display correctly when used with addons

**Buefy** version: 0.6.2
**Vuejs** version: 2.5.13
**OS/Browser**: Chrome

### Description
It looks like the addons don't account for the additional height of the taginput due to its tags:

![image](https://user-images.githubusercontent.com/130231/34545865-88e66d3a-f13b-11e7-9d7c-4a8fa8c2836d.png)

### Steps to reproduce
https://jsfiddle.net/0afsyg9v/63/

### Expected behavior

The addons should work like with other fields 

### Actual behavior

See above image

**Comment by jtommy** [comment]
Double https://github.com/rafaelpimpa/buefy/issues/481

**Comment by gkinsman** [comment]
Not sure this is a double of the other issue sorry. The other issue mentions default sizes, whereas this one is about using add-ons with the tag input - if enough tags are added to cause a wrap, add-ons should increase in size so as to match the height of the input. 

I've worked around it for now with CSS hacks, but it would be nice for it to work out of the box :)

**Comment by jtommy** [comment]
@gkinsman Addons mode doesn't change the size of tag (input, select, ...). So your request it's the same of the other issue.
