### ISSUE TITLE
Detailed b-table throws duplicate keys detected error

### ISSUE THREAD

**Issue by teryngull** [rafaelpimpa/buefy#514]
### Overview of the problem

**Buefy** version: 0.6.2
**Vuejs** version: 2.5.13
**OS/Browser**: Chrome, Firefox, and IE11

### Description

When using the detailed table from the examples (https://buefy.github.io/#/documentation/table), there is a console error when expanding the rows. The error is:

[Vue warn]: Duplicate keys detected: '0'. This may cause an update error.
found in
---> <BTable>

### Steps to reproduce

1. Copy sample code from the table section of the documentation for the detailed table.
2. Open the developer's console window.
3. Expand one of the rows.
4. See the console error as stated above.

### Expected behavior

No console errors should happen when expanding to see the detailed row of the table.

### Actual behavior

Console error was displayed:
[Vue warn]: Duplicate keys detected: '0'. This may cause an update error.
found in
---> <BTable>

![2018-01-05_12-21-12](https://user-images.githubusercontent.com/27399690/34620306-08adf1e6-f213-11e7-90d0-755dbda39e1a.png)

**Comment by rafaelpimpa** [comment]
This is fixed in dev branch, fixed for next release

**Comment by StanislavBerezin** [comment]
I face the same issue :(

**Comment by bwayne2015** [comment]
Facing the Same Issue Here
