### ISSUE TITLE
<b-radio-button> matching v-model and native-value doesn't work with integers

### ISSUE THREAD

**Issue by cvgeldern** [rafaelpimpa/buefy#517]
### Overview of the problem

**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.13]
**OS/Browser**: Windows 10 Pro / Chrome 63

### Description

Binding `<b-radio-button>` component using `v-model` attribute does not work with integer values, while `<b-radio>` component or string values do. Using `v-model` or `v-model.number` don't make a difference (on both working `<b-radio>` and not working `<b-radio-button>`). Also removing double quotes on `native-value` attribute value doesn't make a difference.

```
...
data () {
  return {
    batchInvoice: 1
  }
},
...
```

Not working (first radio button is not checked):
```
<b-field>
  <b-radio-button v-model="batchInvoice" native-value="1">
    <span>Yes</span>
  </b-radio-button>
  <b-radio-button v-model="batchInvoice" native-value="0">
    <span>No</span>
  </b-radio-button>
</b-field>
```

Working (first radio is checked):
```
<b-field>
  <b-radio v-model="batchInvoice" native-value="1">
    <span>Yes</span>
  </b-radio>
  <b-radio v-model="batchInvoice" native-value="0">
    <span>No</span>
  </b-radio>
</b-field>
```

### Steps to reproduce

1. Have a `<b-radio-button>` component in a template and bind data to it using the `v-model` attribute
2. Set an integer as data value

### Expected behavior

The appropriate `<b-radio-button`> should become checked if it's `native-value` attribute value matches it's `v-model` attribute value, even if the `v-model` value is an integer.

### Actual behavior

The appropriate `<b-radio-button>` doesn't become checked if it's `native-value` attribute value matches it's `v-model` attribute value if the `v-model` value is an integer.

**Comment by tridcatij** [comment]
@cvgeldern 
Try this one:
```
<b-field>
  <b-radio v-model="batchInvoice" :native-value="1">
    <span>Yes</span>
  </b-radio>
  <b-radio v-model="batchInvoice" :native-value="0">
    <span>No</span>
  </b-radio>
</b-field>
```

**Comment by jtommy** [comment]
@cvgeldern `native-value="1"` is a string attribute and you have to bind it as@tridcatij example.

**Comment by cvgeldern** [comment]
@tridcatij 

Thanks, it works! 

Still doesn't explain why `b-radio` does work without the : binding? But that's not my issue  ;)
