### ISSUE TITLE
DatePicker, unessesary data

### ISSUE THREAD

**Issue by StanislavBerezin** [rafaelpimpa/buefy#526]
I was working with buefy and facing some problems with date picker, not really sure how to solve it. 

                <span>
           <b-datepicker
                inline
               v-model="date" 
               :events="events"
               indicators="bars"
               >
            </b-datepicker>
         </span>

but if i try to display {{date}}
it shows me this weird ISO string "2018-01-11T14:00:00.000Z" ,
The question is how to remove that useless part "T14:00:00.000Z"

**Comment by jtommy** [comment]
@StanislavBerezin You have to format `Date` object. You can format it by Date object methods (`getFullYear(), getMonth(), ...`) or with other lib, for example `moment`.

**Comment by StanislavBerezin** [comment]
but it still not workig correctly if u do getFullYear() or other stuff, it still shows that weird ISO stuff and the entire calendar breaks

**Comment by jtommy** [comment]
@StanislavBerezin Try {{date.getFullYear()}}. What do you see ?

**Comment by StanislavBerezin** [comment]
i see the logic
just need to write something like
   
          <p>{{date.getFullYear()}} / {{date.getMonth()+1}} / {{date.getDate()}}</p>

maybe will help somebody in the future :)
