### ISSUE TITLE
Vuex & Modal system not working together...

### ISSUE THREAD

**Issue by darkylmnx** [rafaelpimpa/buefy#528]
### Overview of the problem

**Buefy** version: [2.4.0]
**Vuejs** version: [2.5.13]
**OS/Browser**: Chrome

### Description
Using Vuex state / getters with the modal sync creates problems and when not using sync the background isn't closable.

### Steps to reproduce
1. Create a Vue project and include (Vuex + Buefy)
2. Create a store with a single state property **modal** set to false
3. Create a button or whatsoever that commits a mutation to the store's state property **modal**
4. Map the state to a computed property used to show / hide the buefy modal

### Expected behavior
I expect it to work without errors

### Actual behavior
I get an error saying that a computed property can't be used by sync if it doesn't have a setter, which makes using the sync system unuseful if each time i have to create a setter, and also creates a bug with the Vuex mutation handler

I think listening / sending to a close event would be better than using sync to toggle the modals. Is it something you could consider ?

**Comment by rafaelpimpa** [comment]
``.sync`` is just a syntax sugar for:

```html
<b-modal :active="isActive" @update:active="value = isActive = value">
```

ref: https://vuejs.org/v2/guide/components.html#sync-Modifier

**Comment by darkylmnx** [comment]
Well i know that, but i mean why not just use a **close** event, because using the update event makes me create a function each time which ends up like this 
`<b-modal :active="isActive" @update:active="value => (value == false && $store.commit('closeModal'))">`

And this can be event longer depending on how i use my store when i have many modals. While something like this : 
`<b-modal :active="isActive" @close="$store.commit('closeModal')">`
is much more clear

**Comment by rafaelpimpa** [comment]
Why not just add a setter to a computed variable to close the modal?

```javascript
computed: {
    isFullScreen: {
        get() {
            return this.$store.getters['settings/isFullScreen']
        },
        set(value) {
            this.setFullScreen(value)
        }
    }
}
```

**Comment by jarridb** [comment]
Not sure if it is a further bug but when I gave your suggestion about adding a setter to a computed variable to close the modal, the esc was still bound and will open and close the modal.
