### ISSUE TITLE
feature request: allow b-datepicker to sit on top of page

### ISSUE THREAD

**Issue by lukio3** [rafaelpimpa/buefy#530]
### Overview of the problem

**Buefy** version: 4.0.5
**Vuejs** version: 4.0.5
**OS/Browser**: Chrome Version 63.0.3239.84 (Official Build) (64-bit)

### Description

Feature request: Allow b-dropdown element within b-datepicker to sit on top of page content (i.e. position: fixed in css terms rather than position: relative). This is how the native html5 datepicker input responds.

### Steps to reproduce

Place date picker within bulma nav bar

### Expected behavior

Date picker dropdown overlays the page and can be seen like the native component:

![image](https://user-images.githubusercontent.com/21043078/34921105-7a1cd04a-f975-11e7-96fb-637d97fe4d53.png)

### Actual behavior

Date picker dropdown is hidden within the nav. Must scroll down within the nav bar to see dropdown.

![image](https://user-images.githubusercontent.com/21043078/34921116-997a2e38-f975-11e7-8674-d09c86bf0931.png)

If there is a way to achieve this using v-bind:style on the datepicker component I am all ears. I couldn't figure out a way to do so without dissecting the component?

**Comment by jtommy** [comment]
@lukio3 Could you provide  your code or an example ? By a quick example it works (see in desktop mode) https://jsfiddle.net/ynpmmbq2/

**Comment by lukio3** [comment]
Hi @jtommy 

Thanks for coming back to me. I can now see that it works in your example

I was using the depreciated nav from bulma as a base. And when I put the datepicker inside the 'nav-right nav-menu' div I was getting the result as pictured.

I can see it works on the new nav from bulma; which is the same version as in your example, by placing in 'nav-end'.

I'll update to the new nav. 

many thanks

Luke
