### ISSUE TITLE
Trouble with coma key (188) on taginput

### ISSUE THREAD

**Issue by MMysiv** [rafaelpimpa/buefy#531]
Hi guys!
There is some trouble with the taginput. It's ok for eng language, but when I try to write tags on russian/ukrainian languages and press key "," its add tag instead of add russian/ukrainian letter "Б" to the input field. 
I highly recommend to delete **event.keyCode === 188** from the source code in TagInput.vue on 202 string.

**Comment by jtommy** [comment]
@MMysiv We might add a new prop to set an array of key codes to use as tag separator. In this way you can remove o add default key codes.

**Comment by MMysiv** [comment]
It would be great! I'll look forward to it.
