### ISSUE TITLE
detailed row table sample in Buefy site giving error of duplicate keys detected

### ISSUE THREAD

**Issue by ibanzajoe** [rafaelpimpa/buefy#532]
### Overview of the problem

**Buefy** version: [0.6.1]
**Vuejs** version: [2.5.13]
**OS/Browser**: Chrome

### Description
Console Error: 
vue.common.js:580 [Vue warn]: Duplicate keys detected: '0'. This may cause an update error.

### Steps to reproduce
1. First Step
  copy the sample code for "detailed row" tables in Buefy website: https://buefy.github.io/#/documentation/table
2. Second Step
  paste the sample code into your code and Run
3. and so on...
### Expected behavior

No Errors

### Actual behavior

vue.common.js:580 [Vue warn]: Duplicate keys detected: '0'. This may cause an update error.

**Comment by bathyscaaf** [comment]
Having the same issue - there was a similar thread closed a few days ago, saying it was fixed in the dev branch and coming next release.

Here it is: https://github.com/rafaelpimpa/buefy/issues/514

**Comment by jtommy** [comment]
Fix https://github.com/rafaelpimpa/buefy/commit/c1eef40a7d661a932d0e834ef8b3b452c6320e94
