### ISSUE TITLE
Tabs below content

### ISSUE THREAD

**Issue by Dave3of5** [rafaelpimpa/buefy#537]
Bit of a longshot but is there anyway of positioning the tabs below the content in the tab container or is this totally out of the hands of buefy ?

**Comment by Dave3of5** [comment]
Anyone have any ideas on this ?

**Comment by jtommy** [comment]
@Dave3of5 It's no possibile.. 
You might play with `.tabs` and `.tab-content` class (for example: position absolute and set top and bottom) or move the first classs under the second by javascript.

**Comment by Dave3of5** [comment]
ok @jtommy thanks.
