### ISSUE TITLE
Triggering focus on Buefy components using directives

### ISSUE THREAD

**Issue by lukio3** [rafaelpimpa/buefy#539]
### Overview of the problem

Unable to trigger 'focus' on buefy components through directives.

**Buefy** version: 0.6.2
**Vuejs** version: 2.5.13
**OS/Browser**: Chrome

### Description

In my project I use directives to trigger 'focus' on components using user actions.

For example, you click an edit button and it focuses an input component on the page.

This works fine for standard bulma components, but I can't figure out a way to do the same for Buefy components. 

### Steps to reproduce

See JsFiddle:

https://jsfiddle.net/lukio3/uLtun3n3/4/

### Expected behavior

Both inputs to 'focus'

### Actual behavior

Only the Bulma input focuses

**Comment by jtommy** [comment]
@lukio3 `b-input` contains as root element a `div` tag, so you have to change your code, for example:
```
'entry-focus': function (el, binding) {
      if (binding.value) {
      	if (el.tagName === 'INPUT') {
        	el.focus()
        } else {
        	el.querySelector('input').focus()
        }
      }
```
A similar case is that https://buefy.github.io/#/extensions/cleavejs

**Comment by lukio3** [comment]
Many thanks @jtommy this worked perfectly.
