### ISSUE TITLE
Add Objects to input type

### ISSUE THREAD

**Issue by lowbits** [rafaelpimpa/buefy#540]
### Overview of the problem

**Buefy** version: 0.6.2
**Vuejs** version: 2.5.7
**OS/Browser**: Mozilla Firefox, Chrome

### Description

I'm trying to bind a type to an `<b-field>`,  but there is an Error.
"Invalid prop: type check failed for prop "type". Expected String, got Object. "

### Steps to reproduce

1. First Step
implement somtehing like 
`<b-field label="E-Mail"  :type="{'is-danger': hasErrors.name}">`

### Expected behavior

I want to bind the errors from my axios post request to my b-field.

### Actual behavior

it actually works but i get errors.

**Comment by jtommy** [comment]
@lowbits At the moment `b-field` accepts a String prop as `type`.
For example, `<b-field label="E-Mail" :type="hasErrors.name? 'is-danger' : ''"`

**Comment by lowbits** [comment]
solved the problem, thank you.
