### ISSUE TITLE
Open/Close Dropdown Programmatically: toggle is not a function

### ISSUE THREAD

**Issue by AlexVFornazieri** [rafaelpimpa/buefy#543]
Hello guys,

I am trying use toggle function of a `<b-dropdown>` element like @rafaelpimpa exemplify in #142, but something weird happens, the log display an error said 'toggle' is not a function.

`
Uncaught TypeError: this.$refs.playitemdrop.toggle is not a function`

In that case 'playitemdrop' is the ref of my `<b-dropdown>` element like follow code:

**The template**
```
<b-dropdown position="is-bottom-left" ref="playitemdrop">
<a class="navbar-item" slot="trigger">
  <b-icon icon="caret-down" class="is-small"></b-icon>
</a>
<b-dropdown-item @click="removeItem(item)">
  <b-icon icon="remove"></b-icon>
  Remover item
</b-dropdown-item>
</b-dropdown>

<a class="button" @click="playitemdropToggle">
  Toggle (in error)
</a>
```

**The script**
`  methods: {
    playitemdropToggle() {
       this.$refs.playitemdrop.toggle();
    },
...
}
`

**Buefy version:** 0.5.4;
**Vue version:** 2.5.13;
**Electron:** 1.8.1;

**Comment by jtommy** [comment]
@AlexVFornazieri I'm trying to replicate it (except electron) https://jsfiddle.net/20vfxux8/. I don't see any errors.

**Comment by AlexVFornazieri** [comment]
@jtommy, thanks for watch,

In fact, in Jsfiddle no error is displayed by clicking in "Toggle (in error)" button like in Electron browser log, but anyway does not have the expected behavior in Jsfiddle either which is make the dropdown's menu items appear as well as clicking "caret-down".

I tried both Chrome and Firefox, the same behavioral fault occurs.

**Comment by grebebird** [comment]
Follow up question: Why does toggle do nothing if "hoverable"? I have a menu showing up on hover, that, when clicks, take a user to a new page. However, the page is rendered without a full page transition, so currently, the dropdown remains displayed until the user moves off of it (while the new pages loads underneath). It's an odd UX interaction. 

The "easy" way to fix this is to make the user click to open the dropdown. In that case, "toggle" works as expected. I wish the source code didn't negate the "toggle" functionality for "hoverable" dropdowns - it's unintuitive. Any chance of a fix for that?

**Comment by slidenerd** [comment]
I double this, hoverable dropdowns dont close unless you move out of the dropdown, this is shoddy UX if left unchecked, any suggestions would be appreciated
