### ISSUE TITLE
[Question] Is the onCancel callback executed when the promp is closed?

### ISSUE THREAD

**Issue by vitogit** [rafaelpimpa/buefy#545]
**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.2]
**OS/Browser**: MacOs, Chrome

### Question

The docs says ```onCancel: Callback function when the dialog is canceled (cancel button is clicked / pressed escape / clicked outside)``` but I think the onCancel is executing even when you execute the onConfirm action (executed when is closed). Is it true? or there is something wrong with my implementation?

```
      this.$dialog.prompt({
          title: `Title`,
          message: `message`,
          inputAttrs: {
              placeholder: 'e.g.'
          },
          cancelText: 'Default',
          onConfirm: (value) => this.start(value),
          onCancel: () => this.start() //default start without value
      })
```

**Comment by jtommy** [comment]
@vitogit Yes, you are right but first `onConfirm` will be invoked.

**Comment by vitogit** [comment]
I think it's a little confusing. What do you think is the best approach? 
Update docs to say that onCancel executes when the promp is closed (after onConfirm). 
Change the name to onClose. 
Update the method ?
I can create a PR if you want

**Comment by jtommy** [comment]
Same request: https://github.com/rafaelpimpa/buefy/issues/599
