### ISSUE TITLE
Autocomplete documentation not up to date

### ISSUE THREAD

**Issue by cobaltway** [rafaelpimpa/buefy#548]
### Overview of the problem

Autocomplete documentation is not up to date with examples and actual code.

### Description

> https://buefy.github.io/#/documentation/autocomplete

**Example:** event is named "select".
**API (bottom of the page):** same event is named "selected".

The correct version is the first one, "select".

Buefy is great & have a nice day!

**Comment by jtommy** [comment]
@cobaltway Thanks! It's already fixed https://github.com/rafaelpimpa/buefy/pull/518
