### ISSUE TITLE
[Feature request] b-table: support hidden toggleDetails

### ISSUE THREAD

**Issue by htfy96** [rafaelpimpa/buefy#551]
# Overview of the problem

**Buefy** version: 0.6.2
**Vuejs** version: all
**OS/Browser**: all
# Description

Currently, when `detailed` is specified in `b-table` component, a 40px-width toggleDetails column is always included in the rendered table. However, in some cases, we would prefer to customize our own way to expand a row (e.g. placing the icon on the right or using text as toggler), where the builtin `toggleDetails` column will be redundant. An option like `detailToggler` will be a great convenience in such cases.

**Comment by jtommy** [comment]
@wanxe What do you think about it ? might be useful ? (keep in mind `bTable` has several slots at the moment...)

**Comment by wanxe** [comment]
I think that we follow's the bulma's styleguide with the paddings and maintaining some consistency.
Feel free to override some styles to adapt into your project. 
In my opinion this change implies that we need to create another slot and create another layer of complexity only for (for the moment) low usecase.

**Comment by kraucy** [comment]
I second and third the need for this.
