### ISSUE TITLE
B-Table not checking rows programatically

### ISSUE THREAD

**Issue by evandroabukamel** [rafaelpimpa/buefy#552]
**Buefy** version: 0.6.2
**Vuejs** version: 2.5.13
**OS/Browser**: Windows / Chrome 63

### Description

In a checkable table rows, the checkbox are not checked programatically .

### Steps to reproduce

Follows the story: I have a B-Table loaded from the back-end, then I check one row and it is saved in some table. After that I want to read the register, load the table and see this row checked again, but this doesn't happen, the checkedRows prop is setted like before but the checkbox isn't checked.

### Expected behavior

The checkbox should be checked if we set the checkedRows prop.

### Actual behavior

The checkbox of the checked rows are not checked programatically.

![image](https://user-images.githubusercontent.com/6452880/35335433-beb9e358-00fc-11e8-96b6-09a246df406a.png)

I think that should be an easier way to do that, maybe using a row key or an index, instead of all the row data.

Thanks.

**Comment by jtommy** [comment]
@evandroabukamel Did you see `custom-is-checked` prop ?

**Comment by evandroabukamel** [comment]
Yes, I did, but its use is not clear to me.

I will give it a try.

Thanks.

**Comment by jtommy** [comment]
@evandroabukamel Yes maybe it might quite trivial. Anyway it's a function to compare two rows, the first parameter it's an element of checked rows and the second is a visible row. 
For example: `custom-is-checked=(a, b) => { return a.id === b.id }` if your object (row) key is only `id` field.

**Comment by evandroabukamel** [comment]
Oh, thanks, it worked.

But now I'm having a problem with the sorting and it is not related with this issue.   :-(

**Comment by miraagee** [comment]
Is there a similar way for is-selected?
Like. `:custom-is-selected="(a, b) => { return a.name === b.name }"` ?
I have a selected object before the user clicks on one of the elements, but its not applying the "is-selected"-class on that row. Similar behaviour as the problem of [evandroabukamel]. The custom-is-checked helped me as well.
