### ISSUE TITLE
Getting values for time-picker

### ISSUE THREAD

**Issue by StanislavBerezin** [rafaelpimpa/buefy#553]
I'm tryin to get the values of a timepicker

            <b-field label="Available from">
            <b-timepicker placeholder="Click to select..." icon="clock" :hour-format="format" v-model="set.from">
            </b-timepicker>
          </b-field>

Is there a way i can record the time a user has picked? 

In my data() i have this

        set:{
          from: new Date,
          to: new Date,
        
        },

but if i try to save set, it saves all of the weird strings that are no usefull for me at all. I tried to do the following in data()
   
    from: new Date().getHours(),

but doesnt work and gives errors. So how can i save the hours and minutes precisely in my data? is it even possible>

**Comment by jtommy** [comment]
@StanislavBerezin I don't understand very well your request. 
Your variable `set.from` is a Date object and by `v-model` you have the current time. 
What is your need ?

**Comment by Pilfer** [comment]
`npm install moment --save`  

```<b-timepicker v-model="postTime" placeholder="Select Time" icon="clock-o" hour-format="12"></b-timepicker>```  

And a little later:  

```
import moment from 'moment'
....
methods: {
    getHours () {
        return moment(this.postTime).hour()
    }
}
```

**Comment by lsbyerley** [comment]
@Pilfer i think you meant to put `v-model="getHours"`

**Comment by StanislavBerezin** [comment]
I have the code 

        <b-field label="Available from">
        <b-timepicker placeholder="Click to select..." icon="clock" :hour-format="format" v-model="set.from">
        </b-timepicker>
      </b-field>

So when a user chooses the time, like lets say 12-00AM. THe only thing that i want to get is "12-00AM", not the date, no weird strings, nothing else but plain simple "12-00AM". But with this component its quite unclear how to get JUST the time, coz it keeps giving weird strings. Like on Buefy website it says "TIMEPICKER" so if i pick 12-00AM, then i guess it should give me 12-00AM right?

**Comment by jtommy** [comment]
@StanislavBerezin Timepicker use a Date object as value. 
When user choose a time you have to use a custom function or use a lib (for example moment) to parse Date object to String.
The format that you decide to use it's only for Timepicker view.
A similar behaviour for Datepicker.
