### ISSUE TITLE
Font-Awesome v5+

### ISSUE THREAD

**Issue by gugarosa** [rafaelpimpa/buefy#554]
### Overview of the problem

**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.2]

### Description

First of all I would like to appreciate all the work and effort done in buefy. It works like a charm!

Although, one thing that it was missing or I have missed in the documentation regards to Font-Awesome versions 5+. Is there any support to them yet?

I mean, I could not find how to import for instance a `far | fas` class with `<b-icon>`. If you use `<i>` tags it works like it should be, but without the pre-formatting that `<b-icon>` offers.

**Comment by gugarosa** [comment]
Nevermind, I found out you can pass a `customClass` argument to `<b-icon>`, which will solve the problem.

**Comment by jtommy** [comment]
@gugarosa In the next release will add support about it!

**Comment by Herteby** [comment]
So FontAwesome is now supported! :tada:
No documentation on how you use it though :sweat_smile:
Is it the font-version or svg, and is it possible to import fa5 svg icons individually (like you can with [fontawesome-vue](https://github.com/FortAwesome/vue-fontawesome)) to reduce bundle size?

**Comment by jtommy** [comment]
@Herteby New icon pack `fas` (or `fab`, `far`) and it works as previous version.

**Comment by kevinhofmaenner** [comment]
I am using vue-fontawesome and fontawesome5 pro which renders the icons as svgs. I cannot get buefy to play along nicely. Am I doing something wrong or is there no support for fontawesome5 pro svg icons?

**Comment by Herteby** [comment]
@kevinhofmaenner Yeah Buefy only supports the webfont icons.
I actually experimented with overriding Buefy's icon component with one that used FontAwesome's SVG icons instead. It worked fairly well actually. I decided to abandon it for the moment though, in favor of keeping it simple, as the font is just 300kb anyway.

**Comment by kevinhofmaenner** [comment]
Thanks @Herteby for the quick reply!

For anyone looking for a solution, this is what I ended up doing. I wanted the fal pro icons (light) but am using vue-fontawesome which is currently incompatible with buefy.

I followed the instructions provided by fontawesome in regards to using their fa5 web fonts (https://fontawesome.com/get-started/web-fonts-with-css)

I brought over the following files into a static directory.

- fontawesome-all.css
- fa-light-300.eot
- fa-light-300.svg
- fa-light-300.ttf
- fa-light-300.woff
- fa-light-300.woff2

I then told Buefy to use the default icon pack of 'fal' in my main.js file.

`Vue.use(Buefy, { defaultIconPack: 'fal' });`

Finally, I made sure in my index.html to add

`<link rel="stylesheet" href="/static/icons/fontawesome/fontawesome-all.css">`

**IMPORTANT:**  Also, make sure you are using 0.6.3 or later.

**Comment by Herteby** [comment]
@kevinhofmaenner You can also just import the webfonts from the NPM package :smile: 
```
import '@fortawesome/fontawesome-pro-webfonts/css/fontawesome.css'
import '@fortawesome/fontawesome-pro-webfonts/css/fa-light.css'
```
Took me a while to figure out as they didn't mention it in the docs.

**Comment by jtommy** [comment]
@Herteby At this link https://buefy.github.io/#/documentation/start we specified `Please note that Buefy doesn't include icon packs. You have to import it as you prefer (NPM, CDN, ...)`.

@kevinhofmaenner Thanks!

**Comment by Herteby** [comment]
@jtommy Ah sorry, by "the docs" I meant FontAwesome's docs. Their "Use with NPM" page only talks about the SVGs and didn't mention that the webfonts are also available there.

**Comment by Stefdv** [comment]
As a total beginner ( vue AND buefy ;p ) i would really appreciate if someone could post some code on how to setup buefy with fontawesome 5,  like where to put the imports . Does the phrase  `Please note that Buefy doesn't include icon packs. You have to import it as you prefer (NPM, CDN, ...).` mean that buefy/bulma doen't have any icons at all ?

**Comment by MeikelLP** [comment]
@Stefdv I achieved it via these to lines in my main.js
```js
import '@fortawesome/fontawesome-free-webfonts/css/fa-solid.css'
import '@fortawesome/fontawesome-free-webfonts/css/fontawesome.css'
```

**Comment by nerdoc** [comment]
This is deprecated because you have to use `fontawesome-free` now. I still don't get it how to use FA wieh Buefy. Any further hints for the newest version?

**Comment by jtommy** [comment]
@nerdoc Did you see our docs code? https://github.com/buefy/buefy/blob/dev/docs/assets/scss/main.scss

**Comment by jtommy** [comment]
Do you try import CSS files as we do with SCSS ?

**Comment by nerdoc** [comment]
With Js you can import css files as well. I do that with others too:

    import 'buefy/dist/buefy.css'

And it works. But I don't want to misuse this issue tracker here for a "forum" help - just thought that this was not updated to  FA5...

**Comment by jtommy** [comment]
Yes, sure.
FA5 is supported but we don't import it because every devs might import as he/she want (CSS, SCSS,...)

**Comment by nerdoc** [comment]
Then I have another issue importing it. Thanks anyway - I'll find out...

**Comment by lajosbencz** [comment]
Passing in the pack as an option to the constructor does not work for me:

```js
// main.js

import '@fortawesome/fontawesome-free/css/solid.css'
import '@fortawesome/fontawesome-free/css/fontawesome.css'

import Buefy from 'buefy';
Vue.use(Buefy, {
  defaultIconPack: 'fas',
});
```

However, importing the config and explicitly setting it works.

```js
// main.js

import '@fortawesome/fontawesome-free/css/solid.css'
import '@fortawesome/fontawesome-free/css/fontawesome.css'

import Buefy from 'buefy';
Vue.use(Buefy);
import config from 'buefy/src/utils/config'
config.defaultIconPack = 'fas';
```

**Comment by admorphit** [comment]
@lajosbencz there's a typo in your import statements- should be fo`n`tawesome, not fo`r`tawesome?

**Comment by pnowy** [comment]
To sum up a discussion I will short working example from me:

// package.js

`"@fortawesome/fontawesome-free": "^5.5.0",`

// main.js

```js
import Buefy from "buefy";
import "@fortawesome/fontawesome-free/css/all.css";
import "@fortawesome/fontawesome-free/css/fontawesome.css";
Vue.use(Buefy, {
  defaultIconPack: "fas"
});
```

// component
`<b-icon icon="file-code" />` // for solid icons use default pack
`<b-icon icon="github" pack="fab" />` // for brands you have to define pack brands (different than default)

**Comment by chrtz** [comment]
When I include Fontawesome this way everything works nice in the dev mode.
But when I bundle everything with webpack/vue-cli - the icons are missing. (failed to load resource .woff 404) any clue how to fix this?

**Comment by shelru** [comment]
1) npm i @fortawesome/fontawesome-free -save
2) ```import Buefy from 'buefy';
import "@fortawesome/fontawesome-free/css/all.css";
import "@fortawesome/fontawesome-free/css/fontawesome.css";

import 'buefy/dist/buefy.css';

Vue.use(Buefy, {
    defaultIconPack: 'fab',//fas, far for pro pack's
});```

**Comment by dgattey** [comment]
> @kevinhofmaenner Yeah Buefy only supports the webfont icons.
> I actually experimented with overriding Buefy's icon component with one that used FontAwesome's SVG icons instead. It worked fairly well actually. I decided to abandon it for the moment though, in favor of keeping it simple, as the font is just 300kb anyway.

Any chance you could share this? I'd love to get it working with SVG icons since we use that elsewhere and I don't want to swap everything over to webfonts just to get Buefy working :(

**Comment by Herteby** [comment]
Hmm don't really remember how I did it. If you look here though it looks
like you can inject your own custom icon component:
https://buefy.org/documentation/constructor-options

Den ons 4 sep. 2019 kl 20:32 skrev Dylan Gattey <notifications@github.com>:

**Comment by jtommy** [comment]
@dgattey you might use vue-fontawesone but in the last release there is an issue. Please follow this https://github.com/buefy/buefy/issues/1730 that contains a workaround waiting a new release

**Comment by dgattey** [comment]
Thanks @Herteby @jtommy! 
```
import { library } from '@fortawesome/fontawesome-svg-core'
import { fab } from '@fortawesome/free-brands-svg-icons'
import { fas } from '@fortawesome/pro-solid-svg-icons'
import { far } from '@fortawesome/pro-regular-svg-icons'
import { fal } from '@fortawesome/pro-light-svg-icons'
import { fas as freeFas } from '@fortawesome/free-solid-svg-icons'
import { far as freeFar } from '@fortawesome/free-regular-svg-icons'
import { FontAwesomeIcon, FontAwesomeLayers } from '@fortawesome/vue-fontawesome'

library.add(fab)
library.add(fas)
library.add(far)
library.add(fal)
library.add(freeFas)
library.add(freeFar)

Vue.component('font-awesome-icon', FontAwesomeIcon)
Vue.use(Buefy, {
  defaultIconComponent: FontAwesomeIcon,
  defaultIconPack: 'far',
})
```
This seems to work perfectly - I think I was trying it before when I was on an older version of Buefy and that's why it didn't seem to work. Updating to latest solved it. woohoo!

**Comment by tomgif** [comment]
@dgattey you have typo in your example - should be 'fontawesome' instead of 'fortawesome'

**Comment by Stetzon** [comment]
changing
> ```js
> defaultIconComponent: 'vue-fontawesome',
> ```
to
> ```js
> defaultIconComponent: FontAwesomeIcon,
> ```
did the trick!  Thank you!
