### ISSUE TITLE
[Feature Request] Multiselect with dropdown options

### ISSUE THREAD

**Issue by papakay** [rafaelpimpa/buefy#556]
Great job with this.

Please I was thinking it would be nice if we have a multi-select with dropdown options. This will really help in situation where the options are really long.

Thank you.

**Comment by jtommy** [comment]
@papakay Thanks. An example about your request?

**Comment by papakay** [comment]
Please see the selectize multi-select example in the link below

https://selectize.github.io/selectize.js/

**Comment by jtommy** [comment]
What is multi-select example ? Anyway it's like 'b-taginput` component, isn't it ?

**Comment by papakay** [comment]
Please i think the link below makes it more clearer.

https://at-ui.github.io/at-ui/#/en/docs/select

You can see how the multiple select has been rendered compared to 

https://buefy.github.io/#/documentation/select

**Comment by jtommy** [comment]
You might combine new autocomplete prop `open-on-focus` with `b-taginput`. For example https://codepen.io/anon/pen/jZbpvz?&editors=101

**Comment by papakay** [comment]
Wow this is awesome! You are the best. I like your approach. It's so nice.

Thank you immensely for this great information.
