### ISSUE TITLE
[Feature Request] Codeview component

### ISSUE THREAD

**Issue by lauthieb** [rafaelpimpa/buefy#557]
Hello guys,

I would like to know if the component "Component.vue" will be available in the library ?

**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.13]
**OS/Browser**: Chrome

Thanks a lot.

**Comment by rafaelpimpa** [comment]
No, that is used only for the docs, you can copy and use it if you will :)

**Comment by lauthieb** [comment]
Ok, I understand, thanks a lot for your library ;)
