### ISSUE TITLE
[Question] Datepicker using a computed date for v-model

### ISSUE THREAD

**Issue by lsbyerley** [rafaelpimpa/buefy#558]
**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.2]
**OS/Browser**: MacOs, Chrome

### Question

I am using the Datepicker component on a scoreboard page. The scoreboard data is loaded by axios in the store and contains games and a scoreboard date. When the scoreboard data is loaded, I set the v-model to the scoreboard date. Since there is no event firing on selecting a date,  I'm trying to use a watcher to load a different date of games when the datepicker is used. I have attempted to do this with a computed value.. however i get warnings about no setter for scoreboard date and the watch method fires twice on page load.. but not at all after changing the date. Any help is appreciated

```
<template>
  <b-datepicker
    v-model="scoreboardDate"
    :focused-date="scoreboardDate"
    :loading="!allDataLoaded"
    icon-pack="fa"
    icon="calendar"
  >
  </b-datepicker>
</template>

<script>
export default {
  computed: {
    ...mapState([
      "ratingsLoaded",
      "scoreboardLoaded",
      "scoreboardError",
      "scoreboard",
    ]),
    allDataLoaded() {
      return (this.scoreboardLoaded && this.ratingsLoaded)
    },
    scoreboardDate() {
      return (this.allDataLoaded) ? moment(this.scoreboard.date, 'YYYYMMDD').toDate() : new Date()
    }
  },
  watch: {
    scoreboardDate: function() {
      console.log('date changed')
    }
  }
}
</script>
```

**Comment by jtommy** [comment]
@lsbyerley `v-model` provide a two way binding and in your case you have to add a set function otherwise you might use `:value` instead of `v-model` and listen `@input` event instead of watch.
```
<b-datepicker
    :value="scoreboardDate"
    @input="(date) => { ... } or method"
    :focused-date="scoreboardDate"
    :loading="!allDataLoaded"
    icon-pack="fa"
    icon="calendar"
  >
</b-datepicker>
```

**Comment by lsbyerley** [comment]
@jtommy Thanks for the response.. Ideally I'd like to use a method so that I can trigger some store commits to get the different scoreboard date data. I'm getting undefined in my method though

`@input="changeScoreboardDate(date)"`

```
methods: {
changeScoreboardDate(date) {
  console.log(date) //undefined
}
```

**Comment by jtommy** [comment]
@lsbyerley Please remove `date` parameter on input method binding, `@input="changeScoreboardDate"`

**Comment by lsbyerley** [comment]
@jtommy Ah, I'm dumb.. awesome, thanks for your help!
