### ISSUE TITLE
icon not display

### ISSUE THREAD

**Issue by lizhongyi** [rafaelpimpa/buefy#559]
### Overview of the problem

**Buefy** version: [0.6.2]
**Vuejs** version: [2.5.X]
**OS/Browser**: chrome

### Steps to reproduce

![image](https://user-images.githubusercontent.com/3292807/35468600-91ef9748-035c-11e8-9b70-46b3cb19c975.png)

**Comment by avrong** [comment]
Can you show the example code? What is the font pack?

**Comment by bsecker** [comment]
Also having this issue. Icon pack is the default (mdi).

Relevant code:
`    <b-icon
      icon="home">
    </b-icon>`

with Buefy 0.6.2 and firefox.

**Comment by jtommy** [comment]
Did you import mdi ?

**Comment by bsecker** [comment]
oops, yep that solved my problem. cheers

**Comment by robertpro** [comment]
I am having the same problem, how do I import mdi?

**Comment by lvbirui** [comment]
i import the mdi in main.js, but the icon still can not display. so what should i do?
