### ISSUE TITLE
New Table doesn't allow non-selectable rows

### ISSUE THREAD

**Issue by adamkelso-rg** [rafaelpimpa/buefy#57]
The new template syntax for tables is great, but it now requires a `:selected` prop on the component. There are times when I'd like for table's rows not to be selectable but still would like most other features on the component.

If no `:selected` prop is synced on the table, clicking a row throws an `Uncaught TypeError: Cannot read property 'row' of undefined` error from the last `$emit` statement in the following code block.

```js
selectRow: function selectRow(row, index) {
    this.$emit('click', row);

    if (this.selected === row) return;

    this.$emit('update:selected', row);

    this.$emit('select', row, this.selected.row);
}
```

**Comment by rafaelpimpa** [comment]
I've fixed this already, gonna wait a little more before releasing a patch.
