### ISSUE TITLE
Timepicker: Only hours possible?

### ISSUE THREAD

**Issue by wdj-ac** [rafaelpimpa/buefy#572]
Hi and thanks for this awesome package!
I am nearly done with a webinterface for industrial machines. Everything is done with Buefy an Chartjs. 
Now I need a timepicker to only select hours and hide the minutes option. Is there a way to achieve this?

BTW: This would be even a nice feature in the datepicker (disable days, disable months, disable year)

**Comment by jtommy** [comment]
About Datepicker we might add a prop to disable year and month. No plans about a Timepicker with only hours select.
