### ISSUE TITLE
How to add canCancel to loading that is opened programmatically

### ISSUE THREAD

**Issue by johnpyp** [rafaelpimpa/buefy#574]
I'm trying to add the canCancel prop to a programmatically opened Loading like this:

```js
      this.loadingComponent = this.$loading.open({
        props: {
          canCancel: true
        }
      })
```
This is the same syntax as how the modals add props programmatically, but it doesn't work for loadings and there isn't anything in the docs about it.

**Comment by jtommy** [comment]
```
this.$loading.open({
     canCancel: false
})
```

**Comment by johnpyp** [comment]
Oh ok, I assumed it had the "props" syntax. Is there any kind of event listener I can use for the loader? For example when it closes, will it fire an event?

**Comment by jtommy** [comment]
Yes close event
