### ISSUE TITLE
Checked example on table in the documentation doesn't work

### ISSUE THREAD

**Issue by adamkelso-rg** [rafaelpimpa/buefy#58]
On the documentation site, the column of checkboxes in the table no longer work. The column appears when the switch is toggled on, but then clicking a checkbox no longer does anything, from either a row or the select all checkbox in the header row.

**Comment by rafaelpimpa** [comment]
Which browser? version? OS?

**Comment by adamkelso-rg** [comment]
Lol. Yes, it was Chrome on Windows 10. Tried it just now in Firefox, no issues.
