### ISSUE TITLE
file upload component broken when using 'accept' property

### ISSUE THREAD

**Issue by chiayutsaipersonal** [rafaelpimpa/buefy#580]
**Buefy** version: [0.6.3]
**Vuejs** version: [2.5.13]
**OS/Browser**: windows 10 /chrome 63.0.3239.132

### Description

after update from 0.6.2 to 0.6.3, file input seems to be broken if 'accept' property is used

### Steps to reproduce
1.  make a file upload input button WITHOUT setting the accept property
![image](https://user-images.githubusercontent.com/19500698/35786433-29567f46-0a62-11e8-97a4-ace6aed96b12.png)

2. console log the variable that holds uploaded file after uploading a file
![image](https://user-images.githubusercontent.com/19500698/35786450-43bc80e2-0a62-11e8-8ce6-a87891bcd9c7.png)

3. the uploaded file exists
![image](https://user-images.githubusercontent.com/19500698/35786474-64c3f3f6-0a62-11e8-9d2a-2971338dba56.png)

4. add accept property to the same control
![image](https://user-images.githubusercontent.com/19500698/35786494-818a2d02-0a62-11e8-9d5c-9fb1ab9ed003.png)

5. result of the console log says the same variable is empty after input event triggers the method
![image](https://user-images.githubusercontent.com/19500698/35786609-5ca64b8c-0a63-11e8-918a-d75f5cb457b6.png)

### Expected behavior

file data should exist in both cases

### Actual behavior

file data does not exist when 'accept' property is being used

**Comment by hemulin** [comment]
Still have some issues here.

> `accept="image/*,.pdf"`

### Uploading image and console.log shows:
```
[File(218479), __ob__: Observer]:
File(218479) {name: "echarts.png", lastModified: 1524175013120, lastModifiedDate: Thu Apr 19 2018 23:56:53 GMT+0200 (CEST), webkitRelativePath: "", size: 218479, …}
length 1
__ob__: Observer {value: Array(1), dep: Dep, vmCount: 0}
__proto__: Array
```

### Uploading pdf and console.log shows:
```
[__ob__: Observer]
```
