### ISSUE TITLE
Dropdown change event firing twice

### ISSUE THREAD

**Issue by dumptyd** [rafaelpimpa/buefy#586]
### Overview of the problem

`b-dropdown`'s `change` event gets fired twice for some reason

**Buefy** version: [0.6.3]
**Vuejs** version: [2.4.4]
**OS/Browser**: Firefox

### Steps to reproduce

http://jsfiddle.net/dumptyd/sepck7mq/6/

Every time you select an item, `num` increases by 2.

**Comment by adrlen** [comment]
Shouldn't the `change` event be fired only if the value actually changed ?

Also, I would like to deselect an item when clicking on it. I can't figure this out without implement it directly in the Dropdown component because of the `v-model` used to determine the selected. Thoughts ?

**Comment by zedrdave** [comment]
@adrlen I know this is quite old, but have you ever figured a way to deselect an item after the event has been fired?
