### ISSUE TITLE
Website breaks on MS Edge & IE

### ISSUE THREAD

**Issue by AngelMunoz** [rafaelpimpa/buefy#6]
Hello
I was just passing by and noticed that the buefy website (docs section) breaks on MS Edge
```
Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063
```
![MS Edge](https://cloud.githubusercontent.com/assets/8684875/24875048/636e0de2-1dec-11e7-83af-d6498f286854.png)

the error says something doesn't support forEach thrown in vendor bundle
perhaps it is related to some ES6+ feature?
but worked fine in other browsers except as well for Internet explorer 11
![Internet Explorer](https://cloud.githubusercontent.com/assets/8684875/24875368/6709a942-1ded-11e7-8b1d-d0eca075b0b9.png)
however internet explorer says it is a syntax error

**Comment by rafaelpimpa** [comment]
Thanks for point out, gonna take a look

**Comment by rafaelpimpa** [comment]
So I could make it work on Edge, but no luck on IE. I'll update the docs later and if someone have any idea on how to fix that IE issue I would love a PR.

**Comment by AngelMunoz** [comment]
hmm IE is always problematic right? I'll try to take a look

**Comment by AngelMunoz** [comment]
I asked the vue-router guys about it perhaps it is a bug; else adding bluebird should work around the issue

**Comment by rafaelpimpa** [comment]
Woa thanks a lot! Didn't know about Bluebird, good to know that this is not a problem with Buefy itself. Gonna update the Browser Support list later ;)
