### ISSUE TITLE
Closable property on bMessage doesn't works properly

### ISSUE THREAD

**Issue by danielschmitz** [rafaelpimpa/buefy#600]
### Overview of the problem

**Buefy** version: [0.6.3]
**Vuejs** version: [2.5.13]
**OS/Browser**: Chrome

### Description

The closable property (bMessage) doesn't works properly.

### Steps to reproduce

https://codepen.io/danielschmitz/pen/XZarRR?editors=1010

### Expected behavior

 The icon must be hidden when `closeable=false`

![image](https://user-images.githubusercontent.com/1509692/36153759-7566c580-10b6-11e8-9c09-cdd335451309.png)

### Actual behavior

Icon its show with `closeable=true` or `closeable=false`

**Comment by adrlen** [comment]
You have to use your prop with **:** as `**:**closeable="false"` to pass a boolean to the component.

https://codepen.io/anon/pen/WMENQR?editors=1010
