### ISSUE TITLE
Can't render Buefy components when customizing Buefy with constructors

### ISSUE THREAD

**Issue by ruust** [rafaelpimpa/buefy#601]
### Overview of the problem

**Buefy** version: 0.6.3
**Vuejs** version: 2.5.13
**OS/Browser**: Google Chrome

### Description
Buefy components fail to load when I attempt to customise Buefy with the constructors instead of using the default values. If it matters, I set this up to work standalone without importing via node or webpack. The components also load without errors if I use `Vue.use(Buefy.default);`

### Steps to reproduce

1) Import the necessary css and js
2) Define the constructors like mentioned in https://buefy.github.io/#/documentation/constructor-options instead of using `Vue.use(Buefy.default);`
3) Insert a Buefy component to your HTML and mount a vue instance to the html

### Expected behavior

Buefy component should appear as expected.

### Actual behavior

Browser throws error on the Buefy element
![cap](https://user-images.githubusercontent.com/20179273/36163610-cf019840-1124-11e8-9bca-991dc04aa0f4.PNG)

**Comment by jtommy** [comment]
@ruust Are using npm or CDN ?

**Comment by ruust** [comment]
@jtommy CDN. Updated my issue description!

**Comment by jtommy** [comment]
Could you provide us your code? Without constructor options is it works?

**Comment by ruust** [comment]
@jtommy Refer to https://jsfiddle.net/am0n1hsj/. Comment out the Constructors and using `Vue.use(Buefy.default);` line would result in the datepicker appearing.

**Comment by jtommy** [comment]
@ruust When you use CDN, you have to use Buefy.default with or without constructor options.
