### ISSUE TITLE
FR: Reverse sorting for Table rows as cards on mobile

### ISSUE THREAD

**Issue by lucasyvas** [rafaelpimpa/buefy#62]
When you have a table, you can click the columns to list the rows in ascending/descending order. If you choose the option to convert table rows to mobile cards, there doesn't seem to be a way I can see to use reverse sorting. The dropdown for sorting naturally has no way of differentiating the intended order as is. I'm wondering if there's something that could be added to allow for toggling the sorting direction, but it's not clear what the best choice would be. Perhaps an arrow next to the drop down that flips direction when pressed?

**Comment by rafaelpimpa** [comment]
You're right there is no current way to sort reverse with collapsed rows. The arrow next to select is actually a good idea tho! Gonna work on that probably.
