### ISSUE TITLE
tables not sorting dates properly

### ISSUE THREAD

**Issue by gwvt** [rafaelpimpa/buefy#67]
### Overview of the problem

**Buefy** version: 0.3.1
**Vuejs** version: 2.3.3
**OS/Browser**: Mac OS/Chrome & Firefox

### Description

The new tables with slotted content are great, thank you! Working perfectly for vue-router links.

But one new issue: when sorting a table by a column containing date objects, if a row contains a null value for the date field the sorting 'breaks' at that row instead of sorting all null values to the beginning/end (for asc/desc sorts). Buefy 0.2.x worked as expected; the issue began when I updated to 0.3.1. Not sure, but could the issue be related to moving the date formatting for the column from a format property in 0.2.x to the v-html directive in 0.3.x?

### Steps to reproduce

Sort a table by a date column with some rows containing null values.

### Expected behavior

Null values for date field will be grouped at beginning of asc sort, and end of desc sort.

### Actual behavior

Sorting by asc/desc works as expected until a row contains a null value, then all other rows are left in original order and not sorted.

**Comment by rafaelpimpa** [comment]
Thanks! Actually it wasn't sorting null values of any types (not only dates).

**Comment by gwvt** [comment]
Awesome, thank you!
