### ISSUE TITLE
User individual components with font-awesome

### ISSUE THREAD

**Issue by darkylmnx** [rafaelpimpa/buefy#73]
### Overview of the problem
Vue ^2.2.6
Buefy ^0.3.2

### Description

How can i use font-awesome while using individual components ? As in you docs you say to do the following :

```
Vue.use(Buefy, {
    defaultIconPack: 'fa',
    defaultContentElement: '#content',
    ...
})
```
but by doing this it enables Buefy for all components not individual.

**Comment by rafaelpimpa** [comment]
To use it with ``b-icon`` you must pass the ``pack`` attribute:

```html
<b-icon icon="search" pack="fa"></b-icon>
```

**Comment by RuslanHasko** [comment]
Same question.

**Overview of the problem**

Vue ^2.2.6
Buefy ^0.3.2

**Description**

In my project I use only tables (with child components for columns and pagination).

As in your docs, I use:

`Vue.use(Buefy, {
    defaultIconPack: 'fa'
})`

But classes for icons have not changed (in pagination component and in table-column component):

`<i class="mdi">chevron_left</i>`

So, how can I fix this?
I do not want to change the default template.

**Comment by rafaelpimpa** [comment]
@RuslanHasko did you import fontawesome to your project? It's nedded.

**Comment by RuslanHasko** [comment]
Yes of course

**Comment by rafaelpimpa** [comment]
I just tested and it's working fine for me 🤔 

``Vue.use(Buefy, { defaultIconPack: 'fa' })`` changes all icons of tables, pagination, message, notifications etc.

If your project is open I could take a look.

**Comment by darkylmnx** [comment]
@rafaelpimpa 

> To use it with b-icon you must pass the pack attribute:

well it's quite cumbersome to do that as i know i'll only use font awesome to add it explicitly on EACH icon...

**Comment by rafaelpimpa** [comment]
That's why you have the option of ``defaultIconPack``.

**Comment by darkylmnx** [comment]
But if I use this options all buefy components are loaded, while I don't
want that.

In terms of component based architecture, I should be able to set a global
config, while still importing components on demand.

I think you should consider adding and option to the Vue install options,
which would be something like : loadAllComponents: false or true.

This gives the possibility to set global options while still keep the
possibility to load all components only of we want to.

Though here the right terme would be "define" components instead of "load"
m, but younger the point

Le 26 mai 2017 16:56, "Rafael Beraldo" <notifications@github.com> a écrit :

That's why you have the option of defaultIconPack.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rafaelpimpa/buefy/issues/73#issuecomment-304304686>,
or mute
the thread

**Comment by rafaelpimpa** [comment]
I see what you want, I didn't get that you are loading by demand. How are you registering the component exactly? If you're importing the non-compiled (from ``src`` folder) you can do this:

```javascript
import config from 'buefy/src/utils/config'
config.defaultIconPack = 'fa' // or any other constructor options
```

**Comment by darkylmnx** [comment]
i'm importing like this : `Vue.component(Buefy.Checkbox.name, Buefy.Checkbox)`
this solution seems nice
