### ISSUE TITLE
[FEATURE] select with icons or dropdown that changes handler

### ISSUE THREAD

**Issue by darkylmnx** [rafaelpimpa/buefy#74]
i came accross a use case where neither the select component nor the dropdown component solves it.

If you are on facebook, you probably came accross the following image 
![image](https://cloud.githubusercontent.com/assets/1426357/26464841/6dd434bc-4189-11e7-9485-734bfbd5409f.png)

It gives you the ability to change the privacy of a post but also explains them. 

Currently, a dropdown would be the way to go (as there is html inside the options), but here's the problem now, when you make your choice, the dropdown handler / trigger does not change value, therefore the user doesn't have feedback on what he choosed.

In this sens, the behaviour seems more like a select, but because of the html issue (icons and stuff) i can't use the select component.

### Api proposal
Could you add on the drop down component a prop **replace** which would be a boolean, and if set, would replace & show the selected dropdown option instead of the handler / trigger.

**Comment by rafaelpimpa** [comment]
Well, I leave the trigger opened for that purpose. You can change the trigger based on the v-model of the dropdown.

**Comment by darkylmnx** [comment]
well i tried something like 
![image](https://cloud.githubusercontent.com/assets/1426357/26496431/cf29c04e-4227-11e7-81bb-92d0860ebcee.png)

and it doesn't seem to work, and btw, why don't you use a slot for html in option ? and use a label attr ? It makes code not really readable

**Comment by rafaelpimpa** [comment]
Could you copy paste your code so I can test?

What you mean by html in option? Give more detailed stuff so I can help you better!

**Comment by darkylmnx** [comment]
sorry, i didn't as it wasn't an issue but a feature request.

i'm using latest vue version and latest buefy version

This is what i'd like to acheive :

```
<b-dropdown v-model="is_public">
        <button class="button is-flat" type="button" slot="trigger">
            <b-icon icon="globe" v-if="is_public"></b-icon>
            <b-icon icon="users" v-if="!is_public"></b-icon>
            <span v-if="is_public">{{ $t('hit_form.public_title') }}</span>
            <span v-if="!is_public">{{ $t('hit_form.private_title') }}</span>
        </button>

        <b-dropdown-option class="columns" :value="true">
          <div class="column">
            <b-icon icon="globe"></b-icon>
          </div>
          <div class="column">
            <h3>{{ $t('hit_form.public_title') }}</h3>
            <p>{{ $t('hit_form.public_text') }}</p>
          </div>
        </b-dropdown-option>
        <b-dropdown-option class="columns" :value="false">
          <div class="column">
            <b-icon icon="users"></b-icon>
          </div>
          <div class="column">
            <h3>{{ $t('hit_form.private_title') }}</h3>
            <p>{{ $t('hit_form.private_text') }}</p>
          </div>
        </b-dropdown-option>
      </b-dropdown>
```

**Comment by rafaelpimpa** [comment]
OK, I've understood now what you want. I didn't allow html in slot for security reasons, but I'll figure it out.

**Comment by darkylmnx** [comment]
Which security reasons ? Maybe I can help through a PR

Le 26 mai 2017 17:14, "Rafael Beraldo" <notifications@github.com> a écrit :

OK, I've understood now what you want. I didn't allow html in slot for
security reasons, but I'll figure it out.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rafaelpimpa/buefy/issues/74#issuecomment-304309193>,
or mute
the thread

**Comment by rafaelpimpa** [comment]
Like receiving the data from the dropdown from a user-generated content.

**Comment by rafaelpimpa** [comment]
Available in next patch:

![dropdown](https://cloud.githubusercontent.com/assets/18370605/26507459/d27bd5a8-4226-11e7-8060-9fa4d9d03a48.gif)

Code is basically the same you discribed:

```html
<b-dropdown v-model="isPublic">
    <button class="button is-primary" type="button" slot="trigger">
        <template v-if="isPublic">
            <b-icon icon="public"></b-icon>
            <span>Public</span>
        </template>
        <template v-else>
            <b-icon icon="people"></b-icon>
            <span>Friends</span>
        </template>
        <b-icon icon="arrow_drop_down"></b-icon>
    </button>

    <b-dropdown-option :value="true">
        <div class="media">
            <b-icon class="media-left" icon="public"></b-icon>
            <div class="media-content">
                <h3>Public</h3>
                <small>Everyone can see</small>
            </div>
        </div>
    </b-dropdown-option>

    <b-dropdown-option :value="false">
        <div class="media">
            <b-icon class="media-left" icon="people"></b-icon>
            <div class="media-content">
                <h3>Friends</h3>
                <small>Only friends can see</small>
            </div>
        </div>
    </b-dropdown-option>
</b-dropdown>
```

**Comment by darkylmnx** [comment]
that's nice :)

**Comment by smokiebacon** [comment]
Great, what I was looking for. However, I can't seem to figure out how to make all the underlying text to show up in a snuggly box. Overflowing texts gets cut off, like so.

<img width="1437" alt="Screen Shot 2019-12-03 at 4 23 15 PM" src="https://user-images.githubusercontent.com/37253660/70101309-5ec8c280-15e9-11ea-9aac-525d08e7a38e.png">

In mobile:
<img width="495" alt="Screen Shot 2019-12-03 at 4 23 31 PM" src="https://user-images.githubusercontent.com/37253660/70101367-83bd3580-15e9-11ea-9b52-e3e75d051004.png">
