### ISSUE TITLE
b-select outputting wrong

### ISSUE THREAD

**Issue by tribakzero** [rafaelpimpa/buefy#75]
**Buefy** version: ^0.2.2
**Vuejs** version: ^2.2.6
**OS/Browser**: MacOS Sierra 10.12.1 / Chrome Beta 59.0.3071.71

I'm trying to do a select with the examples from buefy docs and seems like the options are being outputted in the wrong path, not sure if I'm doing something wrong, I'll attach both actual and expected screenshots.

<img width="720" alt="actual" src="https://cloud.githubusercontent.com/assets/6462719/26474612/a9a43fa8-4177-11e7-83da-38705694792b.png">

<img width="722" alt="expected" src="https://cloud.githubusercontent.com/assets/6462719/26474457/cec3d2c2-4176-11e7-86a5-1a7d71fbfd22.png">

**Comment by rafaelpimpa** [comment]
You must update Buefy.
