### ISSUE TITLE
Rich modal with custom component

### ISSUE THREAD

**Issue by ciaasteczkowy** [rafaelpimpa/buefy#8]
Would you consider adding another modal, that can be open programmatically, where you could pass a component? This would allow to create rich modals (eg. with forms).

**Comment by rafaelpimpa** [comment]
Sure, it's actually on my [backlog](https://github.com/rafaelpimpa/buefy/projects/1). It won't be totally programatically (like Snackbar & Toast) but something like Notification but with methods.

**Comment by ciaasteczkowy** [comment]
That's great! I was wondering if it could look like this:

```javascript
import UserForm from '~components/UserForm'

export default {
  methods: {
    openUserForm () {
      this.$dialog.custom({
        component: UserForm
      })
    }
  }
}
```

**Comment by rafaelpimpa** [comment]
Hmm, I see, seems like it's not that complicated to do this, will take a look later

**Comment by korpa** [comment]
@rafaelpimpa: I could have a look into this and add a component injection like I did for tables. In my opinion this is the most flexible way.

What do you think?

**Comment by dyreby** [comment]
I think this would be a great addition that would really expand the capabilities of buefy's dialog/modal feature.  Beyond forms I could also imagine dynamic content like progress indicators or a small modal-based UI that would allow a developer to pop up a quick control panel or settings editor.  I'm not sure how everything would work with a component that requires props, but using vuex behind the scenes would allow a modal component complete access to the state and vuex mutations / actions.

(And selfishly this is exactly what I need for a project I'm working on right now...)

@korpa I wish I could be some help, but I'm still learning JavaScript development and git workflows.  If you do have time to implement this feature I would really appreciate it.

@rafaelpimpa Thanks for your work on buefy!!

**Comment by rafaelpimpa** [comment]
Actually I'm not really sure if the Dialog should be mixed into this, I was thinking about creating another component (maybe Modal) to do this kind of stuff, inject components, show images and so on.

What you guys think?

**Comment by ciaasteczkowy** [comment]
I think it's a good idea. Dialogs would be a set of predefined modals with custom content inside a `modal-card`. That would make sense, if you allow users to put custom components in place of `modal-card`. Of course if `modal-background` and `modal-close` will be configurable with options, I won't complain :smile:

**Comment by korpa** [comment]
Hi guys,
I missed the discussion :( while I added a component injection into dialog :)  #27 
Let's use it as a further discussion basis

**Comment by rodymol123** [comment]
I think it would be easiest to just be able to pass the full component object and handle it like ```<component :is="component"></component>```  as the programmatic instantiation is the best thing about these dialogs/modals :)

It would allow for something like this:
```JS

import SomeForm from './form/SomeForm.vue'
...

this.$modal.open({
      title: 'My rich modal',
      component: SomeForm
})
```

**Comment by rafaelpimpa** [comment]
Will be available in v3.0.0

**Comment by drisschelouati** [comment]
How can i have access to the bulma modal "modal-content" class without altering all other buefy dialogs one the page ? I would like to add a special class to that element just for one dialog, so i can restyle it properly. Any hints ?

**Comment by chrtz** [comment]
This isn't still implemented, right?

**Comment by ciaasteczkowy** [comment]
It is. Here's documentation for it:
https://buefy.github.io/#/documentation/modal

**Comment by chrtz** [comment]
OT:
Oh, I thought this would be a different approach, as the current Buefy modal component doesn't work in my case. (I tried to make it a stand alone component itself.)
