### ISSUE TITLE
buefy with browserify vue template

### ISSUE THREAD

**Issue by Youdaman** [rafaelpimpa/buefy#81]
If I start a new Vue project via the cli with the browserify template, and paste in the required lines to get Buefy working:

```
import Vue from 'vue'
import Buefy from 'buefy'
import 'buefy/lib/buefy.css'

Vue.use(Buefy)
```

Then when you run `npm run build` it throws the following error:

```
C:\Users\Youdaman\Desktop\test\node_modules\buefy\lib\buefy.css:2
@-webkit-keyframes spinAround {
^
ParseError: Unexpected character '@'
```

After googling browserify and `@-webkit-keyframes` I found:

https://github.com/KyleAMathews/react-spinkit/issues/9

Which mentions using `cssify` to solve their particular problem but apart from adding that the the browserify transform array in package.json I don't know what else to do (and doing that still throws the error).

Maybe Buefy just doesn't work with browserify yet?

**Comment by rafaelpimpa** [comment]
Yep I've never tested with browserify template, if someone could help with that I appreciate.

**Comment by Youdaman** [comment]
The `style-loader` fix here solves this issue https://github.com/rafaelpimpa/buefy/issues/111#issuecomment-309868501
