### ISSUE TITLE
[b-select] select a numeric zero value returns undefined

### ISSUE THREAD

**Issue by iwan-wijaya** [rafaelpimpa/buefy#82]
### Overview of the problem

**Buefy** version: [0.3.2]
**Vuejs** version: [2.3.3]
**OS/Browser**: Ubuntu 16.04/Chrome 55.0.2883.87 

### Description

`b-select` returns `undefined` if selected value equals to numeric 0.
Caused by (?): https://github.com/rafaelpimpa/buefy/blob/dev/src/components/select/Select.vue#L78
### Steps to reproduce

```html
<b-select v-model.number="myVal" expanded>
  <option value="0">0</option> <!-- undefined -->
  <option value="1">1</option>
  <option value="2">2</option>
  <option value="3">3</option>
  <option value="4">4</option>
</b-select>

<!-- Or -->

<b-select v-model="testingval" expanded>
   <option :value="0">0</option> <!-- undefined -->
   <option :value="1">1</option>
   <option :value="2">2</option>
   <option :value="3">3</option>
   <option :value="4">4</option>
</b-select>
```

```javascript
watch: {
 myVal (val) {
  console.log(val)
 }
}
```

### Expected behavior
If first value is selected, myVal should be 0.
(This is the result using a native `<select></select>`)

```html
<select v-model.number="myVal" expanded>
   <option value="0">0</option><!-- 0 (correct) -->
   <option value="1">1</option>
   <option value="2">2</option>
   <option value="3">3</option>
   <option value="4">4</option>
</select>
```

### Actual behavior

myVal is set to empty string and then `undefined`.

**Comment by rafaelpimpa** [comment]
Thanks for the feedback!

**Comment by Elfoslav** [comment]
The same here in 2020

**Comment by jtommy** [comment]
@Elfoslav can you provide an example code?
