### ISSUE TITLE
Switch in group vertical align incorrect

### ISSUE THREAD

**Issue by Herteby** [rafaelpimpa/buefy#83]
Hi! :slightly_smiling_face: The switch is placed too low when placed in a group

How to reproduce:
``` 
<b-field grouped>
  <b-input/><b-switch/><b-checkbox>Scoped slots</b-checkbox>
</b-field>
```
![image](https://cloud.githubusercontent.com/assets/6474685/26575773/d5673dea-4526-11e7-92ea-feba2a85df3f.png)
The blue highlight shows the position of the switch's `<label>` element
Buefy 0.3.2

**Comment by rafaelpimpa** [comment]
HI! I've overhauled the switch style for the next release! And this is already fixed ;)

I'm planning to release this week.
