### ISSUE TITLE
No button snackbar

### ISSUE THREAD

**Issue by matthewpull** [rafaelpimpa/buefy#85]
It would be great if the snackbar was usable without a button. I know that toasts exist for this purpose, but I am using snackbars for other parts of the project and I would greatly prefer to keep all notifications looking the same so as not to confuse the user.

**Comment by rafaelpimpa** [comment]
Isn't the OK green button not good since it's just a message? I thought about that when I was making.

**Comment by matthewpull** [comment]
I could use a green OK button to just act as a dismiss handler, but being able to have a snackbar without a button would be a better solution and would make the snackbar a much more flexible component.

**Comment by rafaelpimpa** [comment]
The default button already dismisses the snackbar ;)

But I can add an option for that too.

**Comment by matthewpull** [comment]
Thanks :)

**Comment by rafaelpimpa** [comment]
Use ``actionText: null`` for buttonless snackbar (already works but text is not really centered).

**Comment by matthewpull** [comment]
Does this make the button really small or mean that there is actually no button?

**Comment by rafaelpimpa** [comment]
no button

**Comment by matthewpull** [comment]
Thanks, this is a really great solution :)
