### ISSUE TITLE
Inputs w/ Add-ons not displaying properly with b-field having a label on it

### ISSUE THREAD

**Issue by mirshko** [rafaelpimpa/buefy#87]
### Overview of the problem

**Buefy** version: [0.4.0]
**Vuejs** version: [2.2.2]
**OS/Browser**: macOS 10.12 Chrome Version 58.0.3029.110 (64-bit)

### Description

Input field with Add-ons not styled properly when b-field has a label attached to it. See screenshots.

<img width="377" alt="screenshot 2017-06-01 21 37 33" src="https://cloud.githubusercontent.com/assets/8116716/26707437/e1c59ef4-4712-11e7-99e7-4b5562ce8e9a.png">

### Steps to reproduce

Markup to reproduce

<img width="1375" alt="screenshot 2017-06-01 21 38 10" src="https://cloud.githubusercontent.com/assets/8116716/26707442/e7046e72-4712-11e7-94cf-c6fe89955cb4.png">

### Expected behavior

Label should be above input with Add-ons

<img width="354" alt="screenshot 2017-06-01 21 42 19" src="https://cloud.githubusercontent.com/assets/8116716/26707487/3e080eae-4713-11e7-8854-f2d8b134b775.png">

### Actual behavior

<img width="377" alt="screenshot 2017-06-01 21 37 33" src="https://cloud.githubusercontent.com/assets/8116716/26707488/4335d168-4713-11e7-82ad-ba396ca21e85.png">

**Comment by rafaelpimpa** [comment]
Yep it's a bug with Bulma actually.

To workaround this you can do this (I'm using like this as well):

```
<b-field label="My label">
    <b-field>
        <b-select placeholder="Select" expanded>
            <option value="">test</option>
            <option value="">Test</option>
        </b-select>

        <p class="control">
            <button class="button is-primary">
                <b-icon icon="add"></b-icon>
                <span>New</span>
            </button>
        </p>
    </b-field>
</b-field>
```

**Comment by rafaelpimpa** [comment]
Just created an issue: https://github.com/jgthms/bulma/issues/777

**Comment by rafaelpimpa** [comment]
Ok, his response was basically what I did, but he separated:

```html
<b-field label="My label"></b-field>
<b-field>
    <b-select placeholder="Select" expanded>
        <option value="">test</option>
        <option value="">Test</option>
    </b-select>

    <p class="control">
        <button class="button is-primary">
            <b-icon icon="add"></b-icon>
            <span>New</span>
        </button>
    </p>
</b-field>
```

**Comment by Tobbe** [comment]
Could buefy generate the needed html structure depending on if there are addons or not? So that when using buefy we can always just have one `b-field`, with or without label, and with or without addons?

**Comment by Mayurifag** [comment]
why is it closed if its not fixed yet? thanks for workarounds, though!
