### ISSUE TITLE
Newbie struggling to use components using data

### ISSUE THREAD

**Issue by johnboc** [rafaelpimpa/buefy#88]
Is it possible to have an example of how to use a buefy component that has a data option such as Tabs. I do not understand how to incorporate them into a page. I have experimented with the code in buefy-simple but none of the components use the data option.
Many thanks

**Comment by rafaelpimpa** [comment]
Tabs doesn't have any ``data`` prop, did you misspell?

If you mean the Table example, if you just copy the code from the example it's going to work.

**Comment by johnboc** [comment]
I am clearly not understanding something. If I copy and paste the example
table code into the buefy-simple App.vue file and add the data() code to the
export default code in the App.vue field I get a lot errors. I must be
putting it in the wrong place. 

 

I get the same problem when I try to use the Tabs example with the Set Music
button that returns activeData data.

export default {

    data() {

        return {

            activeTab: 0

        }

    }

}

 

If you can explain where this code should go I am sure I can get all the
other components to work - which are outstanding by the way.

 

Many thanks

Mike

**Comment by rafaelpimpa** [comment]
You are doing just fine, which errors are shown?

**Comment by johnboc** [comment]
This is what the browser shoes:

Welcome to Your Vue.js App

  _____  

Checkbox

Default

Name

person home dashboard

Right

ERROR in
./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./sr
c/App.vue

Module build failed: SyntaxError:
C:/Projects/buefy-simple-master/src/App.vue: Unexpected token (120:12)

 

  118 |         },

  119 |                 ...

> 120 |             ],

      |             ^

  121 |       checkedRows: [],

  122 |       selected: {},

  123 |       isBordered: false,

 

@ ./src/App.vue 7:2-97

@ ./src/main.js

@ multi ./build/dev-client ./src/main.js

ERROR in
./~/vue-loader/lib/template-compiler?{"id":"data-v-8f7d8204"}!./~/vue-loader
/lib/selector.js?type=template&index=0!./src/App.vue

(Emitted value instead of an instance of Error) 

  Error compiling template:

  

  <div id="app">

    <section class="container">

      <div class="has-text-centered">

        <hello></hello>

      </div>

      <hr>

      <b-field>

        <b-checkbox>Checkbox</b-checkbox>

      </b-field>

  

      <b-field>

        <b-switch>Default</b-switch>

      </b-field>

  

      <b-field label="Name">

        <b-input placeholder="John Silver"></b-input>

      </b-field>

  

      <div class="block">

        <b-icon icon="person"></b-icon>

        <b-icon icon="home"></b-icon>

        <b-icon icon="dashboard"></b-icon>

      </div>

    </section>

    <section class="container">

      <b-tooltip label="Tooltip right" position="is-right">

        <button class="button is-dark">Right</button>

      </b-tooltip>

    </section>

    <b-table :data="tableData" :bordered="isBordered" :striped="isStriped"
:narrowed="isNarrowed" :checkable="isCheckable"
:mobile-cards="hasMobileCards" :paginated="isPaginated" :per-page="perPage"
:pagination-simple="isPaginationSimple" default-sort="user.first_name"

        :selected.sync="selected" :checked-rows.sync="checkedRows">

  

      <template scope="props">

          <b-table-column field="id" label="ID" width="40" sortable numeric>

              {{ props.row.id }}

          </b-table-column>

  

          <b-table-column field="user.first_name" label="First Name"
sortable>

              {{ props.row.user.first_name }}

          </b-table-column>

  

          <b-table-column field="user.last_name" label="Last Name" sortable>

              {{ props.row.user.last_name }}

          </b-table-column>

  

          <b-table-column field="date" label="Date" sortable

              <span v-html="formatDate(props.row.date)">

          </b-table-column>

  

          <b-table-column field="gender" label="Gender">

             <b-icon

                  pack="fa"

                  :icon="props.row.gender === 'Male' ? 'mars' : 'venus'">

              </b-icon>

              {{ props.row.gender }}

          </b-table-column>

      </template>

    </b-table>

  </div>

  

  - tag <span> has no matching end tag.

 

@ ./src/App.vue 9:2-170

@ ./src/main.js

@ multi ./build/dev-client ./src/main.js

**Comment by johnboc** [comment]
Sorry this is the error page:

Welcome to Your Vue.js App

  _____  

Checkbox

Default

Name

person home dashboard

Right

ERROR in
./~/vue-loader/lib/template-compiler?{"id":"data-v-8f7d8204"}!./~/vue-loader
/lib/selector.js?type=template&index=0!./src/App.vue

(Emitted value instead of an instance of Error) 

  Error compiling template:

  

  <div id="app">

    <section class="container">

      <div class="has-text-centered">

        <hello></hello>

      </div>

      <hr>

      <b-field>

        <b-checkbox>Checkbox</b-checkbox>

      </b-field>

  

      <b-field>

        <b-switch>Default</b-switch>

      </b-field>

  

      <b-field label="Name">

        <b-input placeholder="John Silver"></b-input>

      </b-field>

  

      <div class="block">

        <b-icon icon="person"></b-icon>

        <b-icon icon="home"></b-icon>

        <b-icon icon="dashboard"></b-icon>

      </div>

    </section>

    <section class="container">

      <b-tooltip label="Tooltip right" position="is-right">

        <button class="button is-dark">Right</button>

      </b-tooltip>

    </section>

    <b-table :data="tableData" :bordered="isBordered" :striped="isStriped"
:narrowed="isNarrowed" :checkable="isCheckable"
:mobile-cards="hasMobileCards" :paginated="isPaginated" :per-page="perPage"
:pagination-simple="isPaginationSimple" default-sort="user.first_name"

        :selected.sync="selected" :checked-rows.sync="checkedRows">

  

      <template scope="props">

          <b-table-column field="id" label="ID" width="40" sortable numeric>

              {{ props.row.id }}

          </b-table-column>

  

          <b-table-column field="user.first_name" label="First Name"
sortable>

              {{ props.row.user.first_name }}

          </b-table-column>

  

          <b-table-column field="user.last_name" label="Last Name" sortable>

              {{ props.row.user.last_name }}

          </b-table-column>

  

          <b-table-column field="date" label="Date" sortable

              <span v-html="formatDate(props.row.date)">

          </b-table-column>

  

          <b-table-column field="gender" label="Gender">

              <b-icon

                  pack="fa"

                  :icon="props.row.gender === 'Male' ? 'mars' : 'venus'">

              </b-icon>

              {{ props.row.gender }}

          </b-table-column>

      </template>

    </b-table>

  </div>

  

  - tag <span> has no matching end tag.

 

@ ./src/App.vue 9:2-170

@ ./src/main.js

@ multi ./build/dev-client ./src/main.js

**Comment by rafaelpimpa** [comment]
The error says is the last line: `` - tag <span> has no matching end tag.``

**Comment by rafaelpimpa** [comment]
Anyway later I'm gonna update buefy-simple with some other examples, but you should take a better look at how vue works in the meanwhile!

**Comment by johnboc** [comment]
If corrected the missing span tag I still got an error in render function: "TypeError: Cannot read property 'id' of undefined".

 

Believe me I am spending a lot of time looking at how Vue works 😉 Anyway I look forward to seeing the updated examples in buefy-simple.

 

Thanks again for the great work and sorry to have taken up your time.

 

Cheers

Mike

**Comment by rafaelpimpa** [comment]
Sure! Just give a few days. Try to execute the ones with less properties so you can get the feel of it, like a simple checkbox:

On the template tag
```html
<b-checkbox v-model="isActive"></b-checkbox> {{ isActive }}
```

On the script tag
```javascript
export default {
  data() {
    return {
      isActive: false
    }
  }
}
```

And start to increment from there ;)
