### ISSUE TITLE
Use of b-tooltip inside table cell

### ISSUE THREAD

**Issue by sanderheilbron** [rafaelpimpa/buefy#89]
### Overview of the problem

**Buefy** version: 0.4.0
**Vuejs** version: 2.3.3
**OS/Browser**: macOS 10.12.2 Chrome (58) and Safari (10.0.2)

### Description
I would like to combine a tag ```span class="tag"``` with a tooltip inside a table cell. Using this combination outside a table shows the tooltip by hovering the tag, but this does not work inside a table cell.

I'm using a method to generate a tag with some dynamic data, and use the v-html attribute inside b-table-column.

Is this possible inside a table cell, or does this require some additional coding?

**Comment by rafaelpimpa** [comment]
Could you give me a code example? Since dropdown is working in the cell, tooltip should not be a problem either.

**Comment by rafaelpimpa** [comment]
Hey, my bad for the delay on this.

The thing is, you're passing a vue component as string, even if it's on ``v-html`` won't work. You should do the logic inside the ``b-table-column`` for it to render:

```javascript
<b-table-column field="id" label="ID" width="40" sortable numeric>
    <b-tooltip label="Some additional info about the status" position="is-right">
        <span class="tag is-success is-status is-small">{{ props.row.id }}</span>
    </b-tooltip>
</b-table-column>
```

**Comment by sanderheilbron** [comment]
Makes sense! Thanks!

**Comment by amirhkhadem** [comment]
@rafaelpimpa can this be done within a column meta property? or do i have to rewrite the whole table and use b-table-columns ?
