### ISSUE TITLE
Table header select outline border messing up

### ISSUE THREAD

**Issue by donPuerto** [rafaelpimpa/buefy#9]
This is awesome table mate. fully responsive. Do we have search functionality?

![image](https://cloud.githubusercontent.com/assets/9329005/24940692/6003151c-1f77-11e7-89e3-ad9314f25752.png)

**Comment by rafaelpimpa** [comment]
No default search functionality, I left that for the user since it's kinda easy and you can design the way you want, add debounce and so on.
