### ISSUE TITLE
Pagination back and forward invocation

### ISSUE THREAD

**Issue by stychu** [rafaelpimpa/buefy#92]
### Overview of the problem
I've a little problem and I don't know if what I want to achieve is possible right now. 
So I've a table with data from json file : this is the file structure
```
[
 {
    "start": 1496387183833,
    "end": 1496414101207,
    "date": "2017-06-02"
  },
  ....
]
```
And what I want to achieve is that on pagination I wish to have on page only data per one month. So if I would've in the file, data for 3 months from now : June(30 days) July(31 days) And August(31 days) strightforward I would like to display that data in the table like so:
For June 30 records
For July 31 records etc..
But I dont know if there is a way to determine what data is on current page?? So I can dynamically set per-page items.
I would like to know if its possible to get currently displayed data of table and if not so maybe it could be implemented ?

Also is it possible to add fa- icons tho the b-table labels ?

**Buefy** version: [0.4.0]
**Vuejs** version: [2.3.3]
**OS/Browser**: Chrome

**Comment by rafaelpimpa** [comment]
Hi, thanks for using buefy ;) regarding icons on labels: it's currently not possible but I could implement if there are more people interested on that.

About custom pagination, it's also not possible and I don't have intend to do so TBH, you could do that yourself tho:

Add a ``b-table`` and the ``b-pagination`` individually, and the ``:data`` you'll pass to table should be the splitted array based on what you need, just like when using it server-side.

Hope that makes sense!
