### ISSUE TITLE
Misaligned Button Text on Safari when using Icons

### ISSUE THREAD

**Issue by Wheatability** [rafaelpimpa/buefy#93]
### Overview of the problem

**Buefy** version: [0.4.0]
**Vuejs** version: [2.3.3]
**MacOS Sierra** / **Safari** [10.1.1]:

### Description

On Safari, the text is not vertically centered on button elements when used in conjunction with icons.
This also happens on the docs page as seen below:
Screenshot: 
<img width="339" alt="screen shot 2017-06-08 at 3 28 28 pm" src="https://user-images.githubusercontent.com/1501045/26947019-2e67678c-4c5f-11e7-99ae-594cedccb4ac.png">

_**The temporary solution is to use the `<a>` anchor element instead of `<button>` for buttons**_
_**It does work properly on safari using the `<a>` element.**_

### Steps to reproduce

1. Use Button Element inside b-dropdown etc
2. Use Icon
Example from Docs (inside b-dropdown):
```HTML
<button class="button" slot="trigger">
    <span>Dropdown</span>
    <b-icon icon="arrow_drop_down"></b-icon>
</button>
```

### Fix for Safari Users
<img width="146" alt="screen shot 2017-06-08 at 3 26 44 pm" src="https://user-images.githubusercontent.com/1501045/26946955-f9012f24-4c5e-11e7-8e07-0ae3662606a7.png">

*Use `<a>` elements*:
```HTML
<a class="button" slot="trigger">
    <span>Dropdown</span>
    <b-icon icon="arrow_drop_down"></b-icon>
</a>
```

**Comment by rafaelpimpa** [comment]
This is probably a browser bug, not sure if there's something I can do (all those align classes are from bulma).

**Comment by Wheatability** [comment]
From the bulma docs it looks like every button example uses anchor tags instead of buttons. I wonder if that is the recommended convention.

**Comment by rafaelpimpa** [comment]
Might be, even tho I prefer ``button`` for the samatic.

**Comment by rafaelpimpa** [comment]
Could you try changing the ``vertical-align`` from ``.icon`` from ``top`` to ``middle`` and see if there's any difference?

**Comment by Wheatability** [comment]
Didn't find a difference when playing around with `vertical-align` on the `button`, `span`, and `icon` classes

**Comment by rafaelpimpa** [comment]
I'm closing this since there's not much I can do.
