### ISSUE TITLE
Full working table example

### ISSUE THREAD

**Issue by itielshwartz** [rafaelpimpa/buefy#94]
Hi,

I have the latest version installed, and I really like the table component. 

Sadly i couldne't make the example shown here:
https://buefy.github.io/#/documentation/table
work.

any chance you can publish a  full working webapp (or codepen) for the table?
any MVP will be great,
Thanks

**Comment by szafran89** [comment]
I had an issue as well. There are missing closing tags. Let's update this section.
```
<b-table-column field="date" label="Date" sortable>
   <span v-html="formatDate(props.row.date)"></span>
</b-table-column>
```

**Comment by rafaelpimpa** [comment]
The docs example is here (now fixed): https://github.com/rafaelpimpa/buefy/blob/dev/docs/pages/documentation/data/Table.vue

**Comment by Taramouse** [comment]
FYI: Link above is broken.
