### ISSUE TITLE
Feature: Toggle table columns

### ISSUE THREAD

**Issue by vysakhvasanth** [rafaelpimpa/buefy#96]
### Overview of the problem
Hi, I have been using buefy for my project and it has been amazing. I have a request to add toggling for table columns.

Is this currently planned to be added? I am planing to try and customise the table component myself to try and add this, but wanted to ask here whether this is on your list.
 
**Buefy** version: [0.4.0]
**Vuejs** version: [2.2.6]
**OS/Browser**: Any

**Comment by rafaelpimpa** [comment]
What exactly do mean with Toggle columns? Sorting more than one at a time?

**Comment by vysakhvasanth** [comment]
I meant collapsing columns (visibility). So the use case is that, I have a table with many columns and users would like the ability to toggle them.

**Comment by rafaelpimpa** [comment]
Oh sure, I'll add a ``visible`` prop on the column and you do the rest yourself, since it's not a really "core" feature to have built in.

**Comment by vysakhvasanth** [comment]
Thank you.  :+1:
