### ISSUE TITLE
Dialog Options

### ISSUE THREAD

**Issue by stychu** [rafaelpimpa/buefy#97]
**Buefy** version: [0.4.0]
**Vuejs** version: [2.3.3]
**OS/Browser**:
CHROME

### Description

I wonder if it's possible to add multiple inputs in dialog? I can see prompt with only one dialog and not sure if its possible to add second dialog. If not this is kinda lame.. Most of times ppl want propmpts/dialogs with multiple input fieelds for ex like login dialog.. Can we get this kind of functionallity ?? Also adding own template would be useful i think.

**Comment by rafaelpimpa** [comment]
https://buefy.github.io/#/documentation/modal
