### ISSUE TITLE
change.lazy Isn't working in input

### ISSUE THREAD

**Issue by srunicornio** [rafaelpimpa/buefy#98]
### Overview of the problem

**Buefy** version: [0.4.0]
**Vuejs** version: [2.2.6]
**OS/Browser**: Chrome

### Description
Hi there, Buefy is awesome! Thanks for create it!

Bug:
In this example the change.lazy is not working, only it's work when I use change without .lazy

```
<b-table :data="users">
    <template scope="props">
        <b-table-column field="value" label="Value">
            <b-input v-model="props.row.username" @change.lazy="update(props.row.id)"></b-input>
        </b-table-column>
    </template>
</b-table>
```

**Comment by rafaelpimpa** [comment]
Hi, try to use like this ``@change.native.lazy``.

**Comment by srunicornio** [comment]
Perfect!! Thanks
